scripts/sct_utils.py
testing/test_all.py
testing/test_sct_check_atlas_integrity.py
testing/test_sct_crop_image.py
testing/test_sct_propseg.py
testing/test_sct_register_to_template.py
testing/test_sct_warp_template.py

added integrity testing to propseg and register_to_template

testing integrity

---

scripts/sct_straighten_spinalcord.py

This pull request fixes the issue #475. The landmarks pattern has been improved by the addition of internal crosses.
The padding in the left-right direction has been improved as well.

BUG: improved landmarks pattern for straightening. Fixed #475

---

scripts/sct_detect_vertebral_levels.py
testing/test_all.py
testing/test_sct_detect_vertebral_levels.py

Improved labeling:
- patch-base correlations
- no need to indicate contrast
- more accurate and robust

jca_vertebralLabeling

---

scripts/msct_types.py
scripts/sct_label_utils.py
testing/test_sct_label_utils.py

This pull request attemps to fix the issue #514 related to center of mass computation.
The code was completely refactored and improved. The center of mass are not correctly computed.
An integrity test has also been added.

Fix issue #514

---

scripts/msct_gmseg_utils.py
scripts/msct_multiatlas_seg.py
scripts/sct_segment_graymatter.py

For the images with very low WM-GM contrast : 
- the usual normalization (based on a dictionary pre-registration to estimate WM and GM median intensity values) will probably fail
- if so, the image will be normalized using a linear normalization based on minimum and maximum intensity values
- the "min-max" normalization is less efficient than the "median" normalization for good images (with a good WM-GM contrast) but it is more robust since it works for all images.
This should avoid incomplete segmentation result (as Allan's)

GM segmentation

---

batch_processing.sh
scripts/msct_smooth.py
scripts/sct_register_to_template.py
scripts/sct_straighten_spinalcord.py

Fix for this issue: https://github.com/neuropoly/spinalcordtoolbox/issues/722
Major refactoring on sct_straighten_spinalcord

jca_issue722

---

scripts/sct_image.py

in ```sct_image```: -concat and -omc options concatenate images using a loop (open image, concatenante with previous images, close image) to avoid memory saturation. 
--> Fix #715

Issue #715: concat images using a loop 

---

scripts/sct_register_to_template.py
scripts/sct_utils.py

- in ```sct_utils```: function  ```check_if same_space(fname_1, fname_2)``` return True if qform matrix are identical (same space and orientation)
- in ```sct_register_to_template```: check if data, segmentation and landmarks are in the same space, if not, return an error and stop script.
--> Fix Issue #719

Issue 719:  check if same space

---

scripts/sct_dmri_create_noisemask.py
scripts/sct_testing.py
testing/test_sct_dmri_create_noisemask.py

Tanguy issue:
#733 
- sct_dmri_create_noisemask
- sct_testing
- test_sct_dmri_create_noisemask

ch_issue_733

---

.gitignore
install/sct_launcher
install/update_bin.sh
install_sct

fixed issue with timing (do not reimport variables)

Poq issue 729

---

install_sct

added -b option to prevent binaries installation

---

scripts/sct_extract_metric.py
scripts/sct_process_segmentation.py

For the output files: `csa_mean` and `volume`.

Address issue #825

---

scripts/sct_extract_metric.py

Computes and gives total fractional volume of each label (in the terminal window and in the output file)

Address issue #829

---

install_sct

Check exit status of pip and conda install Crash with information if status != 0

Poq issue #869 crash internet

---

install_sct

I also force numpy reinstallation on linux system to fix the conda "Intel MKL FATAL ERROR: Cannot load libmkl_avx2.so or libmkl_def.so."  bug on ubuntu systems

install will fail if miniconda install fails

---

batch_processing.sh
scripts/sct_process_segmentation.py

Related to the correction for data resolution applied after centerline tangent vector normalization.

Fix bug during CSA calculation

---

install_sct
scripts/sct_download_data.py

uploaded all binaries and data to [OSF](https://osf.io/6zbyf/) and updated the necessary files.

jca_use_osf

---

scripts/sct_segment_graymatter.py
testing/test_sct_segment_graymatter.py

Cherry picked changes from branch sd_issue_1059.

Add changes from branch sd_issue_1059

---

scripts/sct_warp_template.py

most complex pull request in the history of github...

fixed typo

---

scripts/sct_create_mask.py
scripts/sct_crop_image.py

Adapt create_mask and crop_image to 2D data to fix issue #1066.

Adapt create_mask and crop_image to 2D data

---

scripts/sct_register_graymatter.py

- Fix issue #1068 
- add comments and minor changes

Fix empty inverse warping field

---

scripts/msct_image.py
scripts/sct_apply_transfo.py
scripts/sct_concat_transfo.py
scripts/sct_image.py
scripts/sct_process_segmentation.py
scripts/sct_register_multimodal.py
testing/test_sct_process_segmentation.py
testing/test_sct_propseg.py

Fixing issues for release 3.0

---

scripts/sct_label_vertebrae.py

- added flag `-param` to control window size and location for finding discs
- changed default params based on testing/large (results will be copied soon in this thread)

Jca_label_vert_param

---

scripts/sct_utils.py
testing/test_sct_label_vertebrae.py

jca_issue_1083

---

scripts/isct_test_function.py
scripts/sct_label_vertebrae.py
scripts/sct_utils.py

created the email address `spinalcordtoolbox@gmail.com` to use as SMTP server
related to issue #1081

OPT: utils: created send_email

---

dev/atlas/create_atlas/create_atlas.m
scripts/sct_download_data.py
scripts/sct_utils.py

fixed issue #411 
batch_processing
Spinal Cord Toolbox (jca_issue_411/518d7c98b7a537fc2c66f0abcadad54b1d6496ba)
~~~
t2/CSA:   76.753884, 2.049822
mt/MTR:   51, white matter, 379.054477, 33.881926, 0.000000
mt/CSA:   19.604350, 1.661074
dmri/FA:  4, WM left lateral corticospinal tract, 22.431553, 0.687499, 0.000000
dmri/FA:  5, WM right lateral corticospinal tract, 18.827148, 0.778602, 0.000000
~~~
--> fairly big L/R discrepancy --> i need to investigate --> this is due to bad registration. New example dataset will solve.
Spinal Cord Toolbox (jca_labelVert_param/06486d879b66f6571415de8e6bccd57b6b031141)
~~~
t2/CSA:   76.753884, 2.049822
mt/MTR:   51, white matter, 387.801068, 33.744919, 0.000000
mt/CSA:   20.052757, 1.286250
dmri/FA:  4, WM left lateral corticospinal tract, 22.799808, …

Jca_issue_411

---

scripts/sct_straighten_spinalcord.py
testing/test_sct_straighten_spinalcord.py

Urgent Pull Request! Master is broken because of this issue.
This pull request also includes the computation of the time that is required to compute straightening accuracy. An evaluation of accuracy and computation time is presented in issue #1075.

Fixing bug in sct_straighten_spinalcord for images with rotation

---

scripts/msct_image.py
scripts/sct_dice_coefficient.py
testing/test_sct_propseg.py

This implementation does not yet integrates all the feature of `isct_dice_coefficient` but it already solves the issue of small origin differences.
This implementation does only check shape of data instead of full orientation matrix.

Introducing a python-based implementation of Dice coefficient computation

---

scripts/msct_image.py
scripts/sct_propseg.py

This PR improves the handling of temporary files in sct_propseg to avoid crashing in multiple cpu large testing.

Fixing subject crashing in propseg large testing

---

scripts/sct_label_vertebrae.py

OPT: label_vertebrae: now outputing verbose=2 pics in ofolder

---

scripts/sct_straighten_spinalcord.py
testing/test_sct_straighten_spinalcord.py

Disabled accuracy computation for straightening

---

scripts/sct_process_segmentation.py

This pull request fixes the issue #1111

REF: display spinal cord length when required (full spinal cord)

---

install_sct
scripts/isct_test_function.py

Because outdated curl commands fail to download from the OSF site. The hack is
to use wget first, hoping that the system also has wget installed and is recent.

Download function uses wget before using curl

---

scripts/sct_propseg.py

Copy header of input file to ensure qform is unchanged

---

scripts/sct_label_vertebrae.py
scripts/sct_maths.py

zero voxels no more included when computing MI + new flag to compute normalized MI

---

scripts/isct_test_function.py
scripts/sct_propseg.py
scripts/sct_testing.py
scripts/sct_utils.py
testing/test_sct_propseg.py

Add message to user when spinal cord is not detected and verbose improvement for testing

---

scripts/sct_maths.py

fixes request in:
https://github.com/neuropoly/spinalcordtoolbox/pull/1136

OPT: maths: visu only produced if verbose=2

---

scripts/sct_compute_snr.py

BUG: compute_snr: fixed variable name

---

scripts/sct_register_to_template.py

index of the new label were passed as floats generating a bug

Patch sct_register_to_template with -ref subject

---

scripts/sct_propseg.py
scripts/sct_viewer.py

This PR enables the option to click wherever you want in an image. The option is enabled when you move around in the sagittal view.
When finished, just close the window.
Red dots appears where you placed points and are displayed when moving around in the sagittal view.

Enable click mode on viewer

---

install/sct_changelog.py

Changed the changelog format and request from user the new version name.

Changelog generator improvements.

---

scripts/sct_process_segmentation.py

sct_process_segmentation: change default output directory for current working directory

---

scripts/sct_register_multimodal.py

fixes https://github.com/neuropoly/spinalcordtoolbox/issues/1176

now possible to do multiresolution and specify gradStep for algo=slicereg

---

scripts/msct_image.py
scripts/sct_create_mask.py
scripts/sct_label_utils.py

Adapt sct_create_mask and sct_label_utils to 2D data

---

scripts/sct_straighten_spinalcord.py

Fixes https://github.com/neuropoly/spinalcordtoolbox/issues/1182

Changed default threshold_distance from 2.5 to 10 to avoid edge effect

---

scripts/sct_propseg.py

Removing discontinuities at edges on segmentation

---

scripts/sct_compute_snr.py

--> use function orientation instead of set_orientation (from script sct_image), set_orientation might have been change and doesn't work with 4D data (crop data to 3D).

Fix issue #1190 (sct_compute_snr)

---

scripts/sct_compute_snr.py

fixes https://github.com/neuropoly/spinalcordtoolbox/issues/1198

enables to specify volumes for -mult option and fix issue in diff method

---

install/requirements/requirementsConda.txt
install/requirements/requirementsPip.txt
scripts/sct_process_segmentation.py

Changed the for loop and made the iteration safer and faster.
Fixes #1191

Fix IndexError exception when getting vertebral slices

---

scripts/sct_process_segmentation.py

This Pull request fixes the issue #1118. The issue is similar to #1202 but for the centerline extraction (centerline fitting is unstable when calculated with voxel coordinates).

Centerline extraction uses physical coordinates

---

scripts/sct_process_segmentation.py

Fixed data type issue in sct_process_segmentation

---

CHANGES.md

updated CHANGES

---

CHANGES.md
install/sct_changelog.py

Fix formatting of the changelog output

---

scripts/sct_fmri_compute_tsnr.py

Fixed tSNR computation

---

scripts/sct_straighten_spinalcord.py

This Pull Request fixes a small issue in `sct_straighten_spinalcord` concerning the options `-disable-straight2curved` and `-disable-curved2straight`.
These options allowed to disable the generation of warping fields. Even if warping fields were not computed, the warping fields were still generated (and therefore were wrong).

Fixing disabling options on straightening

---

scripts/sct_maths.py

NEW: maths: added -rms

---

spinalcordtoolbox/reports/qc.py

Change the format of the SCT version.

---

scripts/sct_download_data.py

Show progress and total size during download

---

scripts/msct_image.py
scripts/sct_image.py

* Added new method called `getDataShape` into `Image` class.
* Added sanity checking for input file dimensions (padding operation);
* Added sanity checking for input parameters (padding operation).
Ref Issue #913

Add dimension sanity checking for input file padding op (issue #913)

---

scripts/sct_testing.py

Provide a warning if the function name is not in the list of test functions.
Fixes #473

Validate the function name in sct_testing

---

install/sct_changelog.py

The markdown generated was malformed and needed new-lines. The pull request ID was
not useful to the user and was removed.

Improved the formatting of the changelog generator

---

scripts/sct_propseg.py
scripts/sct_register_multimodal.py
scripts/sct_segment_graymatter.py

--> to avoid SC edges inconsistency due to registration (see issue #1314)

Get WM seg after post processing by subtracting GM to SC 

---

scripts/sct_label_vertebrae.py
scripts/sct_propseg.py
scripts/sct_register_to_template.py

The parameter `-noqc` prevents the generation of the QC report.
Fixes #1308

Added the command parameter `-noqc`

---

scripts/sct_image.py

In sct_image, the set_orientation function saves the input if it does not
exists. The standard way of checking if the file exist is to use os.path.exists.
Fixes #1340

Use a different function to identify if a file exists

---

scripts/sct_segment_graymatter.py

Avoid differences between probabilistic GM thresholded to 0.5 and binary GM. 
Binarise  Gm segmentation after warping GM and WM from model space back to the original image space.
Fixes Issue #1329

Binarize GM seg after warping back result to original space

---

scripts/sct_image.py

Now copy input data type
Fixes #1362

image/pad: now copy input data type (fixes issue 1362)

---

spinalcordtoolbox/centerline/optic.py

This pull request includes a very small change in the computation of the referential origin of ROI interpreted by JIM software.

Fix referential for JIM centerline

---

scripts/msct_register.py
scripts/msct_smooth.py
scripts/sct_image.py
scripts/sct_pipeline.py
scripts/sct_register_to_template.py
scripts/sct_straighten_spinalcord.py
scripts/sct_utils.py
testing/test_sct_register_to_template.py

- straightening now output image in RPI, i.e., aligned with the PAM50 template
Fixes #1360, #1364

Various fixes for registration to template and straightening

---

spinalcordtoolbox/reports/assets/_assets/css/style.css
spinalcordtoolbox/reports/assets/_assets/js/main.js
spinalcordtoolbox/reports/assets/index.html

The buttons allow the user to navigate the list of QC items.
Partially implements #1271

Insert previous and next buttons in the qc reports page

---

scripts/msct_register.py
scripts/sct_register_multimodal.py

Forces -verbose 1 ``isct_antsRegistration``.
Fixes #1386

Made error message more explicit if crash occurs

---

scripts/msct_register.py
scripts/sct_register_multimodal.py

BUG: register_multimodal: fixed typo when calling isct_antsRegistration

---

scripts/sct_dmri_display_bvecs.py

usage:
~~~
sct_dmri_display_bvecs -bvec bvecs.txt
~~~
Example of output:

NEW: dmri_display_bvecs: new function to display bvecs

---

scripts/sct_dmri_moco.py

Makes more sense to use MI for registration (because DWI contrast varies across volumes)

Changed default values and clarified doc.

---

scripts/sct_register_graymatter.py

With the type_value, the nii is written.
Fixes #1403

Allow the -winv parameter to write a file to disk

---

scripts/sct_register_multimodal.py

Fixes issue #1412 
(I made a mistake in the naming of the branch-- should have been jca_issue1412 instead of jca_issue 1492).

Changed destination image for concatenation of inverse warping field

---

scripts/sct_register_graymatter.py

Allow user to use a custom template to register graymatter
Fixes #1264  
(proposition A)

Use custom template for sct_register_graymatter

---

install/sct_launcher
scripts/sct_check_dependencies.py
scripts/sct_pipeline.py
scripts/sct_utils.py

Fixed small issues in pipeline

---

scripts/sct_label_vertebrae.py

Fixes #1421
Optimization of default `gaussian_std` parameters will be done in https://github.com/neuropoly/spinalcordtoolbox/issues/1423

Enables to set Gaussian weighting of mutual information for finding C2-C3 disk

---

scripts/sct_label_vertebrae.py
scripts/sct_pipeline.py
testing/test_sct_label_vertebrae.py

Various fixes to `sct_pipeline` (parameters were not passed) and `test_sct_label_vertebrae` (improved verbose on checking file existence).

Various fixes to pipeline and testing

---

scripts/msct_image.py
scripts/sct_extract_metric.py
scripts/sct_get_centerline.py
scripts/sct_image.py
spinalcordtoolbox/centerline/optic.py
testing/test_sct_propseg.py

Conversion issue for float32 images with large dynamic

---

scripts/sct_propseg.py

Fixes https://github.com/neuropoly/spinalcordtoolbox/issues/1456

Added try/except for QC report

---

scripts/msct_types.py

This Pull Request introduces a new method for calculating an interpolated coordinate along a centerline, using the vertebrae-based coordinate referential system.
This is used within the template generation: https://github.com/neuropoly/template

Improvements on centerline for template generation

---

spinalcordtoolbox/gui/widgets.py

The user can zoom in and out of the GUI's anatomical views
By moving the mouse over a canvas:
- if the user scrolls up, the canvas zoom in using the mouse as the center point of the zoom.
- if the user scrolls down, the canvas zoom out and stops when reaches max size.

Introduced the zoom functionality to the anatomical canvas

---

README.md

Some of the dropbox links were broken.

Updated bibliographic URL on ReadMe

---

scripts/sct_viewer.py

The code was mangled from the logging refactoring. Reverted back to something functional

Fix a regression bug.

---

dev/atlas/create_atlas/create_atlas.m
dev/atlas/create_atlas/parameters_MNIPolyAMU.m
dev/atlas/create_atlas/parameters_PAM50.m

https://github.com/neuropoly/spinalcordtoolbox/issues/1498

BUG: fix errors in create_atlas.m

---

scripts/sct_propseg.py
setup.py
spinalcordtoolbox/gui/base.py
spinalcordtoolbox/gui/centerline.py
spinalcordtoolbox/gui/sagittal.py

Resolving additional issues
- Added quit key binding
- Quit propseg when GUI quit without saving
Implements or Fixes #1494

More improvements to the viewer

---

scripts/sct_analyze_lesion.py

Voxel size before:
```
im.dim[3:6]
```
corrected by
```
im.dim[4:7]
```

Slice thickness value was incorrect in sct_analyze_lesion

---

install_sct

reinstall only current numpy version

---

install_sct

Fixes https://sourceforge.net/p/spinalcordtoolbox/discussion/help/thread/9d988979/ also mentioned in  #1524

force default channel in conda install

---

install/sct_changelog.py

Fix a markdown format error in the generation of the changelog

---

scripts/sct_download_data.py

Modified `sct_download_data` such that a list of URLs can be added as input. 
Fixes #1562

Find mirror servers in case OSF is not accessible

---

scripts/sct_apply_transfo.py

Fixed output verbose

---

scripts/sct_image.py

Fixed output verbose in case output name not specified

---

batch_processing.sh
scripts/sct_segment_graymatter.py
scripts/sct_warp_template.py

Added example for registering metric to template space

---

batch_processing.sh

Fixes bug in batch_processing, also added code to warp DTI_FA on template

---

scripts/sct_fmri_compute_tsnr.py

Fixed missing output

---

scripts/sct_label_utils.py
testing/test_sct_label_utils.py

Fixes #1580 
To test: run `sct_testing`

Fixed minor verbose issues during testing

---

scripts/sct_download_data.py
spinalcordtoolbox/deepseg_gm/deepseg_gm.py

Fixing the links for the `sct_deepseg_gm`models to the updated ones.

Update links to the sct_deepseg_gm models

---

scripts/sct_download_data.py

Adding a README.txt in the deepseg_sc folder and then updating the links for the sct_deepseg_sc models to the updated ones.

Add README.txt in deepseg_sc folder

---

CHANGES.md

updated CHANGES.md

---

scripts/sct_image.py

It is now possible to change the orientation of data on 4D data.
Fixes #1636

Now possible to change data orientation on 4D data

---

scripts/sct_apply_transfo.py

Re-ordering of 4th dimension when apply transformation on 4D scans

---

scripts/msct_register.py

Slice counting fixed

---

scripts/sct_label_utils.py

In the function getNonZeroCoordinates (sorting = 'z') the value for the parameter sorting was changed from 'z' to 'value'. What allows stamps to be ordered by value.
Implements or Fixes #1606

output of -display ordered per label value

---

README.md

Minor fix on README that needs to be merged ASAP

Fixed broken URL

---

scripts/sct_deepseg_gm.py
scripts/sct_dmri_moco.py
scripts/sct_pipeline.py
scripts/sct_testing.py
scripts/sct_warp_template.py
testing/test_sct_compute_hausdorff_distance.py
testing/test_sct_deepseg_gm.py
testing/test_sct_deepseg_sc.py
testing/test_sct_label_utils.py
testing/test_sct_propseg.py
testing/test_sct_segment_graymatter.py
testing/test_sct_straighten_spinalcord.py

`sct_pipeline` now includes quality metrics (e.g., Dice, Hausdorff distance, etc.) in the output report. PR also includes cosmetic changes. 
Implements #1750, #1747

Added integrity metrics in sct_pipeline report

---

scripts/msct_parser.py
scripts/sct_pipeline.py
scripts/sct_testing.py

Various fixes for `sct_pipeline`
Fixes #1766, Fixes #1768, Fixes #1769

Various fixes for sct_pipeline

---

scripts/msct_parser.py
scripts/sct_extract_metric.py

Make it possible to input single label file

---

.travis.yml
README.md
scripts/sct_check_dependencies.py
spinalcordtoolbox/reports/qc.py

#1772 
Yes, coveralls.io integrated (icon appears in MarkDown
- Fixing the issue by detecting the OS,
- Initial coverage integration
- Minor pep8 format changes
Fixes #1772, Fixes #1785

Fixed verbose in QC, integrated coveralls

---

scripts/sct_register_to_template.py

Added test to make sure not to crop outside of slice range

---

install/sct_changelog.py

Fixup sct_changelog

---

README.md

Added link to github.com/sct-pipeline

---

scripts/sct_process_segmentation.py

Fixed z_centerline_voxel not defined if angle_correction=0

---

install/sct_changelog.py

Now includes documentation and installation in changelog

---

scripts/sct_extract_metric.py

Now possible to specify a vertebral labeling file when using -vert

---

scripts/sct_register_to_template.py

We added a step, before straightening, that orthogonally projects labels onto the cord centerline. This step ensures that the subsequent affine transformation (label_subject --> label_template) is working properly.
Fixes #1826 
Before fix:
After fix:

Fixed registration issue caused by labels far from cord centerline

---

scripts/sct_propseg.py
spinalcordtoolbox/centerline/optic.py

Manual centerline is now output when using viewer

---

.travis.yml

* [* ] Is there a issue open describing the motivation for this pull request ?
#1845 
To add coveralls PIP installation in Travis and prevent build failure
Implements or Fixes #1845

Coveralls added to Travis to prevent build failure

---

README.md
scripts/sct_download_data.py

Updated documentation in preparation of the SCT course in Paris

---

unit_testing.sh

This PR should fix the coveralls reports. I included the `scripts/` and the `spinalcordtoolbox/` folders.
PS: wait for coveralls report before merging this PR, to check if it's ok.

Fix coveralls coverage

---

scripts/sct_register_to_template.py

In cases were input labels (-ldisc or -l) are not in the same voxel space as the input segmentation, the label projection (which is computed assuming that both are in the same voxel space) failed dramatically. 
The implemented solution was to do the projection in the physical space (not voxel).
Fixes #1864

Now computing label projection in physical (not voxel) space

---

scripts/sct_propseg.py

* [*] Is there a issue open describing the motivation for this pull request ?
- Capturing the error if -init introduces negative value
- Using pattern in sct_utils to avoid sending logs to Sentry
Implements or Fixes #1328

The `init` parameter now accepts only positive values

---

install/sct_launcher
install_sct

* [*] Is there a issue open describing the motivation for this pull request ?
Added the necessary code to copy {SCT_DIR}/documentation/imgs/* , this would avoid the import error for sct_plugins (flseye) 
Implements or Fixes #1868

SCT logo is now being copied to the installation folder {SCT_DIR}

---

install/sct_launcher

* [ *] Is there a issue open describing the motivation for this pull request ?
#1827 
* [* ] Does the pull request need additional test(s) ?
Added total execution time in parent call (sct_launcher) to display the execution time for all sct_* modules.
Please ignore formatted imports (I'm using isort)
Implements or Fixes #1827

Added total execution time in sct_launcher to display time for sct_* modules

---

README.md

* [*] Is there a issue open describing the motivation for this pull request ?
* [*] Clean up the warnings generated by the [style guide](https://www.jetbrains.com/help/pycharm/2017.1/code-inspection.html)
Update README.md,Removing the VM usage and include the installation on Windows, using Docker
Implements or Fixes #1873

Update README.md, Installation on Windows, using Docker

---

scripts/sct_utils.py

sct_label_vertebrae: Added subcortical colormap for fslview

---

scripts/sct_testing.py

… function from SCT as well.
* [*] Is there a issue open describing the motivation for this pull request ?
* [*] Does the pull request need additional test(s) ?
Removing `sct_register_graymatter` function from `sct_testing`
Implements or Fixes #1900 
Future work: remove the function from SCT as well.

Removed sct_register_graymatter (obsolete old code) from sct_testing functions

---

scripts/sct_flatten_sagittal.py

sct_flatten_sagittal: Fixed wrong indexation

---

CHANGES.md

updated CHANGES for v3.2.3

---

scripts/sct_propseg.py

Right now the entry point of `sct_propseg` is in `if __name__ == "__main__"` which mandates running it as a subprocess.
This PR brings a "quick & dirty" (the amount of changes was minimized and options still have to be passed with a dictionary) way of doing:
```
import sct_propseg
im_seg = sct_propseg.propseg(im_src, ...)
```
Fixes #1966.

sct_propseg: add lightweight Python API (#1966)

---

scripts/sct_apply_transfo.py
testing/test_sct_register_to_template.py

sct_apply_transfo: fixup image check for something that could be something else than an image

---

scripts/sct_get_centerline.py
spinalcordtoolbox/image.py

sct_get_centerline: fixup image refactoring issues

---

CHANGES.md

Updated CHANGELOG for release v3.2.4

---

CHANGES.md

Updated CHANGES.md for v3.2.6

---

CHANGES.md

Updated CHANGES.md for v3.2.7

---

spinalcordtoolbox/reports/assets/_assets/js/main.js
spinalcordtoolbox/reports/assets/index.html
spinalcordtoolbox/reports/qc.py

Various improvements on the QC html report, including:
- Now possible to use keyboard shortcuts. Fixes #1709
- Now possible to use "search" module. Fixes #2029
- Removed µm on the time, changed "contrast" by "file", added message about keyboard shortcuts up/down. Fixes #2090

Various improvements

---

batch_processing.sh
scripts/sct_download_data.py

Fix small regression bug in ``batch_processing`` which was introduced by #2075

batch_processing: Fix regression bug

---

scripts/sct_extract_metric.py
spinalcordtoolbox/aggregate_slicewise.py
unit_testing/test_aggregate_slicewise.py

Output volume fraction on csv.
Fixes #2121

Output volume fraction on csv

---

spinalcordtoolbox/aggregate_slicewise.py

aggregate_slicewise: save_as_csv: add header if file does not exist

---

scripts/sct_deepseg_sc.py
testing/test_sct_analyze_texture.py
testing/test_sct_label_utils.py

- Fixed a few PEP8 issues (mostly alignment)
- deep_segmentation_spinalcord() now using Image() for i/o
- generate_qc() now using Image() for i/o
Total processing time (with -qc): ~2 min 35 s --> ~1 min 51 s
Fixes #2128

Refactored to improve speed and clarity

---

CHANGES.md

CHANGES.md: Updated for v4.0.0-beta.0

---

CHANGES.md

CHANGES.md: Updated for v4.0.0-beta.1

---

CHANGES.md

CHANGES.md: Updated for v4.0.0-beta.2

---

scripts/isct_test_ants.py

Replaced logger with printv

---

CHANGES.md

CHANGES.md: Updated for v4.0.0-beta.3

---

CHANGES.md

Jca/4.0.0 beta.4

---

CHANGES.md

CHANGES.md: Updated for v4.0.0-beta.5

---

spinalcordtoolbox/centerline/core.py

This Pull Request fixes issue #2258, which is related to calculating the straightening transformation based on the centerline fitting.
The PR also adds some QC capabilities for fitting, including the derivatives of the fitting. The QC is only available in the temporary folder when using the option `-v 2`.
Fixes #2258

Fixing straightening when using NURBS 

---

spinalcordtoolbox/reports/assets/index.html

Automatically sorting by date after loading index.html (Fixes #2282)

Added automatic data sorting in the QC report

---

scripts/sct_crop_image.py

- Changed matplotlib backend to tkagg to allow the GUI utilization.
- Changed the imsave function as it will disappear in the next scipy version. 
Fixes [#2319](https://github.com/neuropoly/spinalcordtoolbox/issues/2319)

Fixed bug when using GUI (flag -g)

---

dev/sct_average_multiecho.sh
dev/sct_correct_header_mosaic.sh

Addresses part of #2347
Vars written with this format `${var}` have been changed to this format `$var`
A square bracket has been added to if statements with single square brackets.
- `sct_average_multiecho.sh`
- `sct_correct_header_mosaic.sh`

Naming and conditionals refactor for /dev scripts

---

dev/githook/install_pre_commit_hook.sh
dev/githook/remove_pre_commit_hook.sh

Addresses part of #2347
A square bracket has been added to if statements with single square brackets.
- `install_pre_commit_hook.sh`
- `remove_pre_commit_hook.sh`

If statements refactor on git hooks

---

batch_processing.sh

Addresses part of #2347
Vars written with this format `${var}` have been changed to this format `$var`
A square bracket has been added to if statements with single square brackets.
- `batch_processing.sh`

Refactor on batch_processing.sh

---

install_sct
scripts/argparse.bash

- `argparse.sh` has been added
- `install_sct` has been refactored to use `argparse`
Adresses #2348

Add argparse module on shell scripts

---

README.md

I took the closest release to the course date.
Fixes #2341

update sct version for associated courses

---

scripts/sct_maths.py

This PR is an addendum to this previously-merged PR: https://github.com/neuropoly/spinalcordtoolbox/pull/2371.
The function `sct_maths` needed further modifications. 
Fixes #2380

sct_maths: Fixed input args for -sub and -div

---

CHANGES.md

CHANGES.md: Updated for 4.0.0

---

README.md

README: Updated references

---

CHANGES.md

CHANGES.md: Updated for 4.0.1

---

scripts/sct_download_data.py

A bug was introduced by #2425. This PR fixes it (Fixes #2448)

Fixed that appeared when copying unzipped files if destination files already exists

---

scripts/sct_download_data.py

fixed another issue related to #2449

Fixed: removed destination file if exist did not have full path

---

spinalcordtoolbox/reports/assets/_assets/js/bootstrap-table.min.js
spinalcordtoolbox/reports/assets/_assets/js/main.js
spinalcordtoolbox/reports/assets/index.html

Fixes #2476,  up/down dysfunction when search mode is activated. 
Replaced the html search input with bootstrap-table's embedded search input.

Fixed up/down dysfunction in the qc report 

---

install_sct

Various improvements during installation. Notably:
- Refactored installation to clarify usage of various shells
- Added compatibility with zshrc. Fixes #2492, Fixes #2493 
- Made sure .zshrc is sourced. Fixes #2481
- Fixed message "installed successfully" when CTRL+C during question

Various fixes during installation, added support for zshrc

---

CHANGES.md

CHANGES.md: Updated for 4.1.0

---

CHANGES.md

CHANGES.md: Updated for 4.1.1

---

README.md

Added info on README for using SCT via VirtualBox. See e.g. http://forum.spinalcordmri.org/t/error-when-install-sct/247/14

Added info for running SCT via Vbox

---

README.md

README: Added entry to London course

---

CHANGES.md

New release 4.2.1

---

CHANGES.md

CHANGES.md: Updated for 4.2.2

---

shell/sct_run_batch.sh

DONE: 
- flag to decide to use GNU parallel (or not) in sct_run_batch. The flag does not have to be used for the moment.
TODO:
- I will better document the use of the flag for the user if this is the fix to be made
Fixes #2610

GNU parallel flag -p added. 

---

spinalcordtoolbox/download.py

Some cleanups I found during #2668, but pulled out separately.
This **depends on** #2700.

sct_download_data safety checks

---

.travis.sh
.travis.yml
install_sct

WIP PR for testing SCT on WSL via travis.
So far failing, got to the point of having and being able to run the ubuntu binary, however failing to attach the tty to the main travis git-bash session. 
When done, will fix #2691

CI for WSL (2691)

---

CHANGES.md

Bumped version to 4.3

---

README.md

Added reference in README

---

documentation/source/conf.py

This fixes the rendering of the `API` section in the rst docs: https://spinalcordtoolbox.com/en/aj-fix-docs-api-render/dev_section/api.html

Fix docs API section rendering.

---

LICENSE

Fixes #2824.
I think this is self-explanatory. :stuck_out_tongue: 
Source used: https://www.gnu.org/licenses/lgpl-3.0.txt

Update LICENSE to LGPLv3

---

.ci.sh
.travis.sh

Run batch_processing if building master

---

conftest.py

closes #2902
closes #2907
after #2909

pytest: download test data before test collection

---

scripts/sct_image.py

sct_image: -copy-header should use -o as output file

---

scripts/sct_check_dependencies.py

sct_check_dependencies: use psutil instead of subprocess

---

documentation/source/user_section/installation.rst

Fixes #2970.
Link updated here: https://spinalcordtoolbox.com/en/jn-2970-fix-rtd-changlog-link/user_section/installation.html#install-from-package-recommended

Switch CHANGES.md hyperlink to document reference

---

spinalcordtoolbox/centerline/nurbs.py
spinalcordtoolbox/centerline/optic.py
spinalcordtoolbox/deepseg_sc/core.py
spinalcordtoolbox/image.py
spinalcordtoolbox/qmri/mt.py
spinalcordtoolbox/reports/qc.py
spinalcordtoolbox/straightening.py
spinalcordtoolbox/utils/shell.py
spinalcordtoolbox/vertebrae/core.py

API should use logging, not `printv`.
At the same time cleanup dead code and imports here and there.
Closes #2809

Use logger in API code, not printv.

---

documentation/source/user_section/installation.rst

Fixes #3001.
These instructions are identical to what was done in #2952. This simply restores the work that was accidentally removed.

Restore WSL Win10 installation instructions 

---

unit_testing/test_deepseg.py

Fixes #3009 
Re-adds needed subpackage module imports to fix failing tests.

Restore subpackage module imports to fix test errors

---

CHANGES.md

Updated CHANGES for 5.0.0

---

CHANGES.md

Generated by `changelog`. Needed for new patch.

Update CHANGES.md for 5.0.1 release

---

documentation/source/overview/references.rst

Add URL for Burke et al.
Fixes https://github.com/neuropoly/spinalcordtoolbox/issues/3058

Fix link reference

---

spinalcordtoolbox/scripts/sct_label_vertebrae.py

After #2966
Closes #2976 
As per suggestion: https://github.com/neuropoly/spinalcordtoolbox/issues/2976#issuecomment-718058597

Obsolete -denoise functionality

---

spinalcordtoolbox/compat/launcher.py

This PR sets an environment variable to prevent user site packages from being used over SCT's installed package versions.
Re: the two unchecked checklist items, I don't think there's any relevant tests/documentation that could be added regarding this change. This is a difficult thing to test! 
Fixes #3067.

Set PYTHONNOUSERSITE=True to prevent user site packages from interfering

---

documentation/source/dev_section/api.rst
spinalcordtoolbox/flattening.py
spinalcordtoolbox/labels.py
spinalcordtoolbox/math.py

Documentation fixes

---

spinalcordtoolbox/deepseg/models.py

The following changes were made:
- New model for multiclass (tumor, edema, cavity) tumor segmentation is added.
- The following models are updated with new patch size and stride parameters: findcord_tumor, t2_tumor.
- Only github URLs are kept for new models

Update tumor segmentation models

---

documentation/source/overview/concepts/quality-control.rst
documentation/source/overview/concepts/spaces-and-coordinates.rst
spinalcordtoolbox/download.py
spinalcordtoolbox/registration/register.py

`“` causes issues. Replace with `'`.
Part of fixing #3128.

Replace troublesome unicode quote characters with more friendly ones

---

spinalcordtoolbox/scripts/sct_straighten_spinalcord.py

~~- [x] I've consulted [SCT's internal developer documentation](https://github.com/neuropoly/spinalcordtoolbox/wiki) to ensure my contribution is in line with any relevant design decisions~~
~~- [x] I've added [relevant tests](https://github.com/neuropoly/spinalcordtoolbox/wiki/Programming%3A-Tests) for my contribution~~
~~- [x] I've updated the [relevant documentation](https://github.com/neuropoly/spinalcordtoolbox/wiki/Programming%3A-Documentation) for my changes, including argparse descriptions, docstrings, and ReadTheDocs tutorial pages~~
Made sct_straighten_spinalcord .add_argument parameters more readable.
Fixed -ldisc_input and -ldisc_dest to -ldisc-input and -ldisc-dest throughout script to be consistent.
Resolves #3089

Readability of parameters. Fixed -ldisc-input and -ldisc-dest typos

---

documentation/source/_static/css/custom.css
documentation/source/overview/references.rst

Previously, references for CLI tools and Template/Atlas were provided in an unordered list. It was unclear which references referred to which parts of SCT, so this PR creates tables to make it clearer.
Fixes #3118.

Organize "Specific references" into clearer tables 

---

README.md
documentation/source/index.rst

title is self-explanatory (i hope)

Updated badge from travis.org to travis.com

---

spinalcordtoolbox/scripts/sct_propseg.py

Fixes inconsistent behavior where incorrect path would sometimes be returned.
Not sure if it's worth writing a test for, as it slipped by Travis to begin with. :sweat_smile: 
Fixes #3164.

Replace os.path.dirname with pathlib.Path().parent

---

spinalcordtoolbox/scripts/msct_gmseg_utils.py
spinalcordtoolbox/scripts/sct_compute_hausdorff_distance.py
spinalcordtoolbox/scripts/sct_dmri_compute_dti.py

In #3091, I made some mistakes that weren't caught. :sweat_smile: 
* Forgetting to rename `args` to `argv` in one place.
* Forgetting to remove redundant argument parsing in two scripts.
These issues weren't caught due to the large scope of that PR, and the repetitive changes being made across scripts. 
Follows #3091.
Fixes #3085.

Fix bugs introduced by recent init step refactoring pull request

---

install_sct
requirements.txt

This pinned version:
* Does nothing (because it is overridden anyway)
* Wasn't needed in the first place, and 
* Causes an ugly error in `sct_check_dependencies`
So, remove it!
Fixes #3145.

Remove tensorboard==1.14.0 version pinning from requirements.txt

---

CHANGES.md

See https://github.com/neuropoly/spinalcordtoolbox/wiki/Misc%3A-Creating-a-new-release for the steps I'm following.
Batch processing results (Ubuntu):
```
Version:         git-master-cbee58504bb95ebe036f721dd2411c1fb109f437
Ran on:          Linux XPS-15-9560 5.8.0-38-generic
Duration:        0hrs 15min 47sec
---
t2/CSA:          73.87711295363036
mt/MTR(WM):      54.38001524289822
t2s/CSA_GM:      12.487834828856176
t2s/CSA_WM:      64.93830702088249
dmri/FA(CST_r):  0.775626536503328
dmri/FA(CST_l):  0.7800112277757334
```
Batch processing results (macOS):
```
Version:         git-master-cbee58504bb95ebe036f721dd2411c1fb109f437
Ran on:          Darwin Joshuas-iMac.local 19.6.0
Duration:        0hrs 33min 9sec
---
t2/CSA:          73.87711295363036
mt/MTR(WM):      54.41591839176276 …
```

Update CHANGES.md for 5.1.0 release

---

.github/ISSUE_TEMPLATE/config.yml

A quick copy of the same changes made recently in https://github.com/neuropoly/axondeepseg/pull/430/.
N/A.

Add config that links to SCT forum and removes blank issues

---

documentation/source/user_section/installation.rst

* Set `channel_priority` to `strict` to prevent conda's dependency solver from hanging.
* While we're at it, remove `wxPython` install, as it is now a requirement of FSLeyes, as per @mariehbourget's suggestion in Slack.
Fixes #3206.

Update FSLeyes install instructions for Win10/WSL

---

documentation/source/user_section/installation.rst
requirements.txt
spinalcordtoolbox/deepseg/models.py

This PR integrates a new segmentation model to `sct_deepseg`.
This model has been trained on MRI exvivo DWI data provided by @ihattan2020 (University of Queensland - Center of Advanced Imaging). Model was trained with `ivadomed`, including the following features: 2D unet, multiclass (grey and white matters), softseg.
Fixes #3004.

New segmentation model: GM and WM for exvivo DWI data (University of Queensland)

---

documentation/source/overview/references.rst

Add reference Johnson

---

documentation/source/overview/references.rst

Add reference Ost et al.

---

documentation/source/overview/references.rst

Add reference Azzarito et al.

---

spinalcordtoolbox/scripts/sct_download_data.py

Add an entry to `sct_download_data` to install the exvivo template.
Resolves #3280

Add entry to download exvivo template

---

batch_processing.sh

Thanks to @jcohenadad for figuring out the corresponding commands.
I've re-run the commands and here are the QC results produced: [qc_example_data.zip](https://github.com/neuropoly/spinalcordtoolbox/files/6207820/qc_example_data.zip) 
(Filter for "t2s" and look at `sct_register_multimodal`/`sct_warp_template`.)
Fixes #1821.

Update outdated `sct_register_graymatter` command in `batch_processing.sh`

---

requirements.txt
spinalcordtoolbox/aggregate_slicewise.py
spinalcordtoolbox/scripts/sct_extract_metric.py
unit_testing/test_aggregate_slicewise.py

Adds the `-method median` option to `sct_extract_metric`. 
Done:
Fixes #3327

Implemented weighted median

---

spinalcordtoolbox/utils/shell.py
spinalcordtoolbox/utils/sys.py

Fixes https://github.com/neuropoly/spinalcordtoolbox/issues/3362

Print errors at the end, and in red.

---

spinalcordtoolbox/resampling.py

This was a small bug caught by a test in https://github.com/neuropoly/spinalcordtoolbox/pull/3246#discussion_r587616038.
I can confirm that the change makes the test pass on the [`jn/3093-migrate-sct_testing-to-pytest`](https://github.com/neuropoly/spinalcordtoolbox/compare/jn/3093-migrate-sct_testing-to-pytest) branch. (Specifically, [this test](https://github.com/neuropoly/spinalcordtoolbox/commit/5ce88b8a11c263d3f4926c1a43b58d9672c6daab#r50339607).)
Fixes #3294.

Make sure TR parameter isn't lost when resampling 4D images

---

spinalcordtoolbox/image.py
spinalcordtoolbox/scripts/msct_gmseg_utils.py
spinalcordtoolbox/scripts/sct_compute_hausdorff_distance.py
spinalcordtoolbox/scripts/sct_register_to_template.py
spinalcordtoolbox/scripts/sct_smooth_spinalcord.py
unit_testing/test_image.py

Removes the `generate_path` argument found in a few methods (`change_type`, `change_shape`, `change_orientation`) of the `Image` class in `image.py`. 
Rationale is that `generate_path` does too much + it has non-obvious side-effects (voids the image's `absolutepath`). 
Consequently, this shifts the responsibility of saving the image to the caller.
Closes #3304

Remove generate_path from methods in Image class

---

spinalcordtoolbox/moco.py
spinalcordtoolbox/scripts/sct_dmri_moco.py
spinalcordtoolbox/scripts/sct_dmri_separate_b0_and_dwi.py

This PR:
* Uses absolute path for `-bvals`.
* Edits the argparse help descriptions to fix references to `bvals.nii.gz`
I'd like to write a test for this, but the timing of this is a bit tricky, as it would clash with #3373. Once that PR is complete, writing tests should be more straightforward.
Fixes #3374.
Fixes #3375.

Fix `-bvals` filepath handling and update bvals argparse help

---

documentation/source/overview/testimonials.rst

Addresses an email received regarding the wording of one of the testimonials. 
Also fixes other small details using the help of a grammar checker.

Fix missing words in testimonials

---

spinalcordtoolbox/process_seg.py

Instead of checking if image is exactly 0, use a threshold, as resampling can change 0 -> ~0 (e.g. 1e-16).
Fixes #3402.

Prevent metric calculation for empty slices by checking if array is ~0

---

.ci.sh
.github/workflows/test-batch-processing.yml
.github/workflows/tests.yml
install_sct
setup.cfg

This PR is a quality-of-life update for devs. It introduces an assortment of changes to make the test suite easier to read:
* Splits up the CI script into sub-steps (so that we don't have to scroll through the entire install log to see a failing test)
* Adds an option to run `install_sct` _without_ `sct_check_dependencies` (so that it can be run in a separate step, too)
* More thoroughly disables progress bars (which don't render well in GitHub Actions logs)
* Tweaks the pytest options according to the rationale in #3236 
To demo the benefits, I also temporarily added a commit that causes failing tests:
* [Before this PR](https://github.com/spinalcordtoolbox/spinalcordtoolbox/runs/2858759702?check_suite_focus=true) (Try to scroll to a failing test... it's difficult and tedious!)
* [After …

Improve the readability of the test suite

---

contrib/fsl_integration/sct_plugin.py
spinalcordtoolbox/scripts/sct_propseg.py

This PR fixes an assortment of bugs with SCT's FSLeyes integration script. I have tried to manually test where I could, but further testing from a reviewer would be greatly appreciated. :slightly_smiling_face: 
* I plan to update the internal dev docs so that we have a procedure for manual QA (in lieu of automated testing). The idea would be that we could follow the steps before each stable release, just to confirm that the plugin is in working condition.
* Now may also be a good time to rename the script (#3419), however as @jcohenadad notes in https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3419#issuecomment-861512598, we would have to do something about the video tutorial. So, I have left this for now.
Fixes #3426.

Fix FSLeyes script to make it compatible with both FSLeyes v0.34 and v1.0

---

.github/workflows/test-batch-processing.yml
batch_processing.sh
unit_testing/batch_processing/test_batch_processing.py

Before, we indexed using column numbers, which is very fragile to any changes.
So, this PR fixes up both the test (52daee4) and the `batch_processing.sh` script itself (fc51fe5) to prepare for a new column addition in #3429.
Needed for #3429.

Test `batch_processing.sh` values by indexing column name, not number

---

documentation/source/user_section/tutorials/spinalcord-segmentation/sct_deepseg_sc.rst

Fix typo (`sct_deepsec_sc` -> `sct_deepseg_sc`)

---

spinalcordtoolbox/reports/assets/index.html

This PR addresses #3445.
This PR includes:
* A field `FILES_PMJ` for the YAML list generated in QC report for `sct_detect_pmj`
* Modification of `FILES_SEG` for `FILES_REG` for `sct_register_multimodal`, `sct_register_to_template` and `sct_warp_template`.
Resolves #3445

Add QC field in .yml list for `sct_detect_pmj`

---

testing/cli/test_cli_sct_compute_snr.py

I mistakenly merged #3455 too early -- the test needed some changes, but I thought it had already passed. Oops. :sweat_smile: 
Fixes #3470.

Fix-up broken test for `sct_compute_snr`

---

.github/workflows/tests.yml

This PR removes Ubuntu 16.04, relegates 18.04 to our nightly builds, and tests 20.04 as our main Ubuntu test.
Fixes #3450.

Upgrade Ubuntu versions in test suite

---

spinalcordtoolbox/math.py
spinalcordtoolbox/scripts/sct_maths.py
testing/api/test_math.py

…) #3319
Add `-uthr` for upper threshold in `sct_maths` to complement `-thr` (lower threshold). Add corresponding unit test.
closes #3319

Introduce -uthr (upper threshold) to complement -thr (lower threshold) in sct_maths

---

documentation/source/overview/studies.rst

fixed inconsistent description

---

install_sct

This PR fixes an `install_sct` issues specific to WSL. The idea here is to merge this PR first, and backport the (very minimal) fix to SCT v5.4.
Then, we would merge the sister PR (https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/3573) that applies additional fixes to the test suite and documentation. However, we don't need to backport those fixes, as they only need to be applied to `master`.
Fixes #3571.

`install_sct`: Add `touch` fixes to address WSL connection issues

---

.github/workflows/tests.yml
documentation/source/user_section/installation/windows.rst
install_sct

This PR fixes a number of WSL-related issues discovered over the past week or so:
* 458226b5bebb266a67050a49e479d110915a793b: This commit rewrites the WSL instructions so that they address https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3572 and https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3501. 
* Note: I've also tested these steps for both WSL1 and WSL2, and both SCT and FSLeyes worked perfectly for me.
* a477fc6894e73ae2f102aebe7f82d7a9e60ce8f9: This commit fixes an issue specific to our WSL runners (https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3564). 
* By working inside `~`, rather than GitHub Action's default working directory (`/mnt/d/a/spinalcordtoolbox/spinalcordtoolbox`), we avoid the Windows part of the filesystem. (I'm not sure …

Fix multiple WSL issues related to installation and display

---

README.rst

`README.rst`: Fix typo

---

spinalcordtoolbox/gui/widgets.py

Fixes https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3587

Upgrade to Qt5.

---

documentation/source/overview/studies.rst

Fix typo in `studies.rst` (Kinawy -> Kinany)

---

.github/workflows/test-batch-processing.yml
install_sct

Perl is available in all of our supported OS's, and should work identically. So, this avoids the platform-specific issues that come from trying to use 2 different `sed`s.
Fixes #3590.
Closes #3592.

`install_sct`: Replace `sed -i` with `perl -pi -e`

---

install_sct

This improves on whatever PR first added these lines (EDIT: #3339), thanks to @javidcf's tip in https://github.com/conda/conda/issues/7173#issuecomment-884098367

Use a more reliable way to disable USER_SITE

---

spinalcordtoolbox/scripts/sct_deepseg_sc.py

Tiny documentation PR! Should be quick to approve.
Fixes #3607.

`sct_deepseg_sc`: Indicate default value for `-brain`

---

documentation/source/user_section/tutorials.rst

All I've done is export the slides from [this iCloud link](https://www.icloud.com/keynote/0th8lcatyVPkM_W14zpjynr5g#SCT%5FCourse%5F20200121) then uploaded the PDF to [this Google Drive folder](https://drive.google.com/drive/u/0/folders/1QBjDxjTUDZjf3Yxy9bgxoMfHsGyHLXXQ).
Fixes #3613.

Replace SCT Course 2020 iCloud link with Google Drive link

---

documentation/source/user_section/installation/linux.rst

During the installation process we need to decide between Linux or Windows, but Windows Subsystem for Linux (WLS) is a bit between both of them and some people (like me 🤕) follow Linux installation until some problem occur and find out too late that they need to redo all the installation from scratch due to some WSL specific configuration (system folder path problem and display settings actually)
This PR aims to help lost Linux user directly see that a specific section for WSL is existing and redirect them to the good part of the documentation.
No linked issues

Help differenciate Linux and WSL user on install documentation

---

spinalcordtoolbox/reports/qc.py
testing/cli/test_cli_sct_get_centerline.py

This PR:
* Adds QC to the existing `sct_get_centerline` test.
* Fixes a small typo (`alpha=10`) that caused a crash when generating the QC report.
* 882b038999bc3497471a8eb3ef90b66dc395c70b provides a possible solution for [#3625](https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3625)/[#2813](https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/2813).
* Setting `p_resample=None` is also used by other QC report options, so _maybe_ this is good enough? 
* However, there's another idea for a larger refactoring to resampling code for single-voxel masks in order to properly fix this issue (see, [this comment](https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3625#issuecomment-993555070)).
Fixes #3560.

Make sure that the QC report for `sct_get_centerline` displays properly

---

.github/PULL_REQUEST_TEMPLATE.md

The [current link](https://www.neuro.polymtl.ca/software/contributing#pr_labels) is dead, and it looks like [this new link](https://intranet.neuro.polymtl.ca/geek-tips/contributing#pr-labels-a-href-pr-labels-id-pr-labels-a) is the current home of the NeuroPoly lab-wide contributing guidelines.
Resolves #3640

Update broken link in PULL_REQUEST_TEMPLATE.md

---

documentation/source/overview/studies.rst

Add Zhang et al., Taheri et al., David et al.
Requested on https://neuropoly.slack.com/archives/CB27THD2T/p1642547582003200

Add studies citing SCT

---

codecov.yml
spinalcordtoolbox/reports/qc.py

Codecov, by default, adds some strict targets for coverage. But, since we mainly want coverage for informational purposes (to nudge us to be aware of the impact of our changes), the CI failures are quite jarring to see. So, this PR switches codecov to informational mode, so that we get the feedback without the harsh :x: failures.
Resolves #3654.

Switch to 'informational mode' to prevent Codecov failures for small changes

---

documentation/source/index.rst
documentation/source/user_section/pipelines.rst

Added a new `pipelines` section to the documentation to reference the work done on SCT-pipeline github organization and help people find some useful example and contributions.
Fixes #3621

Add new "Pipelines" page to the sidebar of SCT's RTD documentation

---

documentation/source/index.rst
documentation/source/user_section/courses.rst
documentation/source/user_section/tutorials.rst

We wanted to clarify the courses section by creating a new page to avoid asking people to scrolls on tutorials before seeing the courses.
In this context I did multiples changes:
1. Moved `courses` sections of `tutorials` page to a new page
2. Added `SCT Courses` to the nav
3. Rename `Tutorial page` section to `Written tutorial` (to match the format of the `Video tutorial`)
4. Move `Video tutorial` on top of the tutorial page to be more easy to see the content of the page
5. Added a section on the bottom of `courses` and `turorials` to cross reference knowledge bases
Fixes #3665

Split "SCT Courses" and "Tutorials" into two separate documentation pages

---

spinalcordtoolbox/scripts/sct_get_centerline.py
testing/cli/test_cli_sct_get_centerline.py

This PR adds a failing test to reproduce the behavior in #3530, then changes the behavior of the script to stop appending `.nii.gz` (which makes the test pass).
Fixes #3530.

Stop appending `.nii.gz` to the centerline output filepath if `-o` has an extension

---

documentation/source/user_section/courses.rst

Now that all of the typos/nitpicks have been fixed in the SCT Course slides, and the slides have been exported to PDF and uploaded to the drive, this PR adds links to the 2021 SCT course material (pdf, video recording).
Fixes #3614.

Add links to the newly-updated 2021 SCT Course material

---

documentation/source/overview/studies.rst

add Rowald et al.
Requested on: https://neuropoly.slack.com/archives/CB27THD2T/p1645149903772629

add studies

---

.github/workflows/tests.yml
install_sct.bat
requirements.txt
spinalcordtoolbox/compat/launcher.py
spinalcordtoolbox/reports/qc.py
spinalcordtoolbox/scripts/sct_check_dependencies.py
spinalcordtoolbox/scripts/sct_download_data.py
spinalcordtoolbox/utils/sys.py

This PR accomplishes the following 3 tasks:
1. Adds an `install_sct.bat` script that will take care of the necessary steps to install SCT on Windows.
2. Fixes the bare-minimum number of bugs in order to ensure SCT can install correctly on Windows.
3. Adds a native Windows CI runner that installs and tests SCT on Windows.
Note: There will be _many_ test failures on this PR. (There are currently [50 failures in this CI run](https://github.com/spinalcordtoolbox/spinalcordtoolbox/runs/5292198694?check_suite_focus=true), but I've set it up so that the runner will mark as "Passed" as to not cause noise for other PRs, see 096f5c7.)
We do have fixes to get the number of failures from 50 down to ~9~ **0** (see PR #3699), but I'm thinking that we can use this PR as a starting point, then merge the …

Add minimally functional Windows installer and GitHub Actions CI runner

---

spinalcordtoolbox/aggregate_slicewise.py
spinalcordtoolbox/moco.py

This PR applies the fix from https://stackoverflow.com/q/3191528 to solve a Windows-specific bug where an extra CR would be written to the CSV files.
Fixes #3713.

Open CSV files using `newline=''` to fix `\r\r\n` issue

---

testing/api/test_reports.py

This PR uses the platform-agnostic `tmp_path`, rather than the platform-specific `/tmp`.
Fixes #3708.

Replace hardcoded `/tmp` directory with `tmp_path`

---

install_sct.bat

The previously-suggested menu option requires admin access, which means a Standard Windows account wouldn't be able to access this, and thus wouldn't be able to access SCT scripts from the command line.
This change suggests a user-specific menu option instead.
Addresses https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3740#issuecomment-1083316757.

`install_sct.bat`: Use a non-admin way of adding SCT to the PATH

---

install_sct.bat

This is a bugfix for releases, which use `requirement-freeze.txt`, which is the output of `pip freeze` at time of release.
Without these changes, the more open `requirements.txt` would be installed instead of the frozen requirements.
N/A.

`install_sct.bat`: Use `requirements-freeze.txt` if present

---

install_sct.bat

Allows the usage of `install_sct.bat` instead of `install_sct.bat master`
Can be updated for future releases, too.
N/A.

`install_sct.bat`: Add a default value for `git ref`

---

install_sct.bat

This PR avoids an ugly error if the `deactivate` script isn't present (i.e. the script failed prior to `venv_sct` being activated.
N/A.

`install_sct.bat` Only deactivate if script is available on PATH

---

spinalcordtoolbox/utils/shell.py
spinalcordtoolbox/utils/sys.py
testing/api/test_utils.py

This PR provides `display_viewer_syntax` output more suitable to Windows users by outputting commands for ITK-Snap (rather than leaning so heavily on FSL-based viewers).
<details>
<summary> Some sample images </summary>
</details>
Some small refactors were needed to support both Windows (`itk-snap.exe`) and Linux/macOS (`itksnap`), especially given that Linux/macOS users could theoretically have multiple viewers installed, and we don't want to preference one or the other.
Fixes #3745.

Add support for ITK-Snap + multiple viewers to `display_viewer_syntax`

---

spinalcordtoolbox/deepseg/models.py

Added the deepseg model and task for lumbar SC segmentation with T2w contrast from data sent by EPFL.

Add model for T2w lumbar SC segmentation

---

batch_processing.sh

Fix inaccurate comment in `batch_processing.sh`

---

spinalcordtoolbox/scripts/sct_label_vertebrae.py
spinalcordtoolbox/vertebrae/core.py

Some minor refactoring of `vertebrae/core.py`, since I've been looking at this file for issue #3673. Each commit is a small self-contained change.

Code cleanup

---

documentation/source/user_section/installation/windows.rst

This PR tweaks the Windows installation instructions to make the "native Windows" installation method the most prominent method of installing SCT on Windows.
Fixes #3755.

Add Native Windows installation instructions to the `windows.rst` page

---

install_sct

This is less code, more reliable, and less bash-specific and has the same effect: the script ends in the same directory it started in, though the main body runs in the script's directory.
Improves on https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/3660

Replace pushd/popd with cd-in-a-subshell

---

requirements.txt
spinalcordtoolbox/scripts/sct_check_dependencies.py

This is an upstream fix following the recommendations from https://github.com/protocolbuffers/protobuf/issues/10051#issuecomment-1138671075.
This should be undone in #3735. If #3735 is merged first, this PR can be discarded.
Fixes #3801.

`requirements.txt`: Pin `protobuf` to fix upstream Keras issue

---

spinalcordtoolbox/scripts/sct_label_vertebrae.py

As SCT v5.7 is coming up, we can follow-up on the deprecation removal planned in #3706.
Fixes #3706.

Remove deprecation warning for previously-removed `gaussian_std` argument

---

spinalcordtoolbox/scripts/sct_run_batch.py
testing/cli/test_sct_run_batch.py

This PR:
* Does a bit of refactoring to make the filtering behavior a little easier to test.
* Adds a new test that fails for `-include-list` and `-exclude-list`.
* Updates the behavior of `-include-list` and `-exclude-list` to check against the sub-parts of a directory (e.g. `sub-01` within `sub-01/ses-01`)
Fixes #3598.

Modify `-include-list` and `-exclude-list` to check against parts of a directory, too

---

spinalcordtoolbox/scripts/sct_register_multimodal.py

This is a tiny PR to fix an old issue about the quality of logging from `sct_register_multimodal`.
Before:
After:
Fixes #948.

Add dimensions of data to registration logging

---

.github/workflows/create-release.yml
.github/workflows/test-batch-processing.yml
.github/workflows/tests.yml
.readthedocs.yml
install_sct
requirements.txt
setup.py
spinalcordtoolbox/registration/landmarks.py
spinalcordtoolbox/scripts/sct_check_dependencies.py

This PR is a quick, first-draft PR to test how our CI responds to Python 3.8.
I'll mark this as ready for review when I've finished testing things. :)
Fixes #3367.

Upgrade SCT from Python 3.7 to Python 3.8

---

spinalcordtoolbox/image.py

This PR is based off of the comments in https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/3865#discussion_r976422452.
This PR includes the two bugfixes mentioned in that review thread, as well as 2 other small fixes relating to header/image loading.
N/A (Needed for #3865.)

Fix several bugs when loading headers in the `Image` constructor

---

spinalcordtoolbox/moco.py
spinalcordtoolbox/scripts/sct_analyze_lesion.py
spinalcordtoolbox/scripts/sct_compute_mtr.py
spinalcordtoolbox/scripts/sct_concat_transfo.py
spinalcordtoolbox/scripts/sct_deepseg_lesion.py
spinalcordtoolbox/scripts/sct_deepseg_sc.py
spinalcordtoolbox/scripts/sct_denoising_onlm.py
spinalcordtoolbox/scripts/sct_extract_metric.py
spinalcordtoolbox/scripts/sct_run_batch.py
testing/cli/test_cli_sct_merge_images.py
testing/cli/test_cli_sct_process_segmentation.py

Two missing spaces when the parts of the string get concatenated.

Add missing spaces in multiline strings, and missing commas in lists

---

setup.cfg
spinalcordtoolbox/registration/algorithms.py

Our `setup.cfg` contains many legacy settings accumulated over years of development. 
This PR removes all outdated/unused settings, and keeps only the strictly necessary changes.
Fixes #2499.

Remove outdated/unused settings from `setup.cfg`

---

.github/PULL_REQUEST_TEMPLATE.md

Links in PULL_REQUEST_TEMPLATE.md to the wiki's documentation and testing pages were old.
I have updated them.
Fixes #4032

Update PR template links to testing and documentation

---

spinalcordtoolbox/centerline/nurbs.py
spinalcordtoolbox/deepseg/models.py
spinalcordtoolbox/download.py
spinalcordtoolbox/image.py
spinalcordtoolbox/labels.py
spinalcordtoolbox/math.py
spinalcordtoolbox/moco.py
spinalcordtoolbox/registration/algorithms.py
spinalcordtoolbox/registration/landmarks.py
spinalcordtoolbox/scripts/sct_analyze_lesion.py
spinalcordtoolbox/scripts/sct_analyze_texture.py
spinalcordtoolbox/scripts/sct_compute_ernst_angle.py
spinalcordtoolbox/scripts/sct_compute_hausdorff_distance.py
spinalcordtoolbox/scripts/sct_denoising_onlm.py
spinalcordtoolbox/scripts/sct_dmri_display_bvecs.py
spinalcordtoolbox/scripts/sct_dmri_moco.py
spinalcordtoolbox/scripts/sct_image.py
spinalcordtoolbox/scripts/sct_label_utils.py
spinalcordtoolbox/scripts/sct_label_vertebrae.py
spinalcordtoolbox/scripts/sct_maths.py
spinalcordtoolbox/scripts/sct_register_to_template.py
spinalcordtoolbox/scripts/sct_smooth_spinalcord.py
spinalcordtoolbox/scripts/sct_straighten_spinalcord.py
spinalcordtoolbox/scripts/sct_warp_template.py
spinalcordtoolbox/straightening.py
spinalcordtoolbox/types.py
spinalcordtoolbox/utils/fs.py
spinalcordtoolbox/utils/sys.py

This fixes the remaining lints reported by `flake8 spinalcordtoolbox/`. I tried to group and/or describe the changes in the commit descriptions, so this will probably be easier to review commit-by-commit.
There are still 74 lints reported by `flake8 testing/`, but those can be fixed in a separate PR.
Part of #4040, which is a prerequisite for #3963.

Fix flake8 lints

---

spinalcordtoolbox/deepseg/models.py

Originally, this cropping advice was added to the model description. But, this description isn't actually displayed anywhere. Instead, the advice should have been added to the **task** description, which this PR does.
Fixes #4064

Move MP2RAGE cropping comment from "model" description to "task" description

---

CONTRIBUTING.rst

Encode emoji in utf-8

---

spinalcordtoolbox/types.py

Clarify documentation for `compute_vertebral_distribution`

---

documentation/source/user_section/courses.rst

Add link to slides and Youtube video for course 2023

---

spinalcordtoolbox/scripts/sct_run_batch.py

This is super minor PR, adding explicit examples to the `-include-list` and `-exclude-list` arguments.
Fixes #2854 
Fixes #4195

Add examples to '-include-list' and '-exclude-list' flags

---

spinalcordtoolbox/download.py

For more details, see https://github.com/spinalcordtoolbox/PAM50/pull/29. 
Since the upstream PR was already reviewed, and because SCT processes the `template/` folder as whole during `sct_warp_template`, I don't _think_ this PR needs anything more than a rubber-stamp approval? But, still, I'm opening a PR to at least run the test suite before merging to master.
Once this PR is merged, I'll update the changelog PR (https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/4372) accordingly, then ping @mguaypaq for review.
Fixes #4351.

Update PAM50 link to include new `template/PAM50_rootlets.nii.gz` file

---

spinalcordtoolbox/deepseg/nnunet.py

Context: https://github.com/MIC-DKFZ/nnUNet/commit/1315d2f05a2797438b19be6ceae71de48f2b8452
Fixes #4380.

Rename `_gpu` input param to `_device` to match upstream breaking API change

---

spinalcordtoolbox/scripts/sct_extract_metric.py

Fixed path to PAM50 in help example command

---

spinalcordtoolbox/reports/qc2.py

Follow-up for #4427 in `reports/qc2.py`.

Update QC assets when saving the QC report

---

spinalcordtoolbox/deepseg/models.py
spinalcordtoolbox/deepseg/monai.py

This PR aims to update the existing `contrast-agnostic` model to the [latest version](https://github.com/sct-pipeline/contrast-agnostic-softseg-spinalcord/releases/tag/v2.3). This version of the model is trained on healthy subjects and pathologies in the cervical cord. The training data consists of:
* Contrasts: `T1w`, `T2w`, `T2star`, `MTon-MTS`, `MToff-MTS`, `DWI` (averaged), `mp2rage UNIT1`
* Pathologies: multiple sclerosis (MS) patients, compressed spinal cords in degenerative cervical myelopathy (DCM) patients.
The model works well on:
* Spinal cord injury (SCI) lesions 
* GRE-EPI images
* B0 Field Map images
* Lumbar cord
To test this PR, you will need to install SCT from this branch. Here are the steps:
1. Clone the repo`git clone …

Update `contrast-agnostic` SC segmentation model to the latest v2.3 version

---

.github/workflows/automate-changelog-PR.yml

Fixes #4456.
Looking at [the update guide](https://github.com/peter-evans/create-pull-request/blob/main/docs/updating.md), I don't see any changes that would affect us.

Update github action to Node.js 20

---

spinalcordtoolbox/scripts/sct_run_batch.py

I find that the term: "Processing 2 subjects in parallel. (Worker processes used: 1)." is confusing, in that people might think that the parallelization is done with 2 subjects (whereas here, the parallelization is done with one subject only). So I'm suggesting this rephrasing.
This is a nitpick (not related to an issue).

Clarified how many subjects are processed in parallel

---

spinalcordtoolbox/scripts/sct_deepseg.py

`install-task` can still be used (for backwards compatibility), but `-install` will be shown by default in argparse help.
Fixes #4435.

Change `-install-task` arg to `-install`

---

spinalcordtoolbox/deepseg/models.py
spinalcordtoolbox/download.py
spinalcordtoolbox/scripts/sct_deepseg.py

`source.json` sample:
```json
{
"model_urls": {
"t2star_sc": [
"https://github.com/ivadomed/t2star_sc/releases/download/r20231004/r20231004_t2star_sc.zip",
]
}
}
```
JSON sidecar sample (for `test_segment_nifti`):
```json
{
"GeneratedBy": [
{
"Name": "spinalcordtoolbox: sct_deepseg -i t2s.nii.gz -task seg_sc_t2star -o t2s_seg_deepseg.nii.gz -qc qc -thr 0.9",
"Version": "git-jn/4465-track-model-provenance-80171e6d249befbb23e4bdd41c759b870c08fac5*",
"CodeURL": "https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/80171e6d249befbb23e4bdd41c759b870c08fac5/spinalcordtoolbox/scripts/sct_deepseg.py",
"ModelURL": "https://github.com/ivadomed/t2star_sc/releases/download/r20231004/r20231004_t2star_sc.zip"
}
]
}
```
Fixes #4465.
Fixes #3394.

Track `sct_deepseg` model provenance with `source.json` (in model folder) and JSON sidecar (in output)

---

spinalcordtoolbox/scripts/sct_analyze_lesion.py
testing/cli/test_cli_sct_analyze_lesion.py

This PR improves the documentation for the `-f` argument to hopefully make interpreting the `lesion_statistics.xls` spreadsheet easier.
Also, this PR adds a very basic test (to make running `sct_analyze_lesion -f` easier for devs).
Fixes #4394.

Improve documentation of the `-f` argument to make the percentages clearer

---

spinalcordtoolbox/deepseg/models.py

"Model version" is a bit tricky because we use URLs as versions (because multiple assets can be attached to a single GitHub release, and also because of OSF mirrors).
Using the URLs looks like this:
```
Model 'model_seg_sc_contrast_agnostic_softseg_monai' is up to date (Source: https://github.com/sct-pipeline/contrast-agnostic-softseg-spinalcord/releases/download/v2.4/model_soft_bin_20240425-170840.zip
```
It's a bit verbose, but it is very explicit.
Fixes #4518.

Indicate model version in "model is up to date" log message

---

spinalcordtoolbox/scripts/sct_maths.py
spinalcordtoolbox/utils/shell.py
testing/cli/test_cli_sct_maths.py

~~This is a large change, and probably controversial, so I'm opening this PR-upon-a-PR (for #4485) to give @joshuacwnewton a chance to give feedback on whether it's acceptable.~~
~~I haven't tested it yet, but this is the structure I had in mind. Is it overkill, or too much boilerplate?~~
EDIT: It was overkill, but still contained a few minor improvements.

Minor improvements

---

spinalcordtoolbox/reports/qc2.py

Based on the user request from https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4608, this PR swaps the x-axis in the tissue bridges QC to anterior-posterior (from the current posterior-anterior), so that ventral tissue bridges are on the left and dorsal tissue bridges on the right.
<details><summary>master</summary>
</details>
<details><summary>this branch</summary>
</details>
```console
cd $SCT_DIR
git fetch
git checkout jv/4608-swap_x-axis_for_tissue_bridges_qc
git pull
sct_analyze_lesion -m ...
```
[Dummy test data](https://www.dropbox.com/scl/fo/r76whcpwidcxhjymdgyqb/AOdKwznb6NBKAJFC8yykpoY?rlkey=6fgp900vjqr0hbbw2ffn99uvf&dl=1).
Context: https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4608

Swap x-axis in tissue bridges QC

---

spinalcordtoolbox/deepseg/models.py
testing/cli/test_sct_deepseg.py

This PR adds a failing test for the EPI model. Then, it updates the model release to one with the correct `nnUNetTrainer` structure, which will cause the test to pass.
Fixes #4614.

Test EPI model to ensure that it has the correct `nnUNetTrainer` model structure

---

install_sct

Minimizes the time spent debugging issues if users run into this issue again.
Fixes #4623.

Add clearer instructions to fix issue when $SCT_DIR isn't writeable during installation

---

documentation/source/user_section/tutorials/lesion-analysis/lesion-metrics.rst
spinalcordtoolbox/scripts/sct_analyze_lesion.py
testing/cli/test_cli_sct_analyze_lesion.py

This change is very very minor, since apparently we were already writing files in the `xlsx` format, just with an `xls` extension. ([Source](https://stackoverflow.com/a/33032972): _The format of the file xlsxwriter creates is not affected by the extension you give it._)
(In other words, the true source of the `.xls` -> `.xlsx` _format change_ was #4091, when we first adopted `xlsxwriter`.)
Fixes #4664.

Update extension of lesion analysis spreadsheet from `.xls` to `.xlsx`

---

spinalcordtoolbox/scripts/sct_register_to_template.py

This PR includes the latest method for rootlets-reg to template:
* Using rootlets mid-points in the straightening process
* Refining with the masked image bspinesyn reg

Include rootlet reg2template straight refined version to method

---

spinalcordtoolbox/reports/qc2.py
spinalcordtoolbox/scripts/sct_deepseg.py

This PR adds a possibility to perform sagittal QC for `sct_deepseg`. It displays the entire field of the view without any cropping.
Fixes #4705.

Add `-qc-plane` flag to allow switching the QC view to `'Sagittal'`

---

spinalcordtoolbox/deepseg/models.py

Since I have a new release for the canal segmentation nnU-Net, slightely improving the model, I wanted to update it in SCT. So I switched the last model url that was corresponding to this [release](https://github.com/ivadomed/model-canal-seg/releases/tag/r20241031), to the new latest [release](https://github.com/ivadomed/model-canal-seg/releases/tag/r20241126). 
Here is the linked [issue](https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4718)

Updated canal segmentation model url 

---

spinalcordtoolbox/deepseg/inference.py

The aim of this PR is to make totalspineseg usable with GPU
https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4721

provide torch device to totalspineseg

---

documentation/source/overview/studies.rst

Cumulative totals are more impressive than year-by-year counts.
Link goes here: https://docs.google.com/spreadsheets/d/e/2PACX-1vSwyEvoiTOMflrJveD277xWYSb_1QSwkpxWsZoMSucgHBS7BHcgfvzGG21--1bLRFO_DIV4EhL9lBl2/pubchart?oid=776089160
Fixes #4731.

Embed graph for cumulative citation totals

---

spinalcordtoolbox/reports/qc2.py

Request by @sandrinebedard.
Before: 
After: 
Fixes #4735.

Fix softseg QC by using only a single transparency value (`alpha=1.0`)

---

spinalcordtoolbox/scripts/sct_warp_template.py
spinalcordtoolbox/utils/shell.py

For the following command:
```
sct_deepseg -task seg_sc_lesion_t2w_sci -i t2_fake_lesion.nii.gz
```
Two segs are output (SC seg, lesion seg). Comparing the FSLeyes commands before and after this PR...
Before (both red):
After (one red, one blue):
Fixes #4693.

Use different colormaps for subsequent segs when combined into 1 FSLeyes command

---

documentation/source/overview/studies.rst

Unnecessary duplication-- sorry, in my previous request i should have mentioned that my suggestion was to replace (not add) cumulative counts--.
Fixes https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4731.
Supersedes #4733.

Removed count per year

---

.github/workflows/create-release.yml
.github/workflows/release-body.md
.github/workflows/test-batch-processing.yml
.github/workflows/tests.yml
documentation/source/user_section/installation/windows.rst

This PR addresses the upcoming deprecation of Ubuntu 20.04 runners.
(Side note: This PR might be a cool excuse to test that "compare cross-platform results" feature I made. We could see if the batch_processing.yml results change from Ubuntu 22.04 to 24.04?)
Fixes #4792.

Upgrade Ubuntu 20.04 -> 22.04/24.04 in test suite

---

.github/workflows/test-batch-processing.yml
testing/conftest.py

This PR is a follow-up to:
- https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/4759
In that PR, because the workflow hadn't been merged yet, comparisons could only be done between platforms. But, now that it's been running on `master` for a few weeks, we can compare the results of PRs against the cached results from master.
Follow-up to #4759.

Compare new `batch_processing.sh` file summaries between PRs and `master` branch

---

spinalcordtoolbox/scripts/sct_apply_transfo.py

Direct response to https://github.com/ivadomed/ms-multi-spine-challenge-2024/pull/13#discussion_r2013788948.
N/A

Amend argparse help of transform tool to make `-d` and `-o` arguments clearer

---

spinalcordtoolbox/download.py
spinalcordtoolbox/scripts/sct_compute_compression.py
testing/cli/test_cli_sct_compute_compression.py

This PR updates the link to download the [PAM50-normalized-metrics](https://github.com/spinalcordtoolbox/PAM50-normalized-metrics) to the latest release, and updates `sct_compute_compression` to use csv files under `spinal_cord` folder, (new location) 
Fixes #4842

Update PAM50 normalized metrics URL to latest release (`r20250321`)

---

spinalcordtoolbox/deepseg/models.py

Update `rootlets` model description wording based on the 2025-05-08 SCT dev meeting discussion.
Context: https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/4895#discussion_r2079936575

Update `rootlets` model description wording

---

spinalcordtoolbox/scripts/sct_register_to_template.py

This tiny PR updates the `sct_register_to_template -lrootlet` help to include ventral rootlets and Th1 level, which were added to the PAM50 rootlets in https://github.com/spinalcordtoolbox/PAM50/pull/34.

Update `-lrootlet` help to include ventral rootlets and Th1 level

---

requirements.txt
spinalcordtoolbox/deepseg/inference.py
spinalcordtoolbox/deepseg/models.py

- Release: https://github.com/ivadomed/ms-lesion-agnostic/releases/tag/r20250626
- Dataset diff: https://www.diffchecker.com/1RvTArxQ/
Fixes #4944.
Fixes https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4959. (Once totalspineseg is updated to allow for upgrading `nnunetv2`)

Update `lesion_ms` DeepSeg model from `r20241101` to `r20250626` (ESMRMB 2025)

---

spinalcordtoolbox/reports/qc.py
spinalcordtoolbox/reports/qc2.py

This PR adds a simple text label in the corner of `sct_deepseg` axial mosaics. The function is only applied in this scope (`qc.py`: `no_seg_seg`, `qc2.py`: `sct_deepseg_axial`), and not elsewhere (i.e. no other axial mosaics, no rootlets/totalspineseg, etc.)
Fixes #4980.

Add slice number in QC report for sct_deepseg function

---

install_sct

This PR adds a new exception for [SC2329](https://www.shellcheck.net/wiki/SC2329), which has the same exception conditions as the existing warning for [SC2317](https://www.shellcheck.net/wiki/SC2317) (i.e. functions invoked in traps).
I think this is a small enough change that it shouldn't really require much scrutiny? I'm mostly opening a PR to ensure the code quality test passes before merging.
Fixes #4999.

Disable false-positive shell check for `SC2329` in `install_sct`
