spinalcordtoolbox/spinalcordtoolbox

- scripts/sct_extract_metric.py
Addresses the case when averaging labels from different clusters with method `map` during `sct_extract_metric` (e.g., `-l sc` or `-l 2,30 -a`).
Also handles the case when metric includes voxels with NaN or negative or negative infinity values.
Testing:
- several combinations of parameters were tested
- Travis didn't report bugs when pushed
- batch_processing.sh was run successfully and metric estimations (MTR, FA, CSA) led to similar results.
> Fix issue #656

- scripts/sct_compute_snr.py
- scripts/sct_dmri_compute_snr.py
sct_dmri_compute_snr.py
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Part of the Spinal Cord Toolbox <https://sourceforge.net/projects/spinalcordtoolbox>
Version: 2.1_dev
DESCRIPTION
Compute SNR in a given ROI according to different methods presented in Dietrich et al., Measurement
of signal-to-noise ratios in MR images: Influence of multichannel coils, parallel imaging, and
reconstruction filters (2007).
USAGE
sct_dmri_compute_snr.py -i <image_nifti> -s <image_nifti>
MANDATORY ARGUMENTS
-i <image_nifti>            Input images to compute the SNR on. Must be concatenated in time.
Typically, 2 or 3 b0s concatenated in time (depending on the method
used).
-s <image_nifti>            Mask of the ROI to compute the SNR in.
OPTIONAL …
> Add new function to compute SNR in diffusion-weighted images in a given ROI according to different methods

- install/requirements/requirementsConda.txt
- scripts/sct_extract_metric.py
This pull request only concerns `sct_extract_metric`. It:
- adds the flag -l to enable to only display and save the estimation results for specific labels
- enables to choose to add the results to a pre-existing Excel file or to overwrite it (flag -overwrite)
N.B.: The second point require the installation of 2 light modules (xlrd and xlutils) that I have specified in requirementsConda.txt. Therefore, an update of `sct_check_dependencies` is required.
> improve sct_extract_metric

- CHANGES.md
- scripts/isct_test_function.py
- scripts/msct_register.py
- scripts/sct_register_multimodal.py
- scripts/sct_register_to_template.py
- NEW: **sct_register_multimodal**: flag smoothWarpXY: regularization of warping field (only for algo=columnwize)
- NEW: **sct_register_multimodal**: flag pca_eigenratio_th: Min ratio between the two eigenvalues for PCA-based angular adjustment (only for algo=centermassrot).
jca_columnwise:
~~~
Testing started on: 2016-11-05 20:11:38
SCT commit/branch: 9732c0035c5bf48704bb5db13c23d53fbc6d9642/(detached from 9732c00)
OS: linux (Linux-3.19.0-71-generic-x86_64-with-debian-jessie-sid)
Command: "sct_register_to_template -i t2/t2.nii.gz -s t2/t2_seg_manual.nii.gz -l t2/labels.nii.gz
Dataset: /mnt/data_shared/sct_testing/large/
GLOBAL RESULTS:
Duration: 2656s
Passed: 94/95
Crashed: 0/95
Mean: {'dice_anat2template': 0.9380718315789475, 'dice_template2anat': 0.9430814526315787, 'duration 
[s]': …
> jca_columnwise

- scripts/sct_dmri_moco.py
By creating a list of Image objects, the object opens the file descriptor.
If the list is larger than the maximum allowed by the OS, the application
crashes. In this case, the function only required a list of file names
instead of a list of Image objects.
> BUG: Open files exceeds the maximum allowed by the OS.

- scripts/sct_utils.py
When writing to file, the print statement will exclude the color
markers from the message.
> Removed the color markers in redirected messages.

- scripts/sct_register_graymatter.py
- scripts/sct_register_multimodal.py
- testing/test_sct_register_multimodal.py
- testing/test_sct_register_to_template.py
Make the 'type' param mandatory for sct_register_multimodal.
Results of batch processing:
On this branch : 
```
t2/CSA:   /Users/saradupont/Neuropoly/process/2016-11-24-issue1034/sct_example_data/t2/t2_seg.nii.gz, 76.753884, 2.049822
mt/MTR:   51, white matter, 387.801068, 33.744919, 0.000000
mt/CSA:   /Users/saradupont/Neuropoly/process/2016-11-24-issue1034/sct_example_data/mt/dorsal_column.nii.gz, 20.052757, 1.286250
dmri/FA:  4, WM left lateral corticospinal tract, 22.799808, 0.734177, 0.000000
dmri/FA:  5, WM right lateral corticospinal tract, 20.828494, 0.790546, 0.000000
```
VS 
On master: 
```
t2/CSA:   /Users/saradupont/Neuropoly/process/2016-11-24-issue1034/sct_example_data/t2/t2_seg.nii.gz, 76.753884, 2.049822
mt/MTR:   51, white matter, 387.801068, 33.744919, 0.000000
mt/CSA: …
```
> Fix Issue #1034

- scripts/sct_label_vertebrae.py
- scripts/sct_maths.py
Fix issue #1054 
- Add option to compute normalized mutual information in `sct_maths`
- move function `calc_mi` from `sct_label_vertebrae` to `sct_maths` to avoid code duplication
- output (flag `-o`) can be either a text file (`.txt`) or a pickle file (`.pkl`, `.pklz` or `.pickle`)
- Add option to compute the Pearson's R correlation coefficient between two flatten images in `sct_maths`
> Add option to compute MI

- scripts/sct_register_multimodal.py
Related to issue #1034 : 
- keep a param by default with `step=0,[...]:step=1,[...]` (when the user **doesn't** set the flag -param)
- force `step=x` to be mandatory (when the user **does** set the flag -param)
> sct_register_multimodal: make 'step' mandatory 

- scripts/sct_utils.py
> OPT: utils: use printv to avoid color markers printout

- scripts/isct_test_function.py
With `-v 2` the results of `isct_test_function` are represented with a violin plot. 
The distribution of all metrics is plotted, if no metrics are outputted with a test, only the processing time is plotted. 
--> This will be useful to compare results of two branches (for example as in issue #1059) 
Example of result for `sct_segment_graymatter` on `sct_testing/large`:
Example of result for `sct_propseg` on the t2s of 4 subjects :
> Display results of isct_test_function

- scripts/sct_register_graymatter.py
Minor changes to `sct_register_graymatter` as suggested in issue #1080 :
- output name is now `XX_reg_gm.nii.gz` with XX, the input warping field name. 
- description is now: 
"Registration function to improve the template registration by accounting for the gray and white matter shape using a multi-label approach. Output is a warping field from the template to the target image accounting for the gray matter shape. If -winv is used, output also includes the inverse warping field (from the target image to the template) that accounts for the gray matter shape."
> Fix issue 1080

- install/requirements/requirementsPip.txt
- install_sct
- scripts/sct_check_dependencies.py
- scripts/sct_download_data.py
In some installations, CURL might not be updated, and might not have wget,
downloading from OSF will fail. Instead of using CURL or wget, we will use
the python request module with the security option to download the binaries.
The installation still depends on CURL or wget to download conda, if the
installation of conda fails, we have no other option then to recommend the
user to update their system.
Fixes #1107
> Downloading the binaries using the python module instead of CURL

- scripts/sct_segment_graymatter.py
Bug was that background value of WM segmentation was not null, inducing a bias when computing WM CSA. 
--> Bug occurred during the interpolation of WM segmentation back into the native image space.
--> Corrected by setting negative values to zero right after the label fusion (only very few voxels had negative values).
> [sct_segment_graymatter] correct background value

- scripts/msct_nurbs.py
- scripts/msct_smooth.py
- scripts/sct_process_segmentation.py
- scripts/sct_straighten_spinalcord.py
I added some checking for accuracy on centreline fitting, particularly for NURBS fitting. When the fitting is not accurate enough (threshold arbitrarily set to 5 mm (or pixel)), the segmentation is not fitted (the derivative is computed directly on the segmentation center of mass per slices.
Note that this is a convenient fix for issue #1118 but all functions related to fitting, centerline and smoothing should be refactored as many temporary rules have added in the code over time.
> Improve robustness of segmentation fitting 

- scripts/sct_download_data.py
Replace the regex with the parse_header function. Also removed the old
download function.
Fixes #1144
> Changed the algorithm to fetch the download filename

- scripts/sct_propseg.py
Making the input path explicit, it makes the code easier to debug, but special
characters in the path might cause errors if passed into command. Wrapping the
path in double quotes solves this problem.
> Make the input file path explicit

- scripts/sct_straighten_spinalcord.py
Bug appeared in `sct_process_segmentation` using `-p csa`: 
--> Due to the nurbs fitting of centerline in `sct_straighten_spinalcord`: when the nurbs fitting is not accurate enough (MSE too high), the fitting results are not used and the original centerline coordinates are kept as a list instead of a numpy array. 
--> This caused `sct_process_segmentation` to fail when using the centerline coordinates as a numpy array.
> Correct type of list output 

- scripts/sct_propseg.py
This pull request fixes the issue introduced in commit 26ebdd9.
The problem was a confusion on the names of command. It only appeared when using the viewer.
> Removed confusion with command variables when using PropSeg viewer

- scripts/sct_propseg.py
- scripts/sct_viewer.py
This Pull Request made improvements on `sct_viewer` and `sct_propseg`.
1. The viewer when initializing `sct_propseg` with a three-point mask not allows to select the central slice with the `-init` option. The number of the mid-slice is assumed in the RPI orientation, even though the visualization is made in SLA orientation. That means that the slice "20" is the 20th slice from the bottom of the image (direction inferior --> superior).
This fixes issue #1125 
2. fixed a bug on the function `check_and_correct_segmentation` called at the end of `sct_propseg`. It now allows the correction on the real centerline, even if it has a small coverage of the image.
This fixes issue #1166
> Improvements of viewer with sct_propseg

- scripts/sct_segment_graymatter.py
default -vertfile is `label/template/PAM50_levels.nii.gz` (even when flag is not used), if it does not exist, GM segmentation is done without vertebral information (as with -vertfile None)
--> Fix issue #1172
> Fix issue #1172: -vertfile as an optional parameter

- scripts/sct_extract_metric.py
This feature renders ```sct_average_data_within_mask``` obsolete. We might want to remove it at some point.
Fixes https://github.com/neuropoly/spinalcordtoolbox/issues/1174
> Now possible to extract metric using a single label file

- scripts/isct_test_function.py
In the results display at the end of `isct_test_function` the mean was shown a second time instead of the standard deviation.
> OPT: display mean and std instead of mean twice

- scripts/sct_merge_images.py
~~~
Merge multiple source images onto destination space. All images are warped to the destination space and then added.
To deal with overlap during merging (e.g. one voxel in destination image is shared with two input images), the
resulting voxel is divided by the sum of the partial volume of each image. For example, if src(x,y,z)=1 is mapped to
dest(i,j,k) with a partial volume of 0.5 (because destination voxel is bigger), then its value after linear interpolation
will be 0.5. To account for partial volume, the resulting voxel will be: dest(i,j,k) = 0.5*0.5/0.5 = 0.5.
Now, if two voxels overlap in the destination space, let's say: src(x,y,z)=1 and src2'(x',y',z')=1, then the
resulting value will be: dest(i,j,k) = (0.5*0.5 + 0.5*0.5) / (0.5+0.5) = 0.5. So this function acts like a …
> Merge multiple source images onto destination space.

- scripts/sct_process_segmentation.py
> Fixed data type issue in process_segmentation

- MANIFEST.in
- setup.py
Spinalcordtoolbox will be added to the python's system path by running
python setup.py install
or for setting up the development environment by running
python setup.py develop
This does not change the installation process of spinalcordtoolbox
> Introduction to spinalcordtoolbox setup

- install/sct_launcher
This is a good thing to add in the laucher anyway since it isolate completely the sct install.
> add PYTHONNOUSERSITE=1 in sct_laucher

- scripts/sct_qc.py
Changing the path before copying the assets was calculating the path
incorrectly.
Fixes #1278
> Fix the handling of the path of the QC report.

- install_sct
The variable SCT_SOURCE is the path of the spinalcordtoolbox while SCT_DIR
is the destination directory.
Fixes #1288
> Incorrect variable when installing SCT in a different directory

- scripts/sct_register_to_template.py
Fixes https://github.com/neuropoly/spinalcordtoolbox/issues/1168.
Fixed by removing the check. 
In the future, we need to check if registration works if images have different matrix. If not, then we need to check for it.
> Fixes case if data image, segmentation and labels are not in the same space

- install/requirements/requirementsPip.txt
- scripts/sct_download_data.py
Switching to `tqdm` for progress bars, it works also inside Jupyter notebooks, macOS and *nix environment terminals. This new change will also show the **remaining time** and it will automatically scale the units (bytes/kb/mb, etc).
> Show remaining time status for downloads (#1298)

- scripts/sct_download_data.py
This is a rework of the PR #1299, ref. issue #1298.
Fixed the issue with the "download complete" message appearing before `tqdm` flush buffers.
> Rework for the remaining time display (pull-request #1299)

- scripts/sct_propseg.py
Fixes issue #1322
The -init only accepted values between 0 and 1 when providing a centerline (which is the default case with OptiC). I modified the -init value that is passed to isct_propseg and it now works.
> Allow more init value for propseg

- scripts/msct_shape.py
- scripts/sct_process_segmentation.py
The spinal cord shape symmetry feature is available as part of `sct_process_segmentation -p shape`. As represented on the image below, the shape symmetry is computed by flipping the right half of the spinal cord segmentation on the left half and computing their dice coefficient (values between 0 and 1, 1 representing perfect symmetry), while taking into account the spinal cord rotation.
Credit: Allan R. Martin
Related to issue #1030.
> Introducing spinal cord shape symmetry

- scripts/sct_get_centerline.py
- scripts/sct_propseg.py
- spinalcordtoolbox/centerline/optic.py
Fixing an issue that @peristeri found with the `-init` parameter, this issue was introduced with the creation of the `sct_get_centerline`.
> Fixing an issue introduced with the sct_get_centerline.

- scripts/sct_get_centerline.py
- scripts/sct_process_segmentation.py
- spinalcordtoolbox/centerline/optic.py
This pull request introduces the generation of centerline as ROI, readable by JIM (http://www.xinapse.com/Manual/index.html) so that we can automatize the CordFinder tool (spinal cord segmentation method developed by Horsfield et al.).
For now, only `sct_process_segmentation` allow to generate a ROI based on a segmentation or a centerline, using the following command:
```
sct_process_segmentation -i my_segmentation.nii.gz -p centerline
```
`sct_get_centerline` should also integrate this option.
> Generation of centerline as ROI

- install_sct
new numpy 1.13.0, crashes the sct.
> Force numpy 1.12.1 on osx and linux

- scripts/sct_propseg.py
See issue #1323 
At the creation of the option `-init-mask` in `sct_propseg`'s parser, add `viewer` to the list of the possible inputs that shouldn't be considered as an image. 
Fixes #1323 
With that fix, the option `-init-mask` of `sct_propseg` works but the position of the slices displayed by the viewer is not adapted to the use of `-init-mask` in `sct_propseg` (the viewer displays only three slices from the top of SC).
> The init-mask accepts "viewer" as a value

- scripts/sct_extract_metric.py
Default assignment is a list with all slices. 
data on **/Volumes/folder_shared/sct_issues/20170608_issue1241**
command:
~~~
sct_extract_metric -i Dh_reg.nii -f atlas/ -method map -overwrite 1 -output-map test.nii.gz
~~~
Fixes https://github.com/neuropoly/spinalcordtoolbox/issues/1241
> Fixed unassigned variable in case -z or -vert is not used

- scripts/msct_smooth.py
in msct_smooth, l272, change `if z == None ` by `if z is None` as `z` can be a list of coordinates, creating an error during the straightening. 
Error observed when calling `sct_register_to_template` :
> Use a pythonic way to compare a variable as  None

- install/requirements/requirementsConda.txt
In some systems, the pip version of psutil is not properly installed. So far,
conda's version is the most stable.
> Added the dependency psutil in the conda requirements

- install_sct
unset PYTHONPATH and set PYTHONNOUSERSITE=1 at install time 
All that to make sure local python install is not meddling with the sct
Fixes #1373 and #1381 (might be a conflict to merge manually here)
> Ignore using user packages when install with conda and pip

- scripts/sct_register_multimodal.py
Added parameter ``deformation`` to specify restrict deformation
Fixes https://github.com/neuropoly/spinalcordtoolbox/issues/1345
> Now possible to specify restrict deformation for ANTs algo

- scripts/sct_extract_metric.py
A bug was happening when extracting metric from an empty slice: 
```Traceback (most recent call last):
File "/Users/saradupont/Neuropoly/code/spinalcordtoolbox/scripts/sct_extract_metric.py", line 1315, in <module>
main(fname_data, path_label, method, slices_of_interest, vertebral_levels, fname_output, labels_user, overwrite, fname_normalizing_label, normalization_method, label_to_fix, adv_param_user, fname_output_metric_map, fname_mask_weight)
File "/Users/saradupont/Neuropoly/code/spinalcordtoolbox/scripts/sct_extract_metric.py", line 391, in main
combined_labels_value[i_combined_labels], combined_labels_std[i_combined_labels], combined_labels_fract_vol[i_combined_labels] = extract_metric(method, data, labels, indiv_labels_ids, clusters_all_labels, adv_param, normalizing_label, …
```
> BUG: fix bug when slice is empty

- spinalcordtoolbox/reports/qc.py
> Catch the OSError exception thrown when the git command is missing

- scripts/sct_compute_ernst_angle.py
> compute_ernst_angle: set the parameter t1 default value to optional value of 850ms

- scripts/sct_pipeline.py
Get list of subjects by reading data base from excel sheet 
- excel sheet located in `/Volumes/Public_JCA/sct_testing/large/_data_mri.xlsx`  replaces the `.json` files
- new flags : 
- `-spec` : takes the specifications to select subjects with the following format : `"field1=val1,val2:field2=val3:field3=val4,val5"` (for example: `"center=unf,twh:gm_model=0:contrasts=t2,t2s"`)
- `-file-spec` : path to the excel file to read (default = `/Volumes/Public_JCA/sct_testing/large/_data_mri.xlsx`)
- the fields in the specifications can be any column name in the ggsheet
- not case sensitive
- if there is a space in the ggsheet column name, replace it by "_"
- for some fields ( 'contrasts', 'sc seg', 'gm seg', 'lesion seg') the subjects are selected if the field **contains** the requested value (as …
> Get list of subject from excel sheet 

- scripts/sct_dice_coefficient.py
1. Creation of a temp dir and make the process into it
2. Allow to put a path with the flag `-o` (and not only a filename)
3. If it is crashing because of slight difference between the origin of two images, use `sct_register_multimodal -identity 1` + copy header of im_1 to im_2 --> Tested on 5 cases that crashed in the past
Implements or Fixes #1098
> Precision error while calculating Dice coefficient #1098

- install/requirements/requirementsPip.txt
- scripts/sct_resample.py
The current import resample from the `__init__` module instead of `resample` module. This should prevent from importing `scripting` module that imports `matplotlib`
Fixes #1374
> Change import path of resample

- scripts/sct_apply_transfo.py
* Is there a issue open describing the motivation for this pull request ?
https://github.com/neuropoly/spinalcordtoolbox/issues/640
* Does the pull request need an update of the documentation ?
No Need
* Does the pull request need additional test(s) ?
Tanguy & Harris
For 4D images, we do not want to squeeze data along 4th dim --> squeeze_data=False
> crashes if apply transfo on 4d images issue#640

- scripts/sct_apply_transfo.py
- scripts/sct_concat_transfo.py
Allow `sct_concat_transfo` to work on 2D warping fields
When warping field is 2D, use `isct_ComposeMultiTransform` with dimensionality at 2 instead of 3. 
Only the first warping field of the list is check because we assume all the warping fields are in the same dimensionality (i.e. 2D or 3D) to avoid opening them all. 
Fixes #1419
> Adapt concat and apply transfo to work on 2d images

- testing/test_sct_register_to_template.py
This Pull Request fixes a small bug in SCT testing. `test_sct_register_to_template` was changing the standard stdout during the testing and never changed it back, resulting in the loss of display.
Fixes #1428.
> Fixing stdout issue on sct_testing

- scripts/msct_types.py
- scripts/sct_straighten_spinalcord.py
The registration of two images using the straightening and the vertebral levels failed when the disks labels did not contained the PMJ. The PMJ was used as a reference.
Now, an adaptative reference is selected (first or last label) when it is not found in one of the two images.
Running the template generation (https://github.com/neuropoly/template) produced the error when the PMJ label was not included into the input images.
> DEV: fixed bug on centerline when referencing to the PMJ

- install_sct
- scripts/sct_download_data.py
There is two changes done. First, properly catch the errors when downloading data and the second in the installation script, trap the return value when exiting and re-send it.
Fixes #1365
> Properly exit the installation process if error occurs

- scripts/sct_fmri_compute_tsnr.py
- scripts/sct_maths.py
Now using N-1 instead of N as denominator for computing the STD.
Fixes #1440
> Now using N-1 instead of N as denominator for computing the STD.

- scripts/sct_extract_metric.py
We don't know the exact cause of this instability, but for now, we moved this process inside map and ml (because the user uses bin method).
jca_issue1445:
~~~
t2/CSA:   77.336978, 1.698544
mt/MTR:   51, white matter, 2909.539055, 21.950534, 0.000000
mt/CSA_GM:   18.656204, 1.643710
mt/CSA_WM:   60.487054, 2.473967
dmri/FA:  4, WM left lateral corticospinal tract, 72.751803, 0.697896, 0.156813
dmri/FA:  5, WM right lateral corticospinal tract, 74.051164, 0.741508, 0.132873
~~~
master:
~~~
t2/CSA:   77.336978, 1.698544
mt/MTR:   51, white matter, 2909.539055, 21.950534, 0.000000
mt/CSA_GM:   18.656204, 1.643710
mt/CSA_WM:   60.487054, 2.473967
dmri/FA:  4, WM left lateral corticospinal tract, 72.751803, 0.697896, 0.156813
dmri/FA:  5, WM right lateral corticospinal tract, 74.051164, …
> (Partly-)Fixed bug related to memory issue with diagonalization

- scripts/sct_convert.py
- scripts/sct_label_utils.py
- scripts/sct_register_to_template.py
Note: Please note that in this figure, points are located at the posterior tip of discs, whereas in practice, they should be centered in the cord, although this does not have large impact for sct_register_to_template (because there is a realignment based on the cord centerline).
Implements #574
> Now possible to input single label at disc (instead of mid-body)

- scripts/sct_download_data.py
current version of isct_antsSliceRegularizedRegistration does not regularize along Z. Bug was introduced with new version of isct_antsSliceRegularizedRegistration, which accounts for z-rotation. This fix goes back to the previous version with only TxTy
Implements or Fixes #1464
> Fixed z-regularization for slicereg

- scripts/sct_get_centerline.py
This Pull Request introduces a new manual approach to extract the spinal cord centerline from images. The method is straight-forward:
1. open a viewer to click on a few slices (the gap between slices is 10mm by default and can be change using `-gap` option)
2. use smooth_centerline to approximate the centerline with NURBS
3. generate an image with the centerline
On example data:
```
sct_download_data -d sct_example_data
cd sct_example_data/t2/
sct_get_centerline -i t2.nii.gz -method viewer
```
Implements #1461
> sct_get_centerline - new manual feature

- scripts/sct_propseg.py
Fixes https://github.com/neuropoly/spinalcordtoolbox/issues/1484
> Fixes Optic is used by default if -init-mask is used with external file provided

- spinalcordtoolbox/gui/base.py
The actions are bonded to Using the standard OS key bindings.
Linux / Mac OS
Undo => Ctrl+Z / Command+Z
Save => Ctrl+S / Command+S
Help => F1 / Command+?
> Added key bindings to the undo, save and help actions.

- dev/atlas/create_atlas/create_atlas.m
- dev/atlas/create_atlas/parameters_MNIPolyAMU.m
- dev/atlas/create_atlas/parameters_PAM50.m
- scripts/sct_propseg.py
The main modification is that the file `create_atlas.m` is now a function (previously a script) that calls a parameter.m file, which is set for each project
> Refactored WM atlas creation pipeline and improved documentation 

- install_sct
To avoid the re-installation of SCT with every change in master. The development
mode creates a symbolic link to the source code instead of copying the code in
the python module directory.
Only recommended when developing SCT.
> Option to install SCT in development mode

- scripts/sct_propseg.py
- spinalcordtoolbox/gui/base.py
- spinalcordtoolbox/gui/centerline.py
- spinalcordtoolbox/gui/sagittal.py
The filename for the temporary label file did not match with the one used when cleaning up.
Implements or Fixes #1483
> Used the absolute path to create the temporary label file in propseg

- scripts/sct_analyze_lesion.py
New feature requested by Sara & David: compute the percentage of a given tract occupied by lesions
See the example below: excel output by `sct_analyze_lesions`: 
The novelty is the `Total` row. It provides the following information: 12.6% of the tract PAM50_00 is occupied by lesions = Vol_lesionS_in_PAM50_00 * 100. / Vol_PAM50_00_tot
> Improvement of sct_analyze_lesions: compute percentage of a given tract occupied by lesions

- scripts/sct_fmri_compute_tsnr.py
Some of the code was indented too far and wasn't executing. This was corrected.
https://github.com/neuropoly/spinalcordtoolbox/issues/1521
> BUG: sct_fmri_compute_tsnr does not compute tSNR

- spinalcordtoolbox/reports/qc.py
It will be re-implemented once the new way of getting the version of SCT is implemented.
Fixes #1506
> Removed the version from the list of data collected for the QC reports

- scripts/sct_concat_transfo.py
Now using destination image to catch dimension (instead of warping field).
Fixes https://github.com/neuropoly/spinalcordtoolbox/issues/1429#issuecomment-346182256
> BUG: concat_transfo: fixed wrong catch of dimension

- scripts/sct_resample.py
- spinalcordtoolbox/resample/nipy_resample.py
This is a refactoring of the `sct_resample` command-line tool, according to the new API/command-line tool design.
Changes in this PR:
- Moved the `sct_resample` logic code to a new module called `resample` inside the `spinalcordtoolbox` module;
- The `sct_resample` from the scripts folder is now a wrapper around the API;
- In the API we have now two functions called `resample_image` and `resample_file`, the first one will resample a nifti image object and the later will resample from an input file and will output a new file;
- Didn't change the original resampling code;
- `sct_testing` tested it without any issues and I also tested on other images;
> Refactoring of the sct_resample to separate API and command-line tool.

- install_sct
Now we can easily test releases and in-place (within git) installations if needed:
[...] SCT_INSTALL_TYPE=in-place ./install_sct [...]
[...] SCT_INSTALL_TYPE=package ./install_sct [...]
> install_sct: configurable installation type

- scripts/sct_compute_hausdorff_distance.py
https://github.com/neuropoly/spinalcordtoolbox/issues/1557
https://sourceforge.net/p/spinalcordtoolbox/discussion/help/thread/a94ae2b1/
```
cd sct_testing_data/t2
sct_image -i t2.nii.gz -split z
sct_maths -i t2_Z0045.nii.gz -bin 2000 -o test_bin.nii.gz
sct_compute_hausdorff_distance -i test_bin.nii.gz -d test_bin.nii.gz 
```
1) Use `get_orientation` instead of `get_orientation3d`
2) **Problem:** Problem of conversion nifti-->nipy when data is 2D. **Fix:** Create a 3d image by concatenating two 2d images.
Implements or Fixes #[1557]
> Now working for 2d data

- scripts/sct_label_vertebrae.py
- spinalcordtoolbox/gui/base.py
- spinalcordtoolbox/gui/centerline.py
- spinalcordtoolbox/gui/sagittal.py
- Fixed #1570, which was related to a wrong labeling when using flag `-initc2`. 
- Fixed #1563: Added instructions when using `initc2` flag
> Bug fix and various improvements

- scripts/msct_register.py
- scripts/sct_utils.py
> Fix Timer with progress 

- scripts/msct_image.py
This request fixes a very small bug in `msct_image` that was occurring when converting physical coordinates in an image to continuous pixelar coordinates.
> BUG: Fixed a small bug on None condition

- contrib/docker/Dockerfile
- contrib/docker/README.md
This is just a minimal Dockerfile for SCT w/ Ubuntu 16.04. I made for myself but it might be useful for other people when they cannot run SCT on their platform.
> Adding minimal Dockerfile for SCT.

- batch_processing.sh
Check if fslview is executable, and if not set $DISPLAYQC=false.
code was added to check if fslview is an executable.
Implements #1547
> Check if fslview is executable

- CONTRIBUTING.md
Moving the Contributing information from the wiki page into the repository root, so Github can link to it.
> DOC: Moving contributing information to the repository.

- install/tf_distro_check.py
- install_sct
This is a fix for the issue #1645, where SCT installation fails on some distributions.
Since we're starting to have more than one distribution with these issues, I added a new installation check file that would make it easier to add a new distribution later (by adding the distribution name and optionally the version or id).
> [BUG] Fixing the TensorFlow installation for some old platforms.

- scripts/sct_utils.py
Fslview was still called at the end of process, even though the command gives a "deprecated" output.
Solution was to put fsleyes first in terms of priority when calling `sct_utils.display_viewer_syntax`
Fixes #1614
> Fslview no more called at the end of process if it it deprecated

- scripts/sct_straighten_spinalcord.py
This PR implements a bug fix for the issue #1478, related to the lack of checking for a crop region in `sct_straighten_spinalcord`.
Additionally, the PR fixes some print issue for debugging.
Fixes #1478
> Fixing cropping issue in sct_straighten_spinalcord

- scripts/sct_qc.py
This PR will add a new option called `port` into the `sct_qc`. Motivated by the fact the default port (8888) can conflict with other existing services such as Jupyter notebook server.
Closes #1321.
> Adding a port option for the qc server

- scripts/sct_image.py
With the option "-split" the code of line 274 must be executed.
The error was due to a failure in the flow control that executed the code of line 262.
Fixes #1556
> Fix "-split" option issues on sct_image

- install_sct
With that, the installer doesn't continue on failure.
> install_sct: make installer abort on failure (#1541)

- scripts/sct_fmri_moco.py
Previously, metric was MI, which is suboptimal (more prone to error and longer). "MeanSquares" makes more sense for fMRI time series because images have exactly the same contrast.
Fixes #1468
> Set “MeanSquares” the default metric for sct_fmri_moco

- install_sct
If `rm -rf .../python` fails to remove everything (say, user still runs python, or something, and the OS doesn't allow the file removal) the subsequent `mkdir` will fail. So we just `mkdir -p` and hope for the best.
> install_sct: abort on failure without using set -e

- scripts/msct_register.py
- scripts/msct_register_landmarks.py
- scripts/msct_smooth.py
- scripts/sct_deepseg_gm.py
- scripts/sct_deepseg_sc.py
- scripts/sct_detect_pmj.py
- scripts/sct_label_vertebrae.py
- scripts/sct_make_ground_truth.py
- scripts/sct_propseg.py
- scripts/sct_register_graymatter.py
- scripts/sct_register_multimodal.py
- scripts/sct_register_to_template.py
- scripts/sct_segment_graymatter.py
- scripts/sct_smooth_spinalcord.py
- scripts/sct_straighten_spinalcord.py
- scripts/sct_warp_template.py
- spinalcordtoolbox/reports/qc.py
- spinalcordtoolbox/reports/slice.py
- testing/test_sct_deepseg_gm.py
- testing/test_sct_deepseg_sc.py
- testing/test_sct_detect_pmj.py
- testing/test_sct_label_vertebrae.py
- testing/test_sct_propseg.py
- testing/test_sct_register_graymatter.py
- testing/test_sct_register_to_template.py
- testing/test_sct_segment_graymatter.py
- testing/test_sct_straighten_spinalcord.py
- testing/test_sct_warp_template.py
- tests/test_reports.py
This PR brings:
- Make `sct_*` scripts all use the same QC and `-qc /path/to/qc` option.
The commands which were still using the `-qc {0,1}` option:
- `sct_straighten_spinalcord`
- `sct_detect_pmj`
- `sct_warp_template`
- When a command is called with the QC option, pass it along to its children.
- Refactor the QC code to reduce some duplication, and improve clarity a little.
- Make QC known as the abbreviation of QuickCheck. Later we can have consistency with QuickDiff which would generate A/B comparison reports.
How:
- Each `sct_` script that has a QC feature has a `quick_check()` function added, which (normally) takes the inputs and outputs of the process, and generates a quick check entry.
- The function is called from the `main()` or in a context that is the same that uses the …
> Uniformize use of Quick Check and refactor call sites

- scripts/sct_deepseg_sc.py
This issue was reported twice:
- by @stephaniealley : https://github.com/neuropoly/spinalcordtoolbox/issues/1634
- by @SaraDupont : https://github.com/neuropoly/spinalcordtoolbox/issues/1659
```
>>> from msct_image import Image
>>> s_compressed=Image('t2_seg.nii.gz')
>>> type(s_compressed.data)
<type 'numpy.ndarray'>
>>> s_not_compressed=Image('t2_seg.nii')
>>> type(s_not_compressed.data)
<class 'numpy.core.memmap.memmap'>
>>> from scipy.ndimage.measurements import center_of_mass
>>> from msct_image import Image
>>> s_not_compressed = Image('t2_seg.nii')
>>> type(s_not_compressed.data)
<class 'numpy.core.memmap.memmap'>
>>> center_of_mass(s_not_compressed.data)
File "<stdin>", line 1, in <module>
File …
```
> sct_deepseg_sc - Issue when input is .nii instead of .nii.gz

- scripts/sct_flatten_sagittal.py
The usage for flag -s was misleading (centerline only, whereas segmentation could be input). Also, the variable `centerline_fitting` was not used and the `hanning` algo was always used. Now changed, with hanning by default (no change with master), and removed `polynome` (not a viable option).
> Improved doc and minor fixes with centerline fitting

- scripts/sct_label_vertebrae.py
- scripts/sct_process_segmentation.py
https://github.com/neuropoly/spinalcordtoolbox/issues/1734
- Make the function `label_vert` of `sct_process_segmentation` compatible with non-RPI oriented images
- Use the new definition of discs in `sct_process_segmentation`
> Make sct_process_segmentation compatible with the new ldisc convention

- scripts/sct_label_utils.py
If image has 5 dimensions (e.g., RGB from histology converted to nifti: (690, 462, 75, 1, 3)), `sct_label_utils -create` fails. This PR fixes it.
Fixes #1743
> Added a case if image is not 2D or 3D

- scripts/msct_nurbs.py
- scripts/msct_parser.py
- scripts/sct_check_dependencies.py
- scripts/sct_deepseg_sc.py
- scripts/sct_pipeline.py
- scripts/sct_testing.py
- scripts/sct_utils.py
This PR brings:
- Some `sct_pipeline` minor fixes
- Fix for #1745: Mac installation on system where "ps" could print non-ASCII
- Fix for #1708: print Sentry opt-out message after sending a report
- Fix for one Sentry false positive https://sentry.io/neuropoly-k0/sct/issues/557250868 due to capture of a control flow exception
- Fix for many Sentry false positives: events due to users misusing command line arguments are not reported anymore
- Change `sct.__version__` format to be more human-readable (installed package will simply be the package version)
> Random issue fixes (Sentry, sct_pipeline, install)

- scripts/sct_flatten_sagittal.py
Output type is now float32, regardless of input type. This prevents loss of precision when converting back to input type (e.g. if user inputs int16, converting to float32 and then back to int16 will yield loss of precision). The drawback is a potentially larger file. 
Fixes #1790
> Forcing output type to be float32

- scripts/sct_deepseg_gm.py
- spinalcordtoolbox/deepseg_gm/deepseg_gm.py
- unit_testing/test_deepseg_gm.py
This is a pull request to add an enhancement (related issue #1831).
There is now a new parameter on the `sct_deepseg_gm` command-line tool called `-thr` where the user can specify a custom threshold to be applied in the predictions of the model. For backward compatibility, this threshold is always active with the [recommended value of 0.999](https://www.nature.com/articles/s41598-018-24304-3), but now the user can specify a different threshold or even disable it with `-thr 0`.
PS: just fixed some long running strings as well.
> Adding threshold (or not) option for the sct_deepseg_gm

- scripts/sct_image.py
* [* ] Is there a issue open describing the motivation for this pull request ?
`sct.display_viewer_syntax([fname_out])` includes unnecessary type conversion.
Implements or Fixes #1848
> Type conversion error in sct_image, no need to convert list type, this should prevent TypeError

- .travis.yml
- documentation/sphinx/source/development.rst
- install/sct_launcher
- scripts/sct_download_data.py
- scripts/sct_testing.py
This PR brings:
- `sct_testing` usage of multiprocessing (#1539)
- Fix for #1620 (sct_testing TLS memory usage grows beyond limit) (unless `-j 1` is called)
- `sct_testing` usage of argparse (no problem since it's a script used for development only)
- `sct_download_data` to not send Sentry messages (#1844)
- docs
- since coveralls was complaining about coverage... generate coverage info from `sct_testing`
> Misc. development fixes & improvements

- scripts/sct_deepseg_sc.py
This PR will reduce the excessive TensorFlow cpp logging level for `sct_deepseg_sc`.
Closes #1835
> Reducing TensorFlow cpp logging verbosity level for sct_deepseg_sc

- scripts/sct_deepseg_gm.py
- spinalcordtoolbox/deepseg_gm/deepseg_gm.py
This pull-request will add an **optional parameter** called `-t` that will give better results at the expense of **more processing time** (usually 8x more, depending on how many cores you have of course) during the inference using the `sct_deepseg_gm`. The flag will enable the TTA (test-time augmentation), where a scalar value is sampled from a uniform distribution (between 0.0 and 2.0) and added to each voxel of the entire MRI volume (before doing prediction), this process is repeated for 8 times and in the end all predictions are averaged together with the original prediction. I found that this usually improves the results and it provides a better segmentation without FP (false positives). It also helps when the voxel intensity is far away from the trained distributions (when there is a …
> Adding TTA (test-time augmentation) support for sct_deepseg_gm

- install/sct_launcher
- install/update_bin.sh
- install_sct
This PR brings a "solution" for #1702, whereby users can tinker with the running code in all cases:
- Users installing sct as a package or in ~/sct_dev will not see anything change, but they may edit scripts as well as spinalcordtoolbox files in their installation.
- Users installing sct in-place (from git) will save some installation time (because of no copy needed) and can stop going crazy (previously ``pip install --upgrade`` needed to be ran).
- Users installing sct in development mode will not see anything change (the development mode actually becomes moot as it basically just enables to use the *source* spinalcordtoolbox folder even when performing package installs... it could be removed to save some installer space).
Bonus:
- hot fix for #1895
> install: use pip install -e spinalcordtoolbox to gain flexibility

- install/sct_launcher
- install_sct
* [* ] Is there a issue open describing the motivation for this pull request ?
* [ *] Does the pull request need additional test(s) ?
Tested on macOS
Adding support for non-English language local Unicode during the installation.
Please note that `LC_ALL` overwrites `LANG`
`install_sct` updated
Implements or Fixes #1880  and #1851 (duplicate)
> Local language support (LC_ALL) added to installation& launcher on macOS

- install/sct_launcher
- install_sct
- scripts/sct_testing.py
This PR fixes:
- #1899 
- #1897 
- #1895 (for good)
And brings some misc changes:
- Limit # of forks of sct_testing depending on number of functions to test or host CPUs
- Add verbose feature to sct_testing
> Fixup regressions in sct_launcher & install_sct

- scripts/sct_deepseg_gm.py
This is a minor change to delay the load of the `deepseg_gm` module for only when required, it reduced the command usage help from 3.2s to 0.3s due to Keras/TensorFlow loading.
> Lazy loading for the deepseg_gm module

- scripts/sct_image.py
- scripts/sct_propseg.py
- spinalcordtoolbox/gui/centerline.py
- Fixes #1406: New flag `-rescale`, which rescales the image (only the header, not the data) in order to enable segmentation on spinal cords with dimensions different than that of humans (e.g., mice, rats, elephants, etc.) 
- Fixes #1874: New flag `-correct-seg`, which enables/disables a few corrections on the output segmentation. This was introduced because sometimes the correction makes things worse.
> sct_propseg: Now possible to rescale data header to be able to segment non-human spinal cord (mice, rats, etc.)

- install_sct
- scripts/sct_deepseg_lesion.py
- scripts/sct_download_data.py
- scripts/sct_testing.py
- testing/test_sct_deepseg_lesion.py
- MANDATORY ARGS:
```
sct_deepseg_lesion.py -i t2s.nii.gz -c t2s
```
- AVAILABLE CONTRASTS: `{t2,t2s,t2_ax}`
`-c t2_ax` --> was train on ~200 3D T2-w volumes with anisotropic resolution, axial orientation.
`-c t2` --> was train on 3D T2-w volumes with anisotropic resolution, both axial orientation and sagittal orientation.
- CENTERLINE DETECTION: 2 available ways to do it --> via the flag `-ctr`
`-ctr svm` --> OptiC initialized with SVM+HoG maps (former version, currently the one integrated in master). Avantages: faster, more robust to exotic / new contrasts.
`-ctr cnn` --> OptiC initialized with CNN_1 maps. Avantages: more robust to compressed cord and/or sagittal images.
- DEALING WITH THE PRESENCE OF THE BRAIN:
`-brain 0` --> The algorithm will go through all the axial slices. …
> New function: sct_deepseg_lesion

- scripts/sct_pipeline.py
Title says it all. We have a new branch naming convention but it reveals surprises.
> fixup sct_pipeline crashing when branch name has a slash in it

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- CONTRIBUTING.rst
Make use of Github's [new issue templates](https://blog.github.com/2018-05-02-issue-template-improvements/).
Split the template into one for bug reports, and one for feature requests.
Fixes #1945.
> Make use of Github's new issue templates

- scripts/sct_register_to_template.py
This PR makes it now possible to use single label (previously limited to 2 only) for registering data with the template. Note: this feature was already possible with -ldisc option.
Fixes #1954 
Also added minor cosmetic fixes to converge towards PEP8 and removed old commented code.
> Enable single-label with -l flag

- scripts/sct_fmri_compute_tsnr.py
- scripts/sct_image.py
- scripts/sct_process_segmentation.py
- scripts/sct_register_multimodal.py
- scripts/sct_testing.py
- testing/test_sct_compute_ernst_angle.py
- testing/test_sct_compute_hausdorff_distance.py
- testing/test_sct_crop_image.py
- testing/test_sct_dmri_separate_b0_and_dwi.py
- testing/test_sct_dmri_transpose_bvecs.py
- testing/test_sct_fmri_compute_tsnr.py
- testing/test_sct_image.py
- testing/test_sct_process_segmentation.py
- testing/test_sct_register_multimodal.py
- testing/test_sct_register_to_template.py
- testing/test_sct_straighten_spinalcord.py
- testing/testing_sct_propseg.py
I noticed that my `sct_testing_data` got modified, which was causing test failures when running `sct_testing` several times, and so taking some actions:
- Augment `sct_testing`:  
- To be able to run tests in their own testing subfolder;  
- To be able to check for tests that mess up with input data or write where they shouldn't.  
- Correct problems found (in tests or scripts) after implementation
- Tests don't modify data in the `sct_testing_data` repo
- Tests write to the output folder
- Scripts that modify stuff can write to a second output file (used for testing)
- All scripts can operate in `-ofolder != "."`
PS: I'm not friends with `sct_testing` (and `sct_pipeline` by extension).
> Testing improvements relative to checking correct path handling, associated fixes

- scripts/msct_image.py
- unit_testing/test_image.py
This new code allows to write:
```python
[ im_2d for im_2d in Slicer(im_3d) ]
```
as well as:
```python
[ dice(x, y) for (x,y) in Slicer((im3d_x, im3d_y)) ]
```
illustrating a suggestion in https://github.com/neuropoly/spinalcordtoolbox/issues/1621#issuecomment-406765731
> Totally pimp the Image Slicer (to act like a sequence, to slice many images), and add unit tests for the slicer

- scripts/sct_extract_metric.py
This PR fixes a residual bug in https://github.com/neuropoly/spinalcordtoolbox/pull/1965
> sct_extract_metric: wrong variable name which created bug if output .xls was not present

- scripts/sct_dmri_compute_dti.py
This PR introduces a new feature output for `sct_dmri_compute_dti`, where users now have the possibility to output DTI eigenvectors, using a new boolean flag `-evecs`, which could be used e.g. for tractography applications.
Fixes #1974
> sct_dmri_compute_dti: Output tensor eigenvectors

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.rst
This PR fixes #1964 and adds a small sentence about performing an issue review pass during creation of a corresponding PR.
> Minor contribution guideline & PR template fixes

- batch_processing.sh
- scripts/sct_extract_metric.py
This PR brings a few cosmetic updates:
- Fixes #1987: `batch_processing` final output caused by recent modifications on `sct_extract_metric`
- Fixes #1961: Now running QC on the t2 segmentation with propseg
In addition, `sct_extract_metric` had to be modified because of some recently-introduced bugs in relation to the `perslice` and `perlevel` flags. Moreover, the separation of slice and levels is now done using ";" instead of ",", for better parsing of CSV output. 
Note to @zougloub: the current implementation/fix in `sct_extract_metric` might cause you a heart attack, but this is only a temporary bandage. Full healing will be provided by #1931.
> Few fixes in sct_extract_metric and batch processing outputs

- scripts/sct_deepseg_lesion.py
- scripts/sct_deepseg_sc.py
**Goal:** Allow to input image with only one axial slice.
**Issue:** `isct_spine_detect` requires ```nz>1```.
**Solution:** If ```nz==1```, then ask the user to use `-centerline cnn` instead of `-centerline svm` (default).
To test:
```
cd sct_example_data/t2s
sct_crop_image -i t2s.nii.gz -dim 2 -start 2 -end 2 -o t2s_Z010.nii.gz
sct_deepseg_sc -i t2s_Z010.nii.gz -c t2s
```
Raises an error message:
```
Your image contains only one axial slice, please re-run the function using -centerline cnn.
```
Then,
```
sct_deepseg_sc -i t2s_Z010.nii.gz -c t2s -centerline cnn
```
Same for `sct_deepseg_lesion`.
Note that I have remove some duplicated code: The centerline detection is now done by a function in `sct_deepseg_sc` named `find_centerline`, which is called by `sct_deepseg_lesion`.
> sct_deepseg_sc, sct_deepseg_lesion: Allow to input image with one axial slice

- scripts/sct_straighten_spinalcord.py
**Context:**
`transfo_pix2phys` returns a numpy array while the following lines of `sct_straighten_spinalcord` are expecting a list:
- https://github.com/neuropoly/spinalcordtoolbox/blob/master/scripts/sct_straighten_spinalcord.py#L452
- https://github.com/neuropoly/spinalcordtoolbox/blob/master/scripts/sct_straighten_spinalcord.py#L462
It leads to a AttributeError, as illustrated in the issue #2023.
**Proposed solution:**
Replace:
```c_p = discs_input_image.transfo_pix2phys([[c.x, c.y, c.z]])[0]```
by:
```c_p = discs_input_image.transfo_pix2phys([[c.x, c.y, c.z]]).tolist()[0]```
***To reproduce***
```
cd example_data/t2
sct_get_centerline -i t2.nii.gz -c t2
sct_label_utils -i t2.nii.gz -create-viewer 2,3,4,5,6,7,8,9,10
sct_straighten_spinalcord -i t2.nii.gz -s t2_centerline_optic.nii.gz …
```
> sct_straighten_spinalcord: Fixed AttributeError related to conversion of numpy array to list

- scripts/sct_create_mask.py
Few fixes and improvements in `sct_create_mask`:
- Now account for (px,py) when creating the mask, solving the issue that occurred when px and py (in axial plane) were different. Fixes #1550 
- Fixes a bug that occurred when the size of the mask was bigger than the size of the image. Fixes #820
> sct_create_mask: Few fixes and improvements

- .gitignore
- scripts/msct_moco.py
- scripts/sct_dmri_moco.py
- scripts/sct_fmri_moco.py
- scripts/sct_image.py
- scripts/sct_maths.py
- scripts/sct_utils.py
Currently, sct_fmri_moco is designed such that the input image is assumed to be in axial orientation (i.e. 3rd dimension is S-I), and the algorithm estimates a set of Tx,Ty for each slice, regularized using polynom functions along the S-I direction.
However, for images acquired sagitally (or coronally), this approach does not work anymore. Beyond the simple orientation issue described in #1983, the type of motion-related corruption is not addressed by the current algorithm. More specifically, if motion occurs between sagittal slices, then the cord is non-linearly distorted in the axial plane and a simple translation within the axial plane is not sufficient. This is shown in the animation below. Without motion correction (left), a few slices are translated in the AP direction, leaving ugly …
> sct_fmri_moco: Generalize motion correction for sagittal acquisitions and other improvements

- scripts/sct_get_centerline.py
- scripts/sct_propseg.py
This PR fixes an IOError that appears when using `-init-centerline viewer` in `sct_propseg`. 
Workaround: assign output label file after running "controller = launch_centerline_dialog().
Workaround for #2037 (does not "really" fixes the cause of the problem)
> sct_propseg: Reordered variable assignment

- scripts/msct_nurbs.py
- scripts/msct_smooth.py
- scripts/sct_get_centerline.py
- scripts/sct_process_segmentation.py
This PR attends to fix #2038 (which fixes #1863 and fixes #2031 ) by intercepting the exception caused by a singular matrix. That way the testing of the number of control points can continue and the NURBS fitting can be done even if a singular matrix is encountered.
Thus, the hanning filtering will not be necessary anymore (if the number of slices if sufficient). Moving away from the hanning filtering is something @benjamindeleener suggested when discussing this problem.
However, no change in the method has been done, should I search for methods to improve the NURBS fitting ?
> msct_nurbs: fixes singular matrix error

- scripts/msct_moco.py
- scripts/sct_fmri_moco.py
The main purpose of this PR is to fix a regression bug introduced in v3.2.6, which appears when using a mask with `sct_fmri_moco` and `sct_dmri_moco` (Fixes #2045)
It also fixes another regression bug (Fixes #2046)
> sct_fmri_moco: Fixed regression bug related to the use of a mask

- batch_processing.sh
- scripts/sct_extract_metric.py
- testing/test_sct_extract_metric.py
`sct_extract_metric` function currently assumes that metrics are positive (see: https://github.com/neuropoly/spinalcordtoolbox/blob/master/scripts/sct_extract_metric.py#L366) and there is no good reason for doing that. This PR now enables negative metrics and introduces a new flag `-discard-neg-val` to enable/disable negative values. Default=0.
Fixes #2048
> sct_extract_metric: Do not zero negative values

- scripts/sct_deepseg_lesion.py
- scripts/sct_deepseg_sc.py
This PR aimed at fixing some ValueError or IndexError errors that have been reported to occur when using `sct_deepseg_sc` or `sct_deepseg_lesion`.
**To reproduce the error:**
```
cd example_data/mt
sct_image -i mt1.nii.gz -split z
sct_deepseg_sc -i mt1_Z0005.nii.gz -c t2 -centerline cnn
```
**Error:**
```
charley@charley:~/data/example_data/mt$ sct_deepseg_sc -i mt1_Z0005.nii.gz -c t2 -centerline cnn
--
Spinal Cord Toolbox (cg_deepseg_valueError_indexError_i1921_i2015_i2016/9d9b320757fc4a1db5bac3f706a01817c6b351c7)
Running /home/charley/spinalcordtoolbox/scripts/sct_deepseg_sc.py -i mt1_Z0005.nii.gz -c t2 -centerline cnn
/home/charley/spinalcordtoolbox/python/lib/python2.7/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to …
```
> sct_deepseg_sc/lesion -- ValueError and IndexError fixes

- scripts/sct_label_vertebrae.py
This PR fixes an edge case issue when using `-initlabel` file as input. The path was improperly managed. Now giving absolute path to the variable.
Fixes #2067
> sct_label_vertebrae: Fixed path issue when using -initlabel flag

- scripts/sct_flatten_sagittal.py
On some images a scaling problem was causing the error `ValueError: Images of type float must be between -1 and 1.`. It is now fixed by making sure the input to `img_as_float()` is properly scaled.
Fixes #2069
> sct_flatten_sagittal: Fixes bug related to image scaling

- scripts/sct_maths.py
- scripts/sct_smooth_spinalcord.py
- testing/test_sct_smooth_spinalcord.py
Currently, `sct_smooth_spinalcord` only performs smoothing along the Z direction (after straightening). Users [requested](https://sourceforge.net/p/spinalcordtoolbox/help/4/) the possibility to perform an anisotropic smoothing. This PR enables this option. Changes are:
- enable to set smoothing parameters in all axes
- enable to specify kernel Sigma in "float" (previously "int")
- now enabled caching of straightening (if function is run more than one time with the same image, straightening does not need to be re-done)
WARNING: This refactoring breaks cross-compatibility: the default behaviour of flag "-smooth X" will now produce a kernel of "X,X,X" (as opposed to 0,0,X before). This decision was chosen to be consistent with usage of `sct_maths`. This mean that this PR will be integrated …
> sct_smooth_spinalcord: Enable to set smoothing parameters in all axes

- scripts/sct_dmri_moco.py
- scripts/sct_dmri_separate_b0_and_dwi.py
- testing/test_sct_dmri_separate_b0_and_dwi.py
Currently the function `sct_dmri_separate_b0_and_dwi` outputs by default the files `dwi.nii.gz` and `b0.nii.gz`, assuming that the input file is not called like that (or assuming local files with those names don't exist). This is a problem, especially with the BIDS convention, where the input file is called `dwi.nii.gz`. 
This PR changes the default output names, and automatically append suffix "_dwi" and "_b0" to the input file name. 
WARNING: This PR breaks compatibility with v3.2.7 for pipeline that assumed output name is `dwi.nii.gz` (no more the case).
This does not concern `batch_processing.sh`, which does not use this function. However, many pipelines in [sct-pipeline](https://github.com/sct-pipeline) will be affected. 
Fixes #2074
> sct_dmri_separate_b0_and_dwi: Now append suffix to input file name to prevent conflicts

- scripts/sct_compute_snr.py
- testing/test_sct_compute_snr.py
The following features/fixes were implemented:
- In case users need to discard the 3 first measurements, it is not possible to use ":" for selecting a range of volumes with flag "-vol", e.g., -vol 2:100
- Now possible to output an SNR map with `-method mult`
- With the previous point, the flag -m has been made optional
- Removed -z and -vert flags. It made the code heavy. If users want to compute within particular ROIs, then ROI generation should be wrapped outside of this function.
- Fixed Rayleigh correction for SNR_diff
Fixes #2078
> Now possible to output SNR map, removed requirement for inputing mask, and few other improvements

- scripts/sct_extract_metric.py
Methods `max` was falsely computed (regression bug). This PR fixes it.
Fixes #2086
> Fixed bug in method max

- scripts/sct_deepseg_gm.py
- scripts/sct_deepseg_sc.py
- scripts/sct_label_vertebrae.py
- scripts/sct_propseg.py
- spinalcordtoolbox/image.py
- spinalcordtoolbox/reports/assets/_assets/css/style.css
- spinalcordtoolbox/reports/qc.py
- spinalcordtoolbox/reports/slice.py
- spinalcordtoolbox/resample/nipy_resample.py
This PR fixes the way QC mosaic pictures are scaled and cropped: previously, the scaling was based on number of voxels, which made the scaling dependent to the native resolution of the image. This PR fixes it by resampling the image to a fixed resolution (in-plane: 0.5x0.5mm) before launching the QC. 
Note: The result can still be "ugly" if the native resolution is low (~1mm or higher), because the output segmentation will look "squary". The way to properly address that in the future is to:
- output non-binary segmentations (in `sct_propseg`, `sct_deepseg_sc`, `sct_deepseg_gm`)
- adapt the code in `spinalcordtoolbox.reports.slice` so that overlays can be non-binary
Also: the current implementation is "ugly" because:
- the orientation+interpolation of the output data is done with i/o, …
> QC now scales images based on physical dimensions (previously based on voxels)

- scripts/sct_register_to_template.py
Due to a regression, the flag -param-straighten was not more used. It was notably problematic because users would like to be able to choose the centerline smoothing algorithm (nurbs vs. hanning), as detailed [here](https://sourceforge.net/p/spinalcordtoolbox/help/7/).
A new flag `-straighten-fitting` has now been enabled.
Fixes #2100
> Now possible to specify the type of algorithm used for cord straightening

- scripts/sct_download_data.py
The PAM50 template was modified as follows:
- Aligned the PAM05 template with the ICBM152-MNI template using translation. Note: only the header of the PAM50 files was updated for this operation.
- Cropped the template just above C1 vertebral label. The rationale is that the brainstem already exists in the MNI template, so there is no need to duplicate this structure. 
- Updated the file info_label.txt in the folder template/ to take new files into account
- Shifted the value of the labels in the file PAM50_label_discPosterior.nii.gz by one (previous version was wrong).
**WARNING:** Cross-compatibility broken for studies that map metrics to the PAM50 template (not from the PAM50 to the native space), because the q/sform of the PAM50 has changed. 
Fixes #2085
> Updated PAM50 template header to be in the same coordinate system as the MNI template

- README.md
- scripts/sct_label_vertebrae.py
- scripts/sct_register_to_template.py
[This page](https://sourceforge.net/p/spinalcordtoolbox/wiki/create_labels/) is obsolete because (i) it uses fslview instead of `sct_label_utils -create-viewer` and (ii) it does not describe label values for the discs.
Since we want to slowly move away from sourceforge, the proposed fix:
- implements the labeling documentation in the next SCT course (London, January 21st 2019)
- puts the slides in slideshare and add link in README
- redirect to the appropriate slideshare page in SCT functions and in sourceforge.
Such documentation is important for `sct_register_to_template` and `sct_label_vertebrae`.
Related to https://github.com/neuropoly/spinalcordtoolbox/pull/1451
Fixes #1721, Fixes #699
> Updated documention on how to create vertebral and disc labels

- scripts/sct_label_vertebrae.py
Instead, user can create a label with `sct_label_utils` and then run `sct_label_vertebrae` with flag `-initlabel`. This decision enables to lighter the code and minimize the number of choices for the user (could be overwhelming). 
Example:
~~~
sct_label_utils -i t2.nii.gz -create-viewer 3 -o label_c2c3.nii.gz -msg "Click at the posterior tip of C2/C3 inter-vertebral disc"
sct_label_vertebrae -i t2.nii.gz -s t2_seg.nii.gz -c t2 -initlabel label_c2c3.nii.gz -qc ~/qc_singleSubj
~~~
Fixes #2120
> Removed support for -initc2 flag because there is an alternative approach with sct_label_utils

- scripts/sct_deepseg_lesion.py
- scripts/sct_deepseg_sc.py
This PR aims at accelerating the processing of `sct_deepseg_sc`and `sct_deepseg_lesion`.
The developments are:
> deepseg_sc: Speed processing up 

- scripts/sct_get_centerline.py
- scripts/sct_image.py
- scripts/sct_straighten_spinalcord.py
- spinalcordtoolbox/centerline/core.py
- unit_testing/test_centerline.py
This PR fixes extreme cases where the segmentation is incomplete, causing straightening to crash. There is also speed improvement (less i/o).
Fixes #2153
> Fixed crash caused by wrong estimation of centerline length in case of incomplete segmentation

- spinalcordtoolbox/deepseg_sc/core.py
This PR aims at fixing the bug reported by #2151.
This PR suggests a minor change: do not save tmp file in working directory at the end of the processing.
To test it:
```
cd example_data/t2
sct_deepseg_sc -i t2.nii.gz -c t2
```
> deepseg_sc/core: do not save tmp file in the working directory

- scripts/msct_moco.py
- scripts/sct_dmri_moco.py
- scripts/sct_fmri_moco.py
We're just replacing use of mmap'able .nii files by .nii.gz files, which need to be read entirely, which reduces the number of open files. Obviously now the bottleneck becomes RAM.
Fixes #2149 
Related to: https://sourceforge.net/p/spinalcordtoolbox/help/13/
> Work around "too many open files" by slurping the data

- scripts/sct_straighten_spinalcord.py
- spinalcordtoolbox/image.py
This regression bug was introduced by https://github.com/neuropoly/spinalcordtoolbox/pull/2147.
Fixes #2164
> Fixed wrong estimate of derivatives on ref image

- .gitignore
- batch_processing.sh
- scripts/sct_warp_template.py
- spinalcordtoolbox/reports/qc.py
The main purpose of this PR was to use `isct_antsApplyTransfo` instead of SCT system call for warping each volume, resulting in faster execution. In a typical dataset, execution time goes from 4.5min to 2min. Fixes #2173. This change makes #602 less relevant, there we can consider that this PR Fixes #602.
Other improvements include:
- QC now supporting `sct_warp_template`
- Change display message at the end, in case user does not ask for atlas. Fixes #172 
- Cleanup usage. Fixes #1528
TODO:
- Add QC in batch_processing
> Faster execution and other minor improvements

- spinalcordtoolbox/deepseg_lesion/core.py
- spinalcordtoolbox/deepseg_sc/core.py
- unit_testing/test_deepseg_sc.py
/!\ DO NOT MERGE --> waiting for https://github.com/neuropoly/spinalcordtoolbox/pull/2183
This PR aims at fixing the issue #2186:
when the centerline does not start from `z=0`, then the segmentation is shifted in the I-S direction.
It can happen when:
- `-centerline viewer` --> the user do not add a label on the first slice
- `-centerline file` --> when the centerline does not start from `z=0`
The suggested solution is: To use the z coordinates of the centerline when the segmentation is reconstructed (ie `deepseg_sc.uncrop_image`), instead of assuming that it starts at `z=0`.
To test:
Data (internal server): 20190309_issue2186
```
sct_deepseg_sc -i sanlm_structural.nii.gz -c t1 -ofolder deepseg.viewer -centerline viewer
```
Fixes #2186
> Fix I-S shift when -centerline viewer

- scripts/sct_deepseg_lesion.py
- scripts/sct_deepseg_sc.py
- spinalcordtoolbox/deepseg_lesion/core.py
- spinalcordtoolbox/deepseg_sc/core.py
- unit_testing/test_deepseg_sc.py
This PR aims at:
- fixing the bug #2168 
- implement the suggested enhancement: #2167 
There was a confusion between an old and new naming convention for `-centerline manual` versus `-centerline file`. We have now `file` everywhere, in both `sct_deepseg_lesion` and `sct_deepseg_sc`.
For instance:
```
sct_deepseg_sc -i t2.nii.gz -c t2 -centerline file -file_centerline t2_ctr.nii.gz
```
Output the viewer labels when using `-centerline viewer`. Implemented in both `sct_deepseg_lesion` and `sct_deepseg_sc`. The output file has the following suffix: `_labels-centerline.nii.gz`.
To test:
```
sct_deepseg_sc -i t2.nii.gz -c t2 -centerline viewer
```
Fixes #2167, Fixes #2168
> Fixed bug and clarified usage of -centerline viewer

- scripts/sct_propseg.py
Due to a regression bug, `v4.0.0-beta.1` was not accounting for the flag `-init` anymore. This PR addresses that issue, as well as other minor improvements:
- Fixed `-init` flag ignored in v4.0.0-beta.1. Fixes #2190
- Output segmentation now overlaid with opacity=100 in display_syntax_viewer(). Fixes #1833
- No more save Optic centerline output because there is already another centerline output, called `xxx_centerline.nii.gz` and directly derived from the segmentation directly (hence more precise).
> Fixed ignored -init flag and minor improvements

- spinalcordtoolbox/vertebrae/detect_c2c3.py
This PR aims at:
- Fixing a bug in the post processing of `detect_c2c3` module. Fixes #2191 
- Allowing a way not to remove temporary files, in order to facilitate the debugging.
We create a mask around the centerline, which is used in the post-processing of `detect_c2c3` module. In the new implementation, we only consider z-slices where the spinal cord is present (ie not in the brain area to speed up the process) and do not forget to iterate along the z-axis (which was not the case in the former implementation.. shame.).
Keep temporary files of `detect_c2c3` module is now possible.
To test it:
```
cd spinalcordtoolbox/spinalcordtoolbox/vertebrae/
python
```
Then,
```
>>> from detect_c2c3 import detect_c2c3_from_file
>>> detect_c2c3_from_file('/home/charley/data/thiago/cont_03.nii.gz', …
```
> Fixed bug in the post processing of detect_c2c3

- scripts/sct_extract_metric.py
- scripts/sct_process_segmentation.py
- spinalcordtoolbox/aggregate_slicewise.py
- unit_testing/test_aggregate_slicewise.py
-  Clarified usage: now explicitly says that `-perlevel` requires to set flag `-vert`. Fixes #2195 
- Now always displays `VertLevel` column in csv output. Fixes #2141
> Minor fix in usage and csv output

- spinalcordtoolbox/vertebrae/detect_c2c3.py
This PR aims at fixing the bug reported [here](https://github.com/neuropoly/spinalcordtoolbox/issues/2191#issuecomment-474834806).
`scipy.measurements.center_of_mass` receives `np.array` as input.
The bug occurs when the input segmentation file is not compressed (ie .nii versus .nii.gz). In that case, the type of `seg.data` is `<class 'numpy.core.memmap.memmap'>`.
That's a known issue: #2148.
A solution is to cast `np.array` when calling `seg.data`.
To test:
```
cd example_data/t1
sct_label_vertebrae -i t1.nii.gz -s t1_seg.nii.gz -c t1
```
Fixes #2191.
> Fixed bug that appeared when inputing uncompressed nifti file

- scripts/sct_propseg.py
- spinalcordtoolbox/centerline/core.py
- spinalcordtoolbox/centerline/optic.py
This PR aims at removing Optic temp files by default.
The files are not removed if verbose >= 2.
Fixes #2209.
> Remove Optic temp files by default

- requirements.txt
- scripts/sct_check_dependencies.py
This PR fixes an issue which happens on Python 2 platforms that have an outdated ssl module. These older ssl modules can cause some insecure requests to succeed where they should fail and secure requests to fail where they should succeed. 
Source: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
Fixes #2222
> Fixed installation error caused by old SSL module

- spinalcordtoolbox/process_seg.py
- unit_testing/create_test_data.py
- unit_testing/test_process_seg.py
This PR introduces more exhaustive tests for `process_seg` (fixes #2225) and fix a bug that happens if rotation is too important, raising `LinAlgError: SVD did not converge` (fixes #2228).
> Made tests more sensitive to centerline rotation and fix LinAlgError

- requirements.txt
- scripts/sct_utils.py
- spinalcordtoolbox/reports/qc.py
- spinalcordtoolbox/utils.py
When running several subjects in parallel (using GNU parallel), during QC generation, a `JSONDecodeError` is observed. This error was caused by parallel writing on the json file of the QC report. It was supposed to be fixed by the use of `portalocker` (see https://github.com/neuropoly/spinalcordtoolbox/issues/2205), but in some file systems (OSX, Ubuntu), it is not. 
Another (unsuccessful) locking strategy was tried: create a temporary locked file, and then copy the content in the json file. However, it also failed in some OSs (OSX, Ubuntu).
The fix was to create an individual json file for each instance, instead of appending all the QC metadata within the same json file. 
Fixes https://github.com/neuropoly/spinalcordtoolbox/issues/2248
> Fixed corruption of QC json file when running parallel jobs

- scripts/sct_label_vertebrae.py
- scripts/sct_register_to_template.py
- scripts/sct_smooth_spinalcord.py
- scripts/sct_straighten_spinalcord.py
- spinalcordtoolbox/straightening.py
In a previous implementation of spinal cord straightening, the parameter `xy_size` was misleading, as it produced a dimension that was `2*xy_size` instead of `xy_size`. In PR https://github.com/neuropoly/spinalcordtoolbox/pull/2238, this has been corrected: [before](https://github.com/neuropoly/spinalcordtoolbox/pull/2214/files#diff-06511e50890a7fbffb44629b754dc3f7L370), [after](https://github.com/neuropoly/spinalcordtoolbox/pull/2214/files#diff-2f9350cd76070039f9105b8259030cb4R267). 
However, the default value for `xy_size` was not updated, causing different default behaviours, such as having an output warping field that spans a XY area twice smaller than previously. 
Also see: http://forum.spinalcordmri.org/t/sct-v4-0-0-beta-2-is-out/43/8?u=jcohenadad
- Double the default `xy_size` in …
> Fix regression related to output straight FOV size

- scripts/sct_compute_snr.py
This PR aims to fix the inconsistency between ` sct_fmri_compute_tsnr` and `sct_compute_snr` which was caused by a difference in the way standard deviation was calculated as described in [https://sourceforge.net/p/spinalcordtoolbox/help/10/](https://sourceforge.net/p/spinalcordtoolbox/help/10/)
Fixes #2110 
The resulting values of 'sct_fmri_compute_tsnr -i fmri.nii.gz' and 'sct_compute_snr -i fmri.nii.gz -method mult' would slightly differ due to `sct_compute_snr` using N (ddof = 0) instead of N-1
(ddof = 1) as the denominator when calculating the standard deviation as ` sct_fmri_compute_tsnr` did.
For the sake of consistency,`sct_compute_snr` now uses N-1 (ddof = 1) when calculating the standard deviation.
> Make consistent STD calculation between sct_fmri_compute_tsnr and sct_compute_snr

- requirements.txt
- scripts/sct_check_dependencies.py
In this PR, we are changing the source to the fork jcohenadad/nipy from nipy/nipy due to the new deprecation. (overcomes #2267)
We do this in order to keep an old version of nipy that still has the factorial function that is used in many of the scripts. 
At the moment, the PR is not working. Indeed, after using the function install_sct and verifying installation, we obtain the following log:
Validate installation...
SCT info:
- version: git-HMY/2267-nipy-fork-79629ea34a2d61e335e8bf6dfedd87037bd909a7
- path: /Users/heyan_admin/2267/sct
OS: osx (Darwin-16.7.0-x86_64-i386-64bit)
CPU cores: Available: 4, Used by SCT: 4
RAM: Primary memory available: 12.00 gigabytes
Check Python executable.............................[OK]
Using bundled python 3.7.3 (default, Mar 27 2019, 16:54:48) 
[Clang …
> Changed source of nipy installation to fork

- scripts/sct_dmri_compute_dti.py
It was previously not possible to output DTI eigenvalues. This PR implements the output of the three eigenvalues, using the parameters `-evecs` (previously used only for outputting eigenvectors). The eigenvalues are output with prefix "E": dti_E1.nii.gz, dti_E2.nii.gz, dti_E3.nii.gz.
Example usage:
~~~
sct_dmri_compute_dti -i dmri.nii.gz -bval bvals.txt -bvec bvecs.txt -evecs 1
~~~
Fixes #2273
> Output DTI Eigenvalues

- spinalcordtoolbox/straightening.py
This PR fixes a regression bug likely introduced in https://github.com/neuropoly/spinalcordtoolbox/pull/2257. This bug yields a 2x smaller XY FOV in the straight space, reducing the performance of `sct_label_vertebrae` function.
Fixes #2265
> Fixed wrong scaling factor for output XY size

- .travis.yml
- install_sct
- scripts/sct_check_dependencies.py
As of today, Tensorflow is not compatible with Python 3.7 on Centos7 (see: tensorflow/tensorflow#26826).
In this PR, we downgrade SCT's Python from 3.7 to 3.6 to ensure cross-platform compatibility. In order to do this, we modified `install_sct` as follows: after miniconda install, a virtual environment is created with py3.6, and all SCT external and internal dependencies are installed within this venv. 
This approach offers more flexibility in the future, where similar issue could happen. That way, we will have the possibility to specify a Python version for SCT.
As of now, in order to activate SCT's python, the following should be done:
```bash
source ${SCT_DIR}/python/etc/profile.d/conda.sh
conda activate venv_sct
```
> Fixed Keras/Tensorflow compatibility with CentOS 7 by downgrading to Python 3.6

- scripts/sct_compute_mtr.py
At the moment, the script [sct_compute_mtr.py](https://github.com/neuropoly/spinalcordtoolbox/blob/53b81c4b73fa65ad55ac391649ecb44744c077ad/scripts/sct_compute_mtr.py) does not have a flag to change the output filename or its location ([it would default to mtr.nii.gz in the active directory](https://github.com/neuropoly/spinalcordtoolbox/blob/53b81c4b73fa65ad55ac391649ecb44744c077ad/scripts/sct_compute_mtr.py#L85)).
This PR makes it possible to change the output file name and/or location with the flag `-o`. Fixes #2178 
To do so, the user simply needs to follow the following format when adding the `-o` flag to the rest of the [sct_compute_mtr](https://sourceforge.net/p/spinalcordtoolbox/wiki/sct_compute_mtr/) command:
`-o /path_Leading_To_Output_File/output_File`
Example use with output …
> Added output file and/or folder flag

- scripts/sct_resample.py
- spinalcordtoolbox/reports/qc.py
- spinalcordtoolbox/reports/slice.py
- spinalcordtoolbox/resampling.py
This PR brings a few improvements in the resampling routines and QC report. More specifically:
- When using `n_resample(reference=img_ref)`, the output resampled image was not what it is was expected to be. Fixes #2284
- Added new `-ref` flag for `sct_resample` CLI. Fixes #2284 
- Fixed slow generation of QC reports caused by slow resampling method. Fixes #2217 
There is still some improvements to be done, which will be done in a subsequent PR. See: https://github.com/neuropoly/spinalcordtoolbox/issues/2286
> Fixed resampling method with reference image and improved speed for generating QC report

- scripts/sct_label_utils.py
- scripts/sct_register_to_template.py
At the moment, the function `sct_label_utils` did not have a way to remove or keep specific labels based on their values. 
This PR introduces a feature that allows one to remove one or many specific labels with the `-remove-specific` flag and to keep labels from a reference image with the `-keep-specific` flag when using the sct_label_utils command. (fixes #2247)
Example use of removing labels of value 1,2,3 from file `t2_label.nii.gz`:
```
sct_label_utils -i t2_label.nii.gz -remove-specific 1,2,3
```
Example use of keeping labels of value 7,11 from file `labeled_disc.nii`:
```
sct_label_utils -i labeled_disc.nii -keep-specific 7,11 
```
> Added possibility to remove or keep labels by specifying values

- scripts/msct_types.py
- scripts/sct_label_utils.py
- scripts/sct_label_vertebrae.py
- spinalcordtoolbox/image.py
If input image has Z defined as SI instead of IS, the input Z coordinate used to initialize disc location is wrongly interpreted. 
This PR introduces an internal function that converts Z (or any other coordinate) based on the input and destination orientation. This function is located in `msct_types.Coordinate.permute()`.
Fixes #2236
> Fixed misplaced label in non-RPI data for initializing vertebral labeling

- spinalcordtoolbox/deepseg_lesion/core.py
- spinalcordtoolbox/deepseg_sc/core.py
This PR simply changes output segmentation data type to `uint8` for `deepseg_sc` and `deepseg_lesion`.
To reproduce:
```
cd duke/sct_testing/bids/sct-users/sub-20190427/anat
sct_deepseg_sc -i sub-20190427_acq-MTon_MTS.nii.gz -c t2s
```
Fixes #2243.
> Output segmentation in uint8

- scripts/sct_label_vertebrae.py
- spinalcordtoolbox/vertebrae/detect_c2c3.py
This PR aims at:
1. `sct_label_vertebrae`: Input verbose value to `detect_c2c3` when called in `sct_label_vertebrae` in order to facilitate the debugging.
2. `detect_c2c3`: Display temp folder path in terminal for verbose >= 2, so that we can easily check the temp files.
3. `sct_label_vertebrae`: Quit if detection fails.
To reproduce:
```
cd sct_testing/t2
sct_label_vertebrae -i t2.nii.gz -c t2 -s t2_seg.nii.gz -v 2
```
Before:
<details>
```
C2-C3 not detected...
Temporary files saved to /tmp/sct-20190605214813.450715-c3o5rovb
Automatic C2-C3 detection failed. Please provide manual label with sct_label_utils
Saving image to /tmp/sct-20190605214807.853906-label_vertebrae-ta3i_v8s/labelz.nii.gz orientation AIL shape (60, 55, 52)
WARNING: File …
```
> Added possibility to keep temporary folders in detect_c2c3 and quit if detection fails

- .travis.yml
This PR adds test for Sierra and displays all builds on the Travis Web UI (even the one with `allow_failures`). Regarding the latter point, [a ticket has been opened](https://travis-ci.community/t/allow-failures-does-not-appear-on-the-web-ui/3638) on the Travis forum.
> Travis: Adding distribs and displaying allow_failures

- scripts/sct_extract_metric.py
- spinalcordtoolbox/aggregate_slicewise.py
- unit_testing/test_aggregate_slicewise.py
Currently, when listing flags with -l, estimation is done for each tract separately. This PR makes it possible to combine all tracts within a single estimation. Fixes #2193 
Also address the following points:
- In the previous implementation of MAP estimation, the ML estimation (part of MAP) was using the first label of the combined labels. For example, if user asked for metric in the spinal cord, the beta_0[0] (from ML) would be only based on the first label (WM), not on all the labels (in that case, WM + GM). This PR fixes it.
> Added flag to combine all labels

- .travis.yml
- spinalcordtoolbox/process_seg.py
- unit_testing/test_process_seg.py
Weirdly, when inspecting the variable region.solidity [here](https://github.com/neuropoly/spinalcordtoolbox/blob/master/spinalcordtoolbox/process_seg.py#L176), the program exits with segmentation violation (exit code 139). This has only been observed on Sierra.
Travis build: https://travis-ci.org/neuropoly/spinalcordtoolbox/jobs/542929536#L903
A proposed solution is to discard solidity for Sierra distribution.
Fixes #2307
> Fixed compatibility of skimage.regionprop on OSX Sierra

- .travis.yml
- requirements.txt
- scripts/sct_check_dependencies.py
- spinalcordtoolbox/process_seg.py
With the recent move to 3.6 (https://github.com/neuropoly/spinalcordtoolbox/pull/2238), we had to upgrade Tensorflow. As a consequence, we lost compatibility with older OSs, such as OSX 10.11.
In this PR we introduce a conditional installation of tensorflow version for OSX 10.11. 
Fixes #2302 
<details><summary>Test this PR (run on El Capitan)</summary>
```bash
git clone -b jca/2302-osx10.11 --depth=1 https://github.com/neuropoly/spinalcordtoolbox.git sct-osx10.11
cd sct-osx10.11/
./install_sct
```
</details>
> Fixed compatibility with OSX 10.11 (El Capitan)

- scripts/sct_process_segmentation.py
- spinalcordtoolbox/reports/qc.py
This PR features a new entry to the QC report: CSA results. 
This report would also facilitate the optimization of default parameter for `get_centerline` (used for angle correction in CSA computation), see https://github.com/neuropoly/spinalcordtoolbox/pull/2299
To test:
```bash
sct_download_data -d sct_testing_data
cd sct_testing_data/t2
sct_process_segmentation -i t2_seg.nii.gz -qc qc-csa
```
> Add CSA results on QC report 

- spinalcordtoolbox/reports/assets/_assets/css/style.css
- spinalcordtoolbox/reports/assets/index.html
Currently, there is a mishandling of the columns when using the search module.
To fix this bug, a search bar has replaced the one that used to be automatically generated when generating the table. (fixes #2317 )
Use this qc report to test the solution: [Issue2317.zip](https://github.com/neuropoly/spinalcordtoolbox/files/3311058/Issue2317.zip)
> Fixed mishandling of the columns when using the search module

- spinalcordtoolbox/reports/assets/_assets/css/style.css
- spinalcordtoolbox/reports/assets/index.html
At the moment, there is a mishandling of the columns when the header of any column is clicked. 
Indeed, when the user clicks any part of the header when certain columns are supposed to be hidden, the entirety of the table except for the header cells that are supposed to be hidden is displayed 
To fix this bug, we make a delayed function call that hides the columns that are supposed to be hidden every time the user clicks on the table head. (fixes #2323 )
> Fixed mishandling of columns when sorting

- install_sct
On `install_sct` the echo `saying that the `-k` flag can be used to use Python 2.7 was removed because it is unused. 
Low
> Remove not suported flag -k  fromm install_sct

- batch_processing.sh
Removed square brackets from remove QC folder section. Some OS, don't allow multiple conditionals on if conditionals with double square brackets like in here,
```
if [[ -z "$SCT_BP_NO_REMOVE_QC" -a -d "$SCT_BP_QC_FOLDER" ]]; then
```
Having these two conditionals `-a -d` together doesn't work with square brackets.
Fixes #2354
> Fix batch_processing, remove qc folder conditional failing

- .gitignore
- install_sct
- `die` function added: Throws an error in red color, easier to spot when something happened.
- `check_requirements` function added: Checks if either `wget` or `curl` and `git` are installed before starting with the rest of the script. This saves the user time.
- Check after `pip install`: Throws an error if something wrong happened.
- Small refactor on functions. Keyword `function` added before each function name.
> Refactor install_sct

- README.md
- unit_testing/test_deepseg_lesion.py
- Make test_deepseg_lesion.py::test_intensity_normalization stable by modifying the range of random numbers so that it never fails.
- Update reference of Gros et al.: replace arxiv with NIMG
Fixes #2312, Fixes #2322
> Make test_deepseg_lesion.py::test_intensity_normalization stable

- batch_processing.sh
When running batch_processing.sh, QC folder is saved under ~/qc. The problem is that ~/ is not shared between Docker and the Windows host, therefore users cannot easily open the QC.
The proposed solution is to save the QC locally, and ask users to run the batch_processing.sh once they are under the shared folder.
Fixes #2368
> batch_processing.sh: QC report is now generated locally

- scripts/sct_analyze_lesion.py
- scripts/sct_analyze_texture.py
- scripts/sct_deepseg_lesion.py
- scripts/sct_deepseg_sc.py
- scripts/sct_detect_pmj.py
- spinalcordtoolbox/utils.py
With the passage of the old parser to Python's argparse, output folders now need to be created otherwise it crashes (see #2372). Instead of adding lines of code in the CLI everytime we need to create a folder, a new class `ActionCreateFolder` is now available in `spinalcordtoolbox.utils`, to create the folder when parsing input arguments.
Fixes #2372
> Fixed creation of output folder and introduced new argparse class

- requirements.txt
Install nipy using http directly instead of git.
Fixes: #2362
> Install nipy with http instead of git

- scripts/sct_concat_transfo.py
- scripts/sct_register_multimodal.py
Due to the recent change in `sct_concat_transfo`'s CLIs, `sct_register_multimodal` broke. This PR fixes it.
Fixes #2381
> Fixed broken compatibility with sct_concat_transfo

- scripts/sct_apply_transfo.py
- scripts/sct_deepseg_sc.py
- spinalcordtoolbox/image.py
When applying `sct_apply_transfo`, the registered image and destination space did not have the same header. This was due to the way ANTs deals with q/sform. 
This PR fixes the problem by copying the q/sform and associated q/sform codes from the destination image to the registered image. Fixes #2398
This PR also copies the q/sform from the input image to the output segmentation in `sct_deepseg_sc`. Fixes #2106.
> Fixed q/sform on transformed image

- scripts/sct_image.py
When int type arguments were inputted as `-removed-vol` or `-keep-vol`, those respective arguments were not parsed as the proper variable type.
This PR parses the arguments correctly by changing the variable type of each element of the inputted list from a character to an int (fixes #2395 ).
To test the PR, one may do the following within `sct_testing_data/fmri`: 
For `-keep-vol`: 
`sct_image -keep-vol 0 -i fmri.nii.gz -o fmri_0.nii.gz`
For `-remove-vol`:
`sct_image -remove-vol 0 -i fmri.nii.gz -o fmri_0.nii.gz`
> Proper handling of int arguments contained in list type input

- scripts/sct_process_segmentation.py
At the moment, when outputting the QC report with script `sct_process_segmentation` and specifying a value for argument `-z`, the last graph always displays all slices rather than displaying the slices specified by argument `-z`. 
This PR corrects the slice information on the last (bottom) graph to only display the information related to the wanted slices. (fixes #2391 )
If the following commands are executed:
```
sct_download_data -d sct_testing_data
cd sct_testing_data/data/t2
sct_process_segmentation -i t2_seg_manual.nii.gz -z 2:5 -perslice 1 -qc qc-test
```
The following QC report is outputted:
> Corrected wrong slice information on QC output

- batch_processing.sh
- spinalcordtoolbox/deepseg_gm/deepseg_gm.py
- spinalcordtoolbox/process_seg.py
- spinalcordtoolbox/reports/slice.py
- spinalcordtoolbox/resampling.py
- unit_testing/create_test_data.py
- unit_testing/test_resampling.py
If axial in-plane resolution is anisotropic, some shape morphometric measures, such as RL/AP diameter and orientation are wrong. 
This PR solves it by resampling the data to isotropic resolution (chooses the smallest pixel size between RL and AP dimension for target resolution) before computing shape morphometrics.
Also see: http://forum.spinalcordmri.org/t/sct-process-segmentation-is-mixing-up-diameter-rl-and-diameter-ap/135/3
> Fixed wrong morphometric measures with anisotropic in-plane resolution

- scripts/sct_image.py
- spinalcordtoolbox/image.py
The function `sct_image -setorient-data` was not effectively changing the orientation of the input data as expected. This PR fixes it by **not** changing the header when defining a destination orientation (it is only changing the data).
Fixes #2062
> Fixed -setorient-data giving wrong results

- install_sct
Fixes: #2404 
- Fetching the OS was refactored to be a function and is now called at the beginning of the script. Nice to check from the beginning on the requirements.
- Checks if `gcc` installed and ask the `osx` users if they want to install it right away.
> Check if gcc is installed

- scripts/sct_fmri_moco.py
Use copy instead of move for fmri_moco_params.tsv in sct_fmri_moco.py to avoid the below error when running in a Singularity container.
File "/opt/sct/scripts/sct_fmri_moco.py", line 452, in <module>
main()
File "/opt/sct/scripts/sct_fmri_moco.py", line 225, in main
sct.mv(os.path.join(path_tmp, 'fmri_moco_params.tsv'), os.path.join(path_out + file_data + param.suffix + '_params.tsv'))
File "/opt/sct/scripts/sct_utils.py", line 421, in mv
os.rename(src, dst)
OSError: [Errno 18] Invalid cross-device link: '/tmp/sct-20190821183953.774530-fmri_moco-kvn3v5rh/fmri_moco_params.tsv' -> './fmri_moco_params.tsv'
Fixes https://github.com/neuropoly/spinalcordtoolbox/issues/2419
Tested and working for me.
> Replaced sct.mv with shutil.copyfile for tmp space issue

- spinalcordtoolbox/straightening.py
Fix a bug that was happening when running straightening with more than two disc labels. 
Fixes #2426
> Fixed wrong input arguments

- scripts/sct_process_segmentation.py
- spinalcordtoolbox/aggregate_slicewise.py
- spinalcordtoolbox/process_seg.py
- unit_testing/test_process_seg.py
With the recent removal of `-p` in `sct_process_segmentation`, it was no more possible to measure cord length. This feature was removed because we (wrongly) thought it was not used, but [some users expressed interest](http://forum.spinalcordmri.org/t/computing-cord-length-in-v4-0-0/105) in having this feature back. 
This PR implements cord length computation as part of `sct_process_segmentation`.
In brief, the algorithm for computing cord length is to sum slice thickness (corrected for cord angle) across a specified number of slices (by default, all slices). A new column with label `SUM(length)` is now present in the output .csv file.
To test it:
~~~
sct_download_data -d sct_testing_data
cd sct_testing_data/t2
sct_process_segmentation -i t2_seg_manual.nii.gz -perslice 0
~~~
> Compute cord length

- scripts/sct_denoising_onlm.py
- IndexError bug reported #2430. Now fixed.
- Display `fsleyes` command in terminal output:
```
Done! To view results, type:
fsleyes t2.nii.gz t2_denoised.nii.gz &
```
- Change the default value of `verbose`: set to 1 instead of 0.
Fixes #2430.
NB: We will be able to answer this issue: http://forum.spinalcordmri.org/t/sct-denoising-onlm-error-sct-version-4-0-2/157
> Fix index error and display fsleyes command

- scripts/sct_download_data.py
Removes folder names based on it's name not on `data_name`
Fixes: #2425
> Check if folder already exists by checking its actual name, not the name of the entry to -d flag

- scripts/sct_deepseg_sc.py
- spinalcordtoolbox/deepseg_lesion/core.py
- spinalcordtoolbox/deepseg_sc/core.py
- spinalcordtoolbox/deepseg_sc/postprocessing.py
- unit_testing/test_deepseg_sc.py
When using `sct_deepseg_sc`, sometimes the top and/or bottom segmented slice shows incomplete segmentation: only few isolated voxels have the value "1". This could create some issues later on, see for example #2435. 
In this PR, we implement a fix, which consists in computing the CSA across all slices, and checking if the extreme slices have a CSA that is 50% smaller than the median of the CSA on the previous slides. If it is, it will zero the slide.
Specific changes to this PR include:
- Now checking extreme segmented slices and remove isolated voxels (see description above). Fixes #2435
- Refactored `deepseg_sc.core` by creating a new file `deepseg_sc.postprocessing` that includes post-processing code. For clarity.
Note: this issue is similar to #1074 when using `sct_propseg`, for which …
> Remove isolated voxels at the edge of the output segmentation

- .travis.yml
- README.md
There was likely a change to Keras recently, and El Capitan is no more supported, as suggested by the recent [Travis fail](https://travis-ci.org/neuropoly/spinalcordtoolbox/jobs/586215576#L713).
In this PR we drop support to OSX <10.12 (i.e., El Capitan and older).
Fixes #2445
> Dropped support for El Capitan

- spinalcordtoolbox/centerline/nurbs.py
The function crashes during straightening. It only happens in isolated cases. The segmentation (see "steps to reproduce" below) looks OK: some irregularities on the derivatives, but no discontinuities.
This PR fixes #2443 by changing some indexing, as detailed [here](https://github.com/neuropoly/spinalcordtoolbox/issues/2443#issuecomment-532359342).
Other notable issues addressed in this PR:
TODO:
- the usage does not specify "nurbs" in -param algo_fitting, even though it seems to always use this algorithm regardless the input param. 
- When using -v 2, the straightening command does not pass the verbose info. The sct.run() should be replaced with python call.
- The [linear interpolation before running nurbs](https://github.com/neuropoly/spinalcordtoolbox/blob/master/spinalcordtoolbox/cent …
> Fixed shape mismatch during straightening

- scripts/sct_dmri_concat_b0_and_dwi.py
- scripts/sct_image.py
- scripts/sct_testing.py
- spinalcordtoolbox/image.py
- testing/test_sct_dmri_concat_b0_and_dwi.py
As of now, if users have separate b=0 scans, they have to concatenate them manually, then update bvals/bvecs files manually. This PR introduces the new function `sct_dmri_concat_b0_and_dwi`, which does the following:
- Input: FILE(s): b0, dwi, FILE: bvecs, FILE: bvals
- Output: FILE: b0_dwi, FILE: bvecs_concat, FILE: bvals_concat
Other changes:
- Refactoring: moved `sct_image.concat_data()` --> `spinalcordtoolbox/image.concat_data()`
- Added test for this new function
Fixes #2451
> New script to concatenate b0 and dwi data

- spinalcordtoolbox/image.py
- spinalcordtoolbox/reports/slice.py
- spinalcordtoolbox/resampling.py
Sometimes, the QC report shows an overlay which is shifter by one slice compared to the background image, as illustrated below:
To reproduce:
SCT commit 6cd471ae1c153c71d51ad0c8c808082cd4e1e756
Data:  [data_issue2453.zip](https://github.com/neuropoly/spinalcordtoolbox/files/3653640/data_issue2453.zip)
Syntax:
~~~
sct_qc -i PAM50_t1_reg.nii.gz -p sct_register_multimodal -s sub-amu01_acq-T1w_MTS_seg.nii.gz -d sub-amu01_acq-T1w_MTS_crop.nii.gz
~~~
The problem is rooted in the resampling method, which works by applying an affine transformation matrix to an input image (from nibabel's code). What has likely happened in this issue (and similar issues), is that sometimes there are imprecision in the qform matrix, yielding a slight rotation of the image upon interpolation, even though in this …
> QC report: Fixed shift along slice direction between image and overlay

- scripts/sct_analyze_lesion.py
- scripts/sct_analyze_texture.py
- scripts/sct_apply_transfo.py
- scripts/sct_compute_ernst_angle.py
- scripts/sct_compute_hausdorff_distance.py
- scripts/sct_compute_mscc.py
- scripts/sct_compute_mtr.py
- scripts/sct_compute_mtsat.py
- scripts/sct_compute_snr.py
- scripts/sct_concat_transfo.py
- scripts/sct_convert.py
- scripts/sct_create_mask.py
- scripts/sct_crop_image.py
- scripts/sct_deepseg_gm.py
- scripts/sct_deepseg_lesion.py
- scripts/sct_deepseg_sc.py
- scripts/sct_denoising_onlm.py
- scripts/sct_detect_pmj.py
- scripts/sct_dice_coefficient.py
- scripts/sct_dmri_compute_bvalue.py
- scripts/sct_dmri_compute_dti.py
- scripts/sct_dmri_concat_b0_and_dwi.py
- scripts/sct_dmri_concat_bvals.py
- scripts/sct_dmri_concat_bvecs.py
When mandatory arguments are missing in CLI, the function crashes and gives an error which is difficult to interpret. The parser should take care of providing a human friendlier verbose. 
This is fixed by adding `required=True` in functions where Python's argparse is used.
The Wiki has also been updated [here](https://github.com/neuropoly/spinalcordtoolbox/wiki/example_script) to document how the parser should be used.
Fixes #2456
> Better management of CLI syntax in case mandatory arguments are missing

- scripts/sct_maths.py
The skimage function `threshold_adaptive()` has been deprecated, so this PR replaces it with the equivalent `threshold_local()`.  This PR also includes slight clarifications in the usage.
Fixes #2471
> Fixed deprecation with adaptative thresholding

- install_sct
- scripts/sct_download_data.py
This PR accommodates fixes an issue that appeared when installing SCT under Singulary container, where a folder located in another file system could not be moved.
The implemented solution is to copy the files (instead of moving them). This PR also includes a few minor improvements, notably by replacing shutil by distutils for copying files to existing directories (not possible with shutil.copytree).
Fixes #2472
> Fixed issue that appeared when trying to remove temporary folder from different file systems

- scripts/sct_deepseg_sc.py
- spinalcordtoolbox/deepseg_lesion/core.py
- spinalcordtoolbox/deepseg_sc/core.py
- spinalcordtoolbox/deepseg_sc/postprocessing.py
- spinalcordtoolbox/process_seg.py
- unit_testing/test_deepseg_sc.py
For some reasons, some DWI datasets yield empty segmentations (or highly sub-segmented), causing the postprocessing module to crash later on.
This PR fixes:
- The segmentation issue, which was related to a resampling problem.
- Raises a more elegant error during postprocessing if inputing an empty segmentation.
Fixes #2464 
**WARNING: Output segmentation is overall larger (especially on dwi scans), therefore CSA studies should be based on this SCT version (or previous version), but not a mix of both versions.**
> Fixed segmentation issue that mostly appeared on DWI data

- .travis.yml
- requirements.txt
- setup.py
- spinalcordtoolbox/process_seg.py
- unit_testing/test_process_seg.py
A new version of the library `scikit-image` (16.0.1) changed the way regionprops.orientation() is defined, which made [unit testing crashing](https://travis-ci.org/neuropoly/spinalcordtoolbox/jobs/600352204#L1079). This PR fixes it and brings other minor improvements listed below: 
- Fixed wrong orientation in `process_seg` with `scikit-image==16.0.1`. Fixes #2494 
- Pytest is now installed by default to facilitate running unit tests.
> Fixed wrong orientation with new version of scikit-image

- batch_processing.sh
- spinalcordtoolbox/deepseg_sc/core.py
The recently-merged PR (https://github.com/neuropoly/spinalcordtoolbox/pull/2479), which consisted in finding the optimal threshold per contrast, by minimizing the STD of CSA across contrasts, was implemented with a flaw: the binarization after resampling was not done properly. This PR fixes it, and updated the optimal threshold per contrast using [this repository](https://github.com/sct-pipeline/deepseg-threshold) (commit a482d205120d76893c4f21c76e4535cc45bbce11).
Fixes #2488
> Fix deepseg threshold (again)

- scripts/sct_compute_mtr.py
- spinalcordtoolbox/image.py
- spinalcordtoolbox/qmri/mt.py
- unit_testing/test_qmri.py
A combination of issues yielded aberrant MTR values as the output of `sct_compute_mtr`:
- The output dtype was based on the input mt1 image. If it was int, it created ugly precision.
- Division by very small numbers yielded aberrant values (highly dependent on output dtype).
This PR fixes it by:
- Forcing float32 as the output of mtr
- Create a "smart" divider, where zeros are removed before division and output values can be clipped given application-specific priors (e.g., MTR should not be higher than 100). The advantage of aggressive clipping is that the output NIFTI file has a "human-friendly" range (e.g. -100/+100), so people don't have to adjust the dynamics when opening the image in a viewer, as [can happen sometimes](http://forum.spinalcordmri.org/t/computed-mtr-resulting-in-dark-im …
> Fixed aberrant mtr values

- spinalcordtoolbox/resampling.py
When users try to resample with an aberrant matrix size in any dimension, an exception `ZeroDivisionError: float division by zero` is thrown. 
This PR raises the exception and explain the user what is happening.
Fixes #2504, Fixes #1103
> Raise error if trying to resampling to size zero

- spinalcordtoolbox/reports/assets/_assets/css/style.css
- spinalcordtoolbox/reports/assets/_assets/js/main.js
- spinalcordtoolbox/reports/assets/index.html
Some users requested to adjust the frequency of the fading (too fast/slow) for toggling the overlay (e.g. segmentation), while other users preferred to have more control on the toggling. 
This PR removes the automatic toggling of the overlay and implements a new button (with shortkey "right arrow") to toggle the overlay. See below the added button.
Fixes #2511
> Added button to toggle overlay and removed automatic fading

- README.md
I suggest we redirect to the Youtube page instead of populating the README with embedded videos (more maintenance)
> README: Added link to Youtube tutorials

- scripts/sct_register_to_template.py
A bug has been introduced in 4.1.0, where the registered template (in subject space) and subject (in template space) are cropped. This PR fixes it.
Fixes #2531
> Fixed cropping of registered image

- requirements.txt
Linked to the issue signalled here: http://forum.spinalcordmri.org/t/spinal-cord-dki-processing/185/19?u=alexandrufoias
~~~
(venv_sct) osboxes@osboxes:~/Downloads$ sct_deepseg_sc -i kurtosis_dwi_mean.nii -c dwi -centerline viewer
 
--
Spinal Cord Toolbox (4.1.0)
 
Config deepseg_sc:
  Centerline algorithm: viewer
  Brain in image: False
  Kernel dimension: 2d
  Contrast: dwi
  Threshold: 0.01
 
Create temporary folder (/tmp/sct-20191113150318.717328-u564u8q2)...
Reorient the image to RPI, if necessary...
Finding the spinal cord centerline...
/home/osboxes/sct_4.1.0/python/envs/venv_sct/bin/python: relocation error: /home/osboxes/sct_4.1.0/python/envs/venv_sct/lib/python3.6/site-packages/PyQt5/Qt/plugins/platforms/../../lib/libQt5DBus.so.5: symbol …
> PyQt5 version downgrade to fix GUI on Debian 8.11 distros

- shell/sct_run_batch.sh
I fixed building of path for input arguments/files for `sct_run_batch.sh ` script. Script failed when input files were not in same directory as the script or when input files were entered with absolute path (script expected only file names).
Fixes #2517
> Fixed issue when passing absolute path to script

- scripts/sct_apply_transfo.py
This PR aims to add the -label flag to the sct_apply_transfo script. This flag can be used when applying a warping field to images containing point-like labels (e.g., discs label).
It performs the following :
* Change interpolation to 'nearest neighbor'
* Dilate labels on the image 
* Apply the warping field to the dilated image
* Apply cubic_to_point function to retrieve point-like labels on the transformed image.
Fixes #2519
> Added an option for keypoints transformation

- .travis.yml
To temporarily address the following Travis crash: 
https://travis-ci.org/neuropoly/spinalcordtoolbox/jobs/625017450#L3098
Note: This is not a sensitive change given that coveralls has not been thoroughly used so far (we are still building unit tests).
> .travis.yml: Removed coveralls check

- scripts/msct_register.py
A bug likely introduced in #2331 makes the function crash when using the flag -initwarp, throwing an ugly "UnboundLocalError: local variable 'fname_dest2src' referenced before assignment".
This PR fixes the issue by making sure all output variables are defined.
Fixes #2565
> Fixed bug related to missing output file

- scripts/sct_warp_template.py
- spinalcordtoolbox/metadata.py
A bug related to the new definition of `spinalcordtoolbox.metadata.get_file_label()` prevented the generation of the QC report, because the label "white matter" was recently renamed in "mask white matter (probabilistic)". This PR fixes the problem by simply removing the useless if statement.
Fixes #2564
> Fixed generation of QC report

- spinalcordtoolbox/vertebrae/detect_c2c3.py
`detect_c2c3()` called by `sct_label_vertebrae` throws a "This file does not exist...", even though the model is properly installed at the cited location. This bug has likely been introduced in #2560.
This PR fixes the issue by adding a missing file extension when checking file existence.
Also replacing `sys.exit(1)` with the more specific `raise FileNotFoundError`.
Fixes #2568
> Fixed missing file extension in detect_c2c3()

- README.md
- install_sct
On the README: added gcc as pre-requisite software before installing SCT (included instructions for installation on OSX and Linux).
On the installer: Added instructions for gcc installation on Linux.
Fixes #2575
> Added gcc as installation pre-requisite with useful instructions

- scripts/sct_utils.py
The default syntax for opening SCT output file on Linux was `xopen`, which is not widely available. The proposed solution is to replace this command with `xdg-open`, which is [available by default in most distros](https://stackoverflow.com/questions/264395/linux-equivalent-of-the-mac-os-x-open-command). 
Fixes #2574
> sct_utils: Changed default open command for Linux

- install_sct
At a few places, the installer was calling tcsh/tsh commands, whereas the shebang line forces the script to run under bash. This causes issues for tcsh users. Moreover, users with bin/sh shells could not run the installer. The modifications are:
- Remove all tcsh commands that are executed within this script,
- Cover /bin/sh shells (assume .bashrc env file)
Fixes #2584
> Fixed incompatibility with non-bash shells

- scripts/sct_crop_image.py
- spinalcordtoolbox/cropping.py
- testing/test_sct_crop_image.py
I just removed the `+1` in that [line](https://github.com/neuropoly/spinalcordtoolbox/blob/master/spinalcordtoolbox/cropping.py#L43) to get the correct dimension.
Fixes #2603
> Fixed problem with parameters xmax, ymax and zmax

- scripts/sct_crop_image.py
The flag `-b 1` is expected to not crop the image (i.e. reduce dimension), but instead mask the image outside of the bounding box defined by xmin, xmax, etc. with zeros. However, in the current implementation (commit 576ddeb), it does crop the image. This PR fixes the problem (an argument was missing in the crop() function).
The usage for `-b` was also clarified.
Fixes #2605
> Fixed flag -b crops instead of masking

- scripts/sct_maths.py
A bug related to a missing input argument in `convert_list_str()` made `sct_maths -erode` crash. This has now been fixed, and the doc has been clarified.
Fixes #2612
> Fixed missing type when using erode feature

- README.md
Forum link in the README redirected to sourceforge instead of spinalcordmri.org
> Fixed README forum link

- scripts/sct_apply_transfo.py
- scripts/sct_label_vertebrae.py
- scripts/sct_maths.py
- scripts/sct_register_to_template.py
- spinalcordtoolbox/math.py
- spinalcordtoolbox/testing/create_test_data.py
- spinalcordtoolbox/vertebrae/core.py
- unit_testing/test_math.py
This PR brings some improvements to the dilate/erode methods in `sct_maths`:
- ported some of the functions of sct_maths into a new dedicated python module called `math`
- enabled 2D kernel for morpho math operations. Fixes #2615 
- redefinition of selem variable in erosion/dilation kernel.
- added unit tests for morpho math operations
- Updated usage to mention grayscale input. Fixes #2611
> Enable 2D kernel for morpho math operations and various improvements

- scripts/sct_dmri_concat_b0_and_dwi.py
This PR https://github.com/neuropoly/spinalcordtoolbox/pull/2647 raised a wrong usage of the function, due to a lack of documentation.
This is now fixed in this PR.
> Clarified documentation

- scripts/sct_get_centerline.py
> When running sct_create_mask -p CENTERLINE, if the centerline has some slices that are missing (i.e., empty slice), then the mask will also be missing for those slices, which could be problematic when the mask is subsequently used for sct_dmri_moco, where all slices need to have a non-zero mask.
The new feature:  
> An additional option has been added in sct_get_centerline -m where users could input the segmentation, and the output would be the segmentation fitted (e.g. bspline, etc.) for all slices.
My understanding is: if the image has been segmented then the get_centerline function will not skip slices. This new option would be used for images where the spinal cord isn't visible on all slices.
DONE:
-I've added flag -m that takes for argument the centerline fitting method. 
-When the …
> Fit centerline across all slices with input segmentation

- README.md
Previous user badge was pointing to sourceforge (not used anymore). Now pointing to discourse forum.
> Update badge for discourse forum

- scripts/msct_register.py
If input image is not RPI and mask is input, all images were reoriented to RPI except the mask, which made some registration algorithms relying on a mask to fail (e.g. slicereg). This PR fixes it.
> Fixed forgot to reorient mask

- install_sct
This is only useful for debugging. It's more helpful to us to let the install finish,
even if sct_check_dependencies thinks things are wrong, and then for tests to run,
than to jump to a conclusion, at least until sct_check_dependencies gets some maintainance.
> Don't enforce sct_check_dependencies.

- scripts/sct_download_data.py
The URL for PAM50 appears to have changed. This causes the install script to hang, which results it in never performing configurations, writing to the bashrc, etc. With the new link, it installs correctly. jcohenadad raises this in Issue 2649
> sct_download_data: bad link hangs install (fixes #2649)

- .travis.yml
- scripts/sct_testing.py
Switch to using standard boolean exist/nonexisting flags instead of passing an integer value. It's weird to say `--download 0` just to disable downloads, and also the types were broken, possibly because argparse changed?
These were weird:
```
(sct_venv) $ sct_testing -v
--
Spinal Cord Toolbox (git-master-be4f8e9890bfc0ba141a8961d21bc8a12c5c979b)
usage: sct_testing.py [-h] [--function FUNCTION [FUNCTION ...]]
[--download {0,1}] [--path PATH] [--remove-temps {0,1}]
[--jobs JOBS] [--verbose {0,1}] [--abort-on-failure]
[--continue-from CONTINUE_FROM] [--check-filesystem]
[--execution-folder EXECUTION_FOLDER]
sct_testing.py: error: argument --verbose/-v: expected one argument
```
```
(sct_venv) $ sct_testing -v 0
--
Spinal Cord Toolbox (git-master-be4f8e9890bfc0ba141a8961d21bc8a12c5c979b) …
```
> sct_testing: Use boolean flags

- spinalcordtoolbox/utils.py
This prevents lines being broken within words when using R| at the beginning of an argparse help string
Useful for #2658
> Fix argparse linewrap for R| strings

- scripts/sct_download_data.py
- spinalcordtoolbox/download.py
- spinalcordtoolbox/utils.py
- unit_testing/test_utils.py
While working on https://github.com/neuropoly/spinalcordtoolbox/pull/2639, I had to make `sct_download_data`'s subfunctions callable by other Python processes, so the purpose of this PR was to move those functions (previously located in the CLI script) into a new `spinalcordtoolbox.download` module. 
This PR also introduces the following changes to `sct.utils`:
- added: `add_suffix` and `splitext` (formerly `extract_fname`)
- created unit tests for these
> Moved sct_download_data functions to new download module

- .ci.sh
- .travis.sh
- .travis.yml
- util/dockerize.sh
This adds Debian, CentOS, and ArchLinux to Travis, and it is easy to add other Linux distros thanks to Docker.
I could not decide on a better way than to [take Travis' advice](https://docs.travis-ci.com/user/job-lifecycle/#complex-build-commands) and move the entire test script to a separate shell script because we depend deeply on being able to pass environment variables from one step to the next in order to set up our venv (for `bin/` and for `conda`), and that just doesn't work with a series of `docker exec`s. This means losing the nice collapsing of sections that Travis does, but I don't think that's a big deal; I usually look at the raw plaintext logs anyway.
This adds only minimal time to CI because each build runs in mostly parallel. I've seen Travis running 6 at a time. I predict …
> Support Travis testing arbitrary distros via Docker

- .ci.sh
Travis has a strict 4MB log limit (https://github.com/travis-ci/travis-ci/issues/1382) which the progress bar greedily eats up.
> Disable pip's progress bar in CI.

- .travis.sh
- install_sct
This fixes up the issue that, in CI, the WSL install was hanging at `libssl` -- actually, at trying to "configure" it -- with a prompt to the user, which is a concept that only really exists in Debian/Ubuntu:
```
Package configuration
┌──────────────────────┤ Configuring libssl1.1:amd64 ├──────────────────────┐ 
│ There are services installed on your system which need to be restarted    │
| when certain libraries, such as libpam, libc, and libssl, are upgraded.   │
| Since these restarts may cause interruptions of service for the system,   │
│ you will normally be prompted on each upgrade for the list of services    │
│ you wish to restart.  You can choose this option to avoid being           │ 
│ prompted; instead, all necessary restarts will be done for you            │
│ automatically …
```
> WSL CI: DEBCONF_FRONTEND=noninteractive

- batch_processing.sh
- scripts/sct_version.py
This PR adds useful formatting for the output of `batch_processing.sh` in order to compare different SCT versions (e.g. used for each release). Fixes #2498
We also introduce the CLI `sct_version`.
> Added useful formatting to compare SCT versions; introduced sct_version

- .travis.yml
Merging pytorch (6aa1f4e) caused
> OSError: dlopen: cannot load any more object with static TLS
on [Debian 8](https://travis-ci.org/github/neuropoly/spinalcordtoolbox/jobs/690411071) and [Ubuntu Trusty](https://travis-ci.org/github/neuropoly/spinalcordtoolbox/jobs/690411076) ( caught by #2690  :) ).
This is a known issue with pytorch, see e.g.
https://github.com/pytorch/pytorch/issues/2083
https://github.com/scikit-learn/scikit-learn/issues/14485
https://github.com/pytorch/pytorch/issues/2575
https://stackoverflow.com/questions/14892101/cannot-load-any-more-object-with-static-tls
Apparently there might be a workaround involving reordering import statements, but I think the root issue is that pytorch doesn't get testing on "obscure" platforms. Including pytorch means we can't reliably …
> Drop support for 2014-era Linux.

- requirements.txt
- spinalcordtoolbox/deepseg/models.py
Addition of support for ONNX models in sct_deepseg as discussed [here](https://github.com/neuropoly/spinalcordtoolbox/compare/al/onnx-model?expand=1). 
Changes:
- Add support to ONNX models on model's path verification
- Add version requirement on ivadomed (version where ONNX models were implemented)
- Add t2_tumor model
> ONNX model support and addition of tumor segmentation model

- spinalcordtoolbox/reports/qc.py
- unit_testing/test_qc_parallel.py
The cause of the crash in #2683 is that `reports.qc.generate_qc()` was not safe to run in parallel, because it creates a single output report from all the .json files it finds in the directory it is pointed at *for each subreport*. The crashes we were seeing were a result of some processes trying to read half-written .json data.
I'm guessing it is meant to be used in a pipeline that runs a bunch of image processing steps and reports the results as .json, with the expectation that this is to be done interactively -- so that you would rerun a test and then reload the summary report.
This fixes it by using POSIX file locking around the entire working directory (er, well, the directory being operated on, that is).
This shouldn't slow down any actual tests that use `qc`, it only affects the …
> Parallel-safe quality-control

- scripts/sct_pipeline.py
- scripts/sct_utils.py
- spinalcordtoolbox/utils.py
Fix a few import errors and a string interpolation issue in `send_email` and move it from `sct_utils` to `utils`. Fixes #2728
> Fix and move send_email (2728)

- batch_processing.sh
- scripts/sct_straighten_spinalcord.py
- spinalcordtoolbox/centerline/core.py
- spinalcordtoolbox/centerline/curve_fitting.py
- spinalcordtoolbox/centerline/nurbs.py
- spinalcordtoolbox/testing/create_test_data.py
- unit_testing/test_centerline.py
Since recently, `test_get_centerline` is [failing on Travis](https://travis-ci.org/github/neuropoly/spinalcordtoolbox/jobs/700617618). This is probably related to an upgrade of a Python library and/or platform-dependent (as noted in https://github.com/neuropoly/spinalcordtoolbox/pull/2686)
This PR: 
- Replaced `numpy.polyfit` by `numpy.polynomial.Polynomial` as per [numpy's doc](https://numpy.org/doc/stable/reference/generated/numpy.polyfit.html#numpy-polyfit), in `centerline.curve_fitting.polyfit_1d()`
- Removed: test_get_centerline_nurbs[img_ctl5-expected5-params5] due to a ReconstructionError caused by the change in the dummy centerline generation. 
Fixes #2753
> Fixed test_centerline crashing due to bump in Python library

- unit_testing/test_deepseg.py
`pytest:test_deepseg:test_segment_nifti` used to overwrite the `t2s_seg.nii.gz` file. When running in Travis, `sct_testing` runs after pytest, and therefore is affected by modifications in the testing data.
In the issue encountered [here](https://travis-ci.org/github/neuropoly/spinalcordtoolbox/builds/702419420?utm_source=github_status&utm_medium=notification), the integrity test `test_sct_get_centerline` uses the (now modified) `t2s_seg.nii.gz` file as a ground truth, which generates this failure. 
This PR fixes the problem by _not_ overwriting the existing segmentation when running `pytest:test_deepseg:test_segment_nifti`.
Also see https://github.com/neuropoly/spinalcordtoolbox/pull/2748#issuecomment-650470407
> Do not overwrite existing segmentation during pytest:test_deepseg

- install_sct
- scripts/sct_download_data.py
- spinalcordtoolbox/deepseg/models.py
- spinalcordtoolbox/download.py
For #2415.
Using Github releases as CDN, but another CDN fetching data from the releases can also be used.
Data in sct_download_data is converted to be in their own repository, using a conversion script (https://github.com/sct-data/sct-data-archeology), which:
Data is stored in the new https://github.com/sct-data/
Introduce a tool used to automate deployment.
> Retrieve data bundles from their new location

- scripts/sct_download_data.py
- scripts/sct_get_centerline.py
- scripts/sct_label_vertebrae.py
- spinalcordtoolbox/math.py
- testing/test_sct_analyze_lesion.py
- testing/test_sct_analyze_texture.py
- testing/test_sct_convert_binary_to_trilinear.py
- testing/test_sct_crop_image.py
- testing/test_sct_deepseg_sc.py
- testing/test_sct_dice_coefficient.py
- testing/test_sct_flatten_sagittal.py
- testing/test_sct_get_centerline.py
- testing/test_sct_label_utils.py
- testing/test_sct_label_vertebrae.py
- testing/test_sct_merge_images.py
- testing/test_sct_process_segmentation.py
- testing/test_sct_propseg.py
- testing/test_sct_qc.py
- testing/test_sct_register_to_template.py
- testing/test_sct_smooth_spinalcord.py
- testing/test_sct_straighten_spinalcord.py
- tests/test_reports.py
- unit_testing/test_centerline.py
- unit_testing/test_deepseg.py
- unit_testing/test_deepseg_sc.py
- unit_testing/test_qc_parallel.py
- unit_testing/test_straightening.py
Some segmentation methods are not reproducible across OSs, leading to non-reproducible pipelines across OSs.  This PR was initiated by https://github.com/neuropoly/spinalcordtoolbox/issues/2769. 
The purpose of this PR is to:
- Update [sct_testing_data](https://github.com/sct-data/sct_testing_data) repository with the following changes:
- Remove the redundancy of integrity testing between `sct_testing` and `pytest` for:
> Figured out what segmentation technique is reproducible across platforms; improve test sensitivity.

- contrib/fsl_integration/sct_plugin.py
Detailed list of improvements below:
- Added "stop" functionality to `ProgressDialog` and hooked to `SCTCallThread` to send a `SIGINT` if the user presses stop.
- Improve `ErrorDialog` to display a specific/more useful error message to the user instead of the generic one (dialog shown when `SCTCallThread` returns non-zero codes).
- Refactor `SCTCallThread` to retrieve progress in real time.
- Added a `TxtCtrl` widget to the UI in order to display the `SCTCallThread` progress in real time.
- Various other small fixes.
Relates to:
- #2594
Screenshots:
**When processing:**
**When command was successful:**
**When an error occurred:**
> Improvements for the FSLeyes plugin

- scripts/sct_run_batch.py
The output folder `results` includes the `/data` folder which can be **very** large (20GB+ for spine-generic) and not convenient to copy.
A more convenient output organization would be to separate data/ from the output csv files. That way, `results/` can be easily packaged and copied. Something like this:
~~~
results_spinegeneric
|- data_processed/ <--- currently under results/
|- log/
|- qc/
|- results/  <--- only includes the .csv files (and other results artifacts)
~~~
This PR introduces this change.
Fixes #2786
> Introduced variable PATH_DATA_PROCESSED

- scripts/sct_get_centerline.py
- scripts/sct_qc.py
- spinalcordtoolbox/reports/qc.py
Fixes https://github.com/neuropoly/spinalcordtoolbox/issues/2780
I tried with data from https://github.com/spine-generic/data-single-subject.
Here are some screenshots.
> Implement QC sct_get_centerline

- scripts/sct_apply_transfo.py
An unnecessary warning was displayed during normal behaviour. This PR fixes it, and clarifies comments in the code.
Fixes #2810
> Clarified cropping strategy for sct_apply_transfo; remove warning

- README.md
- requirements.txt
- scripts/sct_utils.py
From @rordenlab:
> A pedantic comment on spinalcordtoolbox - the documentation refers to “OS X” (OS ten) extensively. I would suggest changing this to “MacOS”, not only because that is Apple branding, but I guess the upcoming MacOS 11.0 would be “OS XI” (OS eleven)
The instances were found with
```
git grep -i  "OS X" -- './*' ':(exclude)spinalcordtoolbox/reports/*'
```
(reports/ has a lot of archived stuff that I am not going to change!)
> Apple's OS is now macOS.

- scripts/sct_download_data.py
Fixes #2779, by pulling in the fix from https://github.com/ANTsX/ANTs/issues/1040.
This partially follows https://github.com/neuropoly/spinalcordtoolbox/wiki/Package-data-&-binaries, but with the very difficult parts have been replaced by a build script on Github. Reminder: we need to rewrite/remove these wiki pages (https://github.com/neuropoly/spinalcordtoolbox/issues/2815) to incorporate these changes.
> Upgrade bundled ANTs.

- setup.py
* `setup.py`: Use `packages=find_packages()` so that all submodules will be installed, not just `spinalcordtoolbox`(Fixes https://github.com/neuropoly/spinalcordtoolbox/issues/2834#issuecomment-670229911)
* Adds `__init__.py` to `scripts/` to have it be installed as a package, which moves the location of the script files to where `spinalcordtoolbox.compat.launcher` expects. (Fixes https://github.com/neuropoly/spinalcordtoolbox/issues/2834#issuecomment-670660230)
* Note: the `scripts` option in `setup.py` **is not** used. This is because of the limitation that `compat.launcher` imposes, see below:
https://github.com/neuropoly/spinalcordtoolbox/blob/fce82d8c98fab1cc878c4e8c48fa1c515f0db35c/setup.py#L63-L65
Fixes #2834.
Note: This PR is dependent on version changes in #2833. Without #2833, a …
> Change setup.py for `pip install .` to fix Readthedocs CLI rendering

- .travis.yml
- install_sct
- requirements.txt
Travis started failing on macOS 10.12 a few weeks ago, e.g. https://travis-ci.org/github/neuropoly/spinalcordtoolbox/jobs/717668875. Due to changes I made earlier this summer (#2690) this only nagged me once a day when the cron build kicked in and I ignored it. But now I'm here to quiet it.
Here's the error:
> ```
> Collecting requirements-parser
>  Downloading requirements-parser-0.2.0.tar.gz (6.3 kB)
> Collecting scipy
>  Downloading scipy-1.5.2-cp36-cp36m-macosx_10_9_x86_64.whl (28.8 MB)
> Collecting scikit-image
>  Downloading scikit-image-0.17.2.tar.gz (29.8 MB)
>
>    ERROR: Command errored out with exit status 1:
>     command: /Users/travis/build/neuropoly/spinalcordtoolbox/python/envs/venv_sct/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = …
```
> Pre-install numpy to build.

- scripts/sct_run_batch.py
Converts `sct_run_batch` from using `multiprocessing` to either `concurrent.futures` or `mpi4py.futures` for managing the worker pool. This resolves #2806 and #2817
> Fix thread reporting, early termination, and indentation error in sct_run_batch

- scripts/msct_register.py
- scripts/sct_dmri_separate_b0_and_dwi.py
- scripts/sct_label_vertebrae.py
- scripts/sct_register_to_template.py
Fixes #2851.
This explicitly sets `verbose` to prevent `squeeze_data` from incorrectly being set instead.
> Explicitly set verbose in calls to generate_output_file

- scripts/sct_run_batch.py
When launching multiple `sct_run_batch` in parallel using [run_all](https://github.com/sct-pipeline/csa-atrophy/blob/master/run_all.py) with the same output folder, the following error sometimes happens:
~~~
Spinal Cord Toolbox (git-master-253936cfc07712c587d9f4cfbbcb760f151172f0)
/home/jcohen/sct/scripts/sct_run_batch.py:241: UserWarning: Using the `-config|-c` flag with additional arguments is discouraged
warnings.warn(UserWarning('Using the `-config|-c` flag with additional arguments is discouraged'))
configuring
File "/home/jcohen/sct/scripts/sct_run_batch.py", line 479, in <module>
File "/home/jcohen/sct/scripts/sct_run_batch.py", line 300, in main
os.mkdir(pth)
FileExistsError: [Errno 17] File exists: …
> Prevent crash if folder already exists

- scripts/sct_dmri_separate_b0_and_dwi.py
The recent PR #2819 fixed that bug, but also changed the behaviour: the average scan is not more produced, which breaks all the current processing pipelines already in place, e.g.
https://github.com/spine-generic/spine-generic/blob/4143cbfd7a206f06e3fd9f42485d5087129899d7/process_data.sh#L261
This PR changes the default to be average=1 to ensure cross-compatibility.
Fixes #2881
> Change default value for average to maintain cross-compatibility

- spinalcordtoolbox/utils.py
Fixes #2756.
This PR modifies SCT's `SmartFormatter` so that default values are shown if they are not `None`. 
Two questions:
* Are there any cases where we **want** to show `(default: None)`? (See https://github.com/neuropoly/spinalcordtoolbox/issues/2756#issuecomment-650613090.)
* Should this PR go through all of the descriptions to edit redundant info out? If so, this PR is dependent on #2842. An example:
```
-ofolder <folder>  Output folder (e.g. "./") (default: ./)
```
> Automatically show defaults in argparse help descriptions

- .github/workflows/generate-sidebar.yml
Fixes #2855.
This PR adds a GitHub Actions workflow that automatically updates the Wiki sidebar whenever a Wiki page is added or a page title is changed. It does this using a third-party [`github-wiki-sidebar`](https://github.com/adriantanasa/github-wiki-sidebar) tool. This way, the sidebar doesn't have to be manually updated each time a page changes. _(It's a shame that GH doesn't do this natively, but alas!)_
I tested this workflow on a personal repo ([`joshuacwnewton/test-github-action-wiki`](https://github.com/joshuacwnewton/test-github-action-wiki)) and it works nicely:
* [Test page](https://github.com/joshuacwnewton/test-github-action-wiki/wiki/General%3A-Test-page-(should-show-up-In-sidebar)) to check if the GH Actions workflow would automatically add the page to the sidebar.
* …
> Add GitHub Action workflow for automatically updating custom Wiki sidebar

- scripts/sct_run_batch.py
- spinalcordtoolbox/utils.py
Adds a small function to `utils` for checking the url associated with the `origin` remote. Then adds this to the `sct_run_batch` output.
Also modifies the commit check to use the absolute path for both the script and data directory instead of the raw version in the `args` namespace.
> Add git origin checking for sct_run_batch

- scripts/sct_compute_mtsat.py
- unit_testing/test_sct_compute_mtsat.py
Closes #2908 
- When a help entry says `-omtsat <str>  Output file for MTsat. Default is mtsat.nii.gz` -> it is misleading to save the output file in the same folder as the input file (when `-omtsat` is not provided). Instead use the current working directory which better reflects the default.
- Unit test should not save in `sct_testing_data`. For lack of a better place use the current working directory instead.
> sct_compute_mtsat.py: more sane defaults

- install_sct
Fixes #2920.
Updates continuum.io links to new domain, anaconda.com. This fixes issues where users are unable to connect to continuum.io due to its domain change.
> install_sct: Update continuum.io to anaconda.com

- .ci.sh
- .travis.sh
Reverts neuropoly/spinalcordtoolbox#2910.
I appears that this breaks the build on certain platforms (see https://travis-ci.org/github/neuropoly/spinalcordtoolbox/builds/730936670)
> Revert "Run batch_processing if building master"

- requirements.txt
Fixes #2930.
SCT installs `onnxruntime` as it's an IVADOMED dependency. Recently, it's pypi version was bumped from 1.4.0 to 1.5.1. This change breaks our TravisCI job for macOS Mojave. The underlying reason is unclear, but in the meantime, this PR applies a temporary fix to restore the CI job.
This should be followed up on after conferring with the `onnxruntime` project devs.
> Pin onnxruntime version to fix "ImportError: cannot import name 'get_all_providers'" for macOS in CI

- scripts/sct_apply_transfo.py
- scripts/sct_create_mask.py
- scripts/sct_label_utils.py
- scripts/sct_label_vertebrae.py
- scripts/sct_register_to_template.py
- spinalcordtoolbox/labels.py
- spinalcordtoolbox/types.py
- unit_testing/test_labels.py
Closes #2870 
Closes #2905 
Needed by #2873 
After #2842 
After #2903 
batch_processing results
```
Version:         git-aj/2870-refactor_sct_label_utils-144f6950224434a98a474f719c63950064f55ec4*
Ran on:          Linux drupad-p1 5.4.64-1-MANJARO                                                                                                              
Duration:        0hrs 13min 53sec                                 
---
t2/CSA:          73.87711295363036
mt/MTR(WM):      54.420871701809666
t2s/CSA_GM:      12.487834828856178
t2s/CSA_WM:      64.93830702088246
dmri/FA(CST_r):  0.7756557364086285
dmri/FA(CST_l):  0.7801552138489745
```
> Refactor sct_label_utils into proper API

- scripts/sct_register_to_template.py
Fixes #2927. 
Argparses uses `%` for format specification. To display `%` as a regular character, `%%` must be used instead. 
This PR fixes incorrect `%` usage in iCloud links in argparse help descriptions.
> sct_register_to_template: Fix '%' in argparse iCloud help links

- scripts/sct_deepseg.py
- scripts/sct_dice_coefficient.py
- scripts/sct_fmri_compute_tsnr.py
- scripts/sct_image.py
- scripts/sct_maths.py
- scripts/sct_merge_images.py
- scripts/sct_straighten_spinalcord.py
Fixes #2926. 
Replaces the following behaviors with `if arguments.arg is not None`:
* `if '-arg' in arguments`
* `if arguments['arg']`
This PR also fixes a check for a required arg (`if '-i' not in args`) by simply making the argument itself required.
> Fix incorrect checking of input arguments

- .travis.yml
- requirements.txt
Potentially a better fix for #2930. See https://github.com/microsoft/onnxruntime/issues/5344#issuecomment-702124166.
> Replace onnxruntime==1.4.0 version pinning with libomp install for macOS CI jobs

- .travis.yml
Fixes #2930. Follows PRs #2931 and #2932. 
Recap of what's happened so far:
* `onnxruntime` got a version bump, causing the macOS Travis builds to fail due to a missing  `libomp` dependency.
* Travis's Homebrew addon can be used to install `libomp`, which worked for macOS 10.14.
* The version of Homebrew that ships with Travis's macOS 10.12 and 10.13 images [is out of date](https://travis-ci.community/t/macos-build-fails-because-of-homebrew-bundle-unknown-command/7296/14), causing issues with installation.
By supplying `update: true`, this should _hopefully_ be the final change needed to fix the macOS builds. (But, it is hard to say conclusively as 10.12 and 10.13 builds currently only run on merge.)
> Fix issue with outdated Homebrew in older macOS TravisCI images

- scripts/sct_fmri_moco.py
- scripts/sct_label_vertebrae.py
- scripts/sct_process_segmentation.py
- scripts/sct_propseg.py
- scripts/sct_register_multimodal.py
- scripts/sct_register_to_template.py
- scripts/sct_smooth_spinalcord.py
- scripts/sct_warp_template.py
Fixes #2843.
Updates remaining binary options to be typed as integers (rather than using string values). Also updates usage so that `arg == "1"` or `int(arg)` are no longer used.
I've also created a new dev Wiki page called [Argparse in CLI Scripts](https://github.com/neuropoly/spinalcordtoolbox/wiki/Programming:-Argparse-in-CLI-scripts) that includes a section for this change called [Integer (0/1) options vs. action="store_true"](https://github.com/neuropoly/spinalcordtoolbox/wiki/Programming:-Argparse-in-CLI-scripts#integer-01-options-vs-actionstore_true). (It also combines information from a few other recent discussions.)
> Convert argparse '0'/'1' options to be typed as ints rather than strings

- scripts/sct_maths.py
Fixes #2844.
A factory function (`list_type`) was written as part of #2819 to parse typed lists in arguments. 
`list_type` is more general than the `convert_list_str` function in sct_maths, which was created for a similar purpose. So, this PR replaces the 4 instances of `convert_list_str`.
> sct_maths: Convert usage of convert_list_str to use list_type

- .travis.yml
- documentation/source/user_section/installation.rst
- install_sct
Fixes #2930 and #2841. Supersedes #2919.
Apple dropped support for 10.12 in October 2019. Other third-party tools we depend on have either limited support, or have dropped support entirely for 10.12. In several cases, this has forced us to hack together solutions to keep support for 10.12 alive.
By dropping support for 10.12, this PR deals with 2 such 10.12-specific issues at once: `onnxruntime` requiring `libomp` to be installed in the build environment (tricky for 10.12), and `scikit-image`'s 10.12 sdist requiring a `numpy` preinstall.
> Drop 10.12 testing in TravisCI (and fix numpy preinstall)

- scripts/isct_convert_binary_to_trilinear.py
- scripts/isct_test_ants.py
- scripts/sct_analyze_texture.py
- scripts/sct_apply_transfo.py
- scripts/sct_check_dependencies.py
- scripts/sct_compute_hausdorff_distance.py
- scripts/sct_create_mask.py
- scripts/sct_detect_pmj.py
- scripts/sct_dice_coefficient.py
- scripts/sct_dmri_separate_b0_and_dwi.py
- scripts/sct_image.py
- scripts/sct_label_vertebrae.py
- scripts/sct_propseg.py
- scripts/sct_register_multimodal.py
- scripts/sct_register_to_template.py
- scripts/sct_smooth_spinalcord.py
- scripts/sct_testing.py
- scripts/sct_utils.py
- scripts/sct_warp_template.py
- spinalcordtoolbox/centerline/optic.py
- spinalcordtoolbox/moco.py
- spinalcordtoolbox/straightening.py
- spinalcordtoolbox/vertebrae/detect_c2c3.py
- testing/test_sct_dmri_moco.py
- testing/test_sct_orientation.py
- testing/test_sct_propseg.py
In the scope of #2898
After #2943 
Groundwork for further refactoring
- cleanup dead code in `sct_utils.py`
- refactor `sct_utils.run()` to use `spinalcordtoolbox.run_proc()`
> sct_utils: cleanup dead code

- contrib/fsl_integration/sct_plugin.py
Closes #2579 
Implement: https://github.com/neuropoly/spinalcordtoolbox/issues/2579#issuecomment-705004337
> fsleyes: allow user to specify output folder

- documentation/source/index.rst
- spinalcordtoolbox/__init__.py
- spinalcordtoolbox/aggregate_slicewise.py
- spinalcordtoolbox/centerline/__init__.py
- spinalcordtoolbox/compat/__init__.py
- spinalcordtoolbox/deepseg/__init__.py
- spinalcordtoolbox/deepseg_gm/__init__.py
- spinalcordtoolbox/deepseg_lesion/__init__.py
- spinalcordtoolbox/deepseg_lesion/core.py
- spinalcordtoolbox/deepseg_sc/__init__.py
- spinalcordtoolbox/deepseg_sc/cnn_models_3d.py
- spinalcordtoolbox/deepseg_sc/core.py
- spinalcordtoolbox/gui/__init__.py
- spinalcordtoolbox/qmri/__init__.py
- spinalcordtoolbox/registration/__init__.py
- spinalcordtoolbox/reports/__init__.py
- spinalcordtoolbox/reports/qc.py
- spinalcordtoolbox/vertebrae/__init__.py
- unit_testing/test_deepseg_sc.py
Closes #2951 
After #2949
Closes #2954  
- Implements more standard package imports for sub-packages (see https://github.com/neuropoly/spinalcordtoolbox/issues/2951#issuecomment-710053812)
- Fixes various doc warnings
- Removes the unnecessary `set_image_data_format()` calls that cancel each other since functionality seems to have been obsoleted (see https://github.com/neuropoly/spinalcordtoolbox/issues/2954#issuecomment-713138372)
> fix doc build warnings + associated bug

- scripts/isct_convert_binary_to_trilinear.py
- scripts/isct_test_ants.py
Suggestion for https://github.com/neuropoly/spinalcordtoolbox/pull/2982
> Use SystemExit not sys.exit & only on error paths.

- requirements.txt
> Pin h5py~=2.10.0 as a workaround for upstream Keras/TensorFlow issues

- contrib/fsl_integration/sct_plugin.py
- requirements.txt
- scripts/sct_check_dependencies.py
- scripts/sct_deepseg.py
- scripts/sct_download_data.py
- spinalcordtoolbox/deepseg/core.py
Postprocessing is dealt by ivadomed, hence is removed from SCT to avoid code duplication.
Changes include:
- New postprocessing option: remove small objects
- Remove postprocessing code from SCT
- Change default params of '-fill-holes' and '-largest' (now set to 0 by default)
Before merging, a release of ivadomed will be required (sister PR: https://github.com/ivadomed/ivadomed/pull/486)
> Remove deepseg postprocessing

- contrib/docker/Erase_fingerprint_docker.sh
- contrib/docker/README.md
- contrib/docker/sct-win.xlaunch
- contrib/docker/sct-win_docker_toolbox.xlaunch
- documentation/source/user_section/installation.rst
Fixes #2964. 
Related to #2965.
To start this PR, I've left the steps mostly as they were from [the GitHub Wiki page](https://github.com/neuropoly/spinalcordtoolbox/wiki/Misc%3A-Docker-(Installing-SCT,-using-GUI)). But, I imagine these steps will change following discussion from the dev team, especially due to #2965.
**➤ Rendered doc: https://spinalcordtoolbox.com/en/jn-2964-fix-docker-install-docs/**
> Move Docker installation instructions from GitHub Wiki to RTD

- scripts/sct_download_data.py
In the current PAM50 (v4.0.0-beta.0), the cord, levels and levels_continuous are not perfectly matched. See below (slice 904):
PAM50_levels.nii.gz (red) overlaid on PAM50_cord.nii.gz (white):
PAM50_levels_continuous.nii.gz (red) overlaid on PAM50_cord.nii.gz (white):
The purpose of this PR is to update the link to the [new release of the PAM50](https://github.com/sct-data/PAM50/releases/tag/r20201104), which fixes the issue. 
Fixes #2172
P.S. Thank you @lrouhier for generating these new files 💯
> Fixes inconsistencies between PAM50 levels and cord

- scripts/sct_deepseg.py
- spinalcordtoolbox/__init__.py
- spinalcordtoolbox/centerline/__init__.py
- spinalcordtoolbox/compat/__init__.py
- spinalcordtoolbox/deepseg/__init__.py
- spinalcordtoolbox/deepseg_gm/__init__.py
- spinalcordtoolbox/deepseg_lesion/__init__.py
- spinalcordtoolbox/deepseg_sc/__init__.py
- spinalcordtoolbox/gui/__init__.py
- spinalcordtoolbox/qmri/__init__.py
- spinalcordtoolbox/registration/__init__.py
- spinalcordtoolbox/reports/__init__.py
- spinalcordtoolbox/reports/qc.py
- spinalcordtoolbox/vertebrae/__init__.py
This reverts commit f65df321b078b939e5de66755ca0561fe773ed82.
Based on discussion: https://github.com/neuropoly/spinalcordtoolbox/issues/2989
Implicit imports causing undesirable increase in load time.
> Revert "More sane package imports"

- scripts/sct_deepseg.py
- spinalcordtoolbox/deepseg/models.py
- unit_testing/test_deepseg.py
This PR introduces the following changes:
- To avoid confusion and errors, sct_deepseg will only have task (and no models). Fixes #2994
- Update legend to remove the "default [*]" in `-list-tasks`. Fixes #2996
To address in subsequent PRs:
- Remove the field "default" in models: https://github.com/neuropoly/spinalcordtoolbox/issues/3007
- Duplication of logs output. Fixes #2993
> remove models for sct_deepseg 

- scripts/sct_extract_metric.py
Fixes #2934
In `sct_extract_metric`'s help description:
* `info_label.txt` is referenced without having been downloaded. (RTD uses pip install, which doesn't call `sct_download_data` like `install_sct` does.) So, this PR references SCT's documentation instead.
* `sct_extract_metric.py` -> `sct_extract_metric`
* `-v` -> `-vert`
* `-m` -> `-method`
New output:
```
This program extracts metrics (e.g., DTI or MTR) within labels. Labels could be a single file or a folder generated with 'sct_warp_template' containing multiple label files and a label description file (info_label.txt). The labels should be in the same space coordinates as the input image.
The labels used by default are taken from the PAM50 template. To learn about the available PAM50 white/grey matter atlas labels and their …
```
> Update sct_extract_metric help to fix RTD error + fix outdated usage

- spinalcordtoolbox/utils/shell.py
- spinalcordtoolbox/utils/sys.py
closes #3008 
-  `run_proc()` was not checking verbosity and using DEBUG (which is a bit confusing, because verbosity is set to 1 by default in many constructors which I used to think meant `LEVEL==DEBUG`, but now realize it means `LEVEL==INFO`).
- `utils.shell` can use `printv()` with color support as long as it gets called from scripts and not API.
> Logging and printing fixes

- .travis.yml
Fixes #2692.
* Adds 10.15 job to all builds.
* Moves 10.14 job to just release/cron.
* Updates 10.14 image from [`xcode11.2` to `xcode11.3`](https://docs.travis-ci.com/user/reference/osx/)
> Travis: Add 10.15 (Catalina), update 10.14 (Mojave) image

- spinalcordtoolbox/utils/sys.py
Fixes #2388.
This PR causes the command to be output when scripts are called from the command line. It does not add this output when scripts are called internally using `<sct_script>.main()`.
Before 
```sh
--
Spinal Cord Toolbox (git-master-c29d6c332662ae8fad0954f70991f35078d5c399)
Creating temporary folder (/tmp/sct-20201108124345.693440-create_mask-gcnlyd6q)
Process finished with exit code 0
```
After
```sh
--
Spinal Cord Toolbox (git-jn/2388-display-script-command-245baf340bb9d07ade29aa2f708cbedeb0b06502)
Command run: sct_create_mask -i mt/mt1.nii.gz -p coord,15x17 -size 10 -r 0
--
Creating temporary folder (/tmp/sct-20201108124257.376323-create_mask-radd3pxn)
Process finished with exit code 0
```
> Display command when scripts are called from the command-line

- scripts/sct_label_utils.py
Fixes #3024.
Note that this will apply to all functions in `sct_label_utils` and not just `-create-seg`, which was mentioned in the original issue.
Example output:
```
--
Spinal Cord Toolbox (git-jn/3024-label-utils-message-54bc53942ef9ae5c521399d24c416e359e6432d9)
sct_label_utils -i T1_seg.nii.gz -create-seg 0,14:106,8
--
Generating output files...
Done! To view results, type:
fsleyes T1_seg.nii.gz labels.nii.gz &
```
I've used both the input and output images so that users can toggle on and off and view differences/overlays.
> sct_label_utils.py: Add message for generated files

- scripts/sct_run_batch.py
- unit_testing/test_sct_run_batch.py
Either sets the script itself to executable if the output directory is the current working directory, or sets the output directory copy to executable and uses that.
This should resolve #3030.
Potential improvement:
Right now, `sct_run_batch` copies the user's script to the output directory, in the event the current working directory is the output directory there is no copy made. In this case I opted to modify the original script, which is perhaps distasteful, but I feel it is relatively harmless. If others disagree, we could make a copy with a suffix and modify the permissions on that.
> sct_run_batch: handle the case of unexecutable script

- scripts/sct_label_utils.py
Fixes #2424.
* Remove reference to 'z axis' in order to make it explicitly clear that the user is specifying slice indexes along the S-I axis.
* Clarify wording regarding the form of the  ':'/',' delimiting.
* Clarify wording in examples.
Old wording:
```
Create labels along cord segmentation (or centerline) defined by '-i'.
First value is 'z', second is the value of the label. Separate labels
with ':'. Example: 5,1:14,2:23,3.
To select the mid-point in the superior-inferior direction, set z to
'-1'. For example if you know that C2-C3 disc is centered in the S-I
direction, then enter: -1,3
```
New wording:
```
Create labels on a cord segmentation (or centerline) image defined by
'-i'. Each label should be specified using the form 'v1,v2' where 'v1' is
value of the slice index along the …
```
> sct_label_utils.py: Clarify -create-seg usage description

- documentation/source/conf.py
Fixes #3015. (https://github.com/neuropoly/spinalcordtoolbox/issues/3015#issuecomment-723709323)
> RTD: Re-enable showing version text underneath logo 

- .travis.yml
- requirements.txt
Fixes #3033.
Alternate solution compared to #3034.
I believe #3034 is the better long-term solution. But, that PR is blocked by #3035. 
Because of the urgent need for a patch, this PR applies a quicker solution that is easier to test/verify.
> Pin onnxruntime==1.4.0 to avoid libomp issue on macOS

- scripts/sct_process_segmentation.py
Fixes #3038 
Fixes bug where an int arg value (e.g. 1) is parsed a str ('1').
> Add missing type information to argument in sct_process_segmentation

- install/generate-requirements-freeze.sh
Fixes #3040 
Successor to #2745
A quick little script to automate the following steps from the [Creating a new release](https://github.com/neuropoly/spinalcordtoolbox/wiki/Misc%3A-Creating-a-new-release) dev Wiki page:
> - Freeze the requirements:
>     ~~~
>     source ${SCT_DIR}/python/etc/profile.d/conda.sh
>     conda activate venv_sct
>     pip freeze > requirements-freeze.txt
>     conda deactivate
>     ~~~
> - Edit the generated `requirements-freeze.txt` file:
>   - Remove the line that says: `-e git+https://github.com/neuropoly/spinalcordtoolbox.git@...`
>   - Manually-copy the platform-dependent lines (related to Pytorch) from `requirements.txt` to `requirements-freeze.txt`, to avoid [this issue](https://github.com/neuropoly/spinalcordtoolbox/issues/2745). Example of lines:
> …
> Add script to automate requirements-freeze.txt generation

- .travis.yml
- install_sct
Fixes #3048.
Partially addresses #2820.
This PR uses `'.'` delimiting rather than relying on character counts to fix version parsing issue in `install_sct`. 
This PR includes 2 smaller changes that overlap with the above change: 
* It updates the minimum supported OSX version, as that was not done in #2946 when it should have been.
* It updates instances of "OSX" to the more accurate term "macOS" within `install_sct`.
> Fix version parsing to support Big Sur (11.0)

- .github/PULL_REQUEST_TEMPLATE.md
Fixes #3027.
~~Mirror of [`shimming-toolbox/pull_request_template.md`](https://github.com/shimming-toolbox/shimming-toolbox/blob/master/.github/pull_request_template.md).~~
Some changes have been made, mainly:
* Adding additional checklist items to ensure internal documentation is followed.
* Adding links to relevant internal documentation pages.
* Grouping checklist items by type.
> Add slightly modified PR template from shimming-toolbox

- install_sct
- requirements.txt
- scripts/sct_deepseg.py
This PR aims at bumping ivadomed version to 2.5.0. 
This should fix this [reported issue](https://forum.spinalcordmri.org/t/installation-validation-failed-installation-failed/570) by pinning `onnxruntime` to version 1.4.0 
Changes made: 
* update requirements.txt
* Change function call in `scripts/sct_deepseg.py`
fix #3033
> Bump ivadomed version to 2.5.0

- spinalcordtoolbox/scripts/sct_label_utils.py
This PR aims at enabling the use of ':' ( e.g., 2:5 for 2,3,4,5) for the `-create-viewer` option in `sct_label_utils`. This is using the [`parse_num_list`](https://github.com/neuropoly/spinalcordtoolbox/blob/cab82fd13425515a8568225dbe7fc003d9be2b1f/spinalcordtoolbox/utils.py#L357-L370) function. 
Fix #1476
> Update -create-viewer argument to use parse_num_list function

- install_sct
PR #3034 was included in #3041 to fix #3035. But, on closer inspection, I noticed some issues:
* The fix was only applied to the dev install, not the release install.
* Solution: Use a variable to store the name of the requirements file, then have the pip install be done in a single command for both types of installation.
* The fix used multiple separate commands, which invalidates the `$?` status check.
* Solution: Use `&&` to group commands, so that `$?` remains a valid check. 
* _["Commands separated by a double ampersand && are to be run synchronously, with each one running only if the last did not fail (a fail is interpreted as returning a non-zero return status)."](https://bashitout.com/2013/05/18/Ampersands-on-the-command-line.html)_
* The fix missed a comment that had been …
> Add improvements to recent tensorflow-tensorboard fix

- requirements.txt
- spinalcordtoolbox/scripts/sct_deepseg.py
- unit_testing/test_deepseg.py
Change default values to None for postprocessing steps (`-remove-small`, `-fill-holes`, `-largest`, `-thr`). When no values are set, the postprocessing values in the configuration file of each model will be applied. The user has the option to overwrite the postprocessing steps by using the corresponding flag. The old behavior with a default values were overwriting the values set in the configuration file.
Other change:
- `-remove-small` is now compatible with multiclass models. One or more threshold values can be set for this postprocessing. If more than one value is used, each threshold is associated with its corresponding output class. The order of the output class will be specified in the task description. 
- Destination parameters now match the postprocessing name in ivadomed (`thr` …
> Change default option values to None

- spinalcordtoolbox/scripts/sct_label_utils.py
When creating manual labels, the created labels do not have the value asked for: they are output in float (it whould be integer) and the value is slightly different (precision issue). This bug was introduced in v5.0.0.
This PR fixes the problem by forcing the output label to be UINT8 type.
Also see user forum discussion: https://forum.spinalcordmri.org/t/sct-register-to-template-source-and-destination-landmarks-are-not-the-same/590/4
Fixes #3101
> Forces output label image to be UINT8 with -create-viewer

- spinalcordtoolbox/scripts/sct_run_batch.py
Will print "Processing 7 subjects in parallel. (Worker processes used: 15)", fix #2956
> Print actual numbers of jobs run in parallel.

- install_sct
This glues over a rare glitch in conda (#3029, https://github.com/conda/conda/issues/10401).
Reviewers: please run this under the bug we reproduced in #3029 to make sure it handles that well.
We might also check for: `pip`, or `python3`? Open to feedback.
> Check that conda actually activated during install.

- install_sct
Adding in #3103, but https://github.com/neuropoly/spinalcordtoolbox/runs/1601504567?check_suite_focus=true#step:4:1407 shows it failing on Github Actions with
> ```
>   File "<string>", line 1
>    import sys, path; for f in sys.argv[1:]: print(os.path.realpath(f))
>                        ^
> SyntaxError: invalid syntax
> ```
I guess I didn't actually test this.
Strange that it got past CI?? Maybe Travis's macOS images have GNU realpath installed but Actions' don't??
> Fixup realpath polyfill

- spinalcordtoolbox/reports/slice.py
- unit_testing/test_reports.py
The function `get_center_spit` is supposed to return `index: [int] * n_SI` (indices along in the R-L direction for each S-I slice). But, it was incorrectly returning `index: [int] * n_RL` because it was using the wrong axis shape.
This PR fixes the problem so the correct axis shape is used, and also tweaks comments to make this clearer.
It also fixes a bug where `logger.error` was used when an error should have been raised instead.
Fixes #3087.
> Fix incorrect indexing in get_center_spit to prevent QC report cropping

- .ci.sh
- .travis.sh
- .travis.yml
- install_sct
- util/dockerize.sh
Our installer is fragile around this edges and part of that is that shell itself is fragile. This sets the recommended shell strict-mode settings that make it a bit less of a fragile language to work in.
I did these safety improvements:
- setting [recommended shell safeties](https://sipb.mit.edu/doc/safe-shell/): `set -euo pipefail; shopt -s failglob`
- to appease `set -o pipefail`: switch to `#!/usr/bin/env bash`
- every time we're not polyglottal is unfortunate, but this option is so useful that I think it's worth depending on bash
-  to appease `set -u`: initializing all variables; in the cases of checking external envs, using the cryptic (but standard) `${var:-}` syntax
- to appease `set -o pipefail`: replacing all our uses of `yes |` with the proper non-interactive flag for each …
> Turn on stricter shell rules + maintainence

- spinalcordtoolbox/scripts/sct_label_utils.py
- unit_testing/cli/test_cli_sct_label_utils.py
The form "`-create-seg -1,value`" doesn't work with `argparse`, because `argparse` interprets `-1,value` as a separate argument. So, we split this functionality off into a new option, as per https://github.com/neuropoly/spinalcordtoolbox/issues/3119#issuecomment-750388733.
Fixes #3119.
> Add new '-create-seg-mid' option to replace bugged '-create-seg -1' behavior

- spinalcordtoolbox/scripts/sct_deepseg_sc.py
- spinalcordtoolbox/scripts/sct_detect_pmj.py
- spinalcordtoolbox/scripts/sct_propseg.py
- spinalcordtoolbox/scripts/sct_smooth_spinalcord.py
- unit_testing/cli/test_cli_sct_deepseg_sc.py
- unit_testing/cli/test_cli_sct_detect_pmj.py
- unit_testing/cli/test_cli_sct_propseg.py
- unit_testing/cli/test_cli_sct_smooth_spinalcord.py
This PR aims at adding the `-o` flag on a few function in sct:
fix #1802
fix #897
> Implement -o flag for a few functions

- spinalcordtoolbox/scripts/sct_deepseg.py
This PR adds the possibility to use a custom model with sct_deepseg. One or more paths to the folder containing a model can be indicated next to the `-task` flag to use custom model(s). If more than one path is used, the models will be applied one after the other (the output of the previous model will become the input of the next).
`sct_deepseg -i img.nii.gz -task <path(s) to folder containing the packaged model>`
Fixes #3155
> Add option to have a custom task

- setup.py
- spinalcordtoolbox/scripts/sct_concat_transfo.py
- spinalcordtoolbox/scripts/sct_testing.py
- testing/test_sct_concat_transfo.py
- unit_testing/cli/test_cli_sct_concat_transfo.py
`sct_concat_transfo.py` was recently obsoleted, but after user feedback it was decided to un-deprecate and restore the script. https://github.com/neuropoly/spinalcordtoolbox/issues/2912#issuecomment-761897967
#2912
> Restore previously deprecated sct_concat_transfo.py

- CODE_OF_CONDUCT.md
- CONTRIBUTING.rst
- documentation/source/dev_section/api.rst
- documentation/source/overview/concepts/pam50.rst
- documentation/source/overview/concepts/quality-control.rst
- documentation/source/overview/concepts/spaces-and-coordinates.rst
- documentation/source/overview/concepts/temp-directories.rst
- documentation/source/overview/introduction.rst
- documentation/source/overview/overview.rst
- documentation/source/overview/references.rst
- documentation/source/user_section/command-line.rst
- documentation/source/user_section/getting-started.rst
- documentation/source/user_section/installation.rst
- documentation/source/user_section/support.rst
- documentation/source/user_section/tutorials.rst
- documentation/source/user_section/tutorials/correcting_sct_propseg.rst
Just fixing line wrapping everywhere.
If possible I'd like this to be merged fast-forward (no squashing) because I think there's a bit of a difference between general paragraph wrapping across the documentation (no line breaks) vs careful manual semantic line wrapping in the list of references.
> Fix line breaks in documentation

- spinalcordtoolbox/aggregate_slicewise.py
- unit_testing/test_aggregate_slicewise.py
In #3120, I mistakenly assumed that all metrics would be 1D, so I indexed the metric using `[0]`. This updates the check to index the right dimension depending on the metric shape.
This PR also adds a new dummy metric that is 3D, so that the tests are more representative of real-world data. 
Fixes #3202.
> Fix recently-introduced faulty slice index comparison

- spinalcordtoolbox/registration/register.py
- spinalcordtoolbox/scripts/sct_analyze_texture.py
- spinalcordtoolbox/scripts/sct_compute_hausdorff_distance.py
- spinalcordtoolbox/scripts/sct_create_mask.py
- spinalcordtoolbox/scripts/sct_dice_coefficient.py
- spinalcordtoolbox/scripts/sct_dmri_separate_b0_and_dwi.py
- spinalcordtoolbox/scripts/sct_label_vertebrae.py
- spinalcordtoolbox/scripts/sct_merge_images.py
- spinalcordtoolbox/scripts/sct_register_to_template.py
- spinalcordtoolbox/scripts/sct_smooth_spinalcord.py
Continuation of #2876 
After #2966 
Closes #2878 
Remove subprocess calls of `sct_maths` and use `spinalcordtoolbox.math` API.
~~~
Version:         git-aj/2878-refactor_sct_math_callers-9ed9a41ed88c9d04ae3c56e5e03a64301fdb6feb*
Ran on:          Linux gentoo-p53 5.10.5-gentoo-x86_64
Duration:        0hrs 11min 42sec
---
t2/CSA:          73.87711295363036
mt/MTR(WM):      54.38001546261108
t2s/CSA_GM:      12.487834828856176
t2s/CSA_WM:      64.93830702088249
dmri/FA(CST_r):  0.7756265311035226
dmri/FA(CST_l):  0.7800112266489608
~~~
> Refactor sct_maths callers to remove subprocess and use API

- requirements.txt
- setup.cfg
This PR removes the default usage of `pytest-xdist` when running the unit tests. See minutes from dev meeting:
- Motivation: we have hit some limitations/issues with regards to concurrency issues (https://github.com/pytest-dev/pytest-xdist/issues/271#issuecomment-763402552, https://github.com/neuropoly/spinalcordtoolbox/pull/3152). This complicates the ongoing effort to port CI to github actions (https://github.com/neuropoly/spinalcordtoolbox/pull/3125, https://github.com/neuropoly/spinalcordtoolbox/pull/3152)
- Other annoyances such as xdist disabling `-s` (`--capture=no`) thus preventing the user from viewing the output of `stdout` which is confusing for users. (Relevant dev Wiki page about this issue.)
- This issue specifically is causing Julien to disable `xdist` for local testing, …
> Don't use xdist by default.

- spinalcordtoolbox/aggregate_slicewise.py
Both `-method map` and `-method ml` include data from extra labels in their masks:
https://github.com/neuropoly/spinalcordtoolbox/blob/74f068df9042e6cce8473e67f1a3fe60ddadac70/spinalcordtoolbox/aggregate_slicewise.py#L416-L421
This causes the `Size [vox]` calculation to be larger than expected. 
To fix this, we limit the calculation to only include the first label. (Also, remove `.flatten()`, as it is no longer necessary once we index the array.)
This change is coupled very closely to code inside [a separate `extract_metric()` function](https://github.com/neuropoly/spinalcordtoolbox/blob/74f068df9042e6cce8473e67f1a3fe60ddadac70/spinalcordtoolbox/aggregate_slicewise.py#L389-L434): I make the assumption that `mask` will always have an extra dimension for labels, and that only label `[0]` is …
> Fix size calculation bug for '-method map' and '-method ml'

- spinalcordtoolbox/labels.py
- unit_testing/test_labels.py
> Fix unit_testing/test_labels.py::test_remove_missing_labels

- spinalcordtoolbox/scripts/sct_register_to_template.py
In some datasets, when resampling the label files within the `sct_register_to_template` script, the output label files was encoded in FLOAT64, which in some cases could create label precision error, e.g.: 6.0001 instead of 6.0, leading to label mismatch when registering the input file to the PAM50 labels, then causing issue #3229.
Fixes #3229.
> Enforce UINT8 when resampling labels for register to template

- CHANGES.md
See https://github.com/neuropoly/spinalcordtoolbox/wiki/Misc%3A-Creating-a-new-release for the steps I'm following.
This time, I'm using the `batch_processing.sh` produced by #3198, as it runs on a fresh copy of SCT (in a fresh OS) that is up-to-date with master.
Batch processing results (Ubuntu):
```
Version:         git-HEAD-9ffd2dee82bf1714e0958d2d82be3f5fbb8e0052
Ran on:          Linux fv-az139-629 5.4.0-1039-azure
Duration:        0hrs 21min 1sec
---
t2/CSA:          73.87711295363036
mt/MTR(WM):      54.38001541207312
t2s/CSA_GM:      12.487834828856176
t2s/CSA_WM:      64.93830702088249
dmri/FA(CST_r):  0.7756265423313133
dmri/FA(CST_l):  0.7800112141091362
```
Batch processing results (macOS):
```
Version:         git-HEAD-9ffd2dee82bf1714e0958d2d82be3f5fbb8e0052
Ran on: …
```
> Update CHANGES.md for 5.2.0 release

- setup.cfg
- spinalcordtoolbox/scripts/sct_label_vertebrae.py
Using extend-ignore [preserves the default list of ignored warnings/errors](https://gitlab.com/pycqa/flake8/-/issues/466#note_111460896), which is important for fixing the W503/W504 conflict.
Fixes #3235. 
Related to #2679 because of these linting false positives: https://github.com/neuropoly/spinalcordtoolbox/pull/2679/checks?check_run_id=1979921525
> Use 'extend-ignore' in flake8 config to preserve defaults

- spinalcordtoolbox/image.py
- unit_testing/test_image.py
Allows for qform/sform differences that are 1e-3 or smaller, as per https://github.com/neuropoly/spinalcordtoolbox/issues/3251#issuecomment-786657827.
Fixes #3251.
> Decrease the sensitivity of the sform/qform mismatch check

- spinalcordtoolbox/vertebrae/core.py
- unit_testing/cli/test_cli_sct_label_vertebrae.py
I first wrote a failing test to reproduce the problem, then applied a fix which causes the test to pass. 
The fix falls back on an interpolated centerline if the segmentation is missing in places where the disc label should go.
Fixes #3252.
> Handle 'label_discs' case where SC segmentation has holes/discontinuities

- spinalcordtoolbox/scripts/sct_dice_coefficient.py
When copying `-i` and `-d` input files to a tmp directory, if they had the same filenames (but different parent directories), then `-d` would overwrite `-i`. So, the dice calculation would be performed between `-d` and `-d` (instead of between `-i` and `-d`).
This change ensures that each temp filename is unique.
Fixes #3256.
> Uniquely distinguish filenames for tmp files to prevent overwriting

- .github/PULL_REQUEST_TEMPLATE.md
When creating releases, I've noticed milestones were sometimes missed for merged PRs. I've also noticed that our PR template does not have an item for milestones. 
So, this PR proposes a small change to the template. My hope is that this will also nudge us to think about how a PR fits into the overall release plan for SCT.
N/A
> Add checklist item to pull request template for 'Milestone' label

- requirements.txt
When running `sct_deepseg` on an input image which has qform_code=1 and sform_code=1, the output segmentation has the fields qform_code=0 (incorrect) and sform_code=2. 
This issue was fixed in ivadomed 2.7.4, [see PR](https://github.com/ivadomed/ivadomed/pull/714)
For more details on q/sform conventions, see https://github.com/neuropoly/spinalcordtoolbox/issues/3283
Fixes #3284
Related to https://github.com/ivadomed/ivadomed/issues/711
> Unpin ivadomed to get latest version and fix wrong q/sform_code output

- spinalcordtoolbox/registration/landmarks.py
- spinalcordtoolbox/scripts/sct_register_to_template.py
Currently, the function assumes that the user inputs the cord segmentation with the flag `-s`. SCT then automatically associates `-s` with the file with ID=3 from **info_label.txt** file:
https://github.com/neuropoly/spinalcordtoolbox/blob/6d70ad82fbd9ba7961fc1ef7fbb7ebca70ac6fc7/spinalcordtoolbox/scripts/sct_register_to_template.py#L342
This ID label is supposed to correspond to the spinal cord mask.
However, in some cases where the white matter mask is available, the user might want to use it for registration, as it would provide better registration performance.
In this case, we need to specify somehow that another segmentation ID file should be used.
In this PR we introduce the flag `-s-template-id`, which indicates which file to select to be associated with `-s`. By default, the value …
> Added flag -s-template-id to use another segmentation (e.g. white matter) for registration to template

- contrib/docker/Dockerfile
- documentation/source/user_section/installation.rst
I dropped `yes | ` from our installer while doing https://github.com/neuropoly/spinalcordtoolbox/pull/3125, but it's still in the docs and people are still using it. It's not that it doesn't work, it's just that it can break in unusual circumstances.
https://github.com/neuropoly/spinalcordtoolbox/pull/3125
> Drop `yes |` from the docs

- spinalcordtoolbox/deepseg/models.py
- spinalcordtoolbox/scripts/sct_deepseg.py
In this PR:
Resolves #3278, Resolves #3279
> Update model and fixed default output suffix

- spinalcordtoolbox/scripts/sct_image.py
It uses action="store_true", so the default value is actually False, not None.
Because `-set-sform-to-qform` uses `action="store_true"`, it's default value is `False`.
This means that the check `if arguments.set_sform_to_qform is not None` was wrong. This PR replaces it with `if arguments.set_sform_to_qform`.
Some alternate solutions:
* Setting `default=None` for the argument. This would change it from `True/False` to `True/None` which means we could use `if <> is not None` consistently for every argument.
* Setting [`default=argparse.SUPPRESS`](https://stackoverflow.com/a/48004525) for each argument.
Fixes #3311.
> Fix faulty check for `arguments.set_sform_to_qform`

- spinalcordtoolbox/scripts/sct_run_batch.py
This PR adds step 3:
1. `sct_run_batch` is called.
2. `PYTHONNOUSERSITE` is set to True in `compat/launcher.py` for the context of `sct_run_batch`.
3. **`PYTHONNOUSERSITE` is unset for the context of the pipeline shell script.**
4. (Optional) A pipeline script calls `sct_<function>`.
5. (Optional) `PYTHONNOUSERSITE` is set to True in `compat/launcher.py`, but only in the context of `sct_<function>`.
Step 3 is needed because `PYTHONNOUSERSITE=True` would leak into `sct_run_batch` pipeline shell scripts and affect non-SCT commands. Specifically, the command `gradunwarp` couldn't access its dependencies if they were installed in the user's site packages directory.
Fixes #3200.
> Unset `PYTHONNOUSERSITE` in environment before calling batch script

- spinalcordtoolbox/image.py
- spinalcordtoolbox/scripts/sct_image.py
In #3249, we learned that our current recommendation (`-set-sform-to-qform`) is not sufficient to fix all affine mismatch issues. So, this PR makes the following changes:
* Exposes the complementary operation (`-set-qform-to-sform`)
* Broadens the error message so that users are encouraged to inspect the affine matrices and understand how to fix their own affine matrices.
I also wanted to point users to a documentation page about what valid affines look like (so that users can learn how to spot issues). But, there's not really a good page to link! 
* Nibabel has pages that are close (["Coordinate systems and affines"](https://nipy.org/nibabel/coordinate_systems.html), ["The NIFTI affines"](https://nipy.org/nibabel/nifti_images.html#the-nifti-affines)) but those pages contain a lot of …
> Handle affine matrix mismatches better by exposing `-set-qform-to-sform`

- spinalcordtoolbox/scripts/sct_image.py
- unit_testing/cli/test_cli_sct_image.py
This PR fixes a few issues related to `sct_image -display-warp`:
> Various fixes to sct_image -display-warp

- install_sct
- spinalcordtoolbox/compat/launcher.py
- spinalcordtoolbox/scripts/sct_run_batch.py
The fix for https://github.com/neuropoly/spinalcordtoolbox/issues/3067 turned out to be pretty complicated: https://github.com/neuropoly/spinalcordtoolbox/issues/3200
This is a cleaner fix for that issue, inspired by @takluyver's helpful observation https://github.com/conda/conda/issues/7173#issuecomment-389190657 that `site.py` [is the canonical place to manage this sort of thing](https://docs.python.org/3/library/site.html#site.ENABLE_USER_SITE) -- @takluyver, I know you mitigated your opinion later while helping users, but for us, we're using conda to build a sort of .appimage or .app/ folder, with protected, pinned dependencies, and intentionally not exposing conda to our users, so isolating the entire python site is *exactly* what we need!
This turns a 7 line fix into a 1 line fix: …
> Fully isolate the conda env by its site.py

- install_sct
Spaces are not permitted by the Miniconda install script. We could let it fail by itself, but the error happens after the Miniconda script is downloaded (time-consuming), and the message itself is quite bare:
```bash
ERROR: Cannot install into directories with spaces  # Cannot install what? Unclear if it's an SCT or conda issue
```
So, this PR adds a check that fails earlier, and provides more info so that the user will know that it's an upstream issue.
Fixes #2785.
Fixes #3364.
> Throw error during installation if `$SCT_DIR` contains spaces

- spinalcordtoolbox/scripts/sct_apply_transfo.py
- spinalcordtoolbox/scripts/sct_label_vertebrae.py
- spinalcordtoolbox/scripts/sct_warp_template.py
- spinalcordtoolbox/straightening.py
In #3272, the last remaining calls to `isct_antsApplyTransform` were replaced with `sct_apply_transfo`. But, the default output for  `sct_apply_transfo` is much noisier, which in turn makes scripts like `sct_warp_template` much noisier.
So, this PR:
* Tweaks  `sct_apply_transfo -v 0` so it will have identical output to the old `isct_antsApplyTransform` command.
* Changes all of the calls from #3272 to use `-v 0`.
Now all of the calls should behave as they were before. e.g.:
```
--
Spinal Cord Toolbox (git-jn/3352-fix-sct_apply_transfo-verbosity-d71d79824f61533623b32b672c8efc3148e461e5)
sct_warp_template -d fmri_mean.nii.gz -w warp_template2fmri.nii.gz -a 1 -s 1 -qc ~/qc-example-fmri/
--
Check parameters:
Working directory ........ /home/joshua/repos/spinalcordtoolbox/sct_example_data/fmri …
```
> Change `sct_apply_transfo -v 0` to match `isct_antsApplyTransform` output

- spinalcordtoolbox/image.py
This PR follows the suggestion in https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3110#issuecomment-747822584 to make 2 small improvements: 
1. No longer make a copy of the image, which is accomplished by using the `.change_type()` method instead of the `change_type()` function. (So, now the docstring is accurate, when it wasn't before.)
2. No longer set data to 0 after changing type. (This prevents the `change_type` function from unnecessarily rescaling the data.)
Fixes #3110
> Modify `zeros_like` to no longer make a copy, and to avoid rescaling

- spinalcordtoolbox/scripts/sct_dmri_display_bvecs.py
- unit_testing/cli/test_cli_sct_dmri_display_bvecs.py
#3091 added loglevel setting steps to all SCT scripts. However, `sct_dmri_display_bvecs` never had a verbose argument.
This was never caught because there is no test for `sct_dmri_display_bvecs`. So, this adds an (admittedly very basic) test for the script. (A more thorough test would require some refactoring of `sct_dmri_display_bvecs`.)
This test fails on master, but passes on this branch after `-v` is added.
Fixes #3386.
> Add test for `sct_dmri_display_bvecs`, then add `-v` argument to make the test pass

- spinalcordtoolbox/image.py
Because a copy of the header wasn't made, the exact header object would be reused. This meant that if the header in the original image was changed, then the header of the `zeros_like` image would be changed too. :facepalm: 
This caused problems with `sct_label_utils`, because reorienting the input `img` accidentally affected the header of the `out` image:
https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/9a4b45715240d6c08b8d71587ffbe99a41326cc6/spinalcordtoolbox/scripts/sct_label_utils.py#L366
https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/9a4b45715240d6c08b8d71587ffbe99a41326cc6/spinalcordtoolbox/gui/base.py#L323
This had a cascade of effects inside the sagittal viewer (which are a bit complicated to explain, and not really necessary to understand for this PR). …
> Ensure a copy of the header is used in `zeros_like` to fix `-create-viewer` bug

- .github/workflows/test-batch-processing.yml
- .github/workflows/tests.yml
This is a small quality of life update for developers. The change allows the test suite to be run manually, targeting a specific branch (this is already in place [here](https://github.com/spinalcordtoolbox/spinalcordtoolbox/actions/workflows/automate-changelog-PR.yml), for example). It's useful if you want to quietly test something that you wouldn't be able to test locally (e.g. something specific to the CI) but aren't ready to announce it to everyone with a PR.
One other benefit is being able to manually run the entire test suite once for a PR's branch without having to awkwardly comment out the `if:` conditional.
N/A
> Add `workflow_dispatch` for test suite workflows

- spinalcordtoolbox/scripts/sct_propseg.py
1. We've been using "`if rescale is not 1`" to check if a non-default value has been passed for `rescale`. But, the default value for `rescale` is a float (`1.0`), so the check has been silently evaluating to `True` when we expected it to evaluate to `False`. 
2. Because the check has been silently evaluating to `True` 100% of the time, some file renaming code has quietly become the default behavior of the script. If the faulty check is fixed, suddenly the files won't be renamed anymore, causing an existing test to fail.
This PR fixes both issues. (Improves the checks, makes sure files are still renamed.)
This PR is based off of the work in PR #3382.
> Fix `rescale_header is not 1` because the default value is `1.0`

- spinalcordtoolbox/scripts/sct_register_multimodal.py
- spinalcordtoolbox/scripts/sct_register_to_template.py
- unit_testing/cli/test_cli_sct_register_multimodal.py
In `sct_register_multimodal`, if `-initwarp` is passed but `-initwarpinv` isn't passed, then registration will only be performed one way (i.e. only one warping field will be generated). However, we're still outputting 2 registered image files, with one of them (`dest->src`) being completely empty. Instead of outputting an empty file, we should not output it at all.
So, this PR adds a failing test to check file existence, then includes the necessary changes to make the test pass:
* Skip applying the transform and generating the `dest->src` output files when we're performing one-way registration.
* Only display the viewer syntax if the relevant files were created
Fixes #3404.
> Don't output `dest->src` files if registration is only performed one-way

- spinalcordtoolbox/reports/qc.py
- spinalcordtoolbox/reports/slice.py
The purpose of this PR is to add the option to display a soft segmenation in the qc report.
What is done:
What is left:
On T1w:
On T2w:
Resolves #3417
> Display soft segmentation in qc report

- .github/workflows/test-batch-processing.yml
- conftest.py
- install_sct
- spinalcordtoolbox/centerline/core.py
- spinalcordtoolbox/centerline/nurbs.py
- spinalcordtoolbox/compat/launcher.py
- spinalcordtoolbox/registration/landmarks.py
- spinalcordtoolbox/registration/register.py
- spinalcordtoolbox/scripts/sct_check_dependencies.py
- spinalcordtoolbox/scripts/sct_compute_ernst_angle.py
- spinalcordtoolbox/scripts/sct_maths.py
- unit_testing/cli/test_cli_sct_dmri_display_bvecs.py
Historically, to avoid crashes on headless systems (#1784), we've set `MPLBACKEND` to a non-GUI backend in the user's RC file. We've also tried to detect headless systems using `DISPLAY`, then if we are headless, set `MPLBACKEND` in the CLI launcher. 
However, #1784 appears to have been fixed upstream (https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/3401#issuecomment-861614835), so in theory, these heavy-handed `MPLBACKEND` workarounds are no longer needed.
* Avoid setting `MPLBACKEND` at all within SCT, and let matplotlib choose an appropriate backend itself (Fixes #3392)
* Set `MPLBACKEND=Agg` for the test suite only, since showing interactive plots would interrupt the tests (Fixes #3388)
Additionally, since checking for headless systems using `$DISPLAY` is no longer …
> Stop trying to detect headless systems using `DISPLAY`, and no longer set `MPLBACKEND`

- spinalcordtoolbox/scripts/sct_denoising_onlm.py
Currently, `sct_denoise_onlm` gives no indication about the algorithm(s) used for denoising. We should at least add the proper articles where the methods is implemented:
<details><summary>Function usage</summary>
```console
julien-macbook:~/sct_testing_data/t2s $ sct_denoising_onlm 
--
Spinal Cord Toolbox (git-jca/3413-run-batch-session-c41958db922273a66764ef88239587f91af3adad)
sct_denoising_onlm 
--
usage: sct_denoising_onlm -i <file> [-h] [-p {Rician,Gaussian}] [-d <int>] [-std <float>] [-o <str>]
[-r {0,1}] [-v <int>]
Utility function to denoise images. (Return the denoised image and also the difference between the input and the output.)
MANDATORY ARGUMENTS:
-i <file>             Input NIFTI image to be denoised. Example: image_input.nii.gz
OPTIONAL ARGUMENTS:
-h, --help …
```
> Added bibliography reference for sct_denoising_onlm

- spinalcordtoolbox/scripts/sct_check_dependencies.py
- spinalcordtoolbox/scripts/sct_denoising_onlm.py
After [recent issue](https://forum.spinalcordmri.org/t/problem-with-fsleyes/715) of one user with FSLeyes, we concluded in Slack discussion, that it would be useful if `sct_check_dependencies.py` was able to check FSLeyes version.
Thus, this PR adds check of FSLeyes version into `sct_check_dependencies.py`.
<details>
<summary> Output of sct_check_dependencies.py if FSLeyes is installed: </summary>
```console
--
Spinal Cord Toolbox (git-jv/sct_check_dependencies-check-FSLeyes-version-9c0b9bfcca2e936ebbc20a899bb8023972d83028)
sct_check_dependencies 
--
SCT info:
- version: git-jv/sct_check_dependencies-check-FSLeyes-version-9c0b9bfcca2e936ebbc20a899bb8023972d83028
- path: /usr/local/sct
OS: osx (Darwin-19.6.0-x86_64-i386-64bit)
CPU cores: Available: 4, Used by ITK functions: 4
RAM: Total: …
```
> Add check of FSLeyes version into sct_check_dependencies.py

- spinalcordtoolbox/reports/slice.py
This PR addresses #3434. For generating QC report of spinal cord segmentation, when resampling a binary segmentation (with linear interpolation), it introduces non-binary values. Binarization was removed in https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/3418 to be able to display segmentations with a colormap. A threshold of 0.5 was applied. Most binary segmentations were displayed correctly in the QC report, but there were a few exceptions.
This PR includes :
* Check if input image is binary
* If the image is binary, binarize at 0.5
* Else, apply a threshold at 0.5
To test the fix, I suggest to run `sct_qc` on `/spine-generic-processed/derivatives/labels/sub-mpicbs02/anat/sub-mpicbs02_T1w_seg-manual.nii.gz` from `data.neuro.polymtl.ca:datasets/spine-generic-processed` which …
> Check if input segmentation is binary for QC report

- spinalcordtoolbox/reports/qc.py
This PR fixes #3441 where PMJ is wrongly displayed in QC report.
When using `ax.text(x,y, 'X')` with PMJ coordinates, The `X` is not centered on the coordinate.
I tried using the parameters `ha='center', va='center'` (vertical and horizontal alignement), but when changing `X` for `x` or other letters, the position still varied. Using `ax.text` isn't very robust to display a label. 
I chose to use `ax.plot` to display the label as it is done for QC of `sct_label_utils`
Here is in red the label that was displayed before vs now in green:
Resolves #3441
> Fix display of PMJ in QC report

- spinalcordtoolbox/scripts/sct_detect_pmj.py
Hi, 
I have changed the function call to save the image with passing `verbose=0` as parameters for the same. Please check if this is what it was intended to be. I did ran the `sct_detect_pmj` twice after the modification with the testing data. I have attached the console output for the second run. 
Resolves #3469
> Removal of scary message for user by changing certain function call parameters

- testing/conftest.py
Currently, in pytest, we redownload the test data on every run to ensure that we're working with a fresh copy of the test data. This is wasteful and unnecessary when debugging. 
Ideally we would skip this if the existing test data is fine, and in #2959, we outlined some rough plans to use checksums to verify the integrity of the test data. But, #2959 has stalled (likely due to the workload required for it), so in the meantime, this PR adds a simpler way to skip test data downloading.
I'll also document this on the Test data Wiki page.
N/A, born from Slack message.
> Skip redownloading `sct_testing_data/` if the directory already exists

- documentation/source/overview/studies.rst
- spinalcordtoolbox/image.py
- spinalcordtoolbox/scripts/sct_detect_pmj.py
This PR addresses #3456. Currently, the algorithm od `sct_detect_pmj`works by getting the mid-sagittal slice (averaged across a few adjacent slices)
and running a 2D CNN to detect the PMJ. However, if the mid-sagittal slice does not correspond to the anatomical medial plane, then the detected PMJ will be "off" in the right-left direction.
This PR adds a function `compute_cross_corr_3d` after detecting the PMJ to fine tune R-L coordinate. We pass a sliding window of 20x20x20 from the PMJ coordinate in a range of -10 to 10 in R-L direction. We compute cross-correlation between the image and its mirror and find the maximum which corresponds to the symmetry point. The R-L coordinate of the PMJ is updated to be at the symmetry point.
This was an image where the head was tilted. 
**yellow: …
> Improve R-L placement in `sct_detect_pmj`

- spinalcordtoolbox/csa_pmj.py
- spinalcordtoolbox/reports/qc.py
- spinalcordtoolbox/scripts/sct_process_segmentation.py
This PR addresses #3431. It modifies the QC report for `sct_process_segmentation` to visualize the extrapolated centerline smoothed in R-L direction, the PMJ label and the coverage mask.
Currently, the QC report for `sct_process_segmentation ` was only available inside `sct_process_segmentation` and not when calling `sct_qc`. I left it that way, we could also add it. 
**I created this feature from the branch [jca/sb/3063-csa-measure-from-pmj](https://github.com/spinalcordtoolbox/spinalcordtoolbox/tree/jca/sb%2F3063-csa-measure-from-pmj), I'll merge inside the branch and not the master when it is ready.**
The overlay includes smoothed centerline, coverage mask and PMJ label (in one overlay), do we want to seprate them ?(that would require some further changes). Also, to use the QC with …
> Add QC report for `sct_process_segmentation` for PMJ-based CSA

- spinalcordtoolbox/scripts/sct_check_dependencies.py
When checking dependencies don't crash if non-`ImportError` exceptions occur, instead log and carry on.
Closes #3411
> Don't crash on non-ImportError exceptions when checking dependencies

- documentation/source/_static/css/custom.css
- documentation/source/conf.py
- documentation/source/requirements.txt
- documentation/source/user_section/help.rst
- setup.py
The variables updated in `custom.css` were being ignored and the default Furo variables were still being used (most noticeably, causing the sidebar to be illegible). This PR used the `light_css_variables` and `dark_css_variables` parameters in `conf.py` to amend it. It looks good on the PR build, but it looked fine in PR #3355 as well and then built differently in the public page, so we may have to merge to verify that it is fixed 😅 
https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3487
> Fix bug in Read the Docs

- documentation/source/_static/css/custom.css
On the left sidebar of the documentation for SCT, the hover background colour is white, which does not work because the text is also white. The background colour on hover should be a lighter grey, so this pull request fixes that.
Resolves https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3494
> Fix hover colour on sidebar of docs

- batch_processing.sh
- spinalcordtoolbox/scripts/sct_register_multimodal.py
- spinalcordtoolbox/scripts/sct_register_to_template.py
- testing/cli/test_cli_sct_register_multimodal.py
This PR add the ability to specify the filename of the output inverse warping field. This is relevant for the SCT Course, since we often would rename the files using `mv` (because the auto-generated filenames were long and awkward).
For this PR, I've tried to mimic the existing programming conventions in `sct_register_multimodal` (basically just matching `-owarp` without making any further improvements), just to keep the changes easier to understand/review. 
Fixes #1530.
> Add `-owarpinv` to `sct_register_multimodal`

- spinalcordtoolbox/scripts/sct_check_dependencies.py
Before this PR, the order we imported `PyQt` and `matplotlib.pyplot` caused a weird libgcc error. As a workaround, we import `pyplot` earlier to avoid the error. (More info here: https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3511#issuecomment-912167649.)
Notes:
* The exact cause of the issue is still unclear, even to the conda folks. 
* This issue doesn't affect the actual SCT installation; it was just an issue in `sct_check_dependencies`.
Fixes #3511.
> Import `pyplot` before `PyQt` to mitigate a finicky `libgcc_s.so.1` error

- .github/workflows/create-release.yml
In #3383, I added a GitHub Actions workflow to automate the manual steps for creating a release. I had tested it on a separate repo, and it [seemed to work OK](https://github.com/joshuacwnewton/test-github-actions/releases/tag/5.3.1).
However, I realize I made a mistake: In the GitHub action, I installed SCT from the release branch. This will generate the wrong `requirements-freeze.txt`; what I actually needed to do was:
1. Install SCT from the master branch
2. After the correct, up-to-date dependencies have been installed in the conda environment, _then_ checkout the release branch and do [the remaining steps](https://github.com/spinalcordtoolbox/spinalcordtoolbox/wiki/Misc%3A-Creating-a-new-release#legacy-steps-preserved-while-testing-new-automation-workflow----delete-after-confirmation- …
> Make sure correct version of SCT is installed in the release automation workflow

- documentation/source/user_section/installation/fsleyes.rst
Noticed on https://spinalcordtoolbox.com/user_section/installation/fsleyes.html
> `fsleyes.rst`: Fix typo (Installating -> Installing)

- spinalcordtoolbox/scripts/sct_analyze_lesion.py
- spinalcordtoolbox/scripts/sct_compute_snr.py
- spinalcordtoolbox/scripts/sct_create_mask.py
- spinalcordtoolbox/scripts/sct_deepseg_lesion.py
- spinalcordtoolbox/scripts/sct_deepseg_sc.py
- spinalcordtoolbox/scripts/sct_dmri_compute_dti.py
- spinalcordtoolbox/scripts/sct_dmri_moco.py
- spinalcordtoolbox/scripts/sct_download_data.py
- spinalcordtoolbox/scripts/sct_extract_metric.py
- spinalcordtoolbox/scripts/sct_fmri_moco.py
- spinalcordtoolbox/scripts/sct_get_centerline.py
- spinalcordtoolbox/scripts/sct_image.py
- spinalcordtoolbox/scripts/sct_label_utils.py
- spinalcordtoolbox/scripts/sct_label_vertebrae.py
- spinalcordtoolbox/scripts/sct_maths.py
- spinalcordtoolbox/scripts/sct_process_segmentation.py
- spinalcordtoolbox/scripts/sct_propseg.py
- spinalcordtoolbox/scripts/sct_register_multimodal.py
- spinalcordtoolbox/scripts/sct_register_to_template.py
- spinalcordtoolbox/scripts/sct_resample.py
- spinalcordtoolbox/scripts/sct_run_batch.py
- spinalcordtoolbox/scripts/sct_straighten_spinalcord.py
- spinalcordtoolbox/utils/shell.py
This is a tiny PR with just cosmetic changes: With #3361, [raw-text formatting](https://docs.python.org/3/library/argparse.html#argparse.RawTextHelpFormatter) is now applied by default to all descriptions (without the need for `R|`), so I removed those bits of text.
Also, while I was here, I cleaned up the docstrings for SmartFormatter in f3da9b9ca2c95b77e9883428158b37f0d1101814, since one of them referenced `R|`.
Fixes #3546.
> Remove leftover unnecessary `R|` formatting

- install_sct
`pip==21.2.*`'s dependency resolver algorithm caused much longer install times across the Python ecosystem. This change makes sure we're not on that version before we install SCT's requirements.
Fixes #3593.
> `install_sct`: Skip `pip==21.2` to avoid suboptimal dependency resolver

- install_sct
Many people post install errors on the forum without all the details
attached. This logs *the entire install log* to a file for them,
which should make getting errors reliably easier.
This kind of a silly solution but I think it will help.
> Generate issue log automatically, then direct users to share the log when posting on the forum

- spinalcordtoolbox/utils/shell.py
In #3361, some custom methods were removed because they had broken. The inline comments suggested they were the same as the built-in methods: 
https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/be7057cbe57270e20b2e0185a00a63e83b13be38/spinalcordtoolbox/utils/shell.py#L215-L216
As a result, they were replaced by subclassing `RawTextHelpFormatter`. 
However, these methods were actually _not_ identical. So, this PR restores all of the custom code (7178650), then adds documentation to the methods so that the purpose of each part is clearer (761700b). 
<details>
<summary> Comparison with v5.4 (identical) </summary>
</details>
Fixes #3562.
> Restore the argparse linewrapping behavior we had prior to Python 3.7

- spinalcordtoolbox/process_seg.py
`skimage 0.19.0` introduced a backwards incompatible change to the function `transform.pyramid_expand`. This change restores the previous behavior. More details in the linked issue.
Fixes #3615.
> Set `channel_axis=None` for `pyramid_expand` to fix bug in `skimage==0.19.0`

- documentation/LICENSE
- documentation/source/_templates/page.html
- documentation/source/_templates/partials/edit-this-page.html
- documentation/source/_templates/partials/icons.html
- documentation/source/conf.py
- documentation/source/requirements.txt
- setup.py
> Restore "Edit on GitHub" button

- documentation/source/_static/css/custom.css
Setting CSS variables both in our custom.css and via furo's theme options
led to a twisty CSS bug where the <body> would take the colour from furo's
CSS and the <html> would take it from ours, so that in dark mode,
scrolling down revealed illegible light-on-white text.
See https://github.com/pradyunsg/furo/pull/332#issuecomment-991695885
In dark mode this happens:
This happened before, but it's been made a lot more obvious by #3624, which updated `furo` and brought with it a new theme switcher button.
* Fixes https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3487#issuecomment-889390712
* An attempt to fix this was in https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/3489 but it evidently didn't go far enough?
* The diagnosis: …
> Use furo-theme sanctioned dark mode colour controls.

- install_sct
* When we run `conda create`, we install `python` and its dependencies (`pip`, `setuptools`, etc.) using conda packages.
* Then, when we run `pip install -r requirements.txt`, pip reinstalls 3 of those conda packages as pip packages: [`wheel`, `setuptools`, and `certifi`](https://www.diffchecker.com/mK56LAZg).
* I _think_ it's OK to reinstall `wheel` and `setuptools` using pip, but trying to reinstall `certifi` causes an error for older versions of `certifi` (#3609).
So, this PR prevents `pip` from reinstalling the version of `certifi` that gets installed during `conda create`. 
(NB: I spend a few hours trying to wrap my head around this problem, trying to answer "Does it matter which version of `certifi` gets installed? Is `certifi` even necessary? There are some interesting rabbit …
> Use `--ignore-installed` to preserve the version of `certifi` that gets installed during `conda create`

- spinalcordtoolbox/process_seg.py
THis PR addresses #3651. A fix was added for the version 0.19.0 of scikit-image (https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3615), adding the argument `channel_axis=None`. Since the package scikit image has been upgrated to 0.19.1, it is no longer necessary, we can remove it.
Resolves #3651
> Remove `channel=None` bugfix that was superseded by upstream `skimage=0.19.1` patch

- spinalcordtoolbox/scripts/sct_propseg.py
- testing/cli/test_cli_sct_propseg.py
In issue #3608, we came across a case where running `sct_propseg` with the options `-CSF -cross` will cause the script to stall for specific kinds of data. This PR doesn't fix the root cause of that issue, but it _does_ fix 2 bugs that were discovered in the process:
1. Make sure boolean args are checked correctly, so that we stop outputting extra files that the user didn't ask for
2.  Make sure `check_and_correct_segmentation` outputs the corrected segmentation to the right folder, to prevent a failure when `-ofolder` is passed.
Fix 1. will help mitigate the original issue, because that bug was causing `-CSF -cross` to be run even when those options weren't specified by the user!
Partially addresses #3608.
> Fix argument parsing to ensure only the requested files are output

- spinalcordtoolbox/scripts/sct_straighten_spinalcord.py
- spinalcordtoolbox/utils/shell.py
- spinalcordtoolbox/utils/sys.py
- testing/api/test_utils.py
The previous use of `str.strip(".py")` is a bug waiting to happen,
because it strips from both sides of the string (instead of just
the end), and more importantly, treats `".py"` as a set of
characters rather than a substring to look for (see [the docs](https://docs.python.org/3/library/stdtypes.html#str.strip)):
```
$ python3
>>> "ppp.yyy".strip(".py")
''
>>> "no_dot_py".strip(".py")
'no_dot_'
>>> ".py_prefix".strip(".py")
'_prefix'
```
All uses of `.strip(".py")` are either in `utils/sys.py` itself or import this module, so it seemed like the natural place to add this utility function.
> Add utility function to strip '.py' extensions

- spinalcordtoolbox/math.py
- spinalcordtoolbox/scripts/sct_maths.py
- testing/cli/test_cli_sct_maths.py
This PR addresses #3649. In `sct_math` the flag `-symmetrize` is suppose to symmetrize the input image along the specified axis. However, the symmetry was always applied on the first dimension despite the specified dimension.
This PR applies the symmetrization on the specified input dimension.
Fixes #3649
> Appply -symmetrize on specified dimension in `sct_maths`

- install_sct
Allow the `install_sct` script to run from any location, by first changing directory to the script location, and changing back to the original directory at the end.
Possibly this could have been integrated into the existing `finish()` function, but this way seems nicely self-contained to me. The downside is that it's not logged in `install_sct_log.txt`.
The script passes ShellCheck version 0.8.0, and a test run from a different directory worked fine on my machine.
Fixes #3647
> Allow `install_sct` to run from any directory

- spinalcordtoolbox/qmri/mt.py
- testing/cli/test_cli_sct_compute_mtr.py
**Contributing documentation link is broken**
When we use `sct_compute_mtr`, we have an issue with the results when using non `float32` NIFTI images for MT0 and MT1. The values obtained are inconsistent. We need to convert the type of input to float32 before compute the MTR result.
Fixes #3636 
Some things need to be cleaned-up but i need some informations/help to know the way we work here:
- The testing dataset are dynamically download from [sct_testing_data repository](https://github.com/spinalcordtoolbox/sct_testing_data) but i need to test the script with a int_16 file in place of a float_32. What is the process to add a new file of testing (ie: PR ? Request to the team ?) or do i just convert the file first directly in the test ?
- I don't have the PR labels information since the …
> Convert input file to float32 before compute MTR

- .github/workflows/create-release.yml
- .gitignore
- CHANGES.md
- documentation/source/user_section/installation/linux.rst
- documentation/source/user_section/installation/mac.rst
- install_sct
- requirements.txt
- setup.py
- spinalcordtoolbox/scripts/sct_check_dependencies.py
Pull request #3646 reworked how we install dependencies (as a stepping stone towards a pip-installable SCT). However, that pull request wasn't tested against the stable release installation path (see #3669), and thus the changes introduced unforeseen issues with `sct_check_dependencies`. 
I've spent the morning trying to troubleshoot these issues, but I can't find a clean, easy-to-review solution. Given the urgency of the SCT v5.5 release, I think the best path forward is to revert PR #3646, then devote more time to the original problem once we're under less time pressure.
Once this PR is merged, I'll patch the `release` branch, and then we can safely release v5.5.
Fixes #3667.
> Revert "requirements.txt -> setup.py" PR to restore old dependency-checking behavior

- .github/workflows/tests.yml
This is a fix for the CentOS 8 EOL, which went into effect today. Quay.io is an official RHEL channel.
Also, context for this fix can be found in
https://blog.centos.org/2020/12/future-is-centos-stream/:
> When CentOS Linux 8 (the rebuild of RHEL8) ends, your best
> option will be to migrate to CentOS Stream 8, which is a
> small delta from CentOS Linux 8, and has regular updates like
> traditional CentOS Linux releases.
Fixes #3675.
> Replace CentOS 8 with CentOS Stream 8 to address December 2021 EOL

- testing/api/test_qc_parallel.py
This PR fixes the _actual_ root cause of the issue: `multiprocessing.Pool` interacts poorly with `pytest-cov` unless `p.close()` and `p.join()` are called inside a try-finally block.
Note that the `with` context manager isn't good enough for the reasons outlined in https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3661#issuecomment-1029070105.
Fixes #3661.
> Rewrite QC test to use `Pool.close()` to avoid stalling with pytest-cov

- testing/batch_processing/test_batch_processing.py
This PR adds a temporary workaround for the `batch_processing.sh` failures that occur with a specific GitHub Actions runner.
I considered making the check a little more granular (comparing against the specific kinds of values, rather than just all values), but given the level of precision that we're able to consistently produce this result for, the probability of a false positive (e.g. accidentally skipping erroneous value that occurred via a PR change) seems nil to me.
I also tested this change in [`jn/3597-debug`,](https://github.com/spinalcordtoolbox/spinalcordtoolbox/commits/jn/3597-debug) a branch that I've been using to catch the specific Actions CPU and run tests:
* [Summary of GitHub Actions run](https://github.com/spinalcordtoolbox/spinalcordtoolbox/actions/runs/1826289477) (with …
> Add temporary skip for hardware-specific GitHub Actions runner issue

- spinalcordtoolbox/scripts/sct_propseg.py
A simple bugfix for a simple issue. :)
I considered writing a test for this, but it seemed a little silly to write a test for a clear one-off bug for a single argument. Instead, I'd rather devote a separate PR to covering all of this script's arguments + expected behaviors. However, a PR like that might be for naught, because we're planning on phasing out `sct_propseg` anyway (in favor of promoting `sct_deepseg_sc`, as well as the upcoming contrast-agnostic `sct_deepseg` model that is currently in development).
Fixes #3686.
> Fix parsing of `-d` argument in script

- .github/PULL_REQUEST_TEMPLATE.md
- spinalcordtoolbox/centerline/nurbs.py
- spinalcordtoolbox/registration/landmarks.py
Very tiny PR for a very tiny issue.
Fixes #3685.
> Fix broken links to neuro.polymtl.ca

- spinalcordtoolbox/scripts/sct_label_vertebrae.py
- spinalcordtoolbox/vertebrae/core.py
This PR began with the `gaussian_std` parameter in `-param`. This parameter has been silently ignored since it was introduced, and `sct_label_vertebrae` uses `gaussian_std=999` instead.
Getting rid of the Gaussian altogether should have minimal impact, since using 999 is very close to 1.0:
```py3
>>> from scipy.signal import gaussian
>>> gaussian(20*2, std=20*999)[:20]
array([0.99999952, 0.99999957, 0.99999962, 0.99999966, 0.9999997 ,
0.99999974, 0.99999977, 0.9999998 , 0.99999983, 0.99999986,
0.99999989, 0.99999991, 0.99999993, 0.99999995, 0.99999996,
0.99999997, 0.99999998, 0.99999999, 1.        , 1.        ])
```
However, in the course of this PR, several additional bugs were discovered within `-param`:
* Any comma-separated parameters passed to `-param` beyond the first would be …
> Refactor `-param` parsing to address several bugs

- spinalcordtoolbox/scripts/sct_run_batch.py
Otherwise, we'd get a "referenced before assignment" error on
Windows.
This PR fills in the gaps for platforms outside of `darwin` and `linux`. 
I think this check probably could use a more thorough rewrite, though? I'm skeptical of its purpose.
Fixes #3709.
> Account for non-UNIX platforms in `sys.platform` checks

- dev/isct_propseg/CMakeLists.txt
- spinalcordtoolbox/scripts/sct_propseg.py
- testing/cli/test_cli_sct_propseg.py
This PR tries to apply a fix to `CMakeLists.txt` which helps with building `isct_propseg` on Windows. While the fix does address _some_ errors, it doesn't address all of them.
So, ultimately this PR then tries to skip `sct_propseg` entirely, redirecting users to `sct_deepseg_sc` instead.
Partially addresses #3694.
> Attempt to fixup isct_propseg build (but ultimately skip sct_propseg on Windows)

- documentation/README.rst
The `sphinx/` subdirectory of `documentation/` no longer exists.
> Update documentation build instructions

- install_sct.bat
This PR allows the Windows install script to proceed more gracefully if there is an existing spinalcordtoolbox directory.
Addresses https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3740#issuecomment-1081965386.
> `install_sct.bat`: Allow overwriting of existing spinalcordtoolbox installations

- requirements.txt
- spinalcordtoolbox/scripts/sct_check_dependencies.py
This plugs a dependency hole for Windows systems without the "Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 and 2019" or Visual Studio >= 2015 installed.
This fix has been given a soft endorsement by scikit-image (https://github.com/scikit-image/scikit-image/issues/4780#issuecomment-902286097 + preceding discussion), and it's possible that this fix gets included upstream, so we may be able to remove it on a further date. 
Addresses https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3740#issuecomment-1081965473.
> Add `msvc-runtime` to our requirements to avoid DLL load error on Windows

- spinalcordtoolbox/scripts/sct_check_dependencies.py
If `sct_propseg` is called on Windows, users will be directed to `sct_deepseg_sc` instead, because the underlying `isct_propseg` binary isn't yet supported on Windows. (See also: #3694, #3717)
So, there is no need to test running `isct_propseg` via `sct_check_dependencies`.
Addresses https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3740#issuecomment-1088685708.
> Skip checking `isct_propseg` on Windows

- spinalcordtoolbox/gui/base.py
- spinalcordtoolbox/gui/centerline.py
- spinalcordtoolbox/reports/qc.py
- spinalcordtoolbox/scripts/sct_check_dependencies.py
- spinalcordtoolbox/scripts/sct_run_batch.py
- spinalcordtoolbox/utils/shell.py
- spinalcordtoolbox/utils/sys.py
- testing/cli/test_cli_sct_dmri_display_bvecs.py
This PR looks for all instances where we check `sys.platform` to make sure that:
* Windows platforms are included whenever necessary
* `sys.platform ==` is discarded in favor of `sys.platform.startswith()`
In the process of doing this, I noticed that there were a few spots where the same check (determining whether to use `xdg-open` or `open` for QC reports, etc.) was being repeated across multiple locations. But, we already have an existing function for this called `display_open()` that we can re-use in each place.
Fixes #3742.
> Refactor `sys.platform` checks to include Windows and use `.startswith()` idiom

- spinalcordtoolbox/deepseg/models.py
Fixes https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3776
> Cosmetic fixes on `-list-tasks`

- spinalcordtoolbox/scripts/sct_label_vertebrae.py
- spinalcordtoolbox/vertebrae/core.py
- testing/cli/test_cli_sct_label_vertebrae.py
When calling `vertebral_detection` with an invalid initial disc (that is, a disc label that's not in the PAM50 template), the result is a very unfriendly error message:
```python
File "/icometrix-install/spinalcordtoolbox-5.3.0/spinalcordtoolbox/vertebrae/core.py", line 206, in vertebral_detection
approx_distance_to_next_disc = list_distance[list_disc_value_template.index(current_disc - 1)]
ValueError: -2 is not in list
During handling of the above exception, another exception occurred:
File "/icometrix-install/spinalcordtoolbox-5.3.0/spinalcordtoolbox/scripts/sct_label_vertebrae.py", line 482, in <module>
File "/icometrix-install/spinalcordtoolbox-5.3.0/spinalcordtoolbox/scripts/sct_label_vertebrae.py …
```
> Output a better error message when the initial disc is invalid

- spinalcordtoolbox/cropping.py
- spinalcordtoolbox/scripts/sct_crop_image.py
- testing/batch_processing/test_batch_processing.py
- testing/cli/test_cli_sct_crop_image.py
When cropping a nifti file which has a slightly bad qform (which could happen because of rounding errors), nibabel throws an error. This PR implements proposed solution number 3 from issue #3703, which is to set the image's `quaternion_threshold` to `-1e-6` before getting its qform. (This value comes from a suggestion in https://github.com/nipy/nibabel/issues/626 and seems reasonable, see [this comment](https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3703#issuecomment-1049221586).)
The PR also adds a test case for an image with a slightly bad qform, which fails before the main code change, and passes afterwards. See https://github.com/spinalcordtoolbox/sct_testing_data/pull/10 for the actual test file. Either this PR can wait until we do a new release of `sct_testing_data`, …
> Set a more permissive threshold for reading the qform

- install_sct.bat
This PR adds a tiny tiny little fix from https://stackoverflow.com/a/1262726. 
Without this, the check will spit out a noisy "INFO: Could not find files for the given pattern(s)." when it does the thing it's supposed to (ensure that `deactivate` is present before calling it).
N/A
> Suppress output of `where deactivate` check

- install_sct.bat
Allow `install_sct.bat` to be usable from a simple double click in place of a command line execution. It will make it a lot more easy for windows user that don't have a lot of technical knowledge.
#3762
> Allow `install_sct.bat` file execution from double click

- requirements.txt
- spinalcordtoolbox/deepseg/models.py
- spinalcordtoolbox/scripts/sct_check_dependencies.py
- spinalcordtoolbox/utils/sys.py
The `colored` module uses the extended 256 color set, and so it doesn't support Windows terminals, which causes grayscale text when running `sct_deepseg -list-tasks`. So, this PR:
- Rewrites the `bcolors` code snippets so that it's clearer that we're limited to ANSI 16-color escape codes.
- Replaces the use of `colored.stylize` with a new equivalent function that uses these 16-color escape codes.
Now, `sct_deepseg -list-tasks` properly shows coloured output:
And our previous color usage is unaffected:
Further refactoring is definitely possibly (e.g. by using `stylize` in `sct_check_dependencies`), but I wanted to keep this PR as simple to review as possible when first starting out, by minimizing the changes in the diffs.
Fixes #3780
> Rewrite ANSI color code snippets to support terminals limited to 16-colors

- spinalcordtoolbox/image.py
This PR fixes a bug with how we use filepaths to load images:
* Before, the supplied `path` was used to load the image, then assigned to `self.absolutepath`
* But, this is misleading, because we never actually call `os.path.abspath()`, so it's not actually an absolute path.
* Because of this, `..` or any other path shorthands don't get expanded.
* Additionally, it meant that the `if path != self.absolutepath` shorthand was doing absolutely nothing.
So, this PR invokes `os.path.abspath` to restore the expected behavior.
N/A.
This PR is a `git cherry-pick`'ed commit from #3770, so this is just for organizational purposes, so that there will be 2 distinct commits on master. It has already been approved in this PR.
> `image.py`: Use absolutepath when loading images

- spinalcordtoolbox/scripts/sct_download_data.py
Currently, SCT depends on [8 total external C++ tools](https://github.com/spinalcordtoolbox/spinalcordtoolbox/wiki/Misc%3A-How-to-compile-binaries-(ANTs,-isct)#c-binary-dependencies) that must be pre-built and packaged:
* 4/8: `ANTs` binaries we borrow from the external ANTs package.
* 2/8: `ctrDetect` binaries we borrow from an external contributor to SCT.
* 2/8: `isct_` binaries (from the `spinalcordtoolbox/dev` folder).
To make re-building the ANTs binaries easier/more reproducible, PR https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/2821 automated the build process via the [`kousu/ANTs`](https://github.com/kousu/ANTs) repo. 
However, there was still a bit of work left to be done, as:
1. The ANTs-building workflow is stored in a personal repo, rather than a …
> Use binaries that are packaged by the `spinalcordtoolbox-binaries` repo

- install_sct
See https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3804
This was inadvertently broken in https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/3591.
Fixes https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3804
> Repair commenting out pre-4.0 sct settings.

- requirements.txt
At some point recently torch put up a full pip repo (`pip --extra-index-url https://download.pytorch.org/whl/cpu`) instead of just a list of files (`pip --find-links https://download.pytorch.org/whl/torch_stable.html`), meaning the officially stated version of torch (1.8.0, 1.9.0, 1.10, ...) is now orthogonal from the build variant (`cpu`, `cu101`, `cu113`, ...), so we can unpin the version and leave the choice of version encapsulated in ivadomed, especially because `torch` is not something we use directly at all, it's just something `ivadomed` calls.
The version has more to do with what APIs we can call, and the build variant has more to do with what platform the end user is actually installing on, so they are a lot better separated.
Sidesteps …
> Use CPU `--extra-index-url` to remove strict dependency pinning for `torch`

- spinalcordtoolbox/aggregate_slicewise.py
- spinalcordtoolbox/scripts/sct_extract_metric.py
- spinalcordtoolbox/scripts/sct_process_segmentation.py
- testing/api/test_aggregate_slicewise.py
Modified the behaviour of `aggregate_slicewise.py` so that if a user specifies both flags `-z` and `-vert`, the slices considered for the aggregation will be the intersection between the values specified by both flags. Previously, `-vert` would take precedent.
This change introduce a cross-compatibility break in behaviour, however this is not _too_ problematic because the previous behaviour was unclear anyway.
Fixes #3822
> Overlap conditions when slice number and vertebral levels are both specified

- spinalcordtoolbox/aggregate_slicewise.py
- testing/api/test_aggregate_slicewise.py
- testing/api/test_centerline.py
- testing/api/test_deepseg_sc.py
- testing/api/test_math.py
- testing/api/test_process_seg.py
- testing/api/test_resampling.py
- testing/api/test_straightening.py
- testing/cli/test_sct_deepseg.py
Two small followup changes after #3823:
* The `# noinspection 801,PyShadowingNames` comments in various test files are no longer necessary (see #3824).
* The docstring for `aggregate_per_slice_or_level` got out of sync with the code.
Fixes #3824.
> Followups for #3823

- spinalcordtoolbox/image.py
- spinalcordtoolbox/utils/fs.py
This PR applies the feedback from https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/3847#discussion_r925819500:
Clarify the misleading docstring (https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/3847#discussion_r925996449)
Apply the fixes from https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/3833 to `mv`.
Replace direct call to `shutil.move` with `mv`.
Needed for #3847.
> Unify calls to `shutil.move` by using only `utils.fs.mv`

- .github/workflows/create-release.yml
This PR updates the create release workflow so that it will modify `install_sct.bat` to make it release-ready, then attach it as an asset to the release.
The changes in this PR were tested on my fork to create https://github.com/joshuacwnewton/spinalcordtoolbox/releases/tag/5.7.5, which indeed has the batch script attached as a release asset, with the correct line changed:
```
rem Set git ref. If no git ref is specified when calling `install_sct.bat`, use a default instead.
if [%1]==[] (
set git_ref=5.7.5
) else (
set git_ref=%1
)
```
Fixes #3763.
> Add `install_sct.bat` as a release asset during `create-release.yml` workflow

- .github/workflows/create-release.yml
- .github/workflows/test-batch-processing.yml
- .github/workflows/tests.yml
This goes a bit above-and-beyond #3852, but I figured I would update everything together.
As mentioned in f8547fb245d1ed0a05922e8d83b8cc4f4653064a:
> NB: We may also want to test `ubuntu-22.04` and `windows-2022` against both `tests` and `batch-processing`, too, just to be prepared for future deprecations.
I wanted to start by testing `macos-12` in `tests.yml`, but we should maybe add additional commits afterwards for these cases, too.
Fixes #3852.
> Update GitHub Actions runners to match current (non-beta) up-to-date versions

- spinalcordtoolbox/resampling.py
- spinalcordtoolbox/scripts/sct_compute_snr.py
- spinalcordtoolbox/scripts/sct_dmri_moco.py
- spinalcordtoolbox/scripts/sct_fmri_moco.py
- spinalcordtoolbox/scripts/sct_maths.py
- spinalcordtoolbox/scripts/sct_process_segmentation.py
This PR removes the `raise parser.error(...)` anti-pattern from the codebase.
The function `parser.error()` from `argparse` never returns with a value; it either exits the program, or raises an exception. There's no need to raise the non-existent return value.
All other `raise` statements look like they raise actual exceptions (maybe not always the most appropriate one, but at least an exception). While checking this, I couldn't ignore two cases of `raise Exception(TypeError)`, so I fixed those as well.
> Call `parser.error` properly

- spinalcordtoolbox/scripts/sct_extract_metric.py
`sct_extract_metric -list-labels` is a way to display the `info_label.txt` file contained within the folder pointed to by `-f`:
https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/e7b423e3b103faae6759b388c8e2432fc94a8c57/spinalcordtoolbox/scripts/sct_extract_metric.py#L51
However, if the user specifies a new `-f`, then the order of parsing starts to matter:
* If `sct_extract_metric -f <directory> -list-labels` is used, then `-f` will be updated first, and `-list-labels` will display correctly.
* If `sct_extract_metric -list-labels -f <directory>` is used instead, then `-list-labels` will be parsed before `-f` can be updated, and it will either crash, or display the wrong `info_label.txt` file.
To make sure that `-list-labels` always works as expected, we need to parse it last in …
> Ensure that `-list-labels` is the last argument that is parsed

- spinalcordtoolbox/scripts/sct_deepseg_gm.py
- spinalcordtoolbox/scripts/sct_deepseg_sc.py
- spinalcordtoolbox/scripts/sct_detect_pmj.py
- spinalcordtoolbox/scripts/sct_dmri_moco.py
- spinalcordtoolbox/scripts/sct_fmri_moco.py
- spinalcordtoolbox/scripts/sct_get_centerline.py
- spinalcordtoolbox/scripts/sct_process_segmentation.py
- spinalcordtoolbox/scripts/sct_propseg.py
- spinalcordtoolbox/scripts/sct_straighten_spinalcord.py
- spinalcordtoolbox/scripts/sct_warp_template.py
* Commit 80d0150013a474a26810709454543840c48376ae replaces `arguments` with `argv` when passed to `generate_qc`, ensuring that we display the actual command that the user ran:
Before:
After:
* Commit da83255966477076962c59c522692a20ecc3ec04 is probably unnecessary, and doesn't reeeeeeeeeally change much functionally, but it does standardize the calls to `generate_qc` across every CLI script, so... I figured I would add this while I'm here.
Fixes #3851.
> Pass `argv` to `generate_qc` functions (instead of `arguments` or `sys.argv[1:]`)

- spinalcordtoolbox/scripts/sct_run_batch.py
- testing/cli/test_sct_run_batch.py
This PR provides an option that allows users to process `sub-` directories on their own, even when `ses-` subdirectories are present.
Without `-ignore-ses`:
With `-ignore-ses`:
I've used `action='store_true'` here because it preserves the existing behavior, so there should be no changes unless users choose to opt-in.
Fixes #3809.
> Add `-ignore-ses` flag to process `sub-` directories even when `ses-` subdirectories are present

- spinalcordtoolbox/scripts/sct_run_batch.py
This issue is a follow-on for https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/3859. In that PR, a bug was merged to `master`, because the ordering of the arguments for the `_filter_directories` function call was incorrect:
https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/51df5fc0569c0c04571e44601b7ddf95c981631b/spinalcordtoolbox/scripts/sct_run_batch.py#L213
https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/51df5fc0569c0c04571e44601b7ddf95c981631b/spinalcordtoolbox/scripts/sct_run_batch.py#L507-L509
Thank you to @valosekj for catching this. :heart: 
Fixes #3598.
> Fix `include_list`/`exclude` argument ordering in call to `_filter_directories`

- install_sct
`install_sct` uses a regex-based `perl -pi -e` find and replace command to comment out any instances of the `sct_env` environment variable being set (which is no longer used).
This PR amends the `perl -pi -e` statement so that it uses the pattern that was tested by @kousu in https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/3805#discussion_r888226125.
(The reason for this bug is because, in https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/3805#discussion_r888226125, the PR "suggestion" was subtly different than what was actually tested.)
Fixes #3871.
> Properly escape `\` in the regex for removing `sct_env` from old RC files

- spinalcordtoolbox/utils/shell.py
(This is a tiny developer QOL change.)
Currently, SCT uses a custom Enum class called `Metavar` to print `<type>` strings in argparse help descriptions:
PyCharm doesn't like the fact that we're using a bare `Enum`, though:
We can fix this by adding `str` to the list of types that `Metavar` inherits, though:
N/A.
> `shell.py`: Let `Metavar` inherit from `str` to silence PyCharm type warning

- spinalcordtoolbox/image.py
The strings are already concatenated by `+`, and `os.path.join` with a single string argument just returns it unchanged.
> Simplify `add_suffix`

- spinalcordtoolbox/image.py
- spinalcordtoolbox/moco.py
On Unix systems, when motion correction is run on a 4D image with many 3D volumes (e.g. `[x, y, z, 300]`), and the number of volumes exceeds the open file descriptor limit (e.g. `ulimit -Sn ==> 256`), then SCT will throw an `[Errno 24] Too many open files` error.
The reason for this is because of this LOC:
https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/7ce5ea59e213510ff0566eef99d3cefe811f0051/spinalcordtoolbox/moco.py#L640
`Image`, by default, will load the data arrays of `.nii` images as `np.memmap` objects, which keeps an open file descriptor. So, for a 300-volume dMRI image, at least 300 file descriptors will be kept open at once.
To fix this, we can tackle the problem a number of ways:
1. Rely on the workaround of `ulimit -Sn` to increase the limit on open file …
> Address `[Errno 24] Too many open files` during motion correction

- spinalcordtoolbox/scripts/sct_merge_images.py
- spinalcordtoolbox/scripts/sct_smooth_spinalcord.py
For `argparse`-based arguments, if the argument has e.g. `choices=(0, 1)`, then `type=int` must be set. This is because unparsed arguments are passed as strings (e.g. `'0'`, `'1'`), which must be converted to integers to be considered a valid choice.
I did a project-wide regex search for `choices=.*0, 1.*` (this search also included results for `choices=(0, 1, 2)`). Then, I checked each search result to see if `type=int` was specified. I found two instances of this not being the case (`sct_smooth_spinalcord`, `sct_merge_images`).
This PR fixes both arguments so that they now work as intended. 
Fixes #3885.
Needed for the PR that will address https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3883, because `isct_convert_binary_to_trilinear` has a call to `sct_smooth_spinalcord` …
> Enforce `type=int` for arguments that use `choices=(0, 1)`

- spinalcordtoolbox/registration/core.py
- testing/cli/test_cli_sct_register_multimodal.py
`sct_register_multimodal` performs multi-step registration. To be able to specify multiple parameters corresponding to each step, we use the `-param` argument, which takes a string formatted as `step=0,type=<>,algo=<>:step=1,type=<>,algo=<>` and can continue for as many steps the user wishes.
An ugly error occurs when the user erroneously specifies both `type='label'` and `algo=rigid` in a step:
```bash
sct_register_multimodal -param step=0,type=label,algo=rigid -i t2.nii.gz -d t2.nii.gz -ilabel labels.nii.gz -dlabel labels.nii.gz
```
* `type='label'` will output the transformation in the form of a `.txt` file.
* But, specifying `algo='rigid'` will cause the `.txt` file to incorrectly be renamed to a `.mat` file.
* The `.mat` file is incompatible with further transformation steps, hence …
> Improve handling of case where `algo` is specified alongside `type='label'`

- documentation/source/overview/studies.rst
SCT tracks citations in two ways: 
1. The public-facing [`studies.rst`](https://spinalcordtoolbox.com/overview/studies.html) page in our Sphinx documentation.
2. An internal, semi-private Google Sheets spreadsheet that tracks some additional information not in the Sphinx page.
The internal spreadsheet also contains some graphs that aggregate and summarize statistics for SCT's citations (such as pathologies treated, tools used, and type of subject). These graphs can be published and shared via Google Sheets' "publish" feature. 
This PR adds some HTML snippets to display the published graphs on the Sphinx page, alongside the list of citations. You can view the rendered graphs on this page: https://spinalcordtoolbox--3896.org.readthedocs.build/overview/studies.html
Fixes #3857.
> Add Google Sheets summary graphs to `studies.rst`

- spinalcordtoolbox/scripts/isct_convert_binary_to_trilinear.py
- spinalcordtoolbox/scripts/sct_analyze_lesion.py
- spinalcordtoolbox/scripts/sct_analyze_texture.py
- spinalcordtoolbox/scripts/sct_denoising_onlm.py
Most SCT scripts use a function called `display_viewer_syntax` at the end of processing. This function searches for the presence of image viewing software like `fsleyes` or `itksnap`, then outputs commands that let the user open output files in those viewers.
However, some scripts still hardcode a command for `fsleyes`/`fslview`. So, this PR replaces those commands with `display_viewer_syntax`.
> ((NB: The `isct_convert_binary_to_trilinear` script is looking a bit neglected. I've made sure it works, because it's listed in our `setup.py`, and thus is available to our users. That said, the script doesn't use argparse, and its main function isn't properly exposed, so we don't currently test it. 
> 
> We might want to reflect on whether or not these `isct_` scripts are worth maintaining. If …
> Enforce use of `display_viewer_syntax` in four scripts using hardcoded `fsleyes` commands

- documentation/source/overview/studies.rst
Currently, we display a pie chart of "Tools used" from the [studies_citing_SCT](https://docs.google.com/spreadsheets/d/1Utmf-btG7uXmu7RCBBx7fIKobm6yvXstX2Psc-UR2HA/edit?usp=sharing) spreadsheet. However, this pie chart has two main problems:
1. It contains a mix of both descriptors (e.g. Segmentation, Registration) and literal tool names (e.g. sct_deepseg, sct_register_to_template)
2. It contains comma-delimited entries (e.g. "labeling, moco") that are treated as their own entry, rather than parsed as individual parts.
To fix these problems, I created a new column in the spreadsheet, copied the existing data, and applied the following changes:
1. Replaced tool names (e.g. sct_deepseg) with their broader purpose (e.g. Segmentation)
2. In a separate postprocessing sheet, I concatenated the …
> Switch to higher-quality "Tools used" graph on the studies page

- spinalcordtoolbox/scripts/sct_get_centerline.py
- testing/cli/test_cli_sct_get_centerline.py
The SCT CLI script `sct_get_centerline` outputs 2 files: An `.nii.gz` file and a `.csv` file. 
The filename for the `.csv` file is derived from the filename chosen for the `.nii.gz` file:
https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/d17e52f90a971cb778d93d88306b102254e9ba2f/spinalcordtoolbox/scripts/sct_get_centerline.py#L181
However, simply adding `.csv` to the filename results in outputs like `t2s_centerline.nii.gz.csv`, rather than the expected `t2s_centerline.csv`. 
So, this PR properly excludes the original file extension from the `.csv` filename.
Fixes #3913.
> Exclude original file extension (e.g. `.nii.gz`) from the output `.csv` filename

- .github/workflows/tests.yml
In our test suite, we have two kinds of jobs:
1. OSs natively supported by GitHub Actions
2. OSs that must be run via docker containers.
For this 2nd kind, we use `ubuntu-18.04` as the base runner, then run `docker` on top of that using the `container:` keyword. 
However:
* The CentOS Stream 8 CI job is having some troubles, and I want to test whether upgrading to `ubuntu-20.04` fixes this.
* Additionally, support for 18.04 will be removed on Dec 1, 2022. And, ArchLinux is already conducting a brownout for `ubuntu-18.04`:
```
This is a scheduled Ubuntu-18.04 brownout. The Ubuntu-18.04 environment is deprecated and will be removed on December 1st, 2022. For more details, see 
```
Fixes #3918.
> Upgrade Ubuntu 18.04 -> 20.04/22.04 in test suite

- spinalcordtoolbox/scripts/sct_merge_images.py
This PR started with issue #3920, a very simple suggestion for `sct_merge_images` to change the position of a `_` character in an output filename. This was fixed in f72f1bb394ba94811c1aaba18a5e260f106ed45b.
However, while looking at the `sct_merge_images` script, I noticed that there were quite a few PEP8 issues to clean up, as well as some other small style improvements. So, I thought I'd tidy things up while I was here.
Fixes #3920.
> Tidy up PEP8 warnings and other small style issues

- install_sct
For Ubuntu 22.04 (and possibly other OSs), in `sct_check_dependencies`, the matplotlib/pyqt5 checks will throw a non-fatal error about missing `.so` files that should be in `/usr/lib/dri`. 
```
libGL error: MESA-LOADER: failed to open iris: /usr/lib/dri/iris_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast
```
However (on my machine) these files do exist! They're just in …
> Ensure bundled GLIBC is up-to-date in order to resolve `MESA-LOADER` errors

- documentation/source/user_section/command-line.rst
- setup.py
- spinalcordtoolbox/scripts/sct_check_dependencies.py
- testing/dependencies/test_ants.py
Currently, we have a user-facing CLI script called `isct_test_ants.py`. However, its contents are more akin to a test, rather than a traditional CLI script.
So, this PR migrates the test to `testing/`, and calls this test via `sct_check_dependencies` to preserve existing behavior.
Supersedes https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/3915.
Fixes #3905.
> Convert `isct_test_ants` script into a `pytest` test, then call via `sct_check_dependencies`

- documentation/source/user_section/citing_sct.rst
- documentation/source/user_section/tutorials/registration-to-template/shape-metric-computation/csa-pmj.rst
- spinalcordtoolbox/scripts/sct_process_segmentation.py
As discussed during the 2022-11-03 SCT dev meeting:
* The reference is updated in the [PMJ tutorial](https://spinalcordtoolbox.com/user_section/tutorials/registration-to-template/shape-metric-computation/csa-pmj.html).
* A reference is added in the [Citing SCT](https://spinalcordtoolbox.com/user_section/citing_sct.html#command-line-tools) documentation page.
* A reference is added in the `sct_process_segmentation` page for the `-pmj` option:
```
--
Spinal Cord Toolbox (git-mgp/pmj-citation-1fd6354fea25917eee5c82cd034f3e4e30560a00)
sct_process_segmentation -h
--
usage: sct_process_segmentation -i <file> [-h] [-o <file>] [-append <int>] [-z <str>]
[-perslice <int>] [-vert <str>] [-vertfile <str>]
[-perlevel <int>] [-angle-corr <int>]
[-centerline-algo {polyfit,bspline,linear,nurbs}] …
```
> Add references to Bédard and Cohen-Adad

- spinalcordtoolbox/cropping.py
- spinalcordtoolbox/image.py
When `hdr.get_qform()` is called on an image with a slightly negative (~0) qform quaternion values, depending on the magnitude, `nibabel` will sometimes throw an exception, even if the header is still acceptable by SCT's standards. 
```
File "/home/mguaypaq/neuropoly/spinalcordtoolbox/python/envs/venv_sct/lib/python3.7/site-packages/nibabel/nifti1.py", line 1831, in get_qform
return self._header.get_qform(coded)
File "/home/mguaypaq/neuropoly/spinalcordtoolbox/python/envs/venv_sct/lib/python3.7/site-packages/nibabel/nifti1.py", line 915, in get_qform
quat = self.get_qform_quaternion()
File "/home/mguaypaq/neuropoly/spinalcordtoolbox/python/envs/venv_sct/lib/python3.7/site-packages/nibabel/nifti1.py", line 890, in get_qform_quaternion
return fillpositive(bcd, self.quaternion_threshold) …
```
> Set a more permissive `quaternion_threshold` inside `Image` constructor

- requirements.txt
The range here is determined by the following issues:
- pyqt5=5.11.X causes an "ImportError: DLL load failed" error on native Windows (See [#3916 (comment)](https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/3916#discussion_r997435037)).
- pyqt5=5.15.X causes a "Cannot load library libqxcb.so" error on Ubuntu (See [#3925](https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3925)).
So, we limit the range to 5.12-5.14. 
Note: There is probably a more elegant solution for addressing the issues with v5.15.X. But, given that this range solves things in the short-term, I think we can revisit the 5.15.X Ubuntu problems in the future, when 5.14 becomes outdated due to the [Python 3.8 EOL](https://endoflife.date/python) (14 Oct 2024).
This PR has been manually tested on two …
> Limit `pyqt5` to >5.11 and <5.15 to avoid "Cannot load library libqxcb.so" error on Ubuntu

- spinalcordtoolbox/scripts/sct_image.py
This PR is a direct response to the user confusion from https://forum.spinalcordmri.org/t/how-to-use-sct-image-to-fix-the-orientation-of-the-header-and-data-array-setorient-data-vs-setorient/848/1.
My main goals were to:
- Clarify that `-setorient` modifies the header _and_ array in tandem.
- Clarify the usage of `-setorient-data`, since I had to explain its usage multiple times to the user.
Fixes #3741.
> `sct_image`: Clarify descriptions for `-setorient` commands

- .github/workflows/create-release.yml
Tiny change to enable draft releases by default, which would allow the release author to edit the description and etc. without feeling pressured for time.
From [ncipollo/release-action](https://github.com/ncipollo/release-action):
> Input name | Description | Required | Default Value
> -- | -- | -- | --
> draft | Optionally marks this release as a draft release. Set to true to enable. | false | ""
Fixes #3787.
> Set `draft: true` in the release creation workflow

- install_sct.bat
In #3912, we encountered some confusing behavior: `git` _appears_ to be on the PATH (`git --version` succeeds), but running `install_sct.bat` results in:
```
'git' is not recognized as an internal or external command,
operable program or batch file.
Failed with error #1.
Press any key to continue 
```
My hunch is that our users had opened multiple Command Prompt windows: one window prior to the installation of git, and a second window after the installation of git just to double-check the version. The second window displays `git --version` just fine, but the first window has outdated environment variables, and so `git` is not present on the `PATH` when `install_sct.bat` is run.
This PR attempts to weakly enforce the presence of git's directory on the `PATH`, while also providing a more …
> Add more thorough check for `git` within the `PATH` for the Windows installer

- spinalcordtoolbox/scripts/sct_run_batch.py
The `path_output` variable is defined so that it correctly handles paths which start with `~`, via `os.path.expanduser`:
https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/c57b43f715cb85dad87a33623c7caf0ed47543ca/spinalcordtoolbox/scripts/sct_run_batch.py#L407-L418
But the raw value of `arguments.path_output` is used once later on, causing problems:
https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/c57b43f715cb85dad87a33623c7caf0ed47543ca/spinalcordtoolbox/scripts/sct_run_batch.py#L482
(A quick search didn't turn up any other bad uses of `arguments.path_*` parameters.)
Fixes #3957.
> Allow `path_output` parameter to start with `~`

- .github/workflows/lint_code.yml
v6.0.0 of `flake8` breaks our CI linting workflow by removing the `--diff` option. There is no officially-endorsed alternative for linting diffs. So, for now, preserve the old behavior until we work out a better solution. (--> https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3961#issuecomment-1325669386?)
Fixes #3961.
> Pin `flake8<6.0.0` in our linting workflow

- spinalcordtoolbox/registration/algorithms.py
This PR amends the `algo='dl'` feature introduced in SCT v5.7 (https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/3807) by doing 2 things:
1. Minimize memory usage by factoring model inference into a function
* `algo='dl'` runs inference using two successive PyTorch models.
* When inference for both models is kept inside a single function, memory usage stacks.
* However, when model inference is factored out into separate functions, memory usage resets between models.
2. Add a warning to preempt a possible OOM-killed process
* By taking measurements, we can estimate how much memory will be used for images of a given size.
* Then, if the estimated RAM usage will come close to (or exceed) the amount of free memory, we can emit a warning before the OOM killer kills the process.
Fixes …
> Minimize memory usage for `algo=dl` (and add a warning for potential OOM killer issues)

- spinalcordtoolbox/compat/launcher.py
- spinalcordtoolbox/deepseg/models.py
- spinalcordtoolbox/scripts/sct_deepseg.py
- spinalcordtoolbox/scripts/sct_version.py
SCT has several levels of nested modules. For example:
* **2 levels:** `spinalcordtoolbox` -> `image.py`
* **3 levels:** `spinalcordtoolbox` -> `deepseg` -> `models.py`
<details>
<summary> Snapshot </summary>
</details>
There is a dangerous pattern that can arise as a result of nested modules:
```python
import spinalcordtoolbox as sct
result = sct.image.function(input)
import spinalcordtoolbox.deepseg as deepseg
result = deepseg.models.function(input)
```
Typically, this should cause an error, because the submodule itself (`image`, `models`) wasn't actually imported. However, if the submodule _was_ imported elsewhere, this pattern will work! [Until it doesn't,](https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3972#issuecomment-1338128371) and causes a bug...
So, it's a bit of …
> Clean up improper submodule access (via imported parent modules)

- requirements.txt
Numpy 1.24 was released recently, bringing with it the removal of the `np.bool` alias. 
One of our upstream dependencies, `voxelmorph`, depends on `neurite`, which in turn depends on `pystrum`. Pystrum's most recent PyPI version still uses `np.bool`. (See https://github.com/adalca/pystrum/issues/9.)
Until `pystrum` fixes this issue, we can pin `numpy<1.24` to keep our test suite from failing.
Fixes #3980.
> Pin `numpy<1.24` to mitigate incompatibility with `pystrum==0.2`

- spinalcordtoolbox/centerline/core.py
In #3960, I (and both reviewers) overlooked the fact that the `optic` method had its own separate return call. Because of this return call, the PR did not work as intended; the `optic` codeblock exited before the temporary file could be saved.
I believe a big part of why we missed the second `return` statement was due to the layout of the `get_centerline` function. As-is, it's not clear which parts of the function are "optic" lines of code, which parts are "non-optic" lines of code, and which parts apply to both categories.
* Before: [`get_centerline`](https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/464724d1d60637b0bbe3797c9fca0ad787e2f5ab/spinalcordtoolbox/centerline/core.py#L85-L249) (`master`)
To fix the problem, this PR refactors the `get_centerline` function to make the …
> Refactor `get_centerline` function to distinguish between OptiC and non-OptiC methods

- .github/workflows/release-body.md
When new releases are created, the body text of the release is pre-filled using a template (`release-body.md`).
However, during v5.8 release, we noticed that the template file was outdated in two ways:
1. The link to "Full release notes and Changelog" is outdated. (We no longer use the `release` branch.)
2. The `batch_processing.sh` section only contains a single OS, when we now post results for all 3 OSs.
So, this PR rewrites the template file to address these changes.
Fixes #3969.
> Improve `release-body.md` contents to address feedback from v5.8 release

- spinalcordtoolbox/deepseg_/lesion.py
When `sct_deepseg_lesion` is called with `-v 2`, an error is thrown, because `resample_file` is called on the `fname_res_ctr` filename, but that file that doesn't exist.
I tried to infer where exactly this file was supposed to have been created:
- `fname_res_ctr` is the result of `fname_orient` combined with a `_ctr` (centerline) suffix.
https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/6ee19076472c7e42da1e15b4483ff0720772df27/spinalcordtoolbox/deepseg_/lesion.py#L234
- Because the filename implies a centerline file created from `fname_orient`, this clearly seems to me to be:
https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/6ee19076472c7e42da1e15b4483ff0720772df27/spinalcordtoolbox/deepseg_/lesion.py#L157-L163
- So, I've saved `im_ctl` using the filename expected …
> Fix broken `-v 2` case by making sure `fname_res_ctr` exists prior to resampling

- .github/workflows/automate-changelog-PR.yml
This is a follow-up to [changelog#33](https://github.com/neuropoly/changelog/pull/33), to use the new command-line flag `--use-milestone-due-date`, so that the changelog text refers to the planned release date, rather than whatever date the draft is created on.
> Use milestone due date

- spinalcordtoolbox/centerline/core.py
- spinalcordtoolbox/centerline/optic.py
- spinalcordtoolbox/deepseg_/lesion.py
- spinalcordtoolbox/deepseg_/sc.py
- spinalcordtoolbox/download.py
- spinalcordtoolbox/image.py
- spinalcordtoolbox/moco.py
- spinalcordtoolbox/registration/algorithms.py
- spinalcordtoolbox/registration/core.py
- spinalcordtoolbox/scripts/sct_analyze_lesion.py
- spinalcordtoolbox/scripts/sct_analyze_texture.py
- spinalcordtoolbox/scripts/sct_apply_transfo.py
- spinalcordtoolbox/scripts/sct_compute_hausdorff_distance.py
- spinalcordtoolbox/scripts/sct_create_mask.py
- spinalcordtoolbox/scripts/sct_detect_pmj.py
- spinalcordtoolbox/scripts/sct_dice_coefficient.py
- spinalcordtoolbox/scripts/sct_dmri_separate_b0_and_dwi.py
- spinalcordtoolbox/scripts/sct_image.py
- spinalcordtoolbox/scripts/sct_label_vertebrae.py
- spinalcordtoolbox/scripts/sct_merge_images.py
- spinalcordtoolbox/scripts/sct_process_segmentation.py
- spinalcordtoolbox/scripts/sct_propseg.py
- spinalcordtoolbox/scripts/sct_register_to_template.py
- spinalcordtoolbox/scripts/sct_smooth_spinalcord.py
- spinalcordtoolbox/straightening.py
- spinalcordtoolbox/utils/fs.py
- spinalcordtoolbox/vertebrae/detect_c2c3.py
- testing/api/test_image.py
- testing/dependencies/test_ants.py
This PR originated in issue #3978, when @valosekj noticed that `sct_propseg`'s centerline folder name was erroneously called "label_vertebrae".
Separately, however, I've held the opinion that tempdir names in SCT [aren't as clear as they could be](https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3978#issuecomment-1342822951). I've been wanting to update _every_ tempdir name; issue #3978 is just the straw that broke the camel's back.
So, this PR aims to improve the quality of tempdir names in SCT. This PR contains two main parts:
1. Updating the `tmp_create` function in `fs.py`, to improve the general structure of tmpdir names.
2. Updating the `basename` parameters in each _call_ to `tmp_create`, so that they all follow a standard.
The "naming standardization" is explained in …
> Improve the readability of temporary directory names throughout SCT

- spinalcordtoolbox/utils/shell.py
This PR fixes two visual formatting bugs in our argparse help for CLI scripts:
1. 9747707: Wrapped lines for list items (` - Text` or ` * Text`) would not get sufficient indentation. ([Before vs. after](https://www.diffchecker.com/REt4z27A/))
2. 1df5d6e: The "Description" part of each CLI script would get _no_ identation formatting. ([Before vs. after](https://www.diffchecker.com/RYbYVcZr/))
Additionally, the first commit (bb7b6fd356fc55cab4ad087de264cb00bcede0ce) is just a tiny reorganization to make the steps easier to understand.
Fixes #2889.
> Fix indentation for wrapped lines in argparse help

- spinalcordtoolbox/aggregate_slicewise.py
- spinalcordtoolbox/scripts/sct_process_segmentation.py
This PR adresses #3113. In `sct_process_segmentation` when specifying `-vertfile` and `-perslice 1`, it now specifies the vertebral levels (when they are provided). 
Fixes #3113 (and also its duplication #3976)
> Display vertebral levels when provided with `-perslice 1`

- spinalcordtoolbox/metrics_to_PAM50.py
- testing/cli/test_cli_sct_process_segmentation.py
This PR proposes some additional changes for @sandrinebedard's normalization PR, #3977. I'm using the "PR format" because the changes are a bit complex, and so it's easier for me to demonstrate each change using individual commits, as opposed to explaining them in review comments on #3977.
This PR contains purely refactoring; there are no functional changes here, just code reorganization. (I used the modified test to confirm that there are no changes; at each commit, the test passes.)
The goal of this refactoring is to simplify and shorten the `interpolate_metrics` function, so that it is easier to read and understand, thus paving the way for further reviews of the functionality.
I'd recommend using the "Commits" view, since each commit contains an extended commit description to explain …
> Refactor the `interpolate_metrics` function to simplify and shorten it

- spinalcordtoolbox/scripts/sct_deepseg_lesion.py
This PR is about addressing issue #4017 - it applies no functional changes to the code at all, only changes some misleading information in the description of the function and its command line parameters.
Addresses #4017
> Update description of `-file_centerline` flag to mention `-centerline file` instead of `-centerline manual`

- .ci.sh
- .github/workflows/check-code-quality.yml
- batch_processing.sh
- install_sct
This PR expands the `lint_code.yml` workflow file so that it runs `shellcheck` in addition to `flake8`, which would help us ensure the quality of scripts like `install_sct` and `batch_processing.sh`.
Fixes #3143.
> Add shellcheck to CI (and fixup shell scripts to get the check to pass)

- spinalcordtoolbox/scripts/sct_qc.py
Rather than generating a fake, incorrect set of arguments that mimic the original command, such as:
```
sct_dmri_moco -i dmri_crop.nii.gz -d dmri_crop_moco.nii.gz
-s dmri_crop_moco_dwi_mean_seg.nii.gz
```
We instead try to faithfully display the arguments that were passed to sct_qc itself:
```
sct_dmri_moco ("sct_qc -i dmri_crop.nii.gz -d dmri_crop_moco.nii.gz
-s dmri_crop_moco_dwi_mean_seg.nii.gz
-p sct_dmri_moco -qc .")
```
Fixes #3356.
> Faithfully display `sct_qc` arguments, rather than making a fake command

- .github/workflows/create-release.yml
This PR is a follow-up to https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/3999. It makes sure that our `version.txt` on `master` is updated when a new release is created, to reflect the version currently in development.
Fixes #3998.
> Update `version.txt` on master branch during release workflow

- spinalcordtoolbox/math.py
When images are `uint8` or `uint16`, using `filters.rank.{maximum,mininum}` is *much* faster than using `dilation` or `erosion`, especially in our use-case (large 3D images).
Source: [`skimage.morphology.dilation`](https://scikit-image.org/docs/stable/api/skimage.morphology.html#dilation)
> For uint8 (and uint16 up to a certain bit-depth) data, the lower algorithm complexity makes the [skimage.filters.rank.maximum](https://scikit-image.org/docs/stable/api/skimage.filters.rank.html#skimage.filters.rank.maximum) function more efficient for larger images and footprints.
Anecdotally, on my personal laptop, testing on a `sct_example_data/t2` segmentation using `-dilate 32` caused the processing time to reduce from ~260s to ~6s. (And my CPU kind of sucks, so I imagine this would be even faster …
> Use `filters.rank` instead of `dilate`/`erode` for `uint8`/`uint16` images

- .github/workflows/create-release.yml
- .github/workflows/test-batch-processing.yml
- .github/workflows/tests.yml
- batch_processing.sh
- install_sct.bat
Currently, our Windows install script (`install_sct.bat`) requires users to install Python 3.8 system-wide. `install_sct.bat` will then use the system Python to create a virtual environment that SCT will be installed into.
Relying on the system Python is fragile and error-prone, though. It makes upgrading Python versions difficult from SCT's end, and it requires users to juggle SCT's required Python version with any existing/future Python installations they may use on their computer.
So, this PR adds the same solution that we currently use in our Linux/macOS installations: Miniconda. This lets us automatically download and install an isolated, portable version of Python that we can update from our end whenever we like, solving the above issues and removing a prerequisite from the …
> Use Miniconda instead of built-in Python for Windows installations

- contrib/fsl_integration/sct_plugin.py
- documentation/source/user_section/fsleyes.rst
This PR more gracefully handles an error thrown by FSLeyes when WxPython is out of date (buggy: `4.1.1`, fixed: `4.2.0`). 
Before:
After:
This out of date WxPython is installed when using the "FSL installation method" for FSLeyes. So, we provide FSL-specific instructions for updating WxPython within the FSL conda environment. 
(If FSLeyes is installed via a dedicated conda environment, then an up-to-date WxPython will be installed, and thus will be unaffected by this bug.)
Fixes #3988
> Catch errors from outdated `wxpython` versions bundled with FSL, then suggest a solution

- spinalcordtoolbox/scripts/sct_detect_pmj.py
This PR adds `-qc-subject` and `-qc-dataset` flags to `sct_detect_pmj`. 
This PR addresses the comment from https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/4052#pullrequestreview-1315834600:
> I did a project-wide search for -qc, and found one other script that is missing -qc-subject and -qc-dataset: [sct_detect_pmj.py](https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/33e134edf001670725d5fb36a06b8f37245d9580/spinalcordtoolbox/scripts/sct_detect_pmj.py#L90-L94). So, as a follow-up to this PR, we might want to open a separate PR to add those arguments, too.
> Add `-qc-dataset` and `-qc-subject` flags to `sct_detect_pmj.py`

- install_sct
Currently, for Linux/macOS installations of SCT, users must navigate to the Release page, then download a "Source code (.zip)" archive. They must then `cd` into the folder and run `install_sct`. 
This is a bit unwieldy, and has also [prevented us from collecting download statistics](https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3545) for the past several years. Without download statistics, it's more difficult to demonstrate the use and impact of SCT (for the purposes of e.g. grant proposals).
As a test, the Windows installer (`install_sct.bat`) was designed to be run standalone. This allowed us to upload the install script to the release as an asset, which [_does_ grant us download statistics](https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3545#issuecomment-1 …
> Allow `install_sct` to be run standalone (without downloading "Source code" archive)

- spinalcordtoolbox/scripts/sct_analyze_texture.py
This addresses skimage's recent v0.20.0 deprecation of functions with `grey` in their names (https://github.com/scikit-image/scikit-image/pull/5385).
Fixes #4056.
> Change `grey` --> `gray` in imports of `skimage.feature` functions

- spinalcordtoolbox/scripts/sct_get_centerline.py
This PR prevents `-centerline-soft` from being used with non-fitseg methods.
Fixes: https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4062
> Prevents centerline soft being used with non fitseg methods

- spinalcordtoolbox/scripts/sct_analyze_lesion.py
- spinalcordtoolbox/scripts/sct_analyze_texture.py
- spinalcordtoolbox/scripts/sct_compute_mtsat.py
- spinalcordtoolbox/scripts/sct_create_mask.py
- spinalcordtoolbox/scripts/sct_deepseg.py
- spinalcordtoolbox/scripts/sct_deepseg_gm.py
- spinalcordtoolbox/scripts/sct_deepseg_lesion.py
- spinalcordtoolbox/scripts/sct_deepseg_sc.py
- spinalcordtoolbox/scripts/sct_detect_pmj.py
- spinalcordtoolbox/scripts/sct_get_centerline.py
- spinalcordtoolbox/scripts/sct_label_vertebrae.py
- spinalcordtoolbox/scripts/sct_propseg.py
- spinalcordtoolbox/scripts/sct_warp_template.py
- spinalcordtoolbox/utils/shell.py
- testing/api/test_utils.py
This PR enables to select image types (`im_type`) in the function `display_viewer_syntax` to simplify the colormap selection process. Indeed, it is now possible to use specifically predefined mapping between image types and colormap names instead of colormaps directly.
This mapping was proposed in this issue https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4030,
```python
imtypes_colormap = {
'anat':    {'fsleyes': 'greyscale' ,  'fslview': 'Greyscale'},
'seg':     {'fsleyes': 'red',         'fslview': 'Red'},
'softseg': {'fsleyes': 'red-yellow',  'fslview': 'Red-Yellow'},
'labels':  {'fsleyes': 'subcortical', 'fslview': 'MGH-Subcortical'},
}
```
Concerning the colormap selection process, it is still possible to select a specific colormap. However, if both arguments are …
> Add `im_type` argument in `display_viewer_syntax` to facilitate colormap selection

- spinalcordtoolbox/deepseg/inference.py
- spinalcordtoolbox/deepseg/models.py
- spinalcordtoolbox/scripts/sct_deepseg.py
This PR adds support for model ensembles by making the following changes:
1. Adds support for specifying "groups of model files" within the `'url'` field of [`MODELS`](https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/aef83eb1482ea9360065ac8d8913aaf18edd4ce8/spinalcordtoolbox/deepseg/models.py#L22):
- Model ensembles are represented using dictionaries, with the keys being seed names, and the values being URL mirrors.
- When installing an ensemble, multiple subfolders will be created (as per the [proposed spec](https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4036#issue-1579823819)).
- When running a task, the subfolders are parsed and `path_model` is updated accordingly.
- This means that there won't always be a singular "model path" -- there may a list of model …
> Add support for model ensembles to `sct_deepseg`, update `mp2rage_lesion` model

- spinalcordtoolbox/image.py
- spinalcordtoolbox/scripts/sct_image.py
`-setorient-data` is essentially a way to perform flips and transposes on an image's data array. However, its usage requires the
user to specify an orientation string *relative to the orientation string already in the header*, which has historically been [confusing
to our users](https://forum.spinalcordmri.org/t/how-to-use-sct-image-to-fix-the-orientation-of-the-header-and-data-array-setorient-data-vs-setorient/848/1).
To make things clearer, we can instead provide flip and transpose functionality directly to our users, so that they explicitly know
what operations they are applying to their data.
> **Note**: I considered writing a test for these new options, however they are dead simple, as they call `numpy` functions directly in one-liners. The corresponding test would just be... calling …
> Replace `-setorient-data` with `-flip` and `-transpose` options

- spinalcordtoolbox/registration/labeling.py
This would be nicer.
Fixes #4087.
1. Use the files `t2.nii.gz` and `t2_seg.nii.gz` from [the registration tutorial](https://spinalcordtoolbox.com/user_section/tutorials/registration-to-template/template-registration/before-starting.html).
2. Generate labels so that we have more than just 2 labels, with:
```sh
sct_label_vertebrae -i t2.nii.gz -s t2_seg.nii.gz -c t2 -qc qc
```
3. Run the registration command, with verbose output, and look for `Label #` in the output:
```sh
sct_register_to_template -i t2.nii.gz -s t2_seg.nii.gz -l t2_seg_labeled_discs.nii.gz -c t2 -qc qc -v 2 |& grep 'Label #'
```
Labels are in a random order:
```
Label #0: 24, 75, 7 --> 11
Label #1: 24, 80, 26 --> 10
Label #2: 25, 86, 47 --> 9
Label #3: 25, 106, 150 --> 3
Label #4: 26, 103, 132 --> 4
Label #5: 26, 107, 165 …
```
> List resampled labels in order

- spinalcordtoolbox/utils/sys.py
Otherwise it can easily fill the terminal scrollback buffer with irrelevant messages about fonts.
(This PR is basically following the recommendations in [matplotlib's `set_loglevel` documentation](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.set_loglevel.html).)
Fixes #4086.
> Make matplotlib less verbose

- .github/workflows/automate-changelog-PR.yml
- .github/workflows/check-code-quality.yml
- .github/workflows/create-release.yml
- .github/workflows/generate-sidebar.yml
- .github/workflows/test-batch-processing.yml
- .github/workflows/tests.yml
Our current GitHub Actions workflows include a number of external actions that are outdated, as they depend on Node.js 12. 
This triggers the following warning:
To address this warning, I have gone through each of our workflows and looked at the warnings to determine which actions are outdated. Then, I looked at the changelogs for each action to determine if it is safe to update to the latest version. In all cases, I think it is, but I'll let the automated PR checks confirm this.
Fixes #4096.
> Update outdated GitHub Actions to versions that use Node.js 16

- .github/workflows/tests.yml
Debian 9 hit EOL in June 2022. Despite this, SCT has still supported Debian 9 because it's been easy to do so: the distribution channels for Debian 9 packages had remained on http://deb.debian.org/ for some time after EOL status, requiring no action on our part. However, over March-April 2023, these channels were migrated to http://archive.debian.org and removed from http://deb.debian.org/.
This removal has caused our CI runs for Debian 9 to fail. To fix this, we must overwrite the existing entries in `/etc/apt/sources.list`, and add new sources that point to the archive location. This PR does exactly that.
Long-term, we should think about our plans to phase EOL distributions out of our test suite (as well as adding newly-released distributions). It would be nice to have a more concrete …
> Fix Debian 9 CI failures by adding `archive` links to `/etc/apt/sources.list`

- spinalcordtoolbox/gui/sagittal.py
> **Note**: The changes in this PR are small, but they require a lot of context to understand, hence the long description below.
There are two issues with how `-create-viewer` is initilaized:
1. `self._controller` never gets its `label` attribute set. As a result, when you press the undo button without first selecting a point, the following line crashes, because it tries to access the nonexistent `self._controller.label`:
https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/e7c82c359bfb0a24cc852fa4124701bd1b31d659/spinalcordtoolbox/gui/sagittal.py#L81
This was previously reported in #4104.
2. The second issue is that the label checkboxes all start out unchecked:
However, what it _should_ look like is this:
This "partially checked" state indicates that this label is the one being …
> Fix buggy `-create-viewer` behavior on initialization (undo crash, blank checkboxes)

- spinalcordtoolbox/scripts/sct_propseg.py
This is a tiny, tiny PR: We set `verbose=0` when changing the header of an existing image in `sct_propseg`, so that we silence the unnecessary "overwriting" messages.
We already use this approach elsewhere, too, e.g. in `sct_apply_transfo`:
https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/e26a173400fc03dbbb6523186de8a73754ae5168/spinalcordtoolbox/scripts/sct_apply_transfo.py#L292-L296
Fixes #2771.
> Silence unnecessary "overwriting" messages when updating output image header

- .readthedocs.yml
This follows the advice from https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4113#issuecomment-1535392170 to address the recently-failing RTD builds.
Fixes #4113.
> Ensure CI avoids older ReadTheDocs docker images to address OpenSSL mismatch

- .ci.sh
- .github/workflows/create-release.yml
- .github/workflows/tests.yml
- install_sct
- install_sct.bat
In #4049, we added the ability to run `install_sct` standalone, without needing to download the entire SCT source code beforehand.
As a follow up, to test this new standalone installation method, this PR:
- Adds some additional logic to run `install_sct` outside the source directory, which triggers the "standalone installation" procedures (namely: git clone to a tmpdir, copy files to `~/sct_<version`, etc.)
- This is triggered only on `master`, because trying to make this work for PRs is next to impossible. (It requires passing a git ref to the script so that it can `git clone` the PR's branch, but this doesn't work for forks.)
- Now that we no longer need the "git ref"-related logic, the git ref script arguments are removed.
To test this PR, I did the following: 
- …
> Test standalone installations via `tests.yml`, but only on the `master` branch

- testing/cli/test_cli.py
This is a small change to address a deprecation warning in the test suite:
```
python/envs/venv_sct/lib/python3.8/site-packages/pkg_resources/__init__.py:121
/github/home/sct_6.0.dev0/python/envs/venv_sct/lib/python3.8/site-packages/pkg_resources/__init__.py:121: DeprecationWarning: pkg_resources is deprecated as an API
warnings.warn("pkg_resources is deprecated as an API", DeprecationWarning)
```
To address this warning, we remove all usage of `pkg_resources`'s API.
Both the old and new lines of code fetch the list of all 54 scripts defined in SCT's `setup.py` `console_scripts` entry.
Fixes #4123.
> Use `importlib.metadata` to fetch list of scripts instead of `pkg_resources`

- setup.cfg
In #4124, we attempted to address `pkg_resources` API usage DeprecationWarnings by removing all usage of `pkg_resources` from SCT. As it turns out, though, SCT wasn't the only source of these warnings. 
Instead, the call-specific warnings are from upstream packages. (There are open issues for solving these warnings in their respective packages (matplotlib, google_auth), see: https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4123#issuecomment-1568505666)
So, the best we can do is filter these warnings while we wait. (This is the option chosen by many projects, see: https://github.com/search?q=ignore%3ADeprecated+call&type=code)
Fixes #4123
> Add warning filters for upstream `pkg_resources` warnings

- spinalcordtoolbox/scripts/sct_compute_ernst_angle.py
`sct_compute_ernst_angle` will display a "Repetition Time (TR) vs. Ernst angle" plot if `-v 2` is supplied. 
The script starts with a range of TR values `[500ms, 3500ms]` for the x axis of the plot. But, due to a bug in the code, if the input TR value is less than 500ms, a negative TR lower bound will be produced, which results in a `nan` Ernst angle causes an error.
This PR contains 4 commits:
- Commit 99bf2510a15e4c703e29858cd30ab49ce5c51b57 fixes the bug by capping the lower bound at 0ms.
- The remaining 3 commits clean up the `-b` argument to make it easier to use, and the `verbose == 2` block to make the code a little easier to understand.
Fixes #4130.
> Fix upper/lower TR bounds used when plotting Ernst angles (argument `-b`)

- spinalcordtoolbox/deepseg_/sc.py
- spinalcordtoolbox/resampling.py
- testing/cli/test_cli_sct_deepseg_sc.py
During `sct_deepseg_sc`, we resample images to 0.5mm prior to inference, then resample back to the native resolution after inference. However, resampling has a known issue: 
- https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3005
In this case, we _definitely_ want to preserve the codes, because we're resampling back to the native space. So, the segmentation image should be aligned to the same space as the input image, and thus the codes should not change. If we don't preserve the codes, we run into #4132, which can cause issues later down the line when working with e.g. SimpleITK.
To fix this, I could have changed the behavior of the resampling code unconditionally to address #3005 outright. However, there are some cases where the overwriting of the codes may be desirable …
> Ensure that qform/sform codes are preserved when generating segmentation

- spinalcordtoolbox/reports/slice.py
In #4125, we discovered 2 issues with the current `sct_deepseg_lesion` QC:
- For Sagittal images, resampling is applied to the wrong axes, because the code assumes Axial slices by default.
- The method for checking if an image is a segmentation is flawed; instead of inspecting the image contents, the code just assumes that only the last image is a segmentation.
- This means that earlier segmentation images _aren't_ considered segmentations, resulting in no linear interpolation and no thresholding for lesion segmentations.. 
This PR fixes each issue by:
- Applying the resampling to the correct axes for the Sagittal case.
- Detecting segmentations by inspecting the image contents, ensuring correct interpolation/thresholding for non-last segmentations (including softsegs).
Fixes #4125.
> Ensure that sagittal images (and softsegs) are resampled correctly for lesion QC

- install_sct
- install_sct.bat
This PR ensures that we always invoke the correct `python`/`pip` executables during installation, as there are cases when system `python`/`pip` can be prioritized incorrectly, _even when the conda environment is activated_. (#3029, #4142)
Previously, we tried to mitigate this issue in the `python` case by throwing an error:
https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/117e1cbd6be53db336a5ce16854cfa58abaa402e/install_sct#L617-L624
We could add a second check for `pip` to fix #4142. But, by throwing an error, we halt the installation and create debugging work that is often unnecessary, since even in the case of a mismatch, we can still just access the correct executables directly. So, this PR removes this check/error as well.
And, because we remove the `python` check, we also …
> `install_sct`: Use explicit paths to python/pip executables

- install_sct
The `defaults` version of `libffi` performs some (presumably) [backwards-compatible linking](https://github.com/AnacondaRecipes/libffi-feedstock/issues/15) between versions of libffi. However, this isn't actually compatible as assumed; instead, this results in the following errors:
```
Check if figure can be opened with PyQt.............libGL error: MESA-LOADER: failed to open iris: /lib/x86_64-linux-gnu/libLLVM-11.so.1: undefined symbol: ffi_type_sint32, version LIBFFI_BASE_7.0 (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open iris: /lib/x86_64-linux-gnu/libLLVM-11.so.1: undefined symbol: ffi_type_sint32, version LIBFFI_BASE_7.0 (search paths …
```
> `install_sct`: Install `libffi` from `conda-forge`, rather than `defaults`

- spinalcordtoolbox/reports/assets/index.html
- spinalcordtoolbox/reports/qc.py
- spinalcordtoolbox/scripts/sct_image.py
- spinalcordtoolbox/scripts/sct_qc.py
This PR started with issue #4149:
- In `index.html`, the QC key `FILES_GMSEG` is erroneously used for lesion-based scripts.
However, examining `index.html` made me realize that we're actually missing the `sct_image -stitch` in the list of keys, too. This resulted in a cascade of changes:
- Add missing `sct_image -stitch` to `index.html`
- Add missing `sct_image -stitch` to `sct_qc`'s `-p` option
- Rename the (internal use only) "process" string from `sct_image -stitch` to `sct_image_stitch`, to avoid issues with spaces on the command line when trying to specify `sct_qc -p sct_image -stitch`.
Fixes #4149.
> Fix errors in the list of available QC processes (`index.html`, `sct_qc.py`)

- .github/workflows/test-batch-processing.yml
- batch_processing.sh
- install_sct.bat
- spinalcordtoolbox/scripts/sct_run_batch.py
When we first introduced our Windows installation, we decided not to instruct users to set `$SCT_DIR`, as it was already a lot to ask users to update the `$PATH`, and we figured that `$SCT_DIR` wasn't entirely necessary for SCT to run.
That said, having `$SCT_DIR` set makes things a _lot_ easier (in terms of the SCT course, tutorials, `batch_processing.sh`, etc.), since it means we can more easily access assets from within the SCT repo (namely the PAM50 template). Plus, having consistent instructions for all OSs will help a lot when actually teaching the SCT course.
So, this PR brings the Windows installation back in line with Linux/macOS installations, and updates `batch_processing.sh` accordingly so that it can use `$SCT_DIR`, fixing #4146.
Fixes #4146.
> Make sure that `$SCT_DIR` is set for both Windows installations and `batch_processing.sh`

- spinalcordtoolbox/scripts/sct_label_vertebrae.py
- spinalcordtoolbox/scripts/sct_register_to_template.py
- testing/cli/test_cli_sct_label_vertebrae.py
- testing/cli/test_cli_sct_register_to_template.py
This PR adds a check that tests for the existence of straightening files generated by `sct_register_to_template` and `sct_label_vertebrae`. Notably, this test initially fails for `sct_register_to_template` due to #4138.
Then, this PR updates the cache-saving behavior so that A) the cache file is first saved to the temporary directory used by both scripts, then B) the cache file is copied to the output directory along with the other straightening files.
Fixes #4138.
> Ensure that the `straightening.cache` file is output to the PWD during template registration

- spinalcordtoolbox/scripts/sct_image.py
This change undoes a previous commit from PR #4052. (https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/4052/commits/ba8d4d57b82d233a82c482f4fcccb82a11bc06e8)
The purpose of the previous commit was to fix a QC report usability issue (#4051). However, this change inadvertently introduced a second bug: incorrect QC report filepaths (#4152).
Currently, I don't think there is a good way to fix both issues at once, since our QC reporting code is built around the assumption that the first image will be an anat image, and the second image will be the overlay on top of the first image. (But, maybe I'm missing something? Maybe there is a good way to fix both at once...)
Still, if we have to fix one of the two issues, I think that the QC path issue is the more critical of the two? But …
> Swap order of `sct_image -stitch` QC images to fix incorrect YML path

- .github/workflows/automate-changelog-PR.yml
- .github/workflows/create-release.yml
This PR follows up on 2 past errors from previous runs of the workflow.
Please refer to the extended commit message of 751bd42d1c538d0007fdef80b97667cc1292173c for an investigation into why using the milestone title doesn't work for the `create-pull-request` GitHub Action.
Follows https://github.com/spinalcordtoolbox/spinalcordtoolbox/commit/eeabbe72f674d107109dd1a461b7e24151106ceb
Fixes https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3968.
Fixes https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4160.
> Update changelog PR workflow to fix milestone title error and to also change `version.txt`

- spinalcordtoolbox/scripts/sct_propseg.py
With command:
```
sct_propseg -i ./t2.nii.gz -c t2 -o ./test/t2_seg.nii.gz
```
We see the following behavior:
- `-o` becomes `fname_out` (but isn't processed in any way to remove anything before the filename)
- `folder_output` is derived from `fname_out` using `str(pathlib.Path(fname_out).parent)`
- Then, `folder_output` is combined with the unprocessed `fname_out`, leading to `'test/./test/t2_seg.nii.gz'`
To fix this, we process `fname_out` to only use the actual filename, since subfolders are captured within `folder_output`.
Fixes #4167.
> Remove parent parts from `fname_out` to fix buggy `-o` behavior

- spinalcordtoolbox/scripts/sct_compute_compression.py
- testing/cli/test_cli_sct_compute_compression.py
Currently, the existing behavior for saving `sct_compute_compression` CSV files doesn't account for differing column names. So, if a user runs `sct_compute_compression` more than once with different metrics, new columns won't be created -- the data will be incorrectly appended to the existing columns.
So, this PR adds a test for that use-case, and then uses Pandas to correctly merge two different tables with different columns. We also use Pandas to combine rows that have the same filename/compression level/slice, eliminating any duplicate rows with `NaN` values.
((Side note: One day, I would like to use the exact same simplification on `aggregate_per_slice_or_level` too. See: https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4005#issuecomment-1398737874 for my thoughts.)) …
> Use pandas for `.csv` saving to correctly merge existing output metric columns

- spinalcordtoolbox/scripts/sct_compute_compression.py
This PR fixes minor stylistic issues for the CLI output printed by the `sct_compute_compression` function.
master branch:
```console
...
below: 3 above: 0
Compression #0 at level 3.0
MEAN(area) ratio = -12.303804931123953
MEAN(area) ratio norm = 7.17512630355076
MEAN(area) ratio PAM50 = -11.006326905780517
Compression #1 at level 4.0
MEAN(area) ratio = -5.492130816669349
MEAN(area) ratio norm = 17.477859636238293
MEAN(area) ratio PAM50 = -3.8011501206959952
Compression #2 at level 5.0
MEAN(area) ratio = -10.271278278493323
MEAN(area) ratio norm = 11.726811590094034
MEAN(area) ratio PAM50 = -8.010330837998868
Compression #3 at level 6.0
MEAN(area) ratio = 9.053832317696898
MEAN(area) ratio norm = 17.337087670044482
MEAN(area) ratio PAM50 = 9.38835116302329
Saved: …
```
> Improvements of CLI output printed by the `sct_compute_compression`

- spinalcordtoolbox/scripts/sct_compute_compression.py
This is a followup suggestion for #4172.
The Pandas builtin method [`combine_first`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.combine_first.html) does exactly what we want: the row and column indexes of the resulting DataFrame is the union of the two input DataFrames.
> Use the `pandas.DataFrame.combine_first` method

- spinalcordtoolbox/reports/slice.py
Fixes #4173.
I'm not sure that this warrants an automated test?
From manually re-running the steps to reproduce the issue, the crash is gone. There's still a warning printed in the output (from `scipy.ndimage.center_of_mass`, which is maybe hard to avoid):
```
QcImage: layout with Axial slice
Compute center of mass at each slice
.../spinalcordtoolbox/python/sct/lib/python3.9/site-packages/scipy/ndimage/_measurements.py:1535:
RuntimeWarning: invalid value encountered in double_scalars
results = [sum(input * grids[dir].astype(float), labels, index) / normalizer
.../spinalcordtoolbox/python/sct/lib/python3.9/site-packages/scipy/ndimage/_measurements.py:1535:
RuntimeWarning: divide by zero encountered in double_scalars
results = [sum(input * grids[dir].astype(float), labels, index) / …
```
> Gracefully handle infinity as well as NaN values in QC

- spinalcordtoolbox/types.py
https://github.com/neuropoly/template/issues/60 describes a case where the `-dest` image is smaller than the input centerline image. (For context, the template generation pipeline allows you to specify a `last_disc` config setting to exclude lower discs from the `-dest` image.)
The trace of `sct_straighten_spinalcord` goes like this:
- `-dest` becomes `centerline_reference_filename` which becomes the `centerline_straight` variable
- `-s` becomes `centerline_file` which becomes the `centerline` variable
- During the "[create look-up table curved to straight](https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/f5de501d3fe98c53861b54c60b9f5f5b96732772/spinalcordtoolbox/straightening.py#L383-L393)" portion of the straightening, we:
- Loop through the points of `centerline`
- Get the …
> Fix `IndexError` during straightening if `-dest` image is shorter than centerline image (`-s`)

- spinalcordtoolbox/reports/slice.py
In https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/4133, we added a heuristic-based check for segmentations by making sure the values `0.0` or `1.0` are the most common in the image.
However, some softsegs have light regions that are not exactly `1.0`:
So, this PR rounds the segmentation values to 1 decimal place, which ensure that values `>0.95` and `<0.05` must be the most common values in the image, rather than exactly `1.0` and `0.0`.
Fixes https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4178.
Fixes QC issues in https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/4189.
> Fix QC for soft segmentations that have light regions close to `1.0` (e.g. `0.999`)

- spinalcordtoolbox/labels.py
This is a very simple optimization:
- **Before:** Iterate through all possible "src-ref" pairs of labels, comparing their values (`O(n * m)`)
- **After:** Pre-fetch the set of ref labels, then only iterate through the "src" labels (`O(n + m)`)
This works because we only ever access the `value` from the ref labels -- we don't care about the actual coordinates of the ref labels. So, there was no need to compare all of the individual `ref_coord` objects!
Fixes #4191.
> Speed up `-remove-reference` by removing unnecessary iteration

- spinalcordtoolbox/scripts/sct_run_batch.py
When working with the `sct_run_batch` script, I incorrectly defined the suffix of the config file to `.sh`. The error raised by the `sct_run_batch` script was not very specific. Thus, I added an error raise if the config file is not YML or JSON.
`master` branch:
```
$ sct_run_batch -config config.sh
--
Spinal Cord Toolbox (git-master-d6aeaef52466129b5f24a56fa250403839bd0166)
sct_run_batch -config config.sh
--
configuring
File "/Users/valosek/code/sct_latest/spinalcordtoolbox/scripts/sct_run_batch.py", line 597, in <module>
File "/Users/valosek/code/sct_latest/spinalcordtoolbox/scripts/sct_run_batch.py", line 359, in main
config_keys = set(config.keys())
UnboundLocalError: local variable 'config' referenced before assignment
``` …
> Raise error if `sct_run_batch` config file has wrong suffix

- spinalcordtoolbox/scripts/sct_label_vertebrae.py
- spinalcordtoolbox/vertebrae/core.py
Or, conceivably, whether it was made empty by straightening. If/when that happens, the files generated by sct_label_vertebrae are empty and useless, so we should alert the user instead of silently failing.
Fixes #4174.
Manually tested using the reproduction steps from the issue:
```
$ sct_label_vertebrae -i t2.nii.gz -s t2_seg.nii.gz -discfile labels.nii.gz -c t2
--
Spinal Cord Toolbox (git-mgp/empty-discfile-c9dc5e173ffdc6a06d5092cf629308c6ef5c1a79*)
sct_label_vertebrae -i t2.nii.gz -s t2_seg.nii.gz -discfile labels.nii.gz -c t2
--
Creating temporary folder (/tmp/sct_2023-08-17_14-23-00_label-vertebrae_5wp4u5nc)
Copying input data to tmp folder...
Straighten spinal cord...
Reusing existing warping field which seems to be valid
cp /tmp/tmp.PjWfschWY3/straightening.cache …
```
> Check whether the provided discfile is empty

- spinalcordtoolbox/deepseg_/sc.py
- spinalcordtoolbox/scripts/sct_deepseg_sc.py
- spinalcordtoolbox/scripts/sct_label_vertebrae.py
- spinalcordtoolbox/types.py
- spinalcordtoolbox/vertebrae/core.py
This PR provides more intuitive feedback when `sct_deepseg_sc` produces an empty array. This avoids a more unintuitive error later on in the postprocessing function.
Fixes #4197.
> Add checks for empty arrays post-segmentation

- spinalcordtoolbox/scripts/sct_run_batch.py
This PR is just a very minor clarification of the `sct_run_batch` `-script-args` arg.
@naga-karthik encountered errors when using `"~"`, `"${HOME}"` fixed the issues. The reason is that the quotation marks in `"~"` prevent tilde expansion.
> `sct_run_batch` - add note that `~` should not be used in paths passed using the `-script-args` arg

- spinalcordtoolbox/scripts/sct_register_to_template.py
- testing/cli/test_cli_sct_register_to_template.py
This PR adds a test to cover the situation described in #4184 (mismatched qform/sform in input anat image). The command in the test should fail to raise an exception on `master`, but 626dd733b419c2ac3870a836c58bf02509f1aa5e should cause the test to pass.
There is more work that could be done (e.g. papering over the mismatch ourselves in `sct_register_to_template`), but I think for now, I want to leave that for #3283, as discussed in https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4184#issuecomment-1670042547.
Fixes #4184.
> Raise exception if sform/qform don't match during registation

- spinalcordtoolbox/straightening.py
- spinalcordtoolbox/types.py
#4085 describes a registration issue where the top of the registered template image appears buggy/incorrect. The investigation in that issue is long and complex, but the root cause and its fix are quite simple!
- We pass the the wrong `centerline` object to the `backup_centerline` parameter of the `get_closest_index` function. (065afabf9f2ded39861af7d628bcfd851f817a59)
This bug was also the _actual_ cause of https://github.com/neuropoly/template/issues/60, meaning that we can remove the workaround from #4192.
> **Note**: During my investigation, I made two refactoring commits related to #4075, which helped make the `get_closest_index` functions easier to understand. While not strictly necessary for this PR, I think they'll help with future maintainability, and should hopefully make this …
> Fix distorted registration due to straightening bug in `get_closest_to_absolute`

- .readthedocs.yaml
Fixes #4205.
Main changes:
- Cosmetic: renamed `.readthedocs.yml` to `.yaml` extension, to match the ReadTheDocs interface and docs.
- Cosmetic: added some explanatory comments.
- Functional: re-enabled pdf and epub builds (ignored options from the [project settings](https://readthedocs.org/dashboard/spinalcordtoolbox/advanced/)).
> Migrate old ReadTheDocs settings to `.readthedocs.yaml`

- spinalcordtoolbox/scripts/sct_run_batch.py
Fixes #4216, with only 3 extra characters :wink:
From the manual page for `strftime`, the added date information is:
```
%F     Equivalent to %Y-%m-%d (the ISO 8601 date format). (C99)
%Y     The  year  as a decimal number including the century.  (The %EY con‐
version specification corresponds to the full alternative year  rep‐
resentation.)  (Calculated from tm_year)
%m     The month as a decimal number (range 01 to  12).   (Calculated  from
tm_mon.)
%d     The  day of the month as a decimal number (range 01 to 31).  (Calcu‐
lated from tm_mday.)
```
> Add start date information to the logs

- spinalcordtoolbox/scripts/sct_dmri_display_bvecs.py
Previously, we would create a dict of [1,4] numpy arrays representing RGB colors + A (transparency) for each unique bval. Due to a recent matplotlib update, though, using a numpy array causes an unexpected ValueError. (https://github.com/matplotlib/matplotlib/issues/26821)
> This error is what's causing the current CI failures across recent PRs.
Since a tuple of size [4] results in the exact same functionality, we can bypass the error by storing tuple-based colors instead.
Fixes #4220.
> Fix `ValueError` by passing a tuple to `color=` instead of a numpy array

- spinalcordtoolbox/scripts/sct_analyze_lesion.py
Fixes #4214.
The `self.volumes` array was only written, never read by anyone else, so there's no need to have it.
And once it's gone, there's no need to sum each slice first, then sum over the slices; we can just sum the whole array at once.
> Simplify lesion volume computation

- requirements.txt
Due to https://github.com/microsoft/onnxruntime/issues/17631, version 1.16.0 is causing CI to fail on master. We can change the pin to `!=1.16.0` (or to however many versions are buggy) once upstream releases a fix.
Part of #4225.
> Temporarily pin `onnxruntime` to <1.16

- requirements.txt
`sct_dmri_compute_dti` fails on `sct_example_data` images when using `-method restore`:
```
sct_dmri_compute_dti -i dmri.nii.gz -bval bvals.txt -bvec bvecs.txt -method restore
```
I dug into this on the `dipy` side of things, and found that the issue only exists for `dipy==1.6.0,1.7.0`, and has already been fixed upstream. `dipy==1.8.0` is releasing soon, so to avoid freezing a buggy version for SCT v6.1, we skip these two versions in our requirements.txt.
Note: We have an existing test for this. The reason that our test suite didn't catch this is because `dipy` chunks the processing, and the test image is smaller than a single chunk, but the bug only occurs when there are >1 chunks. I'm not quite sure how to test for this given our available testing data? But maybe given that this is a …
> Avoid `dipy` versions 1.6.0 + 1.7.0 that contain a `method=restore` bug

- spinalcordtoolbox/deepseg/models.py
This PR updates the model links so that they point to newly-created releases that change the `target-suffix` key in the `config.json` files to `_seg` (instead of the incorrect `_seg-manual`):
- https://github.com/ivadomed/lumbar_seg_EPFL/releases/edit/r20231004
- https://github.com/ivadomed/t2star_sc/releases/tag/r20231004
This is necessary so that we can write a tutorial for lumbar registration, and have the suffix be appropriate for the tutorial.
Fixes #3278.
> Update model releases (`lumbar_seg`, `t2star_sc`) to fix output suffix (`_seg-manual` -> `_seg`)

- .readthedocs.yaml
They are failing badly on master, and are not useful.
Fixes #4260.
> Disable PDF and EPUB documentation builds

- spinalcordtoolbox/download.py
In PR #4255 it was suggested that the table appended to the argparse help for `sct_download_data` could be colored to indicate whether a dataset was installed.
I have made a simple attempt to check for the existence of each dataset at its default location.
However, this is insufficient if a user has installed to a custom location.
Perhaps calling [`download.py::install_named_dataset()`](https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/23776c374fa183308043f3d95f0017e0e63b51a3/spinalcordtoolbox/download.py#L359C16-L359C16) with a custom `dest_folder` parameter could create or add to a new file that will record custom install paths. This file would be created in a standard location and could then be referenced to accurately reflect whether each dataset has been installed. …
> Color installed datasets for `sct_download_data -h`

- documentation/source/user_section/tutorials/registration-to-template/lumbar-registration/template-registration.rst
See this page for the correct syntax:
https://www.sphinx-doc.org/en/master/usage/referencing.html#role-ref
Sorry for introducing this broken link in [my earlier suggestion](https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/4250#discussion_r1374998121)!
> Fix broken link

- spinalcordtoolbox/scripts/sct_warp_template.py
- testing/cli/test_cli_sct_warp_template.py
Currently, either `linear` or `nn` interpolation is used when warping template files (see https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4280#issuecomment-1789177326). But, neither interpolation method is appropriate for label files _(`nn` may result in lost labels, while `linear` results in the label values themselves not being preserved (int `3.0` -> float `1.0234674`))_. This is why `sct_apply_transfo` has a specific interpolation setting called `label`, so we should use it here.
I've written a test that will fail for the current interpolation, but will pass when interpolation is switched to `label`, to demonstrate that my changes fix the issue.
Fixes #4280.
> Ensure that point label files are correctly interpolated during template warping

- spinalcordtoolbox/download.py
Right now, the manual correction scripts exist outside of the SCT repo, for reasons outlined in:
- https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3353
However, this makes accessing the manual correction script difficult (requiring either a `git clone` or a `wget`/`curl` call).
So, similarly to https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/4271, we make use of `sct_download_data` as a download manager, to ease the process of downloading a URL + unzipping it to the correct folder.
Additionally, I've re-added the separate "Course" download category, which should signal to users that manual correction is intended to be used within the context of the SCT course.
Fixes https://docs.google.com/presentation/d/1t40Fd0fS0SwWR5FU_GWKEvHkB9d96LVddLQW6L3QAx0/edit?disco=AAAA …
> Add `manual-correction` to `download.py` to make downloading easier for the SCT Course

- spinalcordtoolbox/image.py
A tiny tiny PR, but I noticed it once and it bothered me: the attribute `Image.verbose` is saved in `__init__`, but is never actually read anywhere. Instead, the pattern is that individual methods of `Image` which can be chatty accept a `verbose` parameter.
(To be sure that no one at all uses `Image.verbose`, I searched all python files for the string `.verbose`. All instances are either: `self.verbose` in another class, `param.verbose` in various scripts, `SpinalCordStraightener.verbose`, `Transform.verbose`, or `ImageCropper.verbose`.)
> Remove unused `Image.verbose` attribute

- .github/workflows/check-code-quality.yml
This is the easiest way to make sure that developers' commit hooks generate the same warnings/errors as what runs in CI. Otherwise, we get annoyances like in #4294.
> Use the same Python version as SCT for linting

- spinalcordtoolbox/aggregate_slicewise.py
- spinalcordtoolbox/centerline/core.py
- spinalcordtoolbox/compat/launcher.py
- spinalcordtoolbox/deepseg/models.py
- spinalcordtoolbox/deepseg_/postprocessing.py
- spinalcordtoolbox/image.py
- spinalcordtoolbox/math.py
- spinalcordtoolbox/reports/slice.py
- spinalcordtoolbox/scripts/sct_compute_hausdorff_distance.py
- spinalcordtoolbox/scripts/sct_image.py
- spinalcordtoolbox/scripts/sct_merge_images.py
- spinalcordtoolbox/scripts/sct_run_batch.py
This PR replaces most instances of `assert` in SCT with `raise`.
Apart from unit tests, assertions are meant for internal invariants, and are not even guaranteed to be run (for example, if python is run with `-O`).
For bad script arguments, calling `parser.error` is better. For bad function arguments, usually raising `ValueError` or `TypeError` is better.
> Replace assertions with more appropriate errors

- spinalcordtoolbox/scripts/sct_run_batch.py
Every time I use `sct_run_batch`, I am not sure about the syntax for `exclude_list`/`include_list` arguments. For that reason, I added examples to `sct_run_batch -h`.
> Add `exclude_list` example to YAML and JSON config files

- spinalcordtoolbox/qmri/mt.py
The MTsat equations in SCT were inherited from qMRLab. I've just discovered that the initial implementation of the B1 correction of MTsat in qMRLab was missing corrections for the PDw and T1w excitation flip angles, which for large B1 errors causes substantial differences in the T1 and MTsat maps. Other softwares have these B1 corrections ([QUIT](https://github.com/spinicist/QUIT/blob/5af31041a2194c81306826a729e6729f4d806f3d/Source/MT/MTSatModel.cpp#L12-L20), hMRI [R1](https://github.com/hMRI-group/hMRI-toolbox/blob/894a38be696e42a769765c313022f0bf1acafe64/hmri_calc_R1.m#L41-L47) and [A](https://github.com/hMRI-group/hMRI-toolbox/blob/894a38be696e42a769765c313022f0bf1acafe64/hmri_calc_A.m#L41-L47)). 
This PR seeks to fix this bug, and is designed closest to the QUIT implementation (with …
> Apply missing B1 correction to `r1map` and `a` calculations to fix MTsat bug

- spinalcordtoolbox/scripts/sct_analyze_lesion.py
In `sct_analyze_lesion` we perform angle correction [using the centerline derivative](https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/365651dbd7d31b909b7ec85844b0e6492a4649ca/spinalcordtoolbox/scripts/sct_analyze_lesion.py#L504C1-L504C1) (via the `get_centerline` function). The `get_centerline` function [crops the centerline by default](https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/365651dbd7d31b909b7ec85844b0e6492a4649ca/spinalcordtoolbox/centerline/core.py#L137-L141), due to the parameter `minmax` [being `True` by default](https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/365651dbd7d31b909b7ec85844b0e6492a4649ca/spinalcordtoolbox/centerline/core.py#L21).
Cropping has the following knock-on effects:
- The `arr_ctl_der` array's dimensions no longer …
> Set `minmax=False` to prevent cropping during angle correction, avoiding slice number mismatches

- requirements.txt
This PR temporarily resolves a dependency conflict that makes the current version of SCT crash when installing. To temporarily solve the problem, I restricted the use of dipy 1.8.x.
#4319
> Temporary fix for dependency issue with dipy 1.8.0

- spinalcordtoolbox/scripts/sct_label_utils.py
This PR clarifies the `sct_label_utils -disc` help to make it clear that this flag is used to create a labeled segmentation from disc labels without cord straightening.
Resolves: https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4323
> Clarify `sct_label_utils -disc` help

- spinalcordtoolbox/vertebrae/detect_c2c3.py
Hi SCT Group, 
I was trying to use SCT in 3D Slicer environment. Installation works perfect.  
https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/5b9f2451f40f5e45a3c04d2a9826f34b452d19e8/spinalcordtoolbox/vertebrae/detect_c2c3.py#L85C13-L85C13
during https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/5b9f2451f40f5e45a3c04d2a9826f34b452d19e8/spinalcordtoolbox/utils/sys.py#L333C6-L333C6 
it tries to split cmd in couple of argument lists.
The problem for me is Slicer 5.6.1 has a space in between.
(example)
" 'C:\\Users\\admin\\AppData\\Local\\slicer.org\\Slicer 5.6.1\\lib\\Python\\Lib\\site-packages\\bin\\isct_spine_detect -ctype=dpdt "C:\\Users\\admin\\AppData\\Local\\slicer.org\\Slicer 5.6.1\\lib\\Python\\Lib\\site-packages\\data\\c2c3_disc_models\\t1_model" …
> Fix path splitting when space (`' '`) is present in `isct_spine_detect` model path

- spinalcordtoolbox/scripts/sct_process_segmentation.py
- testing/cli/test_cli_sct_process_segmentation.py
This minor PR replaces FileNotFoundError by parser.error when `-normalize-PAM50` is provided without the required option `-vertfile`.
`master` branch:
```console
$ cd dcm-zurich/derivatives/labels/sub-250791
$ sct_process_segmentation -i /anat/sub-250791_acq-axial_T2w_label-SC_mask-manual.nii.gz -normalize-PAM50 1
...
Vertebral level file ./label/template/PAM50_levels.nii.gz does not exist. Vert level information will not be displayed. To use vertebral level information, you may need to run `sct_warp_template` to generate the appropriate level file in your working directory.
File "/Users/valosek/code/sct_latest/spinalcordtoolbox/scripts/sct_process_segmentation.py", line 528, in <module>
File …
```
> For `-normalize-PAM50` option, replace `FileNotFoundError` with `parser.error` so that the argparse help gets displayed

- spinalcordtoolbox/scripts/sct_compute_compression.py
The `sct_compute_compression` function is meant to compute maximum spinal cord compression (MSCC) using the SC segmentation.
This PR updates the `sct_compute_compression` description to make clear that the function can also be used for maximum canal compromise (MCC) computation if spinal canal (aka CSF) segmentation is provided.
More context in https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4330.
Currently, I have updated only the description (without changing any code). This assumes that users will read the description and will not provide spinal canal segmentation in combination with the `-normalize-hc` flag ([normative database](https://github.com/spinalcordtoolbox/PAM50-normalized-metrics) does not contain measures of the spinal canal). I made this clear by the …
> Update argparse descriptions to make it clear that the script can also be used to compute MCC

- spinalcordtoolbox/deepseg/inference.py
- spinalcordtoolbox/scripts/sct_deepseg.py
- spinalcordtoolbox/vertebrae/core.py
In https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3232#issuecomment-1883229811, I ran into a two-pronged bug:
1. `sct_deepseg` uses `nib.save()` rather than `Image.save()`, meaning that it was susceptible to the float/int scaling issues (1.0 -> 0.999) as previously documented in #3232.
2. When using a poorly-scaled segmentation with `sct_label_vertebrae`, the multiplication part of the "clean labels" step would then transfer the scaling issues to the integer labels themselves.
This PR fixes both issues by:
- Working with `spinalcordtoolbox.image.Image` objects in `sct_deepseg` (since `Image.save()` contains a mitigation for the scaling issues.)
- Converting the segmentation to a boolean mask before multiplying it with the label image.
Note: I'm not sure whether it's worth …
> Mitigate scaling issues (`0.999`) in both `sct_deepseg` and `sct_label_vertebrae`

- install_sct
This was a really weird bug to investigate!! General background info references:
- https://eclecticlight.co/2020/07/21/big-sur-is-both-10-16-and-11-0-its-official/
- https://github.com/pypa/packaging/issues/497#issuecomment-1012665274
- https://github.com/pypa/pipenv/issues/4564#issuecomment-829199591
Specific to `onnxruntime`:
- https://github.com/microsoft/onnxruntime/issues/17166
- https://github.com/microsoft/onnxruntime/issues/19371
The above issue has only become relevant for SCT because one of its dependencies, `onnxruntime` switched to wheels that specify `macosx_11_0` in the wheel's name instead of the previous `macosx_10_15`. So, we need the compatibility fix to install the newest `onnxruntime` wheels, at least until `pip` fixes this upstream by vendoring a newer version of …
> Fix broken pip installer by forcing it to detect macOS 11 as `11.0` and not `10.16`

- spinalcordtoolbox/types.py
This PR handles a specific registration case from @jqmcginnis, where:
- The `-ldisc` argument is used with 3+ intervertebral disc labels.
- The topmost disc label is _not_ C1. In this case, it was `'C3'` (`3`).
- There are slices in the spinal cord segmentation that extend above the topmost disc label.
If these three conditions are met, then straightening will fail prior to registration.
The tl;dr for the failure is the following logic:
- When a centerline is fitted to the cord segmentation, then the points of the centerline get labeled with their corresponding vertebral level (inferred from the disc labels). Any points above the C1 intervertebral disc should be left as `0` (since there is no vertebral level above the C1 disc).
- Because of this logic, the rest of the code operates under …
> Fix straightening error during registration if 3+ labels are supplied and topmost disc label is not C1

- spinalcordtoolbox/deepseg/inference.py
As per [this comment on #4345](https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/4345#discussion_r1489625543).
See: https://github.com/MIC-DKFZ/nnUNet/blob/997804c7510634dc8fd83f1194b434c60815a93e/nnunetv2/imageio/nibabel_reader_writer.py#L49-L52
> Reverse spacings to match nnUNet's conventions

- documentation/source/user_section/installation/mac.rst
- install_sct
[Rosetta 2](https://en.wikipedia.org/wiki/Rosetta_(software)#Rosetta_2) is needed to translate `x86_64` executables (which we rely on) so they can run on the `arm64` architecture of Apple silicon chips. This PR documents this requirement on the [Mac installation page for SCT](https://spinalcordtoolbox.com/user_section/installation/mac.html) and in the SCT installer, which:
* detects whether the computer is running macOS;
* if so, it tries to run a builtin command (`true`) while requesting the `x86_64` architecture;
* if this fails, it offers to install Rosetta 2.
The new code mirrors the check for `gcc` which appears right below in the installer.
The test uses the `arch` command, which has different functionality on Linux than on macOS; see [the linux manual page for …
> Document Rosetta 2 as a requirement for installation on Apple silicon (M1, M2, M3)

- requirements.txt
- setup.cfg
- spinalcordtoolbox/scripts/sct_check_dependencies.py
This is a small PR to revisit the warnings caught by our test suite:
- pyqt5-sip: See https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4354
- pkg_resources deprecation --> ~~fixed upstream~~ Not true! `wandb` still uses `pkg_resources`
Fixes #4354.
> Address test warnings by pinning `pyqt5-sip<12.13.0` and updating `setup.cfg` ignore entries (`pkg_resources`)

- .github/workflows/tests.yml
This is a sister PR to #4353. In that PR, the versions for Node.js actions and runner OSs were updated across the board. However, doing so caused some failures that weren't discovered until after the PR was merged.
So, this PR addresses the issue by:
- Replacing EOL (or near-EOL) OSs with modern counterparts.
- Promoting CentOS 9 to "PR testing" and sunsetting CentOS 8 to "nightly testing"
- I'll have to update the branch protection rules to ensure the right version is "Required" on PRs, too. 
- Downgrading the WSL runner temporarily.
- This isn't a long-term fix, but given the complexity of debugging a failing runner that hangs without further feedback, I figure we can revert the change for now, at least until [`windows-2025` forces us to …
> Update GitHub Actions versions (Debian 9->11, CentOS 7->9, WSL 2022->2019) to fix CI failures

- requirements.txt
`dipy==1.8` and above cause conflicts with SCT's venv due to ivadomed. More details here: https://github.com/ivadomed/ivadomed/pull/1308
So, for now, we need to pin `dipy<1.6` to avoid breakage every time a new version of `dipy` is released. But, once https://github.com/ivadomed/ivadomed/pull/1308 is merged and a new version of ivadomed is released, we can switch this pin to `dipy!=1.6.*,!=1.7.*` and allow 1.8/1.9/etc.
Fixes #4397.
> Pin to `dipy<1.6` until conflicts with `dipy>=1.8` can be resolved

- .github/workflows/create-release.yml
- .github/workflows/test-batch-processing.yml
- .github/workflows/tests.yml
This PR solves the queuing issues we've faced due to the limit of 5 concurrent macOS runners.
Here, I've added the lowest-hanging-fruit suggestions from the issue description of https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4400. I've tried to preserve the highest-impact CI workflows (tests.yml, test-batch-processing.yml) while relegating the lower-impact CI workflows (create-release.yml, macos-14) to cron-only. I've also removed the trigger for merges/pushes to master. 
(See extended commit messages for further justification of each change.)
With these changes, we can now:
- Update PRs twice concurrently without running into queuing issues. (2x2 < 5)
- Merge and update PRs without running into queuing issues.
In the short term, this should allow us to quickly work through …
> Reduce concurrent macOS runners on PRs from 6 to 2 (and remove push-to-master triggers)

- spinalcordtoolbox/reports/qc.py
- spinalcordtoolbox/scripts/sct_qc.py
The existing QC report for `-p sct_label_vertebrae` assumes a single continuous set of labels with low values (e.g. `[2, 3, 4, 5, 6]`). However, if the provided labels go beyond 105, and/or  contain multiple distinct subsets of labels, then the generated color mapping will be incorrect, causing segmented labels to be seemingly merged together.
This PR provides two fixes: 
- A simple fix (to ensure that we properly assign a unique color to each label)
- A more complex fix (to try to visually distinguish the different label subgroups)
<details>
<summary> Comparison screenshots </summary>
Before:
After (simple fix):
After (complex fix):
</details>
There was some back and forth in the original issue, but in short: My complex "automatic" approach won't necessarily result in our typical …
> Fix `-p sct_label_vertebrae` QC report when providing TotalSegmentator labels

- .github/workflows/create-release.yml
- .github/workflows/test-batch-processing.yml
This commit is a tiny follow-up fix for PR #4402. In that PR, we relegated the `create-release.yml` workflow to only run on cron jobs. And, because we no longer run the workflow on PRs, we were able to expand the OSs suite without worrying about incurring additional costs. So, `windows-2019` was added back in addition to `windows-2022`.
However, in order to determine which installer to use (win vs. unix), we currently check the exact runner name ("windows-2022"). So, windows-2019 wasn't detected as a Windows runner, and the workflow failed for today's cron job.
To fix this, we can use an alternative syntax that is more general ("Windows") suggested by the official docs: https://docs.github.com/en/actions/learn-github-actions/variables#detecting-the-operating-system
N/A.
> Replace `matrix.os` with `runner.os` to more robustly detect Win OSs in GHA workflows

- .github/workflows/check-code-quality.yml
- requirements.txt
- setup.cfg
- spinalcordtoolbox/deepseg_/onnx.py
- spinalcordtoolbox/process_seg.py
- spinalcordtoolbox/scripts/sct_analyze_lesion.py
- testing/api/test_deepseg_sc.py
- testing/api/test_qmri.py
- testing/cli/test_cli_sct_label_vertebrae.py
Upstream ivadomed changes: https://github.com/ivadomed/ivadomed/pull/1308
The upstream changes enabled a cascade of version upgrades (compared to `master`):
- Explicit dependency upgrades (`requirements.txt`):
- `nibabel`: `3.2.2` -> `5.2.1`
- `dipy`: `1.5.0` -> `1.8.0`
- `numpy`: `1.23.5` -> `1.26.4`
- Second-order dependency upgrades (held back by previous packages):
- `pandas`: `1.4.4` -> `1.5.3`
- `pyparsing`: `2.4.7` -> `3.1.2`
Given that we've been held back on these versions for so long, some additional changes are needed to address upstream deprecation warnings and errors, mainly due to `numpy`.
Fixes #4319.
Mostly addresses https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/4408, but doesn't address https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4408#issuec …
> Pull upstream `ivadomed` changes that let us upgrade previously-pinned versions of `dipy`/`numpy`/`nibabel`

- spinalcordtoolbox/image.py
The primary goal of this PR is to avoid treating PSIR anat images as labeled segmentation images when resampling for QC reports. Segmentations are thresholded after resampling to ensure that their background remains transparent. But, PSIR images can have positive _and_ negative values, so thresholding will make half the image dark:
Before (thresholded as seg image):
After (no thresholding as anat image):
> Note: There is less of a risk of the inverse issue where label images treated as anat images, since `sct_qc -p sct_label_vertebrae` doesn't perform resampling. (Though, `check_image_kind` is also used for picking the colormap to use for `fsleyes` commands, so we do still need to consider labeled segmentations.)
Fixes #4389.
> Fix detection of PSIR images for QC resampling to avoid unnecessary thresholding

- spinalcordtoolbox/deepseg_/gm.py
- spinalcordtoolbox/deepseg_/sc.py
- spinalcordtoolbox/image.py
- spinalcordtoolbox/registration/algorithms.py
- spinalcordtoolbox/resampling.py
- spinalcordtoolbox/scripts/sct_apply_transfo.py
- spinalcordtoolbox/scripts/sct_denoising_onlm.py
- spinalcordtoolbox/scripts/sct_detect_pmj.py
- spinalcordtoolbox/scripts/sct_dmri_denoise_patch2self.py
- spinalcordtoolbox/scripts/sct_propseg.py
- spinalcordtoolbox/straightening.py
This PR is a follow up to previous PRs:
- https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/3944
- https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/4346
We have the fix for the scaling issues in `Image.save()` -- we just need to make sure `Image.save()` is actually being used instead of `nib.save()`. So, this PR takes care of the remaining usages of `nib.save()`, _except_:
- `image.py`: This the 1 necessary usage for `Image.save()`
- `sct_detect_pmj.py`: Here, we use `nib.save()` for a `.hdr` file, which I don't think SCT's `Image` class was built to handle.
- `testing/`: These usages are entirely for dummy data creation, where datatype mismatches wouldn't be an issue.
Fixes #3232.
> Replace remaining usages of `nib.save()` with `Image.save()` to mitigate scaling issues

- spinalcordtoolbox/reports/qc2.py
- spinalcordtoolbox/scripts/sct_register_multimodal.py
This is a draft PR, to get early feedback on a proposed code structure for the QC report generation code.
Currently, it only contains a proof of concept for `sct_register_multimodal` (picked at random).
I manually tested that it produces an identical QC report entry for [a command from the tutorial](https://spinalcordtoolbox.com/user_section/tutorials/multimodal-registration/mtr-computation/coregistering-mt0-mt1.html), but in some corner cases the images may be different.
I'll do a self-review to point out a few things first, but after that I'd love to get @joshuacwnewton's feedback, either as comments or through a slack discussion, whatever's easier.
Fixes #4201.
> Restructure QC report code to use `create_qc_entry` context manager (plus 1 PoC: `multimodal`)

- .github/workflows/check-broken-links.yml
- .github/workflows/check-code-quality.yml
Fixes #4426.
I still kept a limited form of the link checker for PRs. It should only check added/modified lines, so that should catch typos in new/changed links. The daily job should catch websites that stop working.
For the daily run, I picked a scheduled time that's an hour before all the other tests (either 5am or 6am Montreal time, depending on daylight savings), to avoid resource bottlenecks.
> Move most broken link checking to a daily job

- .github/workflows/check-broken-links.yml
- .github/workflows/check-code-quality.yml
Since `grep` no longer receives filenames, it no longer puts `$FILENAME:` at the start of each line. But `check-url.sh` _does_ expect a semicolon before the url to check. So we need to insert it, rather than changing the colon after `https` into a semicolon.
Sorry!
Follow-up for #4428.
> Fix broken link checker

- spinalcordtoolbox/registration/algorithms.py
- spinalcordtoolbox/reports/slice.py
- spinalcordtoolbox/resampling.py
nibabel will throw an error for instances of `Nifti1Image(data, affine)` when data is of type
int64 (and no header/dtype arguments are specified):
```python
File "/home/runner/sct_6.3.dev0/testing/api/test_deepseg_sc.py", line 85, in test_uncrop_image
nii = nib.nifti1.Nifti1Image(data_in, affine)
File "/home/runner/sct_6.3.dev0/python/envs/venv_sct/lib/python3.9/site-packages/nibabel/nifti1.py", line 1836, in __init__
alert_future_error(
File "/home/runner/sct_6.3.dev0/python/envs/venv_sct/lib/python3.9/site-packages/nibabel/deprecated.py", line 120, in alert_future_error
raise error_class(f'{msg} {error_rec}'.strip())
ValueError: """Image data has type int64, which may cause incompatibilities with other tools. 
To use this type, pass an explicit header or dtype argument to …
```
> Avoid nibabel crashes due to `int64` arrays by explicitly passing `dtype`/`header` to `Nifti1Image`

- requirements.txt
I've opened an upstream PR to fix this issue here: https://github.com/MIC-DKFZ/nnUNet/pull/2114
I'm hoping that this will be merged for nnunetv2==2.4.2, hence avoiding only 2.4.0/2.4.1.
Fixes #4444.
> Avoid `nnunetv2=={2.4.0,2.4.1}` to mitigate upstream bug for `predict_single_npy_array`

- documentation/source/overview/concepts/pam50.rst
See https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4247#issuecomment-2020338980:
> > _The spinal levels are estimated from the intervertebral discs, using a methods described in [Frostell et al. (2016)](https://www.frontiersin.org/articles/10.3389/fneur.2016.00238/full)._
> 
> From what is explained in the [issue #16](https://github.com/spinalcordtoolbox/PAM50/issues/16) and [the script](https://github.com/spinalcordtoolbox/PAM50/blob/38f6ce3418aebcee1458594f22646dc94ca889f6/scripts/generate_spinal_levels.py), the levels are computed based on the relative length of each spinal level with respect to the length of the full spinal cord  (expressed as a percentage), found in Table 3 of the article by Frostell et al., 2016.
> 
> I thought it might be important to update this ☺️ …
> Fix inaccurate line in docs regarding the method used for spinal level estimation (Frostell et al.)

- documentation/source/user_section/tutorials/diffusion-weighted-mri/motion-correction-for-dmri.rst
- documentation/source/user_section/tutorials/processing-fmri-data/motion-correction-for-fmri.rst
The columns were changed in #4396, but the tutorial changes should only be merged when SCT v6.3 gets released, since the website updates immediately.
> Update documentation to describe changes to `moco_params.tsv` for SCT v6.3

- .github/workflows/tests.yml
From what I can tell, Debian is in the process of [migrating from `libglib2.0-0` to `libglib2.0-0t64`](https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1958242.html) (64-bit time) to fix the [Year 2038 problem](https://en.wikipedia.org/wiki/Year_2038_problem). 
Currently, we manually install the old `libglib2.0-0`, which appears to cause a conflict with the new `libglib2.0-0t64`. My best guess is that one of the other packages that we install (e.g. `gcc`/`git`/`curl`/etc.) had upgraded to `libglib2.0-0t64`, so by simultaneously installing the old package, we run into: 
```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or …
```
> Replace `libglib2.0-0` with `t64` version to fix Debian Rolling Release test failure

- spinalcordtoolbox/aggregate_slicewise.py
- spinalcordtoolbox/scripts/sct_extract_metric.py
Fixes #4467
I'm having issues creating a test for it (https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4468), we should add the following tests for `test_cli_sct_extract_metric.py`:
- Labels under `Keyword=IndivLabels`: `-l 2,3 -combine 1` --> it should combine 2,3 into a single label
- Labels under `Keyword=IndivLabels`: `-l 2 -combine 1` --> it should not crash, and extract in label 2
- Labels under `Keyword=CombinedLabels`: `-l 52 -combine 1` --> it should not crash, and extract in label 52 (the test I was trying to make)
- Labels under `Keyword=CombinedLabels`: `-l 51,52 -combine 1` --> Now that's an interesting one. I'm now sure what will happen in the code to be honest 😅 but ideally we would produce a label (99) that combines all tracts within 51 and 52 (and deal with …
> Ignore case where user selects 'combine=1' with CombinedLabels

- spinalcordtoolbox/scripts/sct_compute_flow.py
- spinalcordtoolbox/utils/shell.py
This PR ensures that our line-wrapping code doesn't fail when passed a whitespace-only line (e.g. `'     '`). This can occur when using a multiline string with a blank line in between.
As a test, I've reverted the help description string for `sct_compute_flow` back to its multiline version.
Fixes #4471.
> Fix small argparse bug when wrapping help text with whitespace-only lines

- spinalcordtoolbox/reports/assets/_assets/css/style.css
- spinalcordtoolbox/reports/qc.py
- spinalcordtoolbox/reports/slice.py
- spinalcordtoolbox/scripts/sct_qc.py
Sagittal mosaics are a (relatively) new type of QC report, added in https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/4102. They are based off of mosaics of Axial slices. However, there is a key difference: Axial slice mosaics are fixed at 30x30vox per axial slice, whereas sagittal slice mosaics vary depending on the extents of the sagittal segmentation.
In #4458, @NathanMolinier discovered an edge case: If the resolution of the image is sufficiently large, and if the segmentation spans many sagittal slices, then the mosaic can grow way too big in size. At that point, it hits our height limitations for QC reports (both in matplotlib canvas size, and CSS max-height), and thus the whole mosaic image gets scaled down to fit:
So, this PR adjusts the height limitations to allow …
> Fix tiny sagittal mosaic QC Report for large images with many slices

- spinalcordtoolbox/scripts/sct_label_utils.py
> `sct_label_utils`: Clarify argument order for `-disc`

- spinalcordtoolbox/scripts/sct_apply_transfo.py
The fallback filename (`{fname_in}_reg`) was only set inside the context of the `Transform` class. Meaning, if `-o` wasn't passed, then the `fsleyes` command would display a blank filename. So, I moved setting `fname_out` to before we call `Transform`, which is more in line with our API/CLI separation conventions anyway.
(Side note: I notice that our variable naming conventions are all over the place for this module (`fname`, `file`, `filename`, etc.). Maybe that's worth tidying up in this PR, too?)
Fixes #4478.
> Make sure that `fname_out` is set properly for `fsleyes` command when `-o` is not passed

- documentation/source/overview/concepts/spaces-and-coordinates.rst
The old url has a big banner at the top of the page, claiming that this new url contains the latest version. A quick look confirms that the content is essentially the same.
I noticed this when checking the daily broken url results:
https://github.com/spinalcordtoolbox/spinalcordtoolbox/actions/runs/9050554894/job/24866074154
> Update url to slicer documentation

- spinalcordtoolbox/aggregate_slicewise.py
- testing/cli/test_cli_sct_extract_metric.py
For data where an image is [split into multiple chunks](https://github.com/sct-pipeline/spine-park/issues/10#issuecomment-2113482362), you may want to call the same `sct_extract_metric` command on multiple chunks spanning a range of vertlevels (e.g. `-vert 1:12`). But, not all chunks will contain all of the specified levels.
For this case, there is a bug where an `agg_metric` entry will be created for the slicegroup "`()`", i.e. a group containing no slices. This will result in an empty row containing no data.
This PR adds a test that reproduces the condition and fails. As soon as the empty slicegroup row is removed, the test will pass.
Fixes https://github.com/sct-pipeline/spine-park/issues/35.
> Skip empty slicegroups to avoid creating blank rows in output metric CSV file

- spinalcordtoolbox/scripts/sct_apply_transfo.py
My goal was threefold:
- Fix the formatting of the multi-line string
- Provide an example of what a single-voxel label looks like
- Explicitly state that `-x label` is not appropriate for multi-voxel segmentations
Fixes #4497.
> Rewrite help for `-x label` to clarify the difference between single-voxel and multi-voxel labels

- spinalcordtoolbox/deepseg/models.py
The differences between v2.3 and 2.4 seem to be mainly focused on lumbar t2w and PSIR/STIR images: [diff of release body](https://www.diffchecker.com/WSVngW4s/)
This should be a good test for our "keep models up to date" code. If everything works correctly, you should be able to check out this branch, then run the `sct_deepseg -task` command, and the code will automatically verify the version of the model and download the newest version if your local version is out of date.
Fixes #4509.
> Update contrast agnostic model to v2.4 (now improved for lumbar t2w + PSIR/STIR images)

- spinalcordtoolbox/utils/fs.py
- testing/api/test_qc_parallel.py
When many processes are running (e.g. `sct_run_batch -jobs 32`), we may have many different subjects trying to write to the QC report at one time. To avoid corruption/file overwriting, we limit the QC report to 1 process at a time, while other processes have to wait their turn. By default, the timeout is 5s, after which an `AlreadyLocked` error will occur.
To fix this, I first amended our parallel QC test to try to better catch this issue, since this error only occurs when there are many jobs running, but the test only checked against `jobs=2`. (Anecdotally, 2-8 jobs will be able to acquire the lock on first try, but 16+ jobs will start to back up, causing waits and re-attempts to acquire the lock.) Also, I modified portalocker's logger so that we can see `portalocker`'s internal behavior …
> Increase timeout of `mutex` to avoid `AlreadyLocked` errors with many concurrent processes

- requirements.txt
- spinalcordtoolbox/scripts/sct_check_dependencies.py
`matplotlib-inline` is an optional package that comes with `jupyter` for use with the '%matplotlib inline' directive. However, if a user runs `jupyter` from a separate environment and sets '%matplotlib inline', then SCT's environment will be missing this backend, and SCT scripts will crash when trying to import matplotlib.
So, we install `matplotlib-inline` in our env by default to ensure that SCT scripts can be run in Jupyter notebooks without error. (The package is very light, and only adds one small additional sub-dependency `traitlets`.)
Fixes #4523.
> Add `matplotlib-inline` backend for compatibility with Jupyter notebooks

- spinalcordtoolbox/types.py
This is a tiny refactor to simplify two lines of code in `types.py`, since I recently had to dig through this file for debugging.
The reason is that:
- `np.transpose` is generally a little confusing to the reader, so it's best to set up proper conventions up-front and avoid transposes if possible. (It's not always possible, though.)
- `np.einsum` is a powerful tool, but it's a bit hard to read. Let's not make it harder than it needs to be.
- `np.rollaxis` is massively confusing, so it's really best to avoid it.
And in the case of `np.einsum`, we have complete control over the ordering of axes for the inputs and the outputs, so we really can avoid transposes and rollaxes. (This is the equivalent of getting rid of double negatives: it makes things easier to read!)
> Simplify calls to `np.einsum`

- requirements.txt
Numpy just upgraded to 2.0.0 on Sunday, June 16th. Many of our dependencies are not yet ready for numpy==2.0.0, so we are forced to restrict `numpy<2` for now. (Numpy themselves also recommend this in their error message.)
```
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.
If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.
```
Partially addresses #4535. 
(We should probably keep the issue open as a reminder to periodically check whether `numpy==2.0.0` is …
> Restrict `numpy<2` to avoid upstream errors

- spinalcordtoolbox/scripts/sct_label_vertebrae.py
- spinalcordtoolbox/scripts/sct_register_to_template.py
- spinalcordtoolbox/scripts/sct_smooth_spinalcord.py
- testing/api/test_utils_fs.py
- testing/api/test_utils_shell.py
We recently fixed some bugs in the straightening code (see #4514), so we need to make sure that SCT doesn't re-use cached results from before the fix.
Fixes #4526.
> Include the SCT version in the straightening.cache

- spinalcordtoolbox/reports/qc.py
- spinalcordtoolbox/reports/qc2.py
They're locking the same thing, so they should use the same lock name.
* ~~It's not very useful to have `os.path.basename(path_qc)` in the name, since it will most likely just be `qc` for all reports, which is not informative.~~
* Using `os.path.realpath` instead of `os.path.abspath` (or nothing at all) will resolve any potential symlinks in the path, and return a "canonical" name for the qc report path.
* Also, `os.path.realpath` should align well with `pathlib.Path.resolve`, whereas `os.path.abspath` **doesn't** behave the same way as `pathlib.Path.abspath`: the former normalizes path components like `/./` and `/../`, but the latter keeps them unchanged.
Fixes #4539.
> Align the lock names for `qc.py` and `qc2.py`

- spinalcordtoolbox/scripts/sct_qc.py
This is a super minor PR adding an example for `-p sct_detect_pmj` to the `sct_qc` function.
Why? Because it was not clear whether `-p sct_detect_pmj` requires only `-s` or `-s` and `-d` flags; context: https://github.com/ivadomed/model-spinal-rootlets/pull/53/files#r1652958802.
Inspiration for the example: https://github.com/sct-pipeline/pmj-based-csa/blob/419ece49c81782f23405d89c7b4b15d8e03ed4bd/identify_nerve.sh#L65
> Add example command for `-p sct_detect_pmj`

- spinalcordtoolbox/scripts/sct_label_utils.py
This is a minor PR clarifying that `sct_label_utils -disc` does NOT involve the orthogonal projection of the discs onto the cord centerline. Instead, it just takes the slice corresponding to the disc. Context: https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3395#issuecomment-1478435265
We had a discussion about `sct_label_utils -disc` with @naga-karthik and @NathanMolinier and it was not intuitively clear whether the orthogonal projection is done or not.
> Clarify that `sct_label_utils -disc` does not involve orthogonal projection

- documentation/source/user_section/citing_sct.rst
Although the current URL works in the browser, every day it shows up as the only broken link in the link checker workflow. This ~~DOI~~ direct link should be more stable.
> Update redirected citation link

- requirements.txt
Given the comments in `requirements.txt`, it seems like 2.3.1 is the only safe version of `nnunetv2` we can rely on for now.
Action item for myself: 
Testing this is a bit tricky, because our test (on cropped input) still works fine on 2.4.2? The problem only reveals itself on a full test image. 
Maybe we could write a test similar to the mouse test, and stick the large image in the new testing dataset?
Fixes #4556.
> Avoid buggy version of `nnunetv2` that produces empty output predictions

- spinalcordtoolbox/reports/qc.py
Previously, we adjusted the canvas height by the image dimensions. However, for highly anisotropic images with thick axial slices, we also need to make sure to adjust by the pixel resolution. Otherwise, because there are so few axial slices, the canvas will get squished to a very small height.
Before:
After:
Fixes #4563.
> Adjust QC canvas size by physical resolution to avoid tiny QC with anisotropic T2* images

- spinalcordtoolbox/download.py
Fixes #4560 
This PR makes the latest T2w dog template (released here: "https://github.com/spinalcordtoolbox/template-dog/releases/tag/r20240709) downloadable using `sct_download_data`. Below are the steps to test this PR:
1. Download the template folder:
```
sct_download_data -d template-dog -o <OUTPUT_PATH>
```
2. Download data/test data from here: https://github.com/spinalcordtoolbox/template-dog#data
3. Run registration -- register `sub-HarshmanDobby` to the template:
```
sct_register_to_template -i sub-HarshmanDobby_T2w.nii.gz -s sub-HarshmanDobby_T2w_label-SC_seg.nii.gz -ldisc sub-HarshmanDobby_T2w_labels-disc.nii.gz -t <PATH_TO_DOWLOADED_TEMPLATE_FOLDER> -c t2 -s-template-id 2 -param step=1,type=seg,algo=centermassrot:step=2,type=im,algo=syn,metric=CC,iter=3 -ofolder HB_to_temp -qc …
```
> Added T2w dog template

- setup.cfg
With `pytest==8.3.1`, pytest will recursively search our `conda` environment unless we explicitly set `norecursedirs`.
Fixes #4570.
For upstream details, see:
- https://github.com/pytest-dev/pytest/issues/12652
> Set `norecursedirs` in `setup.cfg` to avoid pytest collecting tests from our dependencies within our `venv`

- spinalcordtoolbox/flattening.py
This is a very simple PR that restores the flattened image back to its original state to avoid user confusion.
I was uncertain whether to keep the scaled data as `float` or whether to convert back to original datatype (e.g. `int`). Converting back to `int` can cause some small rounding error (e.g. 350.6473 -> 351), but since this image is meant for visualization only, I figured that the rounding errors are not critical.
Fixes #3737.
> Rescale flattened values from `[-1.0, 1.0]` back to their original range and datatype

- spinalcordtoolbox/scripts/sct_dmri_moco.py
- spinalcordtoolbox/scripts/sct_fmri_moco.py
Proposed change:
with verbose=1:
```
Register. Loop across Z (note: there is only one Z if orientation is axial)
Z=0/0: 100%|██████████████████████████████████| 60/60 [01:22<00:00,  1.38s/iter]
```
with verbose=2:
```
Z=0/0:   0%|                                           | 0/60 [00:00<?, ?iter/s]Loaded /private/var/folders/5f/6n99hhyj5_g5cv_1bbx1q7cr0000gn/T/sct_2024-07-29_15-50-54_moco-wrapper_fo2omc73/datasub-groups_T0000.nii orientation RPI shape (96, 50, 25)
Loaded /private/var/folders/5f/6n99hhyj5_g5cv_1bbx1q7cr0000gn/T/sct_2024-07-29_15-50-54_moco-wrapper_fo2omc73/datasub-groups_T0000.nii orientation RPI shape (96, 50, 25)
/Users/julien/code/spinalcordtoolbox/bin/isct_antsSliceRegularizedRegistration --polydegree 0 --transform 'Translation[1]' --metric …
```
> Output ANTs syntax in moco functions for easier debugging

- spinalcordtoolbox/scripts/sct_maths.py
- testing/cli/test_cli_sct_maths.py
This PR adds a `-volumewise` argument to automate the steps described in issue #4181:
> 1. Run `sct_image -split t my-image.nii.gz` to generate a separate file for each 3D volume.
> 2. Run the actual `sct_maths` transformation in a bash loop over each file.
> 3. Run `sct_image -concat t my-image_t*.nii.gz` to recombine the 3D volumes into a single 4D file.
Instead, in this PR, we split the input data array, run the requested operations on each 3D volume, then recombine the data array.
Fixes #4181.
> Add `-volumewise` to process the individual 3D volumes of 4D input images

- spinalcordtoolbox/reports/qc.py
- spinalcordtoolbox/reports/qc2.py
- spinalcordtoolbox/reports/slice.py
- testing/api/test_reports.py
I'm not finished with porting the existing QC reports to the new structure, but I've completed a significant step, and it's coherent enough to be reviewed, so here's a pull request!
My approach is to erode away the old structure by inlining as many function calls as possible, especially when they're only ever called once.
I tried to make a separate commit for each logical change, but the last one was necessarily bigger.
Part of #4204.
> Refactor `qc.py` to use `create_qc_entry`

- spinalcordtoolbox/scripts/sct_analyze_lesion.py
This PR fixes the crashing of  `sct_analyze_lesion` if there is no midsagittal lesion; details in https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4594. 
Instead of crashing due to the `KeyError`, `sct_analyze_lesion` now prints:
```console
Minimum tissue bridges across all lesions for the midsagittal slice (sagittal slice 9)...
Minimum dorsal bridge width [mm]: nan
Minimum ventral bridge width [mm]: nan
WARNING: There are no tissue bridges in the midsagittal slice.
```
<details><summary>master</summary>
```console
valosek@macbook-pro:~/data/sci-olomouc/sub-001/anat$ sct_analyze_lesion -m sub-001_T2w_lesion.nii.gz -s sub-001_T2w_seg.nii.gz -qc qc
--
Spinal Cord Toolbox (git-master-75ef29d3960f0aa6c3fddce5f40f819d4d72753b)
sct_analyze_lesion -m sub-001_T2w_lesion.nii.gz -s …
```
> Fix crashing `sct_analyze_lesion` if there is no midsagittal lesion

- spinalcordtoolbox/scripts/sct_analyze_lesion.py
This was a tricky refactor, because `-perslice` goes against the default behavior of `sct_analyze_lesion` (aggregating by vertebral levels), and there are a lot of hardcoded `vert` variable names. It took quite a few changes of (vert -> row) to avoid a complete rewrite.
That said, big-picture "aggregating by vertebral levels" basically boils down to this:
- Iterate over vertebral levels.
- For each vertebral level, set all other voxels equal to 0, then compute percentages.
The general structure of this code still works if you substitute "vertebral level" for slice; You can instead iterate over slices and still set all other voxels equal to 0. To do this, I used "rows" to represent either vertebral levels *or* slices, and kept a separate variable "row_name" to track whether we have …
> Add `-perslice` option (plus performance improvements to make it feasible)

- spinalcordtoolbox/scripts/sct_analyze_lesion.py
As per https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4591#issuecomment-2271973627:
> But we are not explicit about whether we want a "view" (i.e. changes the original dataframe) or a "copy" (independent of the original dataframe). Because we are not explicit, there is potential ambiguity, hence why pandas throws this warning. To fix this warning, we just need to be explicit about what we want, and there are multiple ways to do this (not just `.loc`).
I think in this case, because we only ever access the newly-added columns from df_temp and not from the original `tissue_bridges_df` DataFrame, we don't need a "view", and so I think it should be fine to denote df_temp as a copy:
Fixes #4591.
> Silence `pandas` warning by explicitly using `copy` to remove view/copy ambiguity

- spinalcordtoolbox/scripts/sct_analyze_lesion.py
This PR amends two methods responsible for computing the distribution of a lesion within a warped atlas (i.e. the `-f` option of `sct_analyze_lesion`):
- `_measure_eachLesion_distribution`: Responsible for the `lesion#Ndistribution` pages in the sheet. The values are "percentage of the lesion that exists in a given ROI". Since the CombinedLabels are just combined ROIs, we can simply sum the percentages.
- `_measure_totLesion_distribution`: Responsible for the `ROI_occupied_by_lesion` page in the sheet. The values are "percentage of the ROI taken up by _any_ lesion". This is a bit trickier, since the ROI area is in the denominator (rather than the numerator). Thankfully, it turns out that this functionality was already implemented! 
- Before: Hardcoded "combined labels" that are identical …
> Support `CombinedLabels` from `info_label.txt` when computing lesion distributions with `-f`

- install_sct
- install_sct.bat
Pip has started throwing a deprecation warning for `setup.py develop` behavior that gets invoked when we run `pip install -e .`. From what I can tell, though, the upcoming change in `pip==25.0` is mainly a backend change that will be largely invisible.
Since the core Python part (`spinalcordtoolbox`) is a very straightforward package, with no C++ extensions or other complicated build requirements, I think that the switch from `setup.py develop` to the new wheel-building behavior should have no effect. And in fact, it's probably fine to leave `pip install -e .` as-is and let the upgrade to `pip==25.0` happen silently in the background (meaning that I don't think this PR is urgent?). But, I'm seeking clarity on this here: https://github.com/pypa/pip/issues/11457#issuecomment-2276205988
But, …
> Add `--use-pep517` to install scripts to silence warning

- spinalcordtoolbox/image.py
- spinalcordtoolbox/reports/qc2.py
- spinalcordtoolbox/scripts/sct_analyze_lesion.py
Just a first prototype to solve https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4592
<details><summary>master</summary>
</details>
<details><summary>this branch</summary>
Notice that the slice numbers now correspond to the original image orientation (and not to RPI used by `sct_analyze_lesion`).
</details>
```console
cd sci-zurich/derivatives/labels/sub-zh102/ses-01/anat
sct_analyze_lesion.py -m sub-zh102_ses-01_acq-sag_T2w_lesion-manual.nii.gz -s sub-zh102_ses-01_acq-sag_T2w_seg-manual.nii.gz -qc qc
```
Resolves https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4592
> Fix slice numbering in `sct_analyze_lesion` QC and CLI output

- spinalcordtoolbox/scripts/sct_apply_transfo.py
In SCT CLI scripts, it is very common to want to apply a warping field to an image mid-processing (e.g. during registration, motion correction, etc.). SCT has a separate CLI script for this (`sct_apply_transfo`), which means that we're often calling one CLI script from another CLI script. 
In every single case of this, the sub-call specifies `-v 0` (to silence the logging messages, presumably because the intermediate output would be confusing/distracting from the "main" processing). However, this verbose status is not actually propagated to the call from `sct_apply_transfo` (the SCT wrapper script) to `antsApplyTransfo` (the ANTs binary that does the actual warping).
This means that, for scripts such as MOCO that apply warping fields repeatedly to a 4D image, we get a lot of noisy output …
> Properly maintain verbose status for internal ANTs `run_proc` call (to silence logging for `-v 0`)

- testing/cli/test_cli.py
The problem described in #4515 turned out to not be a "one in a blue moon" kind of slowdown. I'd figure it's more a 50/50 chance to get a slow macOS runner, and so I've been having to repeatedly restart the cron jobs to ensure passing runs.
We could go with a fancier solution (checking the runner hardware, having a different "passing" time for macOS, etc.) but given that our other platforms (Ubuntu, Windows) have _never_ failed this check, I think it should be OK to rely on them as a signal for whether a PR is adding a slow import.
Fixes #4515.
> Skip `-h` duration test on macOS CI runners due to sporadic runtimes

- spinalcordtoolbox/aggregate_slicewise.py
In #4552, @jcohenadad tried extracting metrics from a user's data, but the template/atlas files were empty. This meant that the specified vertlevels had no corresponding slices, and thus no metrics could be extracted.
We already have a conditional for when this occurs:
https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/a7a3f8dd021b6b7f8d2b9fa2680002ed4b1c5f2c/spinalcordtoolbox/aggregate_slicewise.py#L321-L325
Yet, we don't provide any feedback to the user when this happening. Even worse, when _all_ of the slicegroups are empty, the `save_as_csv` function fails in an ugly way.
So, this PR ensures that warnings are thrown + no crash occurs, making it easier for the user to debug their own data:
Fixes #4552.
> Add more intuitive feedback when no metrics can be extracted from input data

- .github/workflows/check-url.sh
Our "broken link checker" CI workflow started failing a few days ago due to the Radiopaedia.org domain. The links open fine in browser, but they can't be fetched by curl/wget. I also tried using https://http.app/, but got the same error.
I spent an hour or so deep-diving into the error code, but I couldn't identify the source of the error, so my best guess is that this is a configuration issue in Radiopaedia.org's CloudFlare settings, or an attempt to stop crawlers from scraping Radiopaedia's articles (due to recent LLM controversies re: ignoring `robots.txt`).
We could have also filtered the Radiopaedia domain (as we had done in the past with other domains), but due to the limited scope of the 406 error code, I figure that filtering it would allow us to continue checking Radiopaedia for …
> Allow error code 406 in broken link checker

- spinalcordtoolbox/scripts/sct_get_centerline.py
- testing/cli/test_cli_sct_get_centerline.py
For sample T2* data...
`pix`:
`phys`:
> [!NOTE]
> The affine for the test `t2s.nii.gz` has non-diagonal values (i.e. rotation), hence the different `phys` coordinates for the same `x` `pix` coordinates.
> 
> ![image](https://github.com/user-attachments/assets/88764b6f-e25f-408a-b1d1-c812ca01e3c3)
Fixes #4619.
> Expose `space` API parameter in centerline CLI to allow user to specify `-space phys`

- .github/workflows/check-code-quality.yml
- .github/workflows/check-url.sh
curl was returning error code 429 when testing arxiv links. Initially, I thought to retry requests with a delay, but on further investigation, I found that we were missing `-I`/`--head` (i.e. a HEAD request), meaning we were fetching the full text when we checked for broken links. D:
To fix this, I've made sure we use a standard set of args for all of our curl requests. 
Still, I wanted to keep the retry arguments, since curl implements them in a respectful way (https://github.com/curl/curl/commit/640b9733de74d629af68afcad0ff8bb658e80eff), and this may help to avoid noise from one-off network issues.
Fixes #4648
> Be good netizens when checking broken links (HEAD request only, 30s retries, respect `Retry-All`)

- README.rst
- spinalcordtoolbox/scripts/sct_extract_metric.py
- spinalcordtoolbox/scripts/sct_register_to_template.py
The broken link checker caught these!
SCT's RTD config is _not_ set to the "Multiple versions with translations" option, because we don't have any non-English translations.
Because of this, the presence of `/en/` breaks our URLs, and so we rely on a custom redirect just to keep these links alive. 
However, just for future-proofing, it would be better to just use our "base" url, then let RTD's built-in redirects do their magic (i.e. to stable instead of latest). This way, when we change from having "latest" as our default to "stable" (like we've just done recently), the links update appropriately without needing to change the actual slugs.
(Note: Most of the URLs in our project are the "base" urls, but a few had `/en/latest/`, so this PR unifies our docs.)
N/A
> Remove `/en/latest/` slugs from `spinalcordtoolbox.com` URLs

- .github/workflows/check-url.sh
- documentation/source/overview/concepts/inspecting-results-qc-fsleyes.rst
- documentation/source/overview/concepts/spaces-and-coordinates.rst
- documentation/source/overview/concepts/warping-fields.rst
- documentation/source/user_section/fsleyes.rst
- spinalcordtoolbox/scripts/sct_apply_transfo.py
- spinalcordtoolbox/scripts/sct_concat_transfo.py
This PR is meant to handle the broken links from the latest CI run: https://github.com/spinalcordtoolbox/spinalcordtoolbox/actions/runs/11477585088/job/31939986634
- The `nifti1.h` link is more of an intermittent network issue; the link [does pass](https://github.com/spinalcordtoolbox/spinalcordtoolbox/actions/runs/11477585088/job/31939986634#step:3:988) in other checks. So, I think we may need to be a little more aggressive with our retries. (570f2ca55fd25a92250eeff776f00eba9625fdd1)
- The FSL links are due to the change from the old FSLWiki to the new docs. No links were preserved, so we need to either update them to their new docs where applicable, or use the Wayback Machine when there is no analog. (FSL also provides https://fsl.fmrib.ox.ac.uk/fsl/oldwiki/, but all of the page links …
> Handle newly-broken links (retries, FSLWiki changes)

- spinalcordtoolbox/scripts/sct_maths.py
- testing/cli/test_cli_sct_maths.py
We can't use in-place operators (like `+=`, `*=`) on numpy arrays for operations that would need to promote the array's dtype (for example, integer += float needs to be stored as float, but the existing array can only store integer).
I added a test which fails with "Cannot cast ufunc output dtype" on `master`, and passes with the fix in this branch.
Fixes #4652.
> Fix dtype mismatch error when mixing integers and floating point numbers

- spinalcordtoolbox/deepseg/inference.py
- spinalcordtoolbox/deepseg/models.py
- spinalcordtoolbox/deepseg/monai.py
This PR aims to update the `contrast-agnostic` MONAI model to v2.5. This model should work well on SCI images and whole-spine T1w/T2w images in addition to previous pathologies and contrasts. 
The model architecture (specifically, the number of features in the network) was updated between v2.4 and v2.5 to account for the increasing size of the training dataset. Accordingly, the code has been slightly updated to set the correct number of maximum features in the network when this model is chosen. 
1. Check out to the branch `nk/update-contrast-agnostic-to-v2.5`
3. Run `sct_deepseg -task seg_sc_contrast_agnostic -i <path-to-the-image>.nii.gz` to segment an image (this should automatically download the latest version replacing the existing one)
> Update contrast agnostic model to r20241024 (improved for SCI and whole-spine T1/T2 images)

- spinalcordtoolbox/deepseg/inference.py
This PR:
- Changes the suffix for the rootlets model to `_rootlets` (so that it won't overwrite other files named e.g. `t2_seg.nii.gz`)
- Deduplicates the image saving code inside `segment_nnunet`
Fixes #4662.
> Fix the suffix of the rootlets model (`_seg` -> `_rootlets`) to prevent overwriting

- .github/workflows/create-release.yml
- .github/workflows/test-batch-processing.yml
- .github/workflows/tests.yml
The macOS 12 image is in the process of being removed from github actions: https://github.com/actions/runner-images/issues/10721
For reference, the last time we bumped the macOS version was in #4353.
As an aside, I wonder whether we should update our uses of `macos-14` to `macos-latest`, so that we automatically pick up new versions when they appear. (Whereas I think it's reasonable to need an explicit action on our part to drop old versions when they disappear. And besides, [there's no convenient label like `macos-oldest`](https://github.com/actions/runner-images).)
> Bump oldest macOS version used by test runners (12 -> 13)

- spinalcordtoolbox/scripts/sct_deepseg.py
This tiny PR updates the `sct_deepseg` `-custom-url` argument help by adding example commands.
The PR addressed the second part of https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4654#issue-2602302169.
> Add example commands for the `-custom-url` arg

- requirements.txt
This incompatibility is blocking tests of in-progress PRs, and there is no timeline for when this bug will be fixed upstream.
Fixes #4679.
> Skip `acvl_utils==0.2.1` due to buggy interaction with `nnunetv2`

- documentation/source/user_section/command-line/deepseg/seg_exvivo_gm_wm_t2.rst
- documentation/source/user_section/command-line/deepseg/seg_gm_sc_7t_t2star.rst
- documentation/source/user_section/command-line/deepseg/seg_lumbar_sc_t2w.rst
- documentation/source/user_section/command-line/deepseg/seg_mice_gm.rst
- documentation/source/user_section/command-line/deepseg/seg_mice_sc.rst
- documentation/source/user_section/command-line/deepseg/seg_mouse_gm_wm_t1w.rst
- documentation/source/user_section/command-line/deepseg/seg_ms_lesion_mp2rage.rst
- documentation/source/user_section/command-line/deepseg/seg_ms_sc_mp2rage.rst
- documentation/source/user_section/command-line/deepseg/seg_sc_contrast_agnostic.rst
- documentation/source/user_section/command-line/deepseg/seg_sc_epi.rst
- documentation/source/user_section/command-line/deepseg/seg_sc_lesion_t2w_sci.rst
- documentation/source/user_section/command-line/deepseg/seg_sc_ms_lesion_stir_psir.rst
- documentation/source/user_section/command-line/deepseg/seg_spinal_rootlets_t2w.rst
- documentation/source/user_section/command-line/deepseg/seg_tumor_edema_cavity_t1_t2.rst
- documentation/source/user_section/command-line/deepseg/seg_tumor_t2.rst
- documentation/source/user_section/command-line/sct_deepseg.rst
This PR is roughly equivalent to half of PR https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/4630. It is meant to grant us the benefits of the `sct_deepseg` model gallery right away (for v6.5), while also allowing us to update the gallery when we adopt `sct_deepseg` subparsers for v7.0.
This PR contains no functional changes; only documentation changes. Therefore, it should be safe to merge right away, especially with our recent change to only update the documentation for stable releases.
Note: One new change I added that differs from PR #4630 was switching from a 4-column table to a 3-column table to accommodate the longer task names:
Perhaps this is too large, though? Feedback is appreciated!
Fixes #3767.
> Add model gallery for current version of DeepSeg (`-task` syntax)

- spinalcordtoolbox/scripts/sct_apply_transfo.py
- testing/cli/test_cli_sct_apply_transfo.py
This will preserve integer images when `-x nn` is used (which I've explicitly referenced in my test).
Fixes #4572.
> Preserve integer dtype when warping an image using `NearestNeighbour` interpolation

- requirements.txt
Previously, we encountered a bug with `nnunetv2==2.4.2` where an empty segmentation would be produced by our SCI model. We temporarily limited `nnunetv2==2.3.1`, since that was seemingly the only version that worked for us. See:
- https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/4564
However, there is a newer version of `nnunetv2` (`2.5.1`) that seems to fix the "empty segmentation" problem. 
Note that TotalSpineSeg is incompatible with 2.5.1, so we're probably going to revert back to 2.3.1 immediately. But, this PR will prepare for an eventual 2.5.2 release that will finally work for both SCT and TotalSpineSeg.
Fixes #4556.
> Allow `nnunetv2>=2.5.1` due to bugfix for previous issue with `2.4.2`

- spinalcordtoolbox/math.py
- spinalcordtoolbox/scripts/sct_apply_transfo.py
- spinalcordtoolbox/scripts/sct_label_vertebrae.py
- spinalcordtoolbox/vertebrae/core.py
- testing/api/test_math.py
Since 99.99% of voxels are 0 when `islabel=True`, we don't *need* to run dilation on every single voxel, which is what skimage will do by default. Instead, we can fetch the nonzero voxels, extract an area the size of the footprint, run dilation on that area, and then put it back.
I was concerned that this might behave differently in cases where we have two labels very close together. But, I think it ends up working identically, with the larger label dominating the smaller label (thanks to the use of `maximum` internally).
There's an even faster approach (just multiplying `footprint` by the label value, then setting the area centered on the nonzero voxel equal to this). I've implemented that as well in a follow-up approach.
On my (fast) laptop, dilation time for a typical image went from …
> Use faster dilation algorithm when dilating "mostly zero" point label images (`-x label`)

- spinalcordtoolbox/download.py
This is mostly just a placeholder URL. While a dataset using this name will exist (https://github.com/spinalcordtoolbox/sct_tutorial_data/actions/runs/11958727027), I suspect that we will end up updating the `sct_tutorial_data` repo as we modify the course slides in the coming weeks.
Thankfully, as long as we update the tag `SCT-Course-20241209`, the command `sct_download_data -d sct_course_data` will always stay up to date, and thus we can safely use this command in the SCT Course slides.
Fixes #4703.
> Update `sct_course_data` URL to point to `SCT-Course-20241209`

- documentation/source/user_section/command-line/sct_deepseg.rst
- spinalcordtoolbox/deepseg/models.py
- spinalcordtoolbox/scripts/sct_deepseg.py
This PR adds a new section to the Model Gallery for "Retired models", moves 2 models into this section, and deletes them from the `sct_deepseg` and `models.py` scripts.
Fixes #4700.
> Retire outdated DeepSeg models (`seg_sc_ms_lesion_stir_psir`, `ms_sc_mp2rage`)

- spinalcordtoolbox/scripts/sct_check_dependencies.py
We can no longer rely on `module` to filter this warning due to an upstream addition of `stacklevel=2`. So, we must instead filter based on message, rather than module.
Before:
After:
Fixes #4712.
> Update warnings filter to properly filter `Private repos` warning from `requirements.parse`

- spinalcordtoolbox/reports/qc2.py
Typically, for our QC functions, anisotropic images (i.e. images with resolutions that are not equal for all three x/y/z axes) don't really cause any issues when plotting axial mosaics. This is because typically we will [resample the images to an isotropic resolution](https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/89b1ffcbc649cb0f90573cb37aa378f1a3cd3b08/spinalcordtoolbox/reports/qc2.py#L316-L323), which allows us to proceed under the assumption that the slicewise X/Y resolutions are equal.
However, for the rootlets QC, we skip this resampling step and instead modify the crop radius to fit the native resolution of the data. This helps to preserve the thin, often 1-voxel wide rootlets labels when displaying them in the QC report. (See 4c0c1f4180883d800036a11054f237609095d12b …
> Fix rootlets QC for anisotropic images

- spinalcordtoolbox/scripts/sct_maths.py
- testing/cli/test_cli_sct_maths.py
Numpy arithmetic can be tricky, because subtractions using unsigned integers can result in wraparound to huge positive values. Also, divisions of integer arrays default to `float64`, which may be unnecessarily big.
Rather than relying on these defaults, we should be careful about the expected dtype of arithmetic operations in `sct_maths`. (For uniformity, I also updated the code for addition and multiplication, so that all arithmetic uses the same pattern.)
Fixes #4725.
(I can add a test case on Monday if @joshuacwnewton doesn't beat me to it :wink: but I wanted to get this PR open asap.)
> Make sure subtractions are signed and divisions are floating point

- spinalcordtoolbox/reports/qc2.py
In PR https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/4722, I fixed some issues that affected anisotropic QC reports that we had been blind to for isotropic images (i.e. the case where `radius[0] == radius[1]`). 
One of those changes swapped the x/y coordinates for orientation labels, because numpy arrays use "zyx" axis ordering, thus radius[0] corresponds to y and radius[1] corresponds to x.
However, in doing so, I not only swapped radius[0]/radius[1], but I also swapped the _axis-specific offsets_, causing the orientation labels to be misplaced. To fix this, I need to just swap radii.
Before (isotropic):
After (isotropic):
After (anisotropic):
Fixes https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4734.
> Fix orientation labels by properly swapping x/y radii rather than x/y coords

- spinalcordtoolbox/scripts/sct_apply_transfo.py
Since we're intentionally changing the datatype here, we can also safely change the header datatype (to avoid warnings about the header dtype not being int).
This makes `sct_warp_template` a lot less noisy, with almost all of the warnings coming from uint8 images in the template.
Fixes #4738.
> Set header datatype when applying dtype fix for NearestNeighbours interpolation to avoid warnings in log

- spinalcordtoolbox/reports/qc2.py
Thresholding is done by default (**AFTER** resampling w/linear interpolation) for all segmentations in the old `qc.py` QC:
https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/4868a2cdd79a7109bce1de8747f52cbed9d18b0f/spinalcordtoolbox/reports/slice.py#L174-L183
We remembered to add a simplified version of this thresholding step (that always performs binarization) when we converted the `sct_register_multimodal` QC from `qc.py` to `qc2.py`:
https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/f72607f22cdf1debc4e8da148f3827cbfd941667/spinalcordtoolbox/reports/qc2.py#L199-L205
However, we forgot to add this same step in the `sct_deepseg` QC reports. So, I've added it to both the axial and sagittal mosaic QCs:
Before:
After:
Note that this isn't relevant for …
> Add missing binarization+thresholding step for segmentations in `sct_deepseg` QC

- spinalcordtoolbox/deepseg/monai.py
This is a quick temporary fix (to be backported to v6.5) to address the issue of `num_workers` being greater than the `cpu_count()`.
A more complex fix would be to add a flag to control this value, to be discussed for v7.0.
Fixes https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4750.
> Remove hardcoded `num_workers=8` and replace with `cpu_count()`-based value

- spinalcordtoolbox/reports/qc2.py
I haven't had time to test it yet, but here's a reasonably efficient algorithm for drawing a black outline around multi-valued segmentations in QC reports. (The previous algorithm only handled binary segmentations.)
This should fix #4704.
I imagine it won't get merged into SCTv6.5, so it's really not urgent.
> Implement QC outlines for multi-valued segmentations

- documentation/source/user_section/command-line.rst
- documentation/source/user_section/tutorials/segmentation/sct_deepseg.rst
- spinalcordtoolbox/scripts/sct_deepseg.py
This minor PR updates `sct_deepseg` documentation and arg help to make clear that it also supports other than ivadomed models.
Resolves: #4762
> Update `sct_deepseg` documentation and arg help

- documentation/source/user_section/command-line.rst
- documentation/source/user_section/command-line/all_tools.rst
- documentation/source/user_section/command-line/index/segmentation-analysis.rst
- documentation/source/user_section/command-line/sct_detect_compression.rst
- setup.py
- spinalcordtoolbox/scripts/sct_detect_compression.py
- testing/cli/test_cli_sct_detect_compression.py
This PR adds a script to predict compression probability in a spinal cord MRI image using spinal cord shape metrics. The script requires spinal cord segmentation (used to compute the shape metrics) and disc labels.
Briefly, the script computes shape metrics for 3 axial slices at intervertebral disc levels C3/C4 to C6/7 (3 slices are used to compensate for potential disc label shift in the superior-inferior (S-I) axis; details: https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/4760#discussion_r1903118334 and https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/4760/commits/90cbfa6654154987b0f542a6b544505fcaf8f076). Then, it predicts compression probability for each of these axial slices using a logistic regression model. The compression probability is printed to CLI and …
> Add new CLI script to predict compression probability

- .github/workflows/create-release.yml
- requirements.txt
This commit is a follow-up to the previous fix of pinning `torch<2.6` (#4776).
The `grep -v torch` line is preventing the `torch<2.6` fix from being propagated to the `requirements-freeze.txt` file, causing the Create Release nightly workflow to fail (https://github.com/spinalcordtoolbox/spinalcordtoolbox/actions/runs/13050987631).
The `grep -v torch` line was originally added nearly 4 years ago in https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/3383. At that time, the state of the repository included several platform-specific frozen requirements that we wanted to explicitly copy over, so that we would override the actually-installed version of torch:
https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/634670e4e0e282d27abaf457def5feb49da9a1f6/requirements.txt#L33-L36 …
> Ensure that `torch<2.6` requirement gets copied over to `requirements-freeze.txt`

- requirements.txt
Intel Macs are only supported up until v2.2.2. Meaning, non-ARM runners are installing 2.2.2, and all other platforms are installing 2.5.1/2.6.0.
To keep our platforms in sync, I've added another restriction beyond `2.6`. (Apologies for the repeated PRs for the same dependency; this issue was only discovered during the investigation into the first issue.)
Partially fixes #4781, though we may also wish to backport this fix to v6.2-6.5, which are also affected.
> Pin `torch` to `<2.3` to keep versions in sync with Intel Mac platforms

- spinalcordtoolbox/utils/sys.py
As discussed in https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4655#issuecomment-2430178901, we install `msvc-runtime` on Windows to avoid missing DLL errors. However, we completely missed that subprocesses can't see these DLLs, meaning ANTs binaries will fail if these DLLs aren't present via other means.
We've subtly disguised this missing DLL error by asking users to [install the necessary dependency themselves](https://spinalcordtoolbox.com/stable/user_section/installation/windows.html#visual-c-2019-runtime). However, for workstations with limited installation privileges, this may not be possible. And, this second dependency installation is largely redundant with our own installation of `msvc-runtime`, anyway. 
Since we already have the necessary DLLs in the Scripts …
> Allow ANTs binaries to access `msvc-runtime` DLLs to avoid DLL not found errors

- spinalcordtoolbox/deepseg/models.py
- spinalcordtoolbox/scripts/sct_deepseg.py
- testing/cli/test_sct_deepseg.py
This PR aims to update the `contrast-agnostic` model to the nnunet based one (which was monai-based until now). Experiments showed that the nnunet model was more robust across difficult subjects than the current monai-based model. It also fixed issues we were having with shifted predictions on a few test cases, and works _much more_ better on compressed cord and whole-spine images.  
Notable change is that I set the `keep_largest` argument as the default for this model as we have seen some cases where the model was predicting a few pixels outside the cord (quite rarely though). 
1. Check out to the branch `nk/update-contrast-agnostic-to-v3.1`
2. Run `sct_deepseg -install-task seg_sc_contrast_agnostic`
3. Run `sct_deepseg -task seg_sc_contrast_agnostic -i <path-to-the-image>.nii.gz` on …
> Replace monai-based contrast agnostic model to nnunet-based r20250204 release

- documentation/source/user_section/courses.rst
This PR updates the documentation with the newest links to the material and YouTube video (needed to send out final SCT Course email).
Now that our documentation links to the latest "stable" release, this change won't go live immediately. Meaning, we will need to backport this for it to go live.
We could update the 6.5 tag, but this would require remaking the release and etc. But because `stable` triggers for the most recent tag, it's possible to create a secondary tag just for backported documentation changes. Something as simple as `6.5.docs` would cause `stable` to update while leaving `6.5` itself unchanged.
Partially addresses #4749.
> Update `courses.rst` with SCT Course 2024 links

- .github/workflows/test-past-releases.yml
This PR is part of the plan to backport fixes to the 5.x and 6.x series of SCT releases. We've already tested the fixes as part of the workflow using the `perl` find and replace fix. But, now we're going to actually put those changes into the branches themselves.
I've created some temporary "-bp" ("backport") branches based off of their corresponding tag,  that will contain the fixes and allow us to briefly test them before making any modifications to the tags themselves. Once we confirm that the fixes work in this new context, we can update the tags (and the releases), and revert this PR back to testing the tags.
Fixes #4777. 
Fixes #4696. (When tags are updated.)
Fixes #4670. (When tags are updated.)
> Port "past release" fixes to the tags themselves, and remove them from the GHA workflow

- spinalcordtoolbox/deepseg/inference.py
When the contrast-agnostic model was changed from MONAI to nnUNet, the method for determining the output suffix also changed, thus the output switched from `_seg.nii.gz` to `_sc_seg.nii.gz`. I think adding the "sc" part makes sense for multiclass models (SC/lesion, SC/GM, etc.). But, for our single-class SC tools (`sct_deepseg_sc`, `sct_propseg`, etc.) we typically just output `_seg.nii.gz`. 
So, this PR adds a special case to check for single-output SC models, then choose the "basic" suffix accordingly.
This PR is being tested in https://github.com/spinalcordtoolbox/sct_tutorial_data/pull/27/files#r1985521419, because that PR is getting blocked by this issue (SCT course was written for `_seg.nii.gz suffix`).
Fixes #4805.
Needed for …
> Preserve the `_seg` suffix for the contrast-agnostic model

- spinalcordtoolbox/resampling.py
In #4773, we encountered a confusing error when trying to resample an image with a small amount of slices to begin with. Luckily, we're already catching the error and adding our own message -- we just need to tweak the wording a bit.
Before:
```python
File "/home/joshua/repos/spinalcordtoolbox/spinalcordtoolbox/resampling.py", line 107, in resample_nib
R[i, i] = img.shape[i] / float(shape_r[i])
ZeroDivisionError: float division by zero
During handling of the above exception, another exception occurred:
File "/home/joshua/repos/spinalcordtoolbox/spinalcordtoolbox/scripts/sct_resample.py", line 162, in <module>
File "/home/joshua/repos/spinalcordtoolbox/spinalcordtoolbox/scripts/sct_resample.py", line …
```
> Improve clarity of `ZeroDivisionError` message when resampling

- spinalcordtoolbox/utils/profiling.py
- testing/api/test_utils_profiling.py
This adds automated testing to the time-based profiling utilities added in #4825. Now we'll know if something broke before it errors out during a live run!
**NOTE:** The reason this is a separate PR from the "main" addition is due to way the profiling works (running a command when the program terminates) requiring additional investigation into how to work with PyTest (which, obviously, could not test anything after it was terminated)
N/A
> Added automated testing for new profiling utilities

- spinalcordtoolbox/utils/profiling.py
- spinalcordtoolbox/utils/shell.py
- spinalcordtoolbox/utils/sys.py
- testing/api/test_centerline.py
- testing/api/test_qmri.py
- testing/api/test_utils_profiling.py
- testing/conftest.py
As requested by @sandrinebedard, made the functionality bound to the `-timeit` flag universal and applied to all SCT commands by default. Cheers!
N/A, based on internal feedback
> Remove opt-in `-timeit` flag in favor of running a timer by default 

- documentation/source/user_section/command-line/deepseg/sc_t2star.rst
- documentation/source/user_section/command-line/sct_deepseg.rst
- spinalcordtoolbox/deepseg/models.py
- testing/cli/test_sct_deepseg.py
As discussed in the recent SCT developer meeting, the `sc_t2star` model has been rendered obsolete by the addition of the `spinalcord` contrast-agnostic model and `sc_epi` EPI-BOLD fMRI model. This PR implements that decision into SCT formally.
Resolved #4800
> Retire the model `sc_t2star` from `sct_deepseg` (and move its model gallery entry)

- spinalcordtoolbox/deepseg/models.py
This minor PR updates the model url to point to the latest release of the contrast-agnostic model. Previous SCT PRs failing because of the tag not being found, should be resolved now! 
The full history is as follows:
- #4783 (v2.5 -> v3.1)
- https://github.com/spinalcordtoolbox/spinalcordtoolbox/commit/83422ffeb484cff57239b15dd49343eca23090ea (Emergency hotfix, v3.1 -> v2.5, due to deletion of v3.1)
- https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/4843 (v2.5 -> v3.0)
> Update contrast-agnostic model from v2.5 to v3.0 

- spinalcordtoolbox/process_seg.py
Fixes #4807.
If the input mask supplied in `-i` and the custom centerline supplied in `-angle-corr-centerline` did not start at the same lowest SI slice, then the wrong slice index was used for angle correction.
With the proposed code, everything is indexed directly with SI slice numbers, rather than trying to do relative indexing. A quick manual test using the data from #4807 shows that this fixes the problem: for the slices which appear in both CSVs, they have the same `angle_AP` and `angle_RL`.
If the `-angle-corr-centerline` is too short, there's now an error message to explain the situation:
> Fix slice indexing for `-angle-corr-centerline`

- .gitignore
- spinalcordtoolbox/scripts/sct_compute_snr.py
- spinalcordtoolbox/utils/profiling.py
- spinalcordtoolbox/utils/shell.py
- testing/api/test_utils_profiling.py
As discussed in #4795, we've been meaning to add methods of empirically evaluated SCT's runtime performance for a while. This PR adds two new faculties to accomplish this implicitly:
When activated through the command-line (by adding the `-profile-time` argument), the total runtime inside each call made in the program is tracked. Once the program terminates, the total results are placed in an output file for later review. By default, this file is named `time_profiler_results.txt`, but the user can provide an alternative path after the argument if they wish to save it elsewhere.
When activated through the command-line (by adding the `-trace-memory` argument), memory tracing functionality is activated. This does two things by default:
1. The ability to "snapshot" the memory state of the …
> Add detailed time and memory profiling for CLI scripts

- spinalcordtoolbox/download.py
This PR integrates the following upstream changes into SCT:
- https://github.com/spinalcordtoolbox/PAM50/pull/34
PR https://github.com/spinalcordtoolbox/PAM50/pull/35 was planned for v7.0 as well, however the changes became more complex and nature, and require better testing before we can feel comfortable integrating them into SCT.
N/A
> Update PAM50 release links to `r20250422` (ventral rootlets, Th1 level)

- requirements.txt
- spinalcordtoolbox/scripts/sct_check_dependencies.py
- `onnx` recently released version `1.18.0`, which breaks when imported by `monai` on Windows.
- However, versions `1.16.2` and `1.17.0` also had buggy behavior on Windows, but `1.17.0` kind of worked (as long as SCT itself never imported it), so it's been fine for a while now.
- Given the circumstances, though, I think now is a good time to also avoid these buggy versions, too.
Additional context: https://github.com/onnx/onnx/issues/6267#issuecomment-2877327002
Fixes #4900.
> Limit `onnx<1.16.2` to fix CI failures on Windows runners (Python 3.9)

- spinalcordtoolbox/scripts/sct_straighten_spinalcord.py
- spinalcordtoolbox/utils/shell.py
- spinalcordtoolbox/utils/sys.py
We don't need it anymore, since we're on Python 3.9 (soon, 3.10!)
(Noticed while reviewing #4869.)
> Retire our obsolete shim for `str.removesuffix`

- .github/workflows/check-broken-links.yml
- .github/workflows/check-url.sh
Because of the rise of AI/LLM web scrapers, more and more sites are forbidding access to automated checks. It's quite tedious to manually blacklist each site every time this happens. Sure, there's a small chance that we could manually find an alternate URL for a 403'ing URL. But, for most cases, if a site is giving us 403 Forbidden, there's not much we'll be able to do.
In theory, we could set up a system where we continue to blacklist domains, but manually check the URLs once they get blacklisted (so we at least know which domains to manually test). But, I fear that this is a lot of effort for a relatively minor nuisance. So, I'm content to just filter out 403 domains for now?
Fixes #4897.
> Add a blanket exclusion for `403 - Forbidden` responses to our broken link checker

- .github/workflows/check-code-quality.yml
- testing/conftest.py
In https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/4759, I added a highly sensitive test for `batch_processing.sh` that outputs warnings whenever file properties differ between `master` and PRs.
Because the test checks against filesize and md5 hashes, any sort of branch-specific metadata will throw false-positives. We already encountered this with output `.csv` files that report the SCT version (fixed in #4803), but we didn't catch the output `.json` sidecar files that also report the SCT version.
So, this PR mimics our CSV filtering to also filter JSON sidecar files, which should eliminate the remaining 12 false positives currently reported in PR warnings. From now on, if there are warnings on PRs, it will actually mean something. :)
Fixes #4886.
> Filter out `Version` and `CodeURL` when diffing JSON sidecars

- spinalcordtoolbox/labels.py
- spinalcordtoolbox/reports/qc.py
- spinalcordtoolbox/scripts/sct_label_utils.py
- spinalcordtoolbox/scripts/sct_label_vertebrae.py
- testing/api/test_labels.py
- testing/cli/test_cli_sct_label_vertebrae.py
This PR:
- removes the straightening step from `sct_label_vertebrae` when using the flag `-discfile`
- removes `sct_label_utils -disc` because it is a duplication of the new `sct_label_vertebrae`
Now when calling `sct_label_vertebrae` with the flag `-discfile`:
- Discs are [projected](https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/6c2c6b4d879f27516b9b1bdd2d10a777d38208bb/spinalcordtoolbox/scripts/sct_label_vertebrae.py#L299) onto the spinal cord
- The segmentation is labeled by projecting individual voxels onto the centerline and comparing their z coordinate with the z coordinate of projected discs.
How to use:
```bash
sct_label_vertebrae -i ${file}.nii.gz -s ${file_seg}.nii.gz -discfile ${FILELABEL}.nii.gz -c ${contrast}
```
See the new result below:
Fixes …
> Update `sct_label_vertebrae -discfile` by removing straightening

- spinalcordtoolbox/scripts/sct_register_to_template.py
The presence of label `60` in the template was preventing this check from raising an error for any labels between 22 and 60 (e.g. a user had labels 22-25, which should have raised an error, but didn't).
Before: [Script would run until it hit an unrelated error]
After:
Fixes #4872.
> Fix check for user's labels against template's labels by adopting `issubset` 

- spinalcordtoolbox/registration/core.py
- spinalcordtoolbox/scripts/sct_apply_transfo.py
Registration (e.g. `sct_register_to_template`) will produce warping fields that map the voxels in one coordinate space (e.g. the PAM50 template space) onto the space of another image. 
If a warping field is originally determined using an image with one FOV (e.g. a T2 image with dimensions (40, 515, 512)), but then the warping field is applied to an image with a different FOV (e.g. a dMRI image with dimensions (256, 256, 13)), then the ANTs tool `antsApplyTransforms` may hallucinate phantom copies of the image in areas where the initial warping field was not valid.
<details>
<summary> Warping field FOV (blue) vs. dMRI FOV (red) </summary>
</details>
<details>
<summary> Hallucinated copy outside of the warping field FOV </summary>
</details>
When would a warping field be applied to an image …
> Mask output of `sct_apply_transfo` when applying `-initwarp` during multimodal registration

- .github/workflows/create-release.yml
This is a tiny PR that saves us a manual step when creating a new release.
I had done this manually when creating the 7.0 release:
We could go even further with [`!stable-docs`](https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4798#issue-2858234540) feature that would allow us to tag PRs for automatic backporting to `stable`? But, this comes up infrequently enough that I'm happy to perform `stable` docs backporting manually. (I think I'd feel more comfortable that way, too, given the public-facing nature of our docs.)
(Given this, I've [updated our dev Wiki](https://github.com/spinalcordtoolbox/spinalcordtoolbox/wiki/Websites:-spinalcordtoolbox.com) as well to describe the procedure.)
Fixes #4798.
> Automatically reset the `stable` docs branch when creating a new release

- .github/workflows/test-past-releases.yml
Simple path fix:
- Failing run: https://github.com/spinalcordtoolbox/spinalcordtoolbox/actions/runs/16399178566
- Passing run (this branch): https://github.com/spinalcordtoolbox/spinalcordtoolbox/actions/runs/16525119778
Fixes #4988.
> Remove hardcoded path to `D:\` drive for older Windows tests

- spinalcordtoolbox/math.py
- spinalcordtoolbox/scripts/sct_maths.py
This allows using the `sct_maths -dilate` and `-erode` operations with a single number of voxels (as before), or a list of 2 or 3 numbers separated by `x`, like `1x2x3`, which can be useful for anisotropic images.
While `skimage.morphology.footprint_rectangle` works for 2D and 3D box shapes, the `disk` and `ball` functions only take a single radius. The `ellipse` function could have worked for 2D, but not for 3D, and it confusingly turns (width, height) arguments into a (height, width) resulting array. I decided that it was simpler to just generate the correct numpy array directly.
Fixes #4936.
> Implement anisotropic dilation and erosion

- .github/workflows/create-release.yml
- .github/workflows/tests.yml
- testing/api/test_qc_parallel.py
- testing/cli/test_cli_sct_analyze_lesion.py
- testing/cli/test_cli_sct_deepseg_gm.py
- testing/cli/test_cli_sct_deepseg_sc.py
- testing/cli/test_cli_sct_detect_pmj.py
- testing/cli/test_cli_sct_dmri_moco.py
- testing/cli/test_cli_sct_fmri_compute_tsnr.py
- testing/cli/test_cli_sct_fmri_moco.py
- testing/cli/test_cli_sct_get_centerline.py
- testing/cli/test_cli_sct_image.py
- testing/cli/test_cli_sct_label_utils.py
- testing/cli/test_cli_sct_label_vertebrae.py
- testing/cli/test_cli_sct_process_segmentation.py
- testing/cli/test_cli_sct_propseg.py
- testing/cli/test_cli_sct_register_multimodal.py
- testing/cli/test_cli_sct_register_to_template.py
- testing/cli/test_cli_sct_straighten_spinalcord.py
- testing/cli/test_cli_sct_warp_template.py
- testing/cli/test_sct_deepseg.py
- testing/conftest.py
Many of our `pytest` tests generate QC reports, but it is very tedious to check these reports because we create 1 report per test, and also because Firefox (and maybe other browsers) cannot open HTML files in `/tmp/`. 
Summary of changes:
- Put all `pytest` QC reports into a single report
- Add missing `-qc` flags for any test that can support it.
- Upload the final `pytest` QC report during CI runs.
- Created a personal script that will open the most recent QC report created in `/tmp/pytest/`: [open_pytest_html.sh](https://github.com/user-attachments/files/21372500/open_pytest_html.sh.zip)
- Devs should download this and alias it to something easy. 
Possible future changes:
- Merge cross-platform QC reports to make them easier to check all at once.
- Add some sort of automated annotation …
> Make it easier to manually check QC reports produced by `pytest`

- .github/workflows/tests.yml
- install_sct
- spinalcordtoolbox/compat/launcher.py
Our full "tests.yml" CI has been failing for about a week now on two OSs: [sample run](https://github.com/spinalcordtoolbox/spinalcordtoolbox/actions/runs/16495111042)
This is precisely the same issue (and fix) as https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/4106.
This one is a little more complicated...
- `bash` and `readline` recently updated in lockstep to `5.3` and `8.3` respectively, with the new `bash` version explicitly depending on the new `readline` version. ([helpful thread on `bug-readline`](https://lists.gnu.org/archive/html/bug-readline/2025-07/msg00033.html))
- Arch's 'bleeding edge' package repositories got these updates immediately, while other package repositories (such as `conda-forge`) still have `readline==8.2` (which, importantly, is incompatible with …
> Fix failing CI runs for Arch (`rl_print_keybindings`) and Debian 10 (EOL)

- .github/workflows/tests.yml
`.github/workflows/create-release.yml` correctly uses `matrix.os`, but `.github/workflows/tests.yml` should use `runner.os` instead, since it's not being run inside a matrix.
(Currently, the uploaded QC reports for this workflow get an empty pair of parentheses in their filename.)
See: https://docs.github.com/en/actions/how-tos/write-workflows/choose-what-workflows-do/use-variables#detecting-the-operating-system
> Tag QC reports from automated tests with the OS used

- spinalcordtoolbox/reports/qc2.py
When testing the "full `pytest` QC report" check, I noticed that the `totalspineseg` axial mosaic QC report looked very small and hard to read.
This PR adds several fixes to make the size a bit more manageable. It should be easy to double-check the QC report by checking the artifact uploaded to `tests.yml` for Ubuntu 24.04.
Note that this is still just a stopgap for when we can implement a better QC report for totalspineseg, as the axial mosaic isn't all that useful to begin with.
Fixes #4982.
> Tweak `totalspineseg` axial mosaic QC report to make it easier to read

- spinalcordtoolbox/deepseg/models.py
- spinalcordtoolbox/scripts/sct_deepseg.py
This PR aims to improve the `sct_deepseg -h` (argparse) by limiting what information gets displayed for individual task help (e.g. `sct_deepseg totalspineseg -h`).
The goal is to try and remove arguments that are irrelevant for certain tasks, and also limit warnings and notes to only the tasks that they are relevant for.
Here is a sample before/after:
- Before: https://spinalcordtoolbox.com/stable/user_section/command-line/deepseg/totalspineseg.html
- After: https://spinalcordtoolbox--5008.org.readthedocs.build/5008/user_section/command-line/deepseg/totalspineseg.html
Fixes https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4861.
Fixes https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4974.
Fixes https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4888.
> Clean up argparse help to only display arguments and descriptions relevant to specific tasks

- spinalcordtoolbox/registration/algorithms.py
Dead-simple bug and fix (axes dimension `nz` was being reported instead of pixel size `pz`).
Fixes #5021.
> Fix logging message to correctly print voxel size in `centermassrot` 

- testing/conftest.py
This PR contains 2 tiny fixes for some issues with the "detailed summary" test in out CI.
- Don't run `max` on an empty list.
- Don't run the functionality at all locally
This doubly handles a user error encountered in Windows, while also minimizing the annoyance of generating these files for devs locally.
Fixes #4864.
> Only create "detailed summary" test files in CI (and only when the directory exists)

- spinalcordtoolbox/deepseg/models.py
Added citation for RootletSeg deep learning method (new [arXiv preprint](
https://doi.org/10.48550/arXiv.2509.16255) available). 
Resolves: https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/5015
> Add citation for RootletSeg model in models.py
